/**
 * Variable type configuration and helper functions
 * 
 * With the simplified variable model, type is now derived from the variable ID and value:
 * 
 * Keygroups (ID prefix):
 *   /var/*      - Shared config (plaintext, NOT encrypted) -> "config"
 *   /dev/*      - Dev secrets (encrypted) -> "secret" if ref+sops, else "config"
 *   /staging/*  - Staging secrets (encrypted) -> "secret" if ref+sops, else "config"
 *   /prod/*     - Production secrets (encrypted) -> "secret" if ref+sops, else "config"
 *   /computed/* - Generated by Nix (read-only) -> "computed" or "service"
 * 
 * Value patterns:
 *   ref+sops://...  -> "secret" (encrypted SOPS file)
 *   ref+yaml://...  -> "config" (plaintext YAML file)
 *   ref+*://...     -> "computed" (other vals references like awsssm, vault)
 *   literal string  -> "config"
 */

import { Key, Server, Settings, Sparkles } from "lucide-react";

export const VARIABLE_TYPES = [
	{
		value: "secret",
		label: "Secret",
		description: "Sensitive value stored encrypted",
		icon: Key,
		color: "bg-red-500/20 text-red-400",
		readonly: false,
	},
	{
		value: "config",
		label: "Config",
		description: "Non-sensitive configuration",
		icon: Settings,
		color: "bg-blue-500/20 text-blue-400",
		readonly: false,
	},
	{
		value: "computed",
		label: "Computed",
		description: "Derived from other config",
		icon: Sparkles,
		color: "bg-purple-500/20 text-purple-400",
		readonly: true,
	},
	{
		value: "service",
		label: "Service",
		description: "Auto-generated from service",
		icon: Server,
		color: "bg-green-500/20 text-green-400",
		readonly: true,
	},
] as const;

export type VariableTypeName = (typeof VARIABLE_TYPES)[number]["value"];

/**
 * Determine variable type from ID and value.
 * 
 * Type derivation:
 * 1. ID starts with /computed/services/ -> "service" (read-only)
 * 2. ID starts with /computed/ -> "computed" (read-only)
 * 3. ID starts with /var/ -> "config" (plaintext, shared config)
 * 4. Value is ref+sops://... -> "secret" (encrypted)
 * 5. Value is ref+yaml://... -> "config" (plaintext YAML reference)
 * 6. Value is ref+*://... -> "computed" (external vals reference)
 * 7. Otherwise -> "config" (literal value)
 */
export function getVariableType(id: string, value: string): VariableTypeName {
	// Computed variables from Nix (read-only)
	if (id.startsWith("/computed/services/")) {
		return "service";
	}
	if (id.startsWith("/computed/")) {
		return "computed";
	}
	
	// Shared config variables (plaintext, /var/* keygroup)
	if (id.startsWith("/var/")) {
		return "config";
	}
	
	// Check value for vals references
	if (value.startsWith("ref+sops://")) {
		return "secret";
	}
	if (value.startsWith("ref+yaml://") || value.startsWith("ref+file://")) {
		return "config"; // Plaintext file references
	}
	if (value.startsWith("ref+")) {
		return "computed"; // Other vals references (awsssm, vault, etc.)
	}
	
	// Default to config for literal values
	return "config";
}

/**
 * Get type config from type name or by analyzing id/value.
 */
export function getTypeConfig(typeOrId: VariableTypeName | string, value?: string) {
	// If we have both id and value, derive the type
	if (value !== undefined && typeOrId.startsWith("/")) {
		const typeName = getVariableType(typeOrId, value);
		return VARIABLE_TYPES.find((t) => t.value === typeName) ?? VARIABLE_TYPES[1];
	}
	
	// Otherwise treat as type name
	const typeStr = typeof typeOrId === "string" ? typeOrId.toLowerCase() : "config";
	return VARIABLE_TYPES.find((t) => t.value === typeStr) ?? VARIABLE_TYPES[1];
}

/**
 * Check if a variable is read-only based on its ID.
 */
export function isReadOnlyVariable(id: string): boolean {
	return id.startsWith("/computed/");
}

/**
 * Extract keygroup from variable ID.
 * e.g., "/dev/DATABASE_URL" -> "dev"
 * e.g., "/computed/apps/web/port" -> "computed"
 */
export function getKeyGroup(id: string): string {
	const match = id.match(/^\/([^/]+)\//);
	return match?.[1] ?? "dev";
}

/**
 * Extract variable name from ID.
 * e.g., "/dev/DATABASE_URL" -> "DATABASE_URL"
 * e.g., "/computed/apps/web/port" -> "port"
 */
export function getVariableName(id: string): string {
	const parts = id.split("/");
	return parts[parts.length - 1] ?? id;
}

/**
 * Check if a value is a vals reference.
 */
export function isValsReference(value: string): boolean {
	return value.startsWith("ref+");
}

/**
 * Check if a value is a SOPS secret reference.
 */
export function isSopsReference(value: string): boolean {
	return value.startsWith("ref+sops://");
}

/**
 * Known keygroups and their characteristics.
 */
export const KEYGROUPS = {
	var: { label: "Shared", encrypted: false, description: "Plaintext shared config" },
	dev: { label: "Dev", encrypted: true, description: "Development secrets" },
	staging: { label: "Staging", encrypted: true, description: "Staging secrets" },
	prod: { label: "Prod", encrypted: true, description: "Production secrets" },
	computed: { label: "Computed", encrypted: false, description: "Generated by Nix (read-only)" },
} as const;

export type KeyGroupName = keyof typeof KEYGROUPS;

/**
 * Check if a keygroup stores encrypted secrets.
 */
export function isEncryptedKeyGroup(keyGroup: string): boolean {
	const kg = KEYGROUPS[keyGroup as KeyGroupName];
	return kg?.encrypted ?? false;
}

/**
 * Get the SOPS file path for a keygroup.
 * Returns null for non-SOPS keygroups (var, computed).
 */
export function getSopsFilePath(keyGroup: string): string | null {
	if (keyGroup === "var" || keyGroup === "computed") {
		return null;
	}
	return `.stackpanel/secrets/${keyGroup}.yaml`;
}

/**
 * Build a SOPS reference for a secret.
 */
export function buildSopsReference(keyGroup: string, key: string): string {
	return `ref+sops://.stackpanel/secrets/${keyGroup}.yaml#/${key}`;
}

/**
 * Build a YAML reference for a plaintext config value.
 */
export function buildYamlReference(key: string): string {
	return `ref+yaml://.stackpanel/secrets/vars.yaml#/${key}`;
}
