/**
 * Variable type configuration and helper functions
 *
 * With the direct SOPS model, type is derived from the variable ID prefix:
 *
 * Keygroups (ID prefix):
 *   /var/*      - Shared config (plaintext, NOT encrypted) -> "config"
 *   /dev/*      - Dev secrets (encrypted in dev.sops.yaml) -> "secret"
 *   /staging/*  - Staging secrets (encrypted in staging.sops.yaml) -> "secret"
 *   /prod/*     - Production secrets (encrypted in prod.sops.yaml) -> "secret"
 *   /common/*   - Shared secrets (encrypted in common.sops.yaml) -> "secret"
 *   /computed/* - Generated by Nix (read-only) -> "computed" or "service"
 *
 * Secret variable values are empty strings; the SOPS file is the source of truth.
 */

import { Key, Server, Settings, Sparkles } from "lucide-react";

export const VARIABLE_TYPES = [
  {
    value: "secret",
    label: "Secret",
    description: "Sensitive value stored encrypted",
    icon: Key,
    color: "bg-red-500/20 text-red-400",
    readonly: false,
  },
  {
    value: "config",
    label: "Config",
    description: "Non-sensitive configuration",
    icon: Settings,
    color: "bg-blue-500/20 text-blue-400",
    readonly: false,
  },
  {
    value: "computed",
    label: "Computed",
    description: "Derived from other config",
    icon: Sparkles,
    color: "bg-purple-500/20 text-purple-400",
    readonly: true,
  },
  {
    value: "service",
    label: "Service",
    description: "Auto-generated from service",
    icon: Server,
    color: "bg-green-500/20 text-green-400",
    readonly: true,
  },
] as const;

export type VariableTypeName = (typeof VARIABLE_TYPES)[number]["value"];

/** Variables backend type */
export type VariablesBackend = "vals" | "chamber";

/**
 * Determine variable type from ID and value.
 *
 * Type is primarily derived from the variable ID prefix (keygroup):
 * 1. ID starts with /computed/services/ -> "service" (read-only)
 * 2. ID starts with /computed/ -> "computed" (read-only)
 * 3. ID starts with /var/ -> "config" (plaintext, shared config)
 * 4. ID is in an encrypted keygroup (/dev, /staging, /prod, /common) -> "secret"
 * 5. Otherwise -> "config" (literal value)
 *
 * @param id - Variable ID path (e.g., "/dev/DATABASE_URL")
 * @param value - Variable value (unused, kept for API compat)
 * @param _backend - Variables backend (unused, kept for API compat)
 */
export function getVariableType(
  id: string,
  _value: string,
  _backend: VariablesBackend = "vals",
): VariableTypeName {
  // Computed variables from Nix (read-only)
  if (id.startsWith("/computed/services/")) {
    return "service";
  }
  if (id.startsWith("/computed/")) {
    return "computed";
  }

  // Shared config variables (plaintext, /var/* keygroup)
  if (id.startsWith("/var/")) {
    return "config";
  }

  // Encrypted keygroup -> secret
  const keyGroup = getKeyGroup(id);
  if (isEncryptedKeyGroup(keyGroup)) {
    return "secret";
  }

  // Default to config for literal values in non-encrypted keygroups
  return "config";
}

/**
 * Get type config from type name or by analyzing id/value.
 *
 * @param typeOrId - Either a type name ("secret") or a variable ID ("/dev/FOO")
 * @param value - Variable value (only used when typeOrId is an ID)
 * @param backend - Variables backend. Defaults to "vals".
 */
export function getTypeConfig(
  typeOrId: VariableTypeName | string,
  value?: string,
  backend: VariablesBackend = "vals",
) {
  // If we have both id and value, derive the type
  if (value !== undefined && typeOrId.startsWith("/")) {
    const typeName = getVariableType(typeOrId, value, backend);
    return (
      VARIABLE_TYPES.find((t) => t.value === typeName) ?? VARIABLE_TYPES[1]
    );
  }

  // Otherwise treat as type name
  const typeStr =
    typeof typeOrId === "string" ? typeOrId.toLowerCase() : "config";
  return VARIABLE_TYPES.find((t) => t.value === typeStr) ?? VARIABLE_TYPES[1];
}

/**
 * Check if a variable is read-only based on its ID.
 */
export function isReadOnlyVariable(id: string): boolean {
  return id.startsWith("/computed/");
}

/**
 * Extract keygroup from variable ID.
 * e.g., "/dev/DATABASE_URL" -> "dev"
 * e.g., "/computed/apps/web/port" -> "computed"
 */
export function getKeyGroup(id: string): string {
  const match = id.match(/^\/([^/]+)\//);
  return match?.[1] ?? "dev";
}

/**
 * Extract variable name from ID.
 * e.g., "/dev/DATABASE_URL" -> "DATABASE_URL"
 * e.g., "/computed/apps/web/port" -> "port"
 */
export function getVariableName(id: string): string {
  const parts = id.split("/");
  return parts[parts.length - 1] ?? id;
}

/**
 * Validate a secret key name follows Chamber naming rules:
 * lowercase alphanumeric + hyphens only, must start with alphanumeric.
 */
const SECRET_KEY_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

export function isValidSecretKey(key: string): boolean {
  return SECRET_KEY_PATTERN.test(key);
}

export function formatSecretKeyError(key: string): string | null {
  if (!key) return "Key is required";
  if (/[A-Z]/.test(key))
    return `Key "${key}" contains uppercase letters. Use lowercase only (e.g., "${key.toLowerCase()}")`;
  if (/\//.test(key))
    return `Key "${key}" contains slashes. Use hyphens instead`;
  if (!SECRET_KEY_PATTERN.test(key))
    return `Key "${key}" is invalid. Use only lowercase letters, numbers, and hyphens (must start with a letter or number)`;
  return null;
}

/**
 * Check if a variable is a secret based on its ID keygroup.
 */
export function isSecretVariable(
  id: string,
  value: string,
  backend: VariablesBackend = "vals",
): boolean {
  return getVariableType(id, value, backend) === "secret";
}

/**
 * Known keygroups and their characteristics.
 */
export const KEYGROUPS = {
  var: {
    label: "Shared",
    encrypted: false,
    description: "Plaintext shared config",
  },
  common: {
    label: "Common",
    encrypted: true,
    description: "Shared secrets (all groups)",
  },
  dev: { label: "Dev", encrypted: true, description: "Development secrets" },
  staging: {
    label: "Staging",
    encrypted: true,
    description: "Staging secrets",
  },
  prod: { label: "Prod", encrypted: true, description: "Production secrets" },
  computed: {
    label: "Computed",
    encrypted: false,
    description: "Generated by Nix (read-only)",
  },
} as const;

export type KeyGroupName = keyof typeof KEYGROUPS;

/**
 * Check if a keygroup stores encrypted secrets.
 */
export function isEncryptedKeyGroup(keyGroup: string): boolean {
  const kg = KEYGROUPS[keyGroup as KeyGroupName];
  return kg?.encrypted ?? false;
}

/**
 * Get the SOPS file path for a keygroup.
 * Returns null for non-SOPS keygroups (var, computed).
 */
export function getSopsFilePath(keyGroup: string): string | null {
  if (keyGroup === "var" || keyGroup === "computed") {
    return null;
  }
  return `.stackpanel/secrets/vars/${keyGroup}.sops.yaml`;
}

/**
 * Available secret groups for access control.
 * These correspond to SOPS files in .stackpanel/secrets/vars/
 */
export const SECRET_GROUPS = ["dev", "staging", "prod", "common"] as const;

export type SecretGroupName = (typeof SECRET_GROUPS)[number];

/** Prefix used for app environment links to workspace variables. */
export const VARIABLE_LINK_PREFIX = "var://";

/**
 * Build a stable reference string to a workspace variable ID.
 *
 * Example:
 *   /dev/DATABASE_URL -> var://dev/DATABASE_URL
 */
export function buildVariableLinkReference(variableId: string): string {
  const normalized = variableId.replace(/^\/+/, "");
  return `${VARIABLE_LINK_PREFIX}${normalized}`;
}

/**
 * Check whether an app env value links to a workspace variable.
 */
export function isVariableLinkReference(value: string): boolean {
  return value.startsWith(VARIABLE_LINK_PREFIX);
}

/**
 * Parse an app env variable link and return the referenced workspace variable ID.
 * Returns null if value is not a valid variable link.
 */
export function parseVariableLinkReference(value: string): string | null {
  if (!isVariableLinkReference(value)) {
    return null;
  }

  const raw = value.slice(VARIABLE_LINK_PREFIX.length).trim();
  if (!raw) {
    return null;
  }

  return raw.startsWith("/") ? raw : `/${raw}`;
}

/**
 * Check if a string is a valid secret group name.
 */
export function isValidSecretGroup(group: string): group is SecretGroupName {
  return (SECRET_GROUPS as readonly string[]).includes(group);
}

// =============================================================================
// Group selector (v2)
// =============================================================================

/**
 * Virtual group for variables not scoped to any SOPS group.
 *
 * In plaintext mode: maps to /var/ prefix (not in any SOPS file).
 * In secret mode: maps to common.sops.yaml (encrypted to all group keys).
 */
export const SHARED_GROUP = "shared";

/**
 * Map a group + mode selection to the variable ID prefix and SOPS group.
 *
 * "shared" is a virtual group:
 *   - plaintext: /var/ prefix, no SOPS group
 *   - secret: /common/ prefix, "common" SOPS group
 *
 * All other groups map directly: /<group>/ prefix, <group> SOPS group.
 *
 * Returns:
 *   - idPrefix: the path prefix for the variable ID (e.g., "/var/", "/dev/")
 *   - sopsGroup: the SOPS group name for secrets (null for plaintext /var/ variables)
 */
export function resolveGroup(
  group: string,
  mode: "plaintext" | "secret",
): { idPrefix: string; sopsGroup: string | null } {
  if (group === SHARED_GROUP) {
    return mode === "secret"
      ? { idPrefix: "/common/", sopsGroup: "common" }
      : { idPrefix: "/var/", sopsGroup: null };
  }
  return { idPrefix: `/${group}/`, sopsGroup: group };
}
