# ==============================================================================
# variables.nix
#
# Workspace variables - simple key-value pairs.
#
# Variables are stored as a map of ID to value:
#   "/var/LOG_LEVEL" = { value = "info"; };  # Plaintext config
#   "/dev/DATABASE_URL" = { value = "ref+sops://.stackpanel/secrets/dev.yaml#/DATABASE_URL"; };
#   "/prod/API_KEY" = { value = "ref+sops://.stackpanel/secrets/prod.yaml#/API_KEY"; };
#   "/computed/apps/web/port" = { value = "3000"; };  # Read-only
#
# Keygroups (ID prefix):
#   /var/*      - Shared config (plaintext in vars.yaml, NOT encrypted)
#   /dev/*      - Dev secrets (encrypted in dev.yaml)
#   /staging/*  - Staging secrets (encrypted in staging.yaml)
#   /prod/*     - Production secrets (encrypted in prod.yaml)
#   /computed/* - Generated by Nix modules (read-only)
#
# Values can be:
#   - Literal strings: "3000", "postgresql://localhost/dev"
#   - SOPS refs: "ref+sops://.stackpanel/secrets/dev.yaml#/KEY"
#   - YAML refs: "ref+yaml://.stackpanel/secrets/vars.yaml#/KEY"
#   - Vals refs: "ref+awsssm://...", "ref+vault://...", "ref+exec://..."
# ==============================================================================
{
  lib,
  config,
  ...
}:
let
  cfg = config.stackpanel;

  # Secrets directory relative to project root
  secretsDir = cfg.secrets.secrets-dir or ".stackpanel/secrets";

  # Extract keygroup from variable ID
  # "/dev/DATABASE_URL" -> "dev"
  # "/computed/apps/web/port" -> "computed"
  getKeyGroup = id:
    let
      cleaned = lib.removePrefix "/" id;
      parts = lib.splitString "/" cleaned;
    in
    if parts != [] then builtins.head parts else "dev";

  # Extract variable name from ID (last path component)
  # "/dev/DATABASE_URL" -> "DATABASE_URL"
  getVarName = id:
    let
      cleaned = lib.removePrefix "/" id;
      parts = lib.splitString "/" cleaned;
    in
    if parts != [] then lib.last parts else id;

  # Check if a value is a vals reference
  isValsRef = value: lib.hasPrefix "ref+" value;

  # Check if a value is a SOPS secret reference
  isSopsRef = value: lib.hasPrefix "ref+sops://" value;

  # Check if a variable ID is computed (read-only)
  isComputed = id: lib.hasPrefix "/computed/" id;

  # Variable submodule - just id and value, with computed helpers
  variableModule =
    { config, name, ... }:
    {
      options = {
        id = lib.mkOption {
          type = lib.types.str;
          default = name;
          description = ''
            Variable identifier. Format: /<keygroup>/<NAME>
            
            The keygroup determines which SOPS file the secret lives in:
              /dev/FOO -> .stackpanel/secrets/dev.yaml
              /prod/FOO -> .stackpanel/secrets/prod.yaml
            
            Computed variables use /computed/<source>/<path>:
              /computed/apps/web/port
              /computed/services/postgres/port
          '';
        };

        value = lib.mkOption {
          type = lib.types.str;
          default = "";
          description = ''
            The value - either a literal string or a vals reference.
            
            Literals: "3000", "postgresql://localhost/dev"
            Vals refs: "ref+sops://...", "ref+awsssm://...", "ref+exec://..."
          '';
        };

        # Computed attributes (read-only)
        keyGroup = lib.mkOption {
          type = lib.types.str;
          readOnly = true;
          description = "Key group extracted from ID (e.g., 'dev', 'prod', 'computed')";
        };

        varName = lib.mkOption {
          type = lib.types.str;
          readOnly = true;
          description = "Variable name extracted from ID (last path component)";
        };

        isSecret = lib.mkOption {
          type = lib.types.bool;
          readOnly = true;
          description = "Whether this is a SOPS-encrypted secret";
        };

        isComputed = lib.mkOption {
          type = lib.types.bool;
          readOnly = true;
          description = "Whether this is a computed (read-only) variable";
        };

        isValsRef = lib.mkOption {
          type = lib.types.bool;
          readOnly = true;
          description = "Whether the value is a vals reference";
        };

        sopsFile = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          readOnly = true;
          description = "Path to the SOPS file for this keygroup (null for /var/* and /computed/*)";
        };

        isPlaintext = lib.mkOption {
          type = lib.types.bool;
          readOnly = true;
          description = "Whether this is a plaintext config variable (/var/*)";
        };
      };

      config =
        let
          keyGroup = getKeyGroup config.id;
          # /var/* and /computed/* don't use SOPS
          usesSops = keyGroup != "var" && keyGroup != "computed";
        in
        {
          keyGroup = keyGroup;
          varName = getVarName config.id;
          isSecret = isSopsRef config.value;
          isComputed = isComputed config.id;
          isValsRef = isValsRef config.value;
          isPlaintext = keyGroup == "var";
          sopsFile = if usesSops then "${secretsDir}/${keyGroup}.yaml" else null;
        };
    };
in
{
  options.stackpanel.variables = lib.mkOption {
    type = lib.types.attrsOf (lib.types.submodule variableModule);
    default = { };
    description = ''
      Workspace variables - literals, secrets, and vals references.
      
      Keygroups determine storage and encryption:
        /var/*      - Shared config (plaintext, NOT encrypted)
        /dev/*      - Dev secrets (encrypted)
        /staging/*  - Staging secrets (encrypted)
        /prod/*     - Production secrets (encrypted)
        /computed/* - Nix-computed values (read-only)
      
      Values are either literal strings or vals references:
        "info"                                  (literal)
        "ref+sops://.../dev.yaml#/DATABASE_URL" (encrypted SOPS)
        "ref+yaml://.../vars.yaml#/LOG_LEVEL"   (plaintext YAML)
        "ref+awsssm://prod/api-key"             (AWS SSM)
    '';
    example = lib.literalExpression ''
      {
        # Shared config (plaintext, NOT encrypted)
        "/var/LOG_LEVEL" = { value = "info"; };
        "/var/API_VERSION" = { value = "v1"; };
        
        # Dev secrets (encrypted in dev.yaml)
        "/dev/DATABASE_URL" = {
          value = "ref+sops://.stackpanel/secrets/dev.yaml#/DATABASE_URL";
        };
        
        # Prod secrets (encrypted in prod.yaml)
        "/prod/API_KEY" = {
          value = "ref+sops://.stackpanel/secrets/prod.yaml#/API_KEY";
        };
      }
    '';
  };
}
