# ==============================================================================
# variables.nix
#
# Workspace variables - simple key-value pairs.
#
# Variables are stored as a map of ID to value:
#   "/var/LOG_LEVEL" = { value = "info"; };      # Plaintext config
#   "/dev/DATABASE_URL" = { value = ""; };        # Secret (SOPS file is source of truth)
#   "/prod/API_KEY" = { value = ""; };            # Secret (SOPS file is source of truth)
#   "/common/SHARED_SECRET" = { value = ""; };    # Secret (all groups)
#   "/computed/apps/web/port" = { value = "3000"; };  # Read-only
#
# Keygroups (ID prefix):
#   /var/*      - Shared config (plaintext, NOT encrypted)
#   /common/*   - Shared secrets (encrypted in common.sops.yaml, all groups)
#   /dev/*      - Dev secrets (encrypted in dev.sops.yaml)
#   /staging/*  - Staging secrets (encrypted in staging.sops.yaml)
#   /prod/*     - Production secrets (encrypted in prod.sops.yaml)
#   /computed/* - Generated by Nix modules (read-only)
#
# Secret variable values are empty strings; the SOPS file is the source of truth.
# The keygroup determines which SOPS file contains the secret value.
# ==============================================================================
{
  lib,
  config,
  ...
}:
let
  cfg = config.stackpanel;

  # Secrets directory relative to project root
  secretsDir = cfg.secrets.secrets-dir or ".stackpanel/secrets";

  # Extract keygroup from variable ID
  # "/dev/DATABASE_URL" -> "dev"
  # "/computed/apps/web/port" -> "computed"
  getKeyGroup =
    id:
    let
      cleaned = lib.removePrefix "/" id;
      parts = lib.splitString "/" cleaned;
    in
    if parts != [ ] then builtins.head parts else "dev";

  # Extract variable name from ID (last path component)
  # "/dev/DATABASE_URL" -> "DATABASE_URL"
  getVarName =
    id:
    let
      cleaned = lib.removePrefix "/" id;
      parts = lib.splitString "/" cleaned;
    in
    if parts != [ ] then lib.last parts else id;

  # Check if a variable ID is computed (read-only)
  isComputed = id: lib.hasPrefix "/computed/" id;

  # Variable submodule - just id and value, with computed helpers
  variableModule =
    { config, name, ... }:
    {
      options = {
        id = lib.mkOption {
          type = lib.types.str;
          default = name;
          description = ''
            Variable identifier. Format: /<keygroup>/<NAME>

            The keygroup determines which SOPS file the secret lives in:
              /dev/FOO -> .stackpanel/secrets/dev.yaml
              /prod/FOO -> .stackpanel/secrets/prod.yaml

            Computed variables use /computed/<source>/<path>:
              /computed/apps/web/port
              /computed/services/postgres/port
          '';
        };

        value = lib.mkOption {
          type = lib.types.str;
          default = "";
          description = ''
            The value of this variable.

            For plaintext variables (/var/*): the literal value.
            For secrets (/dev/*, /prod/*, /common/*): empty string (SOPS file is source of truth).
            For computed (/computed/*): the computed value from Nix.

            Legacy: ref+sops:// values are still supported during migration.
          '';
        };

        # Computed attributes (read-only)
        keyGroup = lib.mkOption {
          type = lib.types.str;
          readOnly = true;
          description = "Key group extracted from ID (e.g., 'dev', 'prod', 'computed')";
        };

        varName = lib.mkOption {
          type = lib.types.str;
          readOnly = true;
          description = "Variable name extracted from ID (last path component)";
        };

        isSecret = lib.mkOption {
          type = lib.types.bool;
          readOnly = true;
          description = "Whether this is a SOPS-encrypted secret";
        };

        isComputed = lib.mkOption {
          type = lib.types.bool;
          readOnly = true;
          description = "Whether this is a computed (read-only) variable";
        };

        isValsRef = lib.mkOption {
          type = lib.types.bool;
          readOnly = true;
          description = "Whether the value is a vals reference";
        };

        sopsFile = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          readOnly = true;
          description = "Path to the SOPS file for this keygroup (null for /var/* and /computed/*)";
        };

        isPlaintext = lib.mkOption {
          type = lib.types.bool;
          readOnly = true;
          description = "Whether this is a plaintext config variable (/var/*)";
        };
      };

      config =
        let
          keyGroup = getKeyGroup config.id;
          # /var/* and /computed/* don't use SOPS; all other keygroups are encrypted
          usesSops = keyGroup != "var" && keyGroup != "computed";
        in
        {
          keyGroup = keyGroup;
          varName = getVarName config.id;
          isSecret = usesSops;
          isComputed = isComputed config.id;
          isValsRef = false;
          isPlaintext = keyGroup == "var";
          sopsFile = if usesSops then "${secretsDir}/vars/${keyGroup}.sops.yaml" else null;
        };
    };
in
{
  options.stackpanel.variables = lib.mkOption {
    type = lib.types.attrsOf (lib.types.submodule variableModule);
    default = { };
    description = ''
      Workspace variables.

      Keygroups determine storage and encryption:
        /var/*      - Shared config (plaintext, NOT encrypted)
        /common/*   - Shared secrets (encrypted, all groups)
        /dev/*      - Dev secrets (encrypted)
        /staging/*  - Staging secrets (encrypted)
        /prod/*     - Production secrets (encrypted)
        /computed/* - Nix-computed values (read-only)

      Secret variable values are empty strings; the SOPS file is the source of truth.
      Plaintext variables store their value directly.
    '';
    example = lib.literalExpression ''
      {
        # Shared config (plaintext, NOT encrypted)
        "/var/LOG_LEVEL" = { value = "info"; };
        "/var/API_VERSION" = { value = "v1"; };
        
        # Dev secrets (value in dev.sops.yaml, variable value is empty)
        "/dev/DATABASE_URL" = { value = ""; };
        
        # Prod secrets (value in prod.sops.yaml)
        "/prod/API_KEY" = { value = ""; };
        
        # Common secrets (encrypted to all groups)
        "/common/SHARED_TOKEN" = { value = ""; };
      }
    '';
  };
}
