#!/usr/bin/env bash
# ==============================================================================
# alchemy:deploy - Provider-scoped alchemy deploy helper
#
# Auto-generated by Stackpanel -- do not edit manually.
#
# Checks prerequisites (Cloudflare token, state token) and runs alchemy deploy.
# If tokens are missing, loads them from secrets or triggers alchemy:setup.
#
# Usage:
#   alchemy:deploy [stage] [-- alchemy-args...]
#   alchemy:deploy staging
#   alchemy:deploy prod
#   alchemy:deploy staging -- --force
#   alchemy:deploy staging -- --adopt
#
# Template variables (replaced at codegen time):
#   __CF_TOKEN_ENV_VAR__    - env var name for Cloudflare token
#   __STATE_TOKEN_ENV_VAR__ - env var name for alchemy state token
#   __ALCHEMY_RUN_FILE__    - path to main alchemy.run.ts
#   __STATE_PROVIDER__      - state store provider (cloudflare, filesystem, auto)
# ==============================================================================
set -euo pipefail

# --- Configuration (embedded at codegen time) --------------------------------
CF_TOKEN_ENV_VAR="__CF_TOKEN_ENV_VAR__"
STATE_TOKEN_ENV_VAR="__STATE_TOKEN_ENV_VAR__"
ALCHEMY_RUN_FILE="__ALCHEMY_RUN_FILE__"
STATE_PROVIDER="__STATE_PROVIDER__"

# --- Helpers ------------------------------------------------------------------
info() { echo "  $*"; }
fail() {
	echo "  ERROR: $*" >&2
	exit 1
}

# --- Parse arguments ----------------------------------------------------------
STAGE=""
ALCHEMY_ARGS=()
PAST_SEPARATOR=false

for arg in "$@"; do
	if [ "$PAST_SEPARATOR" = "true" ]; then
		ALCHEMY_ARGS+=("$arg")
	elif [ "$arg" = "--" ]; then
		PAST_SEPARATOR=true
	elif [ "$arg" = "--help" ] || [ "$arg" = "-h" ]; then
		echo "Usage: alchemy:deploy [stage] [-- alchemy-args...]"
		echo ""
		echo "Deploy your app via alchemy."
		echo ""
		echo "Arguments:"
		echo "  stage              Deployment stage (default: \$USER)"
		echo ""
		echo "Alchemy arguments (after --):"
		echo "  --force            Force update all resources"
		echo "  --adopt            Adopt existing unmanaged resources"
		echo "  --watch            Watch and redeploy on changes"
		echo "  --quiet            Suppress resource change messages"
		echo "  --env-file FILE    Load environment from file"
		echo ""
		echo "Examples:"
		echo "  alchemy:deploy staging"
		echo "  alchemy:deploy prod -- --force"
		echo "  alchemy:deploy staging -- --adopt --quiet"
		echo ""
		echo "If Cloudflare is not configured, runs alchemy:setup first."
		exit 0
	elif [ -z "$STAGE" ]; then
		STAGE="$arg"
	else
		ALCHEMY_ARGS+=("$arg")
	fi
done

# Default stage to $USER (alchemy convention)
if [ -z "$STAGE" ]; then
	STAGE="${USER:-dev}"
fi

# --- Check alchemy.run.ts exists ---------------------------------------------
if [ ! -f "$ALCHEMY_RUN_FILE" ]; then
	fail "Alchemy run file not found: $ALCHEMY_RUN_FILE"
fi

# --- Check prerequisites -----------------------------------------------------
NEEDS_CF_TOKEN=false

# Only need CF token if state provider requires it
if [ "$STATE_PROVIDER" = "cloudflare" ]; then
	NEEDS_CF_TOKEN=true
elif [ "$STATE_PROVIDER" = "auto" ]; then
	# For auto, we want the token so we get shared state
	NEEDS_CF_TOKEN=true
fi

if [ "$NEEDS_CF_TOKEN" = "true" ] && [ -z "${!CF_TOKEN_ENV_VAR:-}" ]; then
	# Token not in environment -- try loading from secrets
	if command -v secrets-get &>/dev/null; then
		info "Loading Cloudflare token from secrets..."

		CF_TOKEN_VALUE=$(secrets-get cloudflare-api-token 2>/dev/null || true)
		STATE_TOKEN_VALUE=$(secrets-get alchemy-state-token 2>/dev/null || true)

		if [ -n "$CF_TOKEN_VALUE" ]; then
			export "${CF_TOKEN_ENV_VAR}=${CF_TOKEN_VALUE}"
			info "Loaded $CF_TOKEN_ENV_VAR from secrets"
		fi

		if [ -n "$STATE_TOKEN_VALUE" ] && [ -z "${!STATE_TOKEN_ENV_VAR:-}" ]; then
			export "${STATE_TOKEN_ENV_VAR}=${STATE_TOKEN_VALUE}"
			info "Loaded $STATE_TOKEN_ENV_VAR from secrets"
		fi
	fi
fi

# Still missing? Run setup
if [ "$NEEDS_CF_TOKEN" = "true" ] && [ -z "${!CF_TOKEN_ENV_VAR:-}" ]; then
	echo ""
	info "Cloudflare is not configured."
	info "Running alchemy:setup to set up authentication..."
	echo ""

	alchemy:setup

	# Re-load tokens from secrets after setup
	if command -v secrets-get &>/dev/null; then
		CF_TOKEN_VALUE=$(secrets-get cloudflare-api-token 2>/dev/null || true)
		STATE_TOKEN_VALUE=$(secrets-get alchemy-state-token 2>/dev/null || true)

		if [ -n "$CF_TOKEN_VALUE" ]; then
			export "${CF_TOKEN_ENV_VAR}=${CF_TOKEN_VALUE}"
		fi
		if [ -n "$STATE_TOKEN_VALUE" ] && [ -z "${!STATE_TOKEN_ENV_VAR:-}" ]; then
			export "${STATE_TOKEN_ENV_VAR}=${STATE_TOKEN_VALUE}"
		fi
	fi

	# Final check
	if [ -z "${!CF_TOKEN_ENV_VAR:-}" ]; then
		fail "Setup completed but $CF_TOKEN_ENV_VAR is still not set. Check your secrets."
	fi
fi

# --- Deploy -------------------------------------------------------------------
echo ""
info "Deploying to $STAGE..."
echo ""

exec bunx alchemy deploy "$ALCHEMY_RUN_FILE" \
	--stage "$STAGE" \
	"${ALCHEMY_ARGS[@]+"${ALCHEMY_ARGS[@]}"}"
