#!/usr/bin/env bash
# ==============================================================================
# alchemy:setup - One-time Cloudflare deployment setup
#
# Auto-generated by Stackpanel -- do not edit manually.
#
# Orchestrates:
#   1. alchemy configure (Cloudflare OAuth profile)
#   2. alchemy login (browser-based OAuth consent)
#   3. alchemy util create-cloudflare-token (scoped API token)
#   4. ALCHEMY_STATE_TOKEN generation
#   5. Token storage in secrets module (SOPS-encrypted)
#   6. Bootstrap: deploy CloudflareStateStore worker (filesystem state)
#
# Template variables (replaced at codegen time):
#   __APP_NAME__            - alchemy app name
#   __SOPS_GROUP__          - SOPS group to store tokens in
#   __CF_TOKEN_ENV_VAR__    - env var name for Cloudflare token
#   __STATE_TOKEN_ENV_VAR__ - env var name for alchemy state token
#   __TOKEN_SCOPES__        - "profile" or "god"
#   __AUTO_PROVISION__      - "true" or "false"
#   __BOOTSTRAP_FILE__      - path to bootstrap alchemy.run.ts
# ==============================================================================
set -euo pipefail

# --- Configuration (embedded at codegen time) --------------------------------
APP_NAME="__APP_NAME__"
SOPS_GROUP="__SOPS_GROUP__"
CF_TOKEN_ENV_VAR="__CF_TOKEN_ENV_VAR__"
STATE_TOKEN_ENV_VAR="__STATE_TOKEN_ENV_VAR__"
TOKEN_SCOPES="__TOKEN_SCOPES__"
AUTO_PROVISION="__AUTO_PROVISION__"
BOOTSTRAP_FILE="__BOOTSTRAP_FILE__"

# --- Helpers ------------------------------------------------------------------
info() { echo "  $*"; }
step() {
	echo ""
	echo "  [$1/$TOTAL_STEPS] $2"
}
ok() { echo "  -> $*"; }
fail() {
	echo "  ERROR: $*" >&2
	exit 1
}

# Determine total steps based on config
if [ "$AUTO_PROVISION" = "true" ]; then
	TOTAL_STEPS=5
else
	TOTAL_STEPS=4
fi

# --- Parse flags --------------------------------------------------------------
FORCE=false
SKIP_SECRETS=false

while [[ $# -gt 0 ]]; do
	case "$1" in
	--force)
		FORCE=true
		shift
		;;
	--skip-secrets)
		SKIP_SECRETS=true
		shift
		;;
	--help | -h)
		echo "Usage: alchemy:setup [--force] [--skip-secrets]"
		echo ""
		echo "One-time Cloudflare deployment setup."
		echo ""
		echo "Options:"
		echo "  --force          Re-run setup even if tokens already exist"
		echo "  --skip-secrets   Print tokens to stdout instead of storing in SOPS"
		echo "  -h, --help       Show this help"
		exit 0
		;;
	*)
		fail "Unknown flag: $1 (try --help)"
		;;
	esac
done

# --- Pre-flight checks -------------------------------------------------------
echo ""
echo "  Cloudflare Deployment Setup"
echo "  ==========================="

# Check if already configured
if [ "$FORCE" != "true" ]; then
	if [ -n "${!CF_TOKEN_ENV_VAR:-}" ]; then
		info "Cloudflare is already configured ($CF_TOKEN_ENV_VAR is set)."
		info "Run with --force to re-configure."
		exit 0
	fi

	# Also check if token exists in SOPS (even if not loaded in env)
	if [ "$SKIP_SECRETS" != "true" ] && command -v secrets-get &>/dev/null; then
		if secrets-get cloudflare-api-token --group "$SOPS_GROUP" &>/dev/null 2>&1; then
			info "Cloudflare token found in secrets (group: $SOPS_GROUP)."
			info "Load it with: secrets:env"
			info "Or run with --force to re-configure."
			exit 0
		fi
	fi
fi

# Check for required tools
command -v bunx &>/dev/null || fail "bunx not found. Is bun installed in the devshell?"
command -v openssl &>/dev/null || fail "openssl not found."

# =============================================================================
# Step 1: Configure alchemy profile
# =============================================================================
step 1 "Configuring alchemy profile..."
info "This will set up Cloudflare OAuth authentication."
info ""

bunx alchemy configure

ok "Alchemy profile configured"

# =============================================================================
# Step 2: Authenticate via OAuth
# =============================================================================
step 2 "Authenticating with Cloudflare..."
info "A browser window will open for OAuth consent."
info ""

bunx alchemy login

ok "Authenticated with Cloudflare"

# =============================================================================
# Step 3: Create API token + state token
# =============================================================================
step 3 "Creating tokens..."

# Create Cloudflare API token
if [ "$TOKEN_SCOPES" = "god" ]; then
	info "Creating god token (full access)..."
	CF_TOKEN=$(bunx alchemy util create-cloudflare-token --god-token 2>&1 | tail -1)
else
	info "Creating scoped token (mirrors OAuth profile permissions)..."
	CF_TOKEN=$(bunx alchemy util create-cloudflare-token --profile default 2>&1 | tail -1)
fi

if [ -z "$CF_TOKEN" ] || [ "$CF_TOKEN" = "undefined" ]; then
	fail "Failed to create Cloudflare API token. Check your alchemy profile."
fi

ok "Cloudflare API token created"

# Generate alchemy state token
STATE_TOKEN=$(openssl rand -base64 32)

ok "Alchemy state token generated"

# =============================================================================
# Step 4: Store tokens
# =============================================================================
step 4 "Storing tokens..."

if [ "$SKIP_SECRETS" = "true" ]; then
	info "Skipping secrets storage (--skip-secrets)."
	info ""
	info "Add these to your environment:"
	echo ""
	echo "  export $CF_TOKEN_ENV_VAR='$CF_TOKEN'"
	echo "  export $STATE_TOKEN_ENV_VAR='$STATE_TOKEN'"
	echo ""
else
	# Store in SOPS via secrets module
	if ! command -v secrets-set &>/dev/null; then
		fail "secrets-set not found. Is the secrets module enabled?"
	fi

	info "Storing in SOPS (group: $SOPS_GROUP)..."

	echo "$CF_TOKEN" | secrets-set cloudflare-api-token --group "$SOPS_GROUP"
	ok "Cloudflare API token saved"

	echo "$STATE_TOKEN" | secrets-set alchemy-state-token --group "$SOPS_GROUP"
	ok "Alchemy state token saved"

	info ""
	info "Tokens encrypted in vars/$SOPS_GROUP.sops.yaml"
	info "Commit this file to share with your team."
fi

# Export for bootstrap step
export "${CF_TOKEN_ENV_VAR}=${CF_TOKEN}"
export "${STATE_TOKEN_ENV_VAR}=${STATE_TOKEN}"

# =============================================================================
# Step 5: Bootstrap state store (optional)
# =============================================================================
if [ "$AUTO_PROVISION" = "true" ]; then
	step 5 "Bootstrapping Cloudflare state store..."

	if [ ! -f "$BOOTSTRAP_FILE" ]; then
		fail "Bootstrap file not found: $BOOTSTRAP_FILE"
	fi

	info "Deploying alchemy-state-service worker..."
	info "This uses filesystem state to avoid the chicken-and-egg problem."

	bunx alchemy deploy "$BOOTSTRAP_FILE" --stage bootstrap --quiet || {
		echo ""
		info "Bootstrap deploy failed. This is usually fine -- the state store"
		info "will be auto-provisioned on your first real deploy."
		info ""
		info "You can retry with: $CF_TOKEN_ENV_VAR=\$($CF_TOKEN_ENV_VAR) bunx alchemy deploy $BOOTSTRAP_FILE --stage bootstrap"
	}

	ok "State store worker deployed"
fi

# =============================================================================
# Done
# =============================================================================
echo ""
echo "  Setup complete!"
echo ""
if [ "$SKIP_SECRETS" != "true" ]; then
	info "Tokens stored in: vars/$SOPS_GROUP.sops.yaml"
	info "Load them with:   secrets:env"
	info ""
fi
info "Alchemy helper:   alchemy:deploy staging"
info "Canonical path:   stackpanel deploy <app>"
info "                  deploy prod"
echo ""
