{
  lib,
  categories,
  sections,
}:
let
  allVariables = lib.flatten [
    (lib.attrValues sections.core)
    (lib.attrValues sections.paths)
    (lib.attrValues sections.agent)
    (lib.attrValues sections.stepca)
    (lib.attrValues sections.aws)
    (lib.attrValues sections.minio)
    (lib.attrValues sections.services)
    (lib.attrValues sections.devenv)
    (lib.attrValues sections.ide)
  ];

  # Get all required variables
  requiredVariables = lib.filter (v: v.required) allVariables;

  # Get variables by category
  byCategory = category: lib.filter (v: v.category == category) allVariables;

  # Get variables by source
  bySource = source: lib.filter (v: v.source == source) allVariables;

  mkValidationScript =
    {
      pkgs,
      strict ? false,
    }:
    pkgs.writeShellScriptBin "stackpanel-validate-env" ''
      #!/usr/bin/env bash
      set -euo pipefail

      ERRORS=0
      WARNINGS=0

      check_required() {
        local var_name="$1"
        local description="$2"
        if [[ -z "''${!var_name:-}" ]]; then
          echo "❌ MISSING: $var_name - $description"
          ((ERRORS++)) || true
        else
          echo "✓ $var_name"
        fi
      }

      echo "Validating Stackpanel environment variables..."
      echo ""

      ${lib.concatMapStringsSep "\n" (v: ''
        check_required "${v.name}" "${v.description}"
      '') requiredVariables}

      echo ""
      if [[ $ERRORS -gt 0 ]]; then
        echo "Found $ERRORS missing required variables"
        ${if strict then "exit 1" else "exit 0"}
      else
        echo "All required variables are set!"
      fi
    '';

  # Generate markdown documentation
  mkDocumentation =
    let
      renderVar = v: ''
        ### `${v.name}`

        ${v.description}

        | Property | Value |
        |----------|-------|
        | Category | ${v.category} |
        | Source | ${v.source} |
        | Required | ${if v.required then "Yes" else "No"} |
        ${lib.optionalString (v.default != null) "| Default | `${v.default}` |"}
        ${lib.optionalString (v.example != null) "| Example | `${v.example}` |"}
        ${lib.optionalString (v.goField != null) "| Go Field | `${v.goField}` |"}
        ${lib.optionalString v.deprecated "| ⚠️ Deprecated | ${
          v.deprecationMessage or "This variable is deprecated"
        } |"}
      '';

      renderCategory = name: vars: ''
        ## ${name}

        ${lib.concatMapStringsSep "\n---\n" renderVar vars}
      '';
    in
    ''
      # Stackpanel Environment Variables Reference

      This document is auto-generated from `nix/stackpanel/core/lib/envvars.nix`.

      ${lib.concatStringsSep "\n" (
        lib.mapAttrsToList (name: _: renderCategory name (byCategory name)) categories
      )}
    '';

  # Generate Go constants file content
  mkGoConstants = ''
      // Code generated by envvars.nix. DO NOT EDIT.
      package envvars

      // Environment variable names used by Stackpanel
      const (
      ${lib.concatMapStringsSep "\n" (v: ''
        // ${v.description}
        ${lib.toUpper (lib.replaceStrings [ "-" " " ] [ "_" "_" ] v.name)} = "${v.name}"
      '') (lib.filter (v: v.source != "devenv") allVariables)}
      )

      // Categories groups environment variables by their purpose
      var Categories = map[string][]string{
      ${lib.concatMapStringsSep "\n" (cat: ''
        	"${cat}": {
              ${lib.concatMapStringsSep ",\n" (
                v: "${lib.toUpper (lib.replaceStrings [ "-" " " ] [ "_" "_" ] v.name)}"
              ) (byCategory cat)}
        	},
      '') (lib.attrValues categories)}
    };
  '';
in
{
  inherit
    allVariables
    requiredVariables
    byCategory
    bySource
    mkValidationScript
    mkDocumentation
    mkGoConstants
    ;
}
