# Generated by prelude setup.
#
# This file is intentionally separate from flake.nix so existing flakes are
# never overwritten. Wire it into your flake-parts flake:
#
#   inputs.prelude.url = "github:darkmatter/prelude";
#   # …
#   flake-parts.lib.mkFlake { inherit inputs; } {
#     imports = [
#       inputs.prelude.flakeModules.default
#       ./prelude.nix          # ← this file
#     ];
#     # …
#     perSystem = { config, ... }: {
#       devShells.default = pkgs.mkShell {
#         packages = [ config.packages.prelude ];
#         shellHook = "motd";
#       };
#     };
#   };
#
# Every supported option is listed below. Values you chose in the wizard are
# active; everything else is commented at its default so you can see and
# enable options without leaving this file. Defaults mirror
# src/prelude/defaults.nix. Full prose reference:
# docs/reference/options.md (regenerated by docs-sync).
#
{ ... }:
{
  prelude = {
    theme = "mono";  # color theme for all components; default "prelude"

    # Per-token overrides on top of the theme (null keeps the theme token).
    # Values: null | hex string | ANSI-256 index.
    # palette.fg = null;
    # palette.muted = null;
    # palette.dim = null;
    # palette.border = null;
    # palette.accentBorder = null;
    # palette.accent = null;
    # palette.accent2 = null;
    # palette.success = null;
    # palette.warning = null;
    # palette.info = null;
    # palette.error = null;
    # palette.selectionFg = null;
    # palette.bg = null;
    # palette.surface = null;
    # palette.secondary = null;

    colorProfile = "auto";  # "auto" | "truecolor" | "ansi256"; default "auto"

    project = "stackpanel";  # shown in the MOTD banner and menu header; default "acme"

    # Project commands keyed by public `x` name. The first colon infers the
    # menu group; the complete key stays callable (e.g. `x db:migrate`).
    # Defaults ship an ACME example catalogue (dev/test/build + database/ops);
    # defining any commands.* replaces that catalogue entirely.
    commands = {

      dev = {
        exec = "dev";  # defaults to the key suffix after the first colon
        description = "run the dev server";
        # group inferred from key: develop  # first colon segment; builtins land in "prelude"
        # key = null;  # single-key accelerator (`x <key>`)
        # usage = "dev";  # usage form shown in menu details
        # details = null;  # extended description before arg entry
        # examples = [ "dev" ];  # worked example invocations
        # args = [ ];  # arg-entry mode: { token, description?, required?, boolean?, options? }
        # invocation = null;  # canonical shell text for duplicate detection; defaults to exec
        motd = 1;  # MOTD Getting Started sort order; null hides from MOTD
      };
    };

    # Static devshell welcome banner.
    motd = {
      enable = true;


      title = {
        text = ./title.txt;  # multiline title file; null uses the project-name wordmark
        # align = "center";  # left|center|right; default "center"
        # style = "spine";  # wordmark when text is null: plain|spine|bracketed|label|inline|inverted
      };

      # background = false;  # block fill: null/false | true (theme bg) | color | { relative } | { blend }
      # windowBackground = false;  # full-width window fill; same value forms as background
      # clearScreen = true;  # clear the terminal before rendering
      # align = "center";  # horizontal placement of the MOTD block: left|center|right
      # width = "full";  # content width or "full"
      # maxWidth = 120;  # maximum content width
      # fullscreen = false;  # fill terminal width with no cap (width=full + maxWidth=null)

      # Outer spacing: top/bottom blank lines, left/right columns (sides supersede x/y).
      # Omitted sides are fine — they fall through to the axis (or 0).
      # margin = {
      #   x = 4;           # horizontal shorthand
      #   y = 0;           # vertical shorthand
      #   top = null;      # supersedes y
      #   bottom = 4;      # supersedes y; gated by minHeight
      #   left = null;     # supersedes x
      #   right = null;    # supersedes x
      #   minHeight = 40;  # apply vertical sides only at/above this terminal height
      # };

      # Inner spacing between content and block edge (sides supersede x/y).
      # padding = {
      #   x = 4;
      #   y = 2;
      #   # top = null;
      #   # bottom = null;
      #   # left = null;
      #   # right = null;
      #   minHeight = 0;
      # };

      # Hero: tagline, status lights, activation copy.
      # header = {
      #   tagline = {
      #     text = "everything you need to build, test & ship";
      #     subtitle = "edit prelude.nix to replace this ACME example with your project";
      #     layout = "stack";  # "stack" | "inline"
      #     align = "left";  # "left" | "center"
      #   };
      #   background = false;  # true = raised bar; null/false = transparent; color | { relative }
      #   statusHint = {
      #     layout = "inline";  # "below" | "inline"
      #     links = [ ];  # terminal hyperlinks after the reload hint: { label, url }
      #   };
      #   # Keyed lights, sorted by order then name. Static: { status }. Live: { check, … }.
      #   status = {
      #     ready = { label = "devshell"; status = "ready"; };
      #     # nix = {
      #     #   order = 100;
      #     #   label = "nix";
      #     #   check = "nix --version >/dev/null";
      #     #   async = true;  # background refresh
      #     #   ok = "ok";
      #     #   fail = "fail";
      #     #   failLevel = "error";  # "error" | "warning"
      #     #   output = "";  # "" | "light" | "diagnostic"
      #     # };
      #   };
      # };

      # Styled text under the header; empty text hides it.
      # description = {
      #   text = ''
      #     You are inside the ACME example devshell — the out-of-the-box Prelude
      #     welcome banner. Set prelude.project, rewrite the tagline and this
      #     description, and replace prelude.commands with your real workflows.
      #     Run menu to browse every command.
      #   '';
      #   foreground = null;  # null uses the theme role color
      #   background = null;  # null/false | true | color | { relative }
      #   bold = false;
      #   italic = false;
      #   faint = false;
      # };

      # links = [ ];  # terminal hyperlinks under the description: { label, url }
      # env = [  # info chips; each sets exactly one of value (static) or probe (command)
      #   { label = "node"; value = "22"; }
      #   { label = "pnpm"; value = "9"; }
      #   { label = "postgres"; value = "16"; }
      #   # { label = "nix"; probe = "nix --version | awk '{print $NF}'"; }
      # ];
      # recipes = {  # multi-step workflows keyed by name
      #   first-run = {
      #     order = 100;
      #     title = "spin up a clean local stack";
      #     steps = [
      #       { comment = "start services, migrate, then run the app"; }
      #       { command = "x database:up"; }
      #       { command = "x database:migrate"; }
      #       { command = "dev"; }
      #     ];
      #   };
      # };

      # Labels for the commands + examples region.
      # gettingStarted = {
      #   heading = "Getting Started";
      #   commandsLabel = "commands";
      #   examplesLabel = "examples";
      #   commandNote = "prefix with `x` if a command is shadowed";  # "" hides it
      # };
    };

    # Interactive command picker (bubbletea TUI).
    menu = {
      enable = true;
      # placeholder = "type to filter commands…";  # filter input hint
      # height = 20;  # filter list height in rows
      # execute = true;  # false prints the selected command instead of running it
      # width = "full";  # content width or "full"
      # maxWidth = 80;
    };

    # Themed starship config (`packages.prompt` = starship.toml).
    prompt = {
      enable = true;
      # settings = { };  # merged over themed defaults; see https://starship.rs/config/
      #   # add_newline = true;
      #   # format = "$directory$git_branch$character";
      # configFile = null;  # use this starship.toml verbatim instead of generating one
    };

    # Markdown pages in the navigable docs viewer. Each file becomes one
    # CONTENTS sidebar entry; digits 1–9 jump between pages. The first
    # level-one heading labels the entry.
    # Starter page written by setup; add more entries as docs grow.
    docs.pages = [ { text = ./docs/getting-started.md; } ];

    # Preferred command-group order. Groups omitted follow alphabetically;
    # the built-in "prelude" group (menu/docs) stays first.
    # sort.groups = [ "develop" "database" "ops" ];
  };
}
