package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var preflightCmd = &cobra.Command{
	Use:   "preflight",
	Short: "Generate config.local.nix from environment variables for pure mode",
	Long: `Generate config.local.nix from environment variables.

This command reads relevant environment variables and generates a config.local.nix
file, allowing you to use pure mode (nix develop without --impure) by materializing
environment-based configuration into a file.

Environment variables processed:
  - STACKPANEL_ROOT: Project root directory
  - AWS_*: AWS configuration and credentials
  - STEP_CA_*: Step CA configuration
  - Other stackpanel-specific variables

After running this, you can use 'nix develop' (without --impure) and direnv
will work in pure mode, making evaluation fully reproducible.`,
	RunE: runPreflight,
}

var (
	preflightDryRun bool
	preflightForce  bool
)

func init() {
	rootCmd.AddCommand(preflightCmd)
	preflightCmd.Flags().BoolVar(&preflightDryRun, "dry-run", false, "Show what would be generated without writing files")
	preflightCmd.Flags().BoolVar(&preflightForce, "force", false, "Overwrite existing config.local.nix")
}

func runPreflight(cmd *cobra.Command, args []string) error {
	// Find project root
	projectRoot := os.Getenv("STACKPANEL_ROOT")
	if projectRoot == "" {
		var err error
		projectRoot, err = findProjectRoot()
		if err != nil {
			return fmt.Errorf("could not find project root: %w", err)
		}
	}

	// Collect environment variables to materialize
	envConfig := collectEnvConfig()

	// Generate Nix expression
	nixExpr := generateNixConfig(envConfig)

	if preflightDryRun {
		fmt.Println("# Would generate the following config.local.nix:")
		fmt.Println(nixExpr)
		fmt.Printf("\n# Project root: %s\n", projectRoot)
		return nil
	}

	// Write .stackpanel-root marker
	markerPath := filepath.Join(projectRoot, ".stackpanel-root")
	if err := os.WriteFile(markerPath, []byte(projectRoot+"\n"), 0644); err != nil {
		return fmt.Errorf("failed to write .stackpanel-root marker: %w", err)
	}

	// Write config.local.nix
	configPath := filepath.Join(projectRoot, ".stackpanel", "config.local.nix")
	if !preflightForce {
		if _, err := os.Stat(configPath); err == nil {
			return fmt.Errorf("config.local.nix already exists (use --force to overwrite)")
		}
	}

	if err := os.WriteFile(configPath, []byte(nixExpr), 0644); err != nil {
		return fmt.Errorf("failed to write config.local.nix: %w", err)
	}

	fmt.Printf("✅ Generated config.local.nix\n")
	fmt.Printf("   Project root: %s\n", projectRoot)
	fmt.Printf("   Config file: %s\n", configPath)
	fmt.Printf("\n💡 You can now use pure mode:\n")
	fmt.Printf("   nix develop  # (without --impure)\n")
	fmt.Printf("   direnv allow # (will use pure mode)\n")

	return nil
}

// envConfig holds environment variable configuration
type envConfig struct {
	// AWS Configuration
	AWSProfileARN      string
	AWSRoleARN         string
	AWSTrustAnchorARN  string
	AWSRegion          string
	AWSAccessKeyID     string
	AWSSecretAccessKey string
	AWSSessionToken    string

	// Step CA Configuration
	StepCAURL         string
	StepCAFingerprint string
	StepCACert        string

	// Stackpanel paths (not typically needed, but available)
	StackpanelRoot       string
	StackpanelConfigJSON string
	StackpanelStateDir   string
}

// collectEnvConfig reads relevant environment variables
func collectEnvConfig() envConfig {
	return envConfig{
		// AWS
		AWSProfileARN:      os.Getenv("AWS_PROFILE_ARN"),
		AWSRoleARN:         os.Getenv("AWS_ROLE_ARN"),
		AWSTrustAnchorARN:  os.Getenv("AWS_TRUST_ANCHOR_ARN"),
		AWSRegion:          getAWSRegion(),
		AWSAccessKeyID:     os.Getenv("AWS_ACCESS_KEY_ID"),
		AWSSecretAccessKey: os.Getenv("AWS_SECRET_ACCESS_KEY"),
		AWSSessionToken:    os.Getenv("AWS_SESSION_TOKEN"),

		// Step CA
		StepCAURL:         os.Getenv("STEP_CA_URL"),
		StepCAFingerprint: os.Getenv("STEP_CA_FINGERPRINT"),
		StepCACert:        os.Getenv("STEP_CA_CERT"),

		// Stackpanel (usually not needed in config.local.nix)
		StackpanelRoot:       os.Getenv("STACKPANEL_ROOT"),
		StackpanelConfigJSON: os.Getenv("STACKPANEL_CONFIG_JSON"),
		StackpanelStateDir:   os.Getenv("STACKPANEL_STATE_DIR"),
	}
}

// getAWSRegion returns AWS region with fallback
func getAWSRegion() string {
	if region := os.Getenv("AWS_REGION"); region != "" {
		return region
	}
	return os.Getenv("AWS_DEFAULT_REGION")
}

// generateNixConfig generates a Nix expression from environment config
func generateNixConfig(cfg envConfig) string {
	var sb strings.Builder

	sb.WriteString("# config.local.nix\n")
	sb.WriteString("# Generated by: stackpanel preflight\n")
	sb.WriteString("#\n")
	sb.WriteString("# This file materializes environment variables into Nix configuration,\n")
	sb.WriteString("# enabling pure mode evaluation (nix develop without --impure).\n")
	sb.WriteString("#\n")
	sb.WriteString("# To regenerate: stackpanel preflight --force\n")
	sb.WriteString("# To remove: rm .stackpanel/config.local.nix && use impure mode again\n")
	sb.WriteString("{\n")

	hasAnyConfig := false

	// AWS Configuration
	if hasAWSConfig(cfg) {
		hasAnyConfig = true
		sb.WriteString("  # AWS Configuration\n")
		sb.WriteString("  aws = {\n")

		if cfg.AWSProfileARN != "" {
			sb.WriteString(fmt.Sprintf("    profileArn = %s;\n", nixString(cfg.AWSProfileARN)))
		}
		if cfg.AWSRoleARN != "" {
			sb.WriteString(fmt.Sprintf("    roleArn = %s;\n", nixString(cfg.AWSRoleARN)))
		}
		if cfg.AWSTrustAnchorARN != "" {
			sb.WriteString(fmt.Sprintf("    trustAnchorArn = %s;\n", nixString(cfg.AWSTrustAnchorARN)))
		}
		if cfg.AWSRegion != "" {
			sb.WriteString(fmt.Sprintf("    region = %s;\n", nixString(cfg.AWSRegion)))
		}

		sb.WriteString("  };\n\n")
	}

	// Step CA Configuration
	if hasStepCAConfig(cfg) {
		hasAnyConfig = true
		sb.WriteString("  # Step CA Configuration\n")
		sb.WriteString("  stepCA = {\n")

		if cfg.StepCAURL != "" {
			sb.WriteString(fmt.Sprintf("    url = %s;\n", nixString(cfg.StepCAURL)))
		}
		if cfg.StepCAFingerprint != "" {
			sb.WriteString(fmt.Sprintf("    fingerprint = %s;\n", nixString(cfg.StepCAFingerprint)))
		}
		if cfg.StepCACert != "" {
			sb.WriteString(fmt.Sprintf("    cert = %s;\n", nixString(cfg.StepCACert)))
		}

		sb.WriteString("  };\n\n")
	}

	// Note about secrets
	if cfg.AWSAccessKeyID != "" || cfg.AWSSecretAccessKey != "" || cfg.AWSSessionToken != "" {
		sb.WriteString("  # Note: AWS credentials are NOT included in config.local.nix for security.\n")
		sb.WriteString("  # Use secrets management (vals/sops) or shell environment for credentials.\n")
		sb.WriteString("  # The following are available via environment only:\n")
		sb.WriteString("  #   - AWS_ACCESS_KEY_ID\n")
		sb.WriteString("  #   - AWS_SECRET_ACCESS_KEY\n")
		sb.WriteString("  #   - AWS_SESSION_TOKEN\n\n")
	}

	if !hasAnyConfig {
		sb.WriteString("  # No configuration found in environment variables.\n")
		sb.WriteString("  # This file can be deleted if not needed.\n")
	}

	sb.WriteString("}\n")

	return sb.String()
}

// nixString escapes a string for Nix
func nixString(s string) string {
	// Escape special characters for Nix strings
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "${", "\\${")
	return fmt.Sprintf(`"%s"`, s)
}

// hasAWSConfig checks if any AWS configuration is present
func hasAWSConfig(cfg envConfig) bool {
	return cfg.AWSProfileARN != "" ||
		cfg.AWSRoleARN != "" ||
		cfg.AWSTrustAnchorARN != "" ||
		cfg.AWSRegion != ""
}

// hasStepCAConfig checks if any Step CA configuration is present
func hasStepCAConfig(cfg envConfig) bool {
	return cfg.StepCAURL != "" ||
		cfg.StepCAFingerprint != "" ||
		cfg.StepCACert != ""
}
