package testclient
package main


































































}	}		c.WriteMessage(websocket.CloseMessage, websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))		fmt.Println("Interrupted")	case <-interrupt:	case <-done:	select {	c.WriteMessage(websocket.TextMessage, data)	fmt.Printf("Sending: %s\n", data)	data, _ := json.Marshal(msg)	}		"payload": map[string]interface{}{},		"type":    "nix.generate",		"id":      "1",	msg := map[string]interface{}{	// Example: run nix generate	}()		}			fmt.Printf("Response:\n%s\n", pretty)			pretty, _ := json.MarshalIndent(resp, "", "  ")			json.Unmarshal(message, &resp)			var resp map[string]interface{}			}				return				fmt.Println("read error:", err)			if err != nil {			_, message, err := c.ReadMessage()		for {		defer close(done)	go func() {	// Read messages	done := make(chan struct{})	signal.Notify(interrupt, os.Interrupt)	interrupt := make(chan os.Signal, 1)	// Handle interrupt	defer c.Close()	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "dial error: %v\n", err)	if err != nil {	c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)	fmt.Printf("Connecting to %s\n", u.String())	u := url.URL{Scheme: "ws", Host: *addr, Path: "/ws"}	flag.Parse()	addr := flag.String("addr", "localhost:9876", "Agent address")func main() {// Simple CLI client for testing the agent)	"github.com/gorilla/websocket"	"os/signal"	"os"	"net/url"	"fmt"	"flag"	"encoding/json"import (
