# ==============================================================================
# module.nix - Entrypoints Module Implementation
#
# Nix module for generating per-app entrypoint shell scripts.
#
# Each app defined in stackpanel.apps can have an entrypoint generated that:
#   - Auto-sources devshell in dev mode
#   - Loads secrets for the appropriate environment
#   - Sets up environment variables
#
# IMPORTANT: Entrypoints ONLY inject environment variables. They do NOT run
# commands. The caller is responsible for running the actual command after
# sourcing the entrypoint.
#
# Generated entrypoints are written to packages/scripts/entrypoints/<app>.sh
# via the stackpanel.files system.
#
# Usage (source the entrypoint, then run your command):
#   source packages/scripts/entrypoints/web.sh --dev
#   bun run dev
#
# Or in process-compose:
#   command: "source packages/scripts/entrypoints/web.sh --dev && bun run dev"
# ==============================================================================
{
  lib,
  config,
  pkgs,
  ...
}:
let
  meta = import ./meta.nix;
  cfg = config.stackpanel;

  # Variables backend config
  variablesBackend = cfg.secrets.backend or "vals";
  isChamber = variablesBackend == "chamber";
  chamberServicePrefix =
    if isChamber then (cfg.secrets.chamber.service-prefix or cfg.name or "stackpanel") else "";

  # Get master keys config for secrets loading (use empty default to avoid recursion)
  secretsCfg = cfg.secrets or { };
  masterKeysConfig = secretsCfg.master-keys or { };
  masterKeysJson = builtins.toJSON (
    lib.mapAttrs (name: key: {
      age-pub = key.age-pub or "";
      ref = key.ref or "";
      "resolve-cmd" = key.resolve-cmd or null;
    }) masterKeysConfig
  );

  # Generate entrypoint shell script for an app
  # NOTE: This function is called lazily inside mkIf, so it's safe to access app options
  #
  # IMPORTANT: Entrypoints ONLY set up environment variables. They do NOT run commands.
  # The caller should source this script, then run their command.
  generateEntrypointSh =
    name: app:
    let
      appPath = app.path or "apps/${name}";
    in
    ''
      #!/usr/bin/env bash
      # ==============================================================================
      # Auto-generated entrypoint for ${name}
      # Generated by stackpanel - do not edit manually
      # Regenerate by entering the devshell: nix develop --impure
      #
      # This script ONLY sets up environment variables. It does NOT run commands.
      # Source this script, then run your command:
      #
      #   source packages/scripts/entrypoints/${name}.sh --dev
      #   bun run dev
      #
      # Or inline:
      #   source packages/scripts/entrypoints/${name}.sh --dev && bun run dev
      # ==============================================================================

      # Prevent execution - this script should only be sourced
      if [[ "''${BASH_SOURCE[0]}" == "''${0}" ]]; then
        echo "[ERROR] This script should be sourced, not executed directly." >&2
        echo "Usage: source $0 [--dev] [--env <env>] [--no-secrets]" >&2
        exit 1
      fi

      # Find script directory and source common library
      _ENTRYPOINT_SCRIPT_DIR="$(cd "$(dirname "''${BASH_SOURCE[0]}")" && pwd)"
      _ENTRYPOINT_LIB_DIR="$(dirname "$_ENTRYPOINT_SCRIPT_DIR")/lib"

      if [[ -f "$_ENTRYPOINT_LIB_DIR/common.sh" ]]; then
        source "$_ENTRYPOINT_LIB_DIR/common.sh"
      else
        echo "[ERROR] Could not find common.sh at $_ENTRYPOINT_LIB_DIR/common.sh" >&2
        return 1
      fi

      # ==============================================================================
      # App Configuration (from Nix)
      # ==============================================================================

      export STACKPANEL_APP_NAME="${name}"
      export STACKPANEL_APP_PATH="${appPath}"
      export STACKPANEL_VARIABLES_BACKEND="${variablesBackend}"
      ${if isChamber then ''export STACKPANEL_CHAMBER_SERVICE_PREFIX="${chamberServicePrefix}"'' else ""}
      export STACKPANEL_MASTER_KEYS='${masterKeysJson}'

      # ==============================================================================
      # Argument Parsing
      # ==============================================================================

      _ENTRYPOINT_DEV_MODE=false
      _ENTRYPOINT_ENVIRONMENT=""
      _ENTRYPOINT_SKIP_SECRETS=false

      while [[ $# -gt 0 ]]; do
        case "$1" in
          --dev)
            _ENTRYPOINT_DEV_MODE=true
            shift
            ;;
          --env)
            _ENTRYPOINT_ENVIRONMENT="$2"
            shift 2
            ;;
          --no-secrets)
            _ENTRYPOINT_SKIP_SECRETS=true
            shift
            ;;
          *)
            # Ignore unknown args (they're for the command, not for us)
            shift
            ;;
        esac
      done

      # Set default environment
      if [[ -z "$_ENTRYPOINT_ENVIRONMENT" ]]; then
        if [[ "$_ENTRYPOINT_DEV_MODE" == "true" ]]; then
          _ENTRYPOINT_ENVIRONMENT="dev"
        else
          _ENTRYPOINT_ENVIRONMENT="prod"
        fi
      fi

      # Export environment for downstream use
      export STACKPANEL_ENVIRONMENT="$_ENTRYPOINT_ENVIRONMENT"
      export STACKPANEL_DEV_MODE="$_ENTRYPOINT_DEV_MODE"

      log_debug "Entrypoint: ${name}"
      log_debug "Environment: $_ENTRYPOINT_ENVIRONMENT"
      log_debug "Dev mode: $_ENTRYPOINT_DEV_MODE"

      # ==============================================================================
      # Environment Setup
      # ==============================================================================

      _ENTRYPOINT_PROJECT_ROOT=$(find_project_root) || { log_error "Could not find project root"; return 1; }
      export STACKPANEL_PROJECT_ROOT="$_ENTRYPOINT_PROJECT_ROOT"

      # Dev mode: ensure devshell environment
      if [[ "$_ENTRYPOINT_DEV_MODE" == "true" ]]; then
        ensure_devshell || { log_error "Failed to set up devshell"; return 1; }
      fi

      # Load secrets (unless skipped)
      if [[ "$_ENTRYPOINT_SKIP_SECRETS" != "true" ]] && [[ "''${STACKPANEL_NO_SECRETS:-}" != "1" ]]; then
        load_secrets "$STACKPANEL_APP_NAME" "$_ENTRYPOINT_ENVIRONMENT" || log_warn "Secrets loading failed, continuing anyway"
      fi

      # ==============================================================================
      # Done - environment is now set up
      # ==============================================================================

      log_debug "Entrypoint complete - environment ready for ${name}"

      # Clean up internal variables (keep exported ones)
      unset _ENTRYPOINT_SCRIPT_DIR _ENTRYPOINT_LIB_DIR
      unset _ENTRYPOINT_DEV_MODE _ENTRYPOINT_ENVIRONMENT _ENTRYPOINT_SKIP_SECRETS
      unset _ENTRYPOINT_PROJECT_ROOT
    '';

  # Entrypoint options submodule - defined at top level
  entrypointModule =
    { lib, ... }:
    {
      options = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = ''
            Whether to generate an entrypoint for this app.

            Entrypoints only set up environment variables (devshell, secrets).
            They do NOT run commands - the caller is responsible for that.
          '';
        };
      };
    };

in
{
  # ===========================================================================
  # Configuration
  # ===========================================================================
  config = lib.mkMerge [
    # Add entrypoint option to all apps via appModules
    {
      stackpanel.appModules = [
        (
          { lib, ... }:
          {
            options.entrypoint = lib.mkOption {
              type = lib.types.submodule entrypointModule;
              default = { };
              description = ''
                Entrypoint configuration for this app.

                When enabled (default), generates a sourceable shell script at
                packages/scripts/entrypoints/<app>.sh that:
                - Auto-sources devshell in --dev mode
                - Loads secrets for the appropriate environment
                - Exports environment variables

                IMPORTANT: Entrypoints ONLY set up environment. They do NOT run
                commands. Source the script, then run your command:

                  source packages/scripts/entrypoints/<app>.sh --dev
                  bun run dev
              '';
            };
          }
        )
      ];
    }

    # Generate entrypoint files when apps are defined
    # NOTE: We compute appsWithEntrypoints lazily here (inside the config block)
    # to avoid infinite recursion with appModules
    (
      let
        # Filter apps that have entrypoints enabled
        # Only check for 'path' attribute which is user-defined (not via appModules)
        # The entrypoint.enable check is done lazily in the filter function
        appsWithPaths = lib.filterAttrs (name: app: (app.path or null) != null) cfg.apps;

        # Further filter by entrypoint.enable (now safe since we're inside mkMerge)
        appsWithEntrypoints = lib.filterAttrs (name: app: (app.entrypoint.enable or true)) appsWithPaths;

        hasApps = appsWithEntrypoints != { };
      in
      lib.mkIf hasApps {
        # Generate entrypoint shell scripts via files system
        stackpanel.files.entries = lib.mkMerge (
          lib.mapAttrsToList (name: app: {
            "packages/scripts/entrypoints/${name}.sh" = {
              type = "text";
              mode = "0755"; # executable
              text = generateEntrypointSh name app;
              source = meta.id;
              description = "Entrypoint script for ${name}";
            };
          }) appsWithEntrypoints
        );

        # Also create as Nix derivations for flake outputs
        stackpanel.outputs = lib.mapAttrs' (name: app: {
          name = "${name}-entrypoint";
          value = pkgs.writeShellApplication {
            name = "${name}-entrypoint";
            runtimeInputs = [ ]; # Dependencies are loaded via devshell
            text = generateEntrypointSh name app;
          };
        }) appsWithEntrypoints;

        # Register module
        stackpanel.modules.${meta.id} = {
          enable = true;
          meta = {
            name = meta.name;
            description = meta.description;
            icon = meta.icon;
            category = meta.category;
            author = meta.author;
            version = meta.version;
            homepage = meta.homepage;
          };
          source.type = "builtin";
          features = meta.features;
          flakeInputs = meta.flakeInputs or [ ];
          tags = meta.tags;
          priority = meta.priority;
        };
      }
    )
  ];
}
