# ==============================================================================
# clean.nix
#
# Clean environment support for stackpanel devshells.
#
# This module:
# 1. Generates a `dev-clean` script in the shell
# 2. Generates a standalone `./devshell` script in the repo root
# 3. Provides sensible defaults for env vars to preserve
#
# Usage (after first shell entry):
#   dev-clean
#
# Usage (from fresh clone - run the generated script):
#   ./devshell
#
# Or manually:
#   nix develop --ignore-environment --impure \
#     --keep HOME --keep USER --keep SSH_AUTH_SOCK ...
# ==============================================================================
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.stackpanel.devshell.clean;
  spCfg = config.stackpanel;

  # Generate --keep flags for nix develop (single line, for dev-clean script)
  keepFlags = lib.concatMapStringsSep " " (v: "--keep ${v}") cfg.keep;

  # Generate --keep flags with line continuation (multi-line, for ./devshell script)
  keepFlagsMultiLine = lib.concatMapStringsSep " \\\n  " (v: "--keep ${v}") cfg.keep;

  # Generate the dev-clean wrapper script (for use inside shell)
  devCleanScript = pkgs.writeShellApplication {
    name = "dev-clean";
    runtimeInputs = [ ];
    text = ''
      # dev-clean: Enter the devshell with a clean environment
      # Generated by stackpanel.devshell.clean
      
      # Find the flake root (look for flake.nix)
      find_flake_root() {
        local dir="$PWD"
        while [[ "$dir" != "/" ]]; do
          if [[ -f "$dir/flake.nix" ]]; then
            echo "$dir"
            return 0
          fi
          dir="$(dirname "$dir")"
        done
        echo "Error: Could not find flake.nix" >&2
        return 1
      }
      
      FLAKE_ROOT="$(find_flake_root)"
      
      echo "🧹 Entering clean environment..."
      echo "   Keeping: ${lib.concatStringsSep ", " cfg.keep}"
      
      cd "$FLAKE_ROOT"
      exec nix develop --ignore-environment --impure ${keepFlags} "$@"
    '';
  };

  # Content for the standalone ./devshell script (checked into repo)
  devScriptContent = ''
    #!/usr/bin/env bash
    # devshell - Enter a clean development environment
    # 
    # This script enters the Nix devshell with a clean environment,
    # ignoring host shell aliases and most environment variables.
    #
    # Generated by stackpanel. Regenerate with: nix develop --impure -c devshell-regen
    #
    # Usage:
    #   ./devshell              # Enter clean devshell (interactive)
    #   ./devshell --dirty      # Enter normal devshell (inherit host env)
    #   ./devshell -- <cmd>     # Run a one-off command in the devshell
    #
    set -euo pipefail

    cd "$(dirname "$0")"

    if [[ "''${1:-}" == "--direnv" ]]; then
      shift
      nix develop \
        --ignore-environment \
        --impure \
        ${keepFlagsMultiLine} \
        --command env -0 "$@" \
      | while IFS= read -r -d ''' kv; do
          key="''${kv%%=*}"
          val="''${kv#*=}"
          printf 'export %s=%q\n' "$key" "$val"
        done
      exit
    fi

    if [[ "''${1:-}" == "--dirty" ]]; then
      shift
      echo "🔧 Entering devshell (inheriting host environment)..."
      exec nix develop --impure "$@"
    fi

    # Check for -- separator (run one-off command)
    if [[ "''${1:-}" == "--" ]]; then
      shift
      if [[ $# -eq 0 ]]; then
        echo "Error: No command specified after --" >&2
        echo "Usage: ./devshell -- <command> [args...]" >&2
        exit 1
      fi
      exec nix develop \
        --ignore-environment \
        --impure \
        ${keepFlagsMultiLine} \
        --command "$@"
    fi

    echo "🧹 Entering clean devshell..."
    exec nix develop \
      --ignore-environment \
      --impure \
      ${keepFlagsMultiLine} \
      "$@"
  '';

  # Also generate a script to print current env vars (useful for debugging)
  devEnvScript = pkgs.writeShellApplication {
    name = "dev-env";
    text = ''
      # dev-env: Show current environment variables
      echo "=== Environment Variables ==="
      env | sort
    '';
  };

  # Write devScriptContent to a file in the store for the regen script to copy
  devScriptFile = pkgs.writeText "devshell-script" devScriptContent;

  # Script to regenerate the ./devshell file
  devshellRegenScript = pkgs.writeShellApplication {
    name = "devshell-regen";
    runtimeInputs = [ ];
    text = ''
      # Regenerate the ./devshell script
      FLAKE_ROOT="''${STACKPANEL_ROOT:-$PWD}"
      DEV_SCRIPT="$FLAKE_ROOT/devshell"
      
      cp "${devScriptFile}" "$DEV_SCRIPT"
      chmod +x "$DEV_SCRIPT"
      echo "✅ Generated $DEV_SCRIPT"
    '';
  };

in
{
  config = lib.mkMerge [
    # Always add dev-clean script when stackpanel is enabled
    (lib.mkIf spCfg.enable {
      # Add the clean wrapper script to the shell (always available)
      stackpanel.devshell.packages = [
        devCleanScript
        devEnvScript
        devshellRegenScript
      ];

      # Generate the ./devshell script as a file
      stackpanel.files.entries."devshell" = {
        enable = true;
        type = "text";
        text = devScriptContent;
        mode = "0755";
        source = "clean.nix";
        description = "Clean devshell entry script";
      };

      # Export marker for clean environment detection
      stackpanel.devshell.env.__STACKPANEL_CLEAN_ENV = lib.mkDefault "";
    })

    # Show tip only when clean.enable is true
    (lib.mkIf (spCfg.enable && cfg.enable) {
      stackpanel.devshell.hooks.after = lib.mkAfter [
        ''
          if [[ -z "''${__STACKPANEL_CLEAN_ENV:-}" ]]; then
            echo "💡 Run './devshell' or 'dev-clean' for a clean environment"
          else
            echo "🧹 Clean environment active (keeping ${toString (builtins.length cfg.keep)} env vars)"
          fi
        ''
      ];
    })
  ];
}
