# ==============================================================================
# direnv.nix
#
# Direnv integration for Stackpanel clean devshell settings.
#
# This module generates direnv configuration that respects:
# - stackpanel.devshell.clean.impure (whether to use --impure flag)
# - stackpanel.devshell.clean.keep (environment variables to preserve)
#
# Generated files:
# - .envrc.local: User-specific direnv settings (gitignored)
# - .stackpanel/gen/direnv-wrapper.sh: Wrapper script for nix print-dev-env
# ==============================================================================
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.stackpanel.devshell.clean;
  spCfg = config.stackpanel;

  # Impure flag (with leading space if enabled)
  impureFlag = lib.optionalString cfg.impure "--impure";

  # Generate --keep flags for nix develop/print-dev-env
  keepFlags = lib.concatMapStringsSep " " (v: "--keep ${lib.escapeShellArg v}") cfg.keep;

  # Generate direnv-compatible environment variable exports
  # This ensures these vars are preserved even in clean mode
  keepExports = lib.concatMapStringsSep "\n" (v: ''
    export_if_set ${lib.escapeShellArg v}
  '') cfg.keep;

  # Wrapper script for nix print-dev-env that respects clean settings
  direnvWrapperScript = pkgs.writeShellScript "direnv-wrapper" ''
    # Wrapper for nix print-dev-env that respects stackpanel clean settings
    # Generated by: nix/stackpanel/devshell/direnv.nix

    set -euo pipefail

    # Find project root
    GIT_ROOT="''${STACKPANEL_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
    cd "$GIT_ROOT"

    # Run nix print-dev-env with clean settings
    ${
      if cfg.enable then
        # Clean mode: use --ignore-environment with selective --keep
        ''
          nix print-dev-env \
            --ignore-environment \
            ${impureFlag} \
            ${keepFlags} \
            "$@"
        ''
      else
        # Normal mode: just use impure flag if set
        ''
          nix print-dev-env ${impureFlag} "$@"
        ''
    }
  '';

  # Content for .envrc.local (user-specific direnv settings)
  envrcLocalContent = ''
    # -*- mode: sh -*-
    # shellcheck shell=bash
    # .envrc.local - Stackpanel direnv configuration
    #
    # This file is auto-generated by stackpanel and contains settings for:
    # - Clean environment mode (${if cfg.enable then "enabled" else "disabled"})
    # - Impure mode (${if cfg.impure then "enabled" else "disabled"})
    # - Environment variables to keep (${toString (builtins.length cfg.keep)} vars)
    #
    # To regenerate: nix develop --impure -c stackpanel generate
    # =============================================================================

    ${lib.optionalString cfg.enable ''
      # Helper function to export a variable only if it's set in parent environment
      export_if_set() {
        local var_name="$1"
        if [[ -n "''${!var_name:-}" ]]; then
          export "$var_name"
        fi
      }

      # Preserve clean environment variables
      ${keepExports}
    ''}

    # Stackpanel settings
    export STACKPANEL_CLEAN_MODE="${if cfg.enable then "1" else "0"}"
    export STACKPANEL_CLEAN_IMPURE="${if cfg.impure then "1" else "0"}"
    ${lib.optionalString cfg.enable ''
      export __STACKPANEL_CLEAN_ENV="1"
    ''}

    # Use wrapper script for nix print-dev-env (respects clean settings)
    # Override the default ./devshell --direnv behavior if needed
    _sp_direnv_wrapper="$PWD/.stackpanel/gen/direnv-wrapper.sh"
    if [[ -f "$_sp_direnv_wrapper" ]]; then
      # Custom function to use our wrapper instead of ./devshell --direnv
      use_stackpanel_clean() {
        watch_file .stackpanel/config.nix
        watch_file .stackpanel/config.local.nix
        watch_file flake.nix
        watch_file flake.lock

        # Use cached env if available, otherwise generate fresh
        _sp_cached_env="$PWD/.stackpanel/gen/nix-print-dev-env.sh"
        if [[ -f "$_sp_cached_env" ]]; then
          watch_file "$_sp_cached_env"
          source "$_sp_cached_env"
        else
          eval "$("$_sp_direnv_wrapper")"
        fi
      }

      # Uncomment to use clean mode in direnv (default uses ./devshell --direnv)
      ${lib.optionalString cfg.enable "# use_stackpanel_clean"}
    fi
  '';

  # Documentation comment for .envrc
  envrcComment = ''
    # =============================================================================
    # Stackpanel Clean Mode Settings
    #
    # Current configuration:
    #   Clean mode: ${if cfg.enable then "enabled" else "disabled"}
    #   Impure: ${if cfg.impure then "enabled" else "disabled"}
    #   Preserved vars: ${toString (builtins.length cfg.keep)}
    #
    # To use clean mode in direnv, add to .envrc.local:
    #   use_stackpanel_clean
    #
    # Or regenerate .envrc.local with:
    #   nix develop --impure -c stackpanel generate
    # =============================================================================
  '';

in
{
  options.stackpanel.devshell.clean.direnv = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = cfg.enable;
      description = ''
        Enable direnv integration for clean devshell settings.

        When enabled, generates:
        - .envrc.local with clean mode configuration
        - .stackpanel/gen/direnv-wrapper.sh for nix print-dev-env

        This allows direnv to respect stackpanel.devshell.clean settings.
      '';
    };

    generateEnvrcLocal = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Generate .envrc.local file with direnv configuration.

        Set to false if you want to manage .envrc.local manually.
      '';
    };
  };

  config = lib.mkIf spCfg.enable {
    # Generate direnv wrapper script
    stackpanel.files.entries.".stackpanel/gen/direnv-wrapper.sh" = {
      enable = true;
      type = "text";
      text = builtins.readFile direnvWrapperScript;
      mode = "0755";
      source = "devshell/direnv.nix";
      description = "Direnv wrapper for nix print-dev-env with clean settings";
    };

    # Generate .envrc.local if enabled
    stackpanel.files.entries.".envrc.local" = lib.mkIf (cfg.direnv.enable && cfg.direnv.generateEnvrcLocal) {
      enable = true;
      type = "text";
      text = envrcLocalContent;
      mode = "0644";
      source = "devshell/direnv.nix";
      description = "User-specific direnv configuration for stackpanel";
    };

    # Add hint to shell hook about direnv integration
    stackpanel.devshell.hooks.after = lib.mkIf cfg.direnv.enable (lib.mkAfter [
      ''
        # Check if direnv is active and show clean mode status
        if [[ -n "''${DIRENV_DIR:-}" ]]; then
          if [[ -n "''${__STACKPANEL_CLEAN_ENV:-}" ]]; then
            echo "🧹 Direnv: Clean mode active (${toString (builtins.length cfg.keep)} preserved vars)" >&2
          elif [[ "${toString cfg.enable}" == "true" ]]; then
            echo "💡 Direnv: Clean mode available (add 'use_stackpanel_clean' to .envrc.local)" >&2
          fi
        fi
      ''
    ]);

    # Add MOTD hint about direnv clean mode
    stackpanel.motd.hints = lib.mkIf (cfg.enable && cfg.direnv.enable) [
      "Direnv clean mode: add 'use_stackpanel_clean' to .envrc.local"
    ];

    # Export settings for debugging
    stackpanel.devshell.env.STACKPANEL_CLEAN_MODE = if cfg.enable then "1" else "0";
    stackpanel.devshell.env.STACKPANEL_CLEAN_IMPURE = if cfg.impure then "1" else "0";
  };
}
