// Code generated by protoc-gen-connect-handlers. DO NOT EDIT.
// Source: agent.proto

package server

import (
	"context"
	"encoding/json"

	"connectrpc.com/connect"
	gopb "github.com/darkmatter/stackpanel/packages/proto/gen/gopb"
	"google.golang.org/protobuf/encoding/protojson"
)

// GetVariables retrieves the variables entity from Nix data.
// Generated from proto - do not edit manually.
func (s *AgentServiceServer) GetVariables(
	ctx context.Context,
	req *connect.Request[gopb.GetVariablesRequest],
) (*connect.Response[gopb.Variables], error) {
	data, err := s.server.readNixEntityJSON("variables")
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	var result gopb.Variables
	if len(data) > 0 {
		if err := protojson.Unmarshal(data, &result); err != nil {
			// Fall back to standard JSON if protojson fails
			if err := json.Unmarshal(data, &result); err != nil {
				return nil, connect.NewError(connect.CodeInternal, err)
			}
		}
	}

	return connect.NewResponse(&result), nil
}

// GetModuleOutputs retrieves the moduleoutputs entity from Nix data.
// Generated from proto - do not edit manually.
func (s *AgentServiceServer) GetModuleOutputs(
	ctx context.Context,
	req *connect.Request[gopb.GetModuleOutputsRequest],
) (*connect.Response[gopb.ModuleOutputs], error) {
	data, err := s.server.readNixEntityJSON("moduleoutputs")
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	var result gopb.ModuleOutputs
	if len(data) > 0 {
		if err := protojson.Unmarshal(data, &result); err != nil {
			// Fall back to standard JSON if protojson fails
			if err := json.Unmarshal(data, &result); err != nil {
				return nil, connect.NewError(connect.CodeInternal, err)
			}
		}
	}

	return connect.NewResponse(&result), nil
}

// GetSecrets retrieves the secrets entity from Nix data.
// Generated from proto - do not edit manually.
func (s *AgentServiceServer) GetSecrets(
	ctx context.Context,
	req *connect.Request[gopb.GetSecretsRequest],
) (*connect.Response[gopb.Secrets], error) {
	data, err := s.server.readNixEntityJSON("secrets")
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	var result gopb.Secrets
	if len(data) > 0 {
		if err := protojson.Unmarshal(data, &result); err != nil {
			// Fall back to standard JSON if protojson fails
			if err := json.Unmarshal(data, &result); err != nil {
				return nil, connect.NewError(connect.CodeInternal, err)
			}
		}
	}

	return connect.NewResponse(&result), nil
}

// GetUsers retrieves the users entity from Nix data.
// Generated from proto - do not edit manually.
func (s *AgentServiceServer) GetUsers(
	ctx context.Context,
	req *connect.Request[gopb.GetUsersRequest],
) (*connect.Response[gopb.Users], error) {
	data, err := s.server.readNixEntityJSON("users")
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	var result gopb.Users
	if len(data) > 0 {
		if err := protojson.Unmarshal(data, &result); err != nil {
			// Fall back to standard JSON if protojson fails
			if err := json.Unmarshal(data, &result); err != nil {
				return nil, connect.NewError(connect.CodeInternal, err)
			}
		}
	}

	return connect.NewResponse(&result), nil
}

// GetApps retrieves the apps entity from Nix data.
// Generated from proto - do not edit manually.
func (s *AgentServiceServer) GetApps(
	ctx context.Context,
	req *connect.Request[gopb.GetAppsRequest],
) (*connect.Response[gopb.Apps], error) {
	data, err := s.server.readNixEntityJSON("apps")
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	var result gopb.Apps
	if len(data) > 0 {
		if err := protojson.Unmarshal(data, &result); err != nil {
			// Fall back to standard JSON if protojson fails
			if err := json.Unmarshal(data, &result); err != nil {
				return nil, connect.NewError(connect.CodeInternal, err)
			}
		}
	}

	return connect.NewResponse(&result), nil
}
