TEST_KEY: ENC[AES256_GCM,data:MBSmpOlju6nZzr0=,iv:wNH6AeWMCaRzb/veEKUWlenLWJSGWyWWCEXgvKbvDVQ=,tag:mbgiCbqKRdZZKLQvjoez8A==,type:str]
ANOTHER_KEY: ENC[AES256_GCM,data:G3gvT8VCJAWhfZqR,iv:vL9fXPfIbC1cnQWuOUvu25oJ60Gcxj+To43wHyNlwx8=,tag:Z+lJGTxb2892sRRfPGJH/Q==,type:str]
sops:
    age:
        - recipient: age18jexhwcd4ehm7th0pqt8x6rmg3yuxstwv8aavqul4hvcmjkkhfaqn75su0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YU9qZUtxQS96L1NtV1Y5
            SWdIMVdpdkNmR25wdmRWeGs4c1pHcmpsYWxBCk5XdTBWVHEzVXd3Qndiei9NaGNr
            SWVUelR4RDkzbW1NcFNHSUxzeVVURVEKLS0tIGJxWG8vVHo4RW5ZekJXV1VDR21n
            RmZYalZtQkdmdUdiL2tndDJMSUNFaFEKFlgNXi+t2B4JND1HDzGTAQ/C/L9x49ar
            Drc4GlEY2Fz1N6LI+Y7PfQhAasPUW2F8rRv3G5atjaF64WIm0tid1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T12:00:13Z"
    mac: ENC[AES256_GCM,data:iCN+aIhv4L2eXpssc5BtEOA4grV0Y5fs7TJFIxZhOuAGDBfUt+KOj1JmJ/+GZ9htYIbZuyEDEObgxhuKkNYixJ4Ni3YFHQb/cetwgeSn0rvns9UmifXAyKOGePVPtplBjsRirCo1Osp1Wh4HJgKT9JH2E9O20PnppITl8lun8kg=,iv:pZn7PATBKjHh1C4gAqhli7p6ndDAJyAlcUlbRssGve0=,tag:GUgq36LSTjbXHuhAXE9oig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
