pre-rotation: ENC[AES256_GCM,data:+785uHtOAhEE,iv:bwfqkp7WlhvZ/Xm9CQia7U41kU9du04AACvVbtbDiY4=,tag:z+MFOSbSaR9QoTLm6zWhSw==,type:str]
post-rotation: ENC[AES256_GCM,data:u575+TCQUFHo,iv:m5n/JPMRlv/TzeueDz5+/s8tXzlHYNq1cdN8MBlpGcg=,tag:P+sMb2dLq8DLRr0MR8tdkA==,type:str]
sops:
    age:
        - recipient: age1gc9ddjfn6jpmpt4hdx0jgcyfft0klvydm2gtwsy503g5vw82udssjtns9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R2NtRDk1OXNCNUNFVHpw
            MlEzNVdCaWdRQ3ZsNXBEclp0YkNhTnQ1ZkQ4ClNiMU9vMHcwSWVJdGYwOXZBaEpy
            Z1ZXajhxTG03UUlzWWcvOW1xN3JxWGMKLS0tIFpFaVMwbDVWZThaam51SlNQVXhk
            YnduamRFcTVqRGhGRC9FVWg5ZWJZMWsK+2RXEYlk4p90d5cnb9O6a0EwBGbJ1k+l
            jnl5KoRwHlrI9jrEaZqwOdzvZByKcPcakJtHUNGHe93Lz6+lyWkoaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T09:36:55Z"
    mac: ENC[AES256_GCM,data:ilGwOTOdHMLVu4DijKqRhBJD1FlHPAmO3W54muHOa0B3P0aH4lMCydF1Bl6XXyqyBPUKzjep4Q5hWc66Sfs08SZozcAUxo8yrqGDldYTw8X9pV+ltRrZCUyooRN6F+AOWwboh1LGdmP1qqpX5JlHIVfgGv2Y5RkIu4zaijZ2ZkE=,iv:GQN4RoUhkv9GRJHUGKIBnLerRNeEW2IpqB/a4SC+uxk=,tag:TarB/AOf8Osl4+B6A4ailQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
