pre-rotation: ENC[AES256_GCM,data:+785uHtOAhEE,iv:bwfqkp7WlhvZ/Xm9CQia7U41kU9du04AACvVbtbDiY4=,tag:z+MFOSbSaR9QoTLm6zWhSw==,type:str]
post-rotation: ENC[AES256_GCM,data:u575+TCQUFHo,iv:m5n/JPMRlv/TzeueDz5+/s8tXzlHYNq1cdN8MBlpGcg=,tag:P+sMb2dLq8DLRr0MR8tdkA==,type:str]
openai-api-key: ENC[AES256_GCM,data:d6ufCwhq8HDo1WHImqPo7okSxUeOik8byOamHXi0CwNz3Gl4diqMnYsgdaehHtDX1uyOquRomUZkYx/mIUKJsUePblIxE3ArZwF3Z2AqEolkflGs5kMOiyMqAbNiVrcciDAMIUYywoos7GDE7uLvb482VLS9bvN+0C91NCOWLqHq2J/YbxEFdoRSg6GmsMdVm/GpvY6pM9DFWvbe4c63XoV63E0=,iv:ed5/1AoNrIcY4VGbLQjuRYo/7Sl3Tu4v3ejyFZRKP0U=,tag:I1uMIVznoRx/tdPayTtamQ==,type:str]
sops:
    age:
        - recipient: age1gc9ddjfn6jpmpt4hdx0jgcyfft0klvydm2gtwsy503g5vw82udssjtns9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R2NtRDk1OXNCNUNFVHpw
            MlEzNVdCaWdRQ3ZsNXBEclp0YkNhTnQ1ZkQ4ClNiMU9vMHcwSWVJdGYwOXZBaEpy
            Z1ZXajhxTG03UUlzWWcvOW1xN3JxWGMKLS0tIFpFaVMwbDVWZThaam51SlNQVXhk
            YnduamRFcTVqRGhGRC9FVWg5ZWJZMWsK+2RXEYlk4p90d5cnb9O6a0EwBGbJ1k+l
            jnl5KoRwHlrI9jrEaZqwOdzvZByKcPcakJtHUNGHe93Lz6+lyWkoaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T20:32:43Z"
    mac: ENC[AES256_GCM,data:svkns2Fa1LXzBfIXWgDyKH2Fj8ixZpP/Pv9jG6uTAkLkUNsgXoUPi2ZO9k54G9IdFz4CPAD+Olt7uoPojrwz6MBiBScmcya2sLwafhdv0QEV8tiO59TRyQdem2qkkhrsMnBw4Bmenvg5XNjreQoybqtGJXaQJ/Toejmw+Krd/90=,iv:BQlpuu6zVCu2OzsJteTxISU+W1ozkBOC4lY6yMwy1KA=,tag:gd4kvtIsOFYM6wTBmwklrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
