#ENC[AES256_GCM,data:eltq2W1VX0JB4zqPpx1QerxZl4v36GO1DH6UF1VZew==,iv:ZyOjPRbCNWQhuf5yJSQe4/8UtYVYEsTtjM3Uvlt+030=,tag:+DCZNMi00m5D7XtCSmIxhw==,type:comment]
#ENC[AES256_GCM,data:D0mDqZBRLdrmwLum370JY0EDbFq1flvBKpZrlgIA092TfGiZfBV1tnVl10QTLwVBQWLyLUmmRQnJbA==,iv:+qRNlZkojGTrazWeFEbufa0cc8faEWK20NIQJsDYuAM=,tag:qnHwiYHbhUYwc2BhxlNpjQ==,type:comment]
#
#ENC[AES256_GCM,data:OAZ2cYFnXelfI2ZLW7mUpN5XyTN7pBXLpCV06TG1JLCU,iv:Zdw7PNbtbHl9gBSlsVE7z/GK802kmLA07qbGsufR4JY=,tag:9/aq/6zL4wbbX/OxITo8+A==,type:comment]
#ENC[AES256_GCM,data:QvyVRycLlsbv9QEGA0AsuzZn75VBjwexpMtB,iv:gGiEg9/oyM45ywHIiUoE92N9M5noTajDkK20y4NNemM=,tag:558psGc8b9avVW8YjlYVEg==,type:comment]
#
#ENC[AES256_GCM,data:DIVt6xJbnOTtDWRdCzwPyvTwKjaX22kpusdAdVrUZVFKTlaobNmE6e4LDq0=,iv:XCY7kxUH0bTKr3BZJoyhjTmxGdYniWHFiMKRCQJ9Xb0=,tag:oA3737H1rInOhNciIQphzg==,type:comment]
#ENC[AES256_GCM,data:2/zxHbz2D1GG/B1JjyYPS4px/bhJ9opGOcln2S7ng49fcmJDPIxWm+k2PEVNBej9grItzCw=,iv:FuSM1GF7ZTwvNvUjFHWailOijX0QVmPQfYG4kFB8gzQ=,tag:4dvl3CB+gCtWU7P9RtG5Og==,type:comment]
#ENC[AES256_GCM,data:Zr2ZCRwbBK5Re/7nskQln5c2SxjPaSsW0/T348PZQSv+h4mQsRJ6rX5fP8nNAnxaVXHaNTgZHR4bMq+2XSs=,iv:GDtBxTYTPc4w2UbgKTvEefleHRwxsISpfWYRHtlUW8s=,tag:1phBi2y7H4ymcBA0Kv71+A==,type:comment]
DATABASE_URL: ENC[AES256_GCM,data:c5jN7rd+0ssqAmn6y5KKAjwQDzEaoBl3i5eBgM9xaNwhcIIzim/Oeg==,iv:pld4ruPs+bvWJZhqnLxHVKksJv4nNsEX6Jpy9214B74=,tag:uiBsWjTWmjahPZyszPBySw==,type:str]
sops:
    age:
        - recipient: age1mr42zd88679gyrk34f5cy8yx2axdrw39f2wq9q3y2du07kxluv5q9cwheu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobEtyNFBJNXRzc2JsUzFz
            L1BCcXFJTDJhNm9MWmllMHFmNWJFRHl4c1I4Cm9tZG9OUnhkUVJYc2xERmtuMW81
            RTlnYnQwOGNCODVjc0hqaTE1cVcxY3MKLS0tIG02UHBldlhlM2o0MnFMSXFOejFp
            Um1tOEdsWmVRREREOHduVWJIczZJbVUK0aGv6DIbYTevISz3e5GI2TDY+5ZVHdAn
            fmISZRZJOAaQtZhCNs7XdJ5KGjmdPlPgq4GZls6M9KGDB164JMcMMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T14:09:49Z"
    mac: ENC[AES256_GCM,data:VhLDWCTFGNyByS0h7r1jGA/HzNHleCjp5fNh0nJ+xrTxniAAmmjg7tqVLnry8zAx+gaHl7Mn+Q9u1yagNda+lHEAlCscQIDcQwedOgNJv2xV7uQsQbFH13k9mWqOmOR+a2bzs3BqLbd5rVsQSbJrRO/Vc1Kxg0nfHXaK1j8F2p8=,iv:eqlDF8mV3FMyqVRJvKzL2gPqyP/UmQnDexLgQyPDbiY=,tag:ncgt3ssK2aIJXaDUrq5ZMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
