#ENC[AES256_GCM,data:ksdulOhdxxhgmbbH5K5kaYTyvXEwxgjxFasc0Rld,iv:StiOmJNzqPdi+iuZ+0xi6cCyA4UqPrQnBtEhkIYV4dg=,tag:a/L8OdFoQbn5p3ZwZIh1Xg==,type:comment]
DATABASE_URL: ENC[AES256_GCM,data:XUO+sLxJ9O5kbbPrUS9qWQ5xJTxpBQ==,iv:sBeGU+LoMzkTBV5EOzJ8OXNvY/zwy14WBUk67Sqcs4w=,tag:3LDtg3mWQO0LMg/EWokYpw==,type:str]
CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:G/L+t+CWE/pJ0vkRguV9sB/udymihA==,iv:aEMwNJmU7/v7PxYTgX1hir33neXZ8LEJyZBip3awdhI=,tag:RPo4ucd9sj8xNyC9vMurxA==,type:str]
ALCHEMY_STATE_TOKEN: ENC[AES256_GCM,data:nv3zRy1yjnwf5TU0Sio4fndWgfBk4QagWE8SeINqBlMZF9CTT/pWHctFDBw=,iv:0jQaV2zRglfC0n42dYzMz2qMb7Jl9wZ4A3qng2rSDoY=,tag:Z3zuTENl7hZVS8uVlc9+Ng==,type:str]
sops:
    age:
        - recipient: age1dszst59kqxrnvpkkh50ad932znnykjte0chnzuvrr4ukmuasey8s3z7xvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUnMyeHZNdGVCSThYZGdi
            VnZjSnljYjF3RHNkbk42OGlHK3NjeENOMFZjCmpqTWxJRWpmKzBRbkhPaEE4QjFs
            YUhEcW1pYkY2cGZ6VjNxeFlhY1ltVm8KLS0tIGpYZXhneGJNaWhVc1VWSnhTaDZN
            SFUvaTN5aStLRmpVZVlvUWVQZGhRUFEKMimZOXDEkMalD1vUvh2m/W2P+Li+KDan
            L5syNxYZxJ4MtRRZktxfn75NSurAVb6E3H6CoYzEUkkeGo4xB+Uguw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T22:57:55Z"
    mac: ENC[AES256_GCM,data:3mNBdxBtYu9tlGzkRnOQb0RBQSb/orC1KAaMFc57FFsluEdcmkXwgqXfstIVO43D0BQnjcf3qRym86J0lQV2WfZbsMYIZaMRmJqX4H3ngEwATyU5rWCKTP4wHb7WGqWYw9v7XjB7PwTRhps6r9Ov09J+aly9GzHbqYs4rKvlt/s=,iv:prfqv+ajczr/nMxh1Di+8ApQGuPsJHVwLe26RTzc9Pw=,tag:rMVBLCwlD29vepcGIfiZlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
