#ENC[AES256_GCM,data:g7xpOktonTGfGaSAe+lp0KGverMszJ8xhCUz6Q==,iv:hxOttMPe1jqOOuH7jBwgPc9anwgSiDhywi5f70NyWak=,tag:vnI7Hg/UT5dAk1OV3TlO2Q==,type:comment]
#ENC[AES256_GCM,data:3NUPhjgIXKYcnUfe9WHSTb8+l2fqY/KFqe4IMkm1Csd9Ea0dpXkWsUI/ZUwvHz8oTI8vnrTXpBy6FA==,iv:Rg9tdilV28zWy1351SgO58Zp9WhuQCl0as5XM9U2V5A=,tag:bBc2DRR7NPlWG89IkRa9fw==,type:comment]
#
#ENC[AES256_GCM,data:ztEn6xYyzSsCwQ2FwVV9VUf2cUxpyh679gcqRqSXjXgsTea0,iv:ALwOemM8BUac1Q11Fvrcuilfm0ljjQ3C9pXP4bEfd00=,tag:0OXtn+lptN4Eez2gdO+VYQ==,type:comment]
#ENC[AES256_GCM,data:e3I7Xn54SH5jNrBb0JWM0ICt+8jWufeJ+s2Nv1TE,iv:T0FojKLXqYFa+SrIZ4rdlMQ8MDmxsq6zBG60V9VkCek=,tag:u43IV2v6hwY5WcZOed/IWA==,type:comment]
#
#ENC[AES256_GCM,data:MaKe4kSPK86BGTIQs+caOl8+asDMwxAAcjLzYrFO17mlGZBPBr7P1tFrDXo=,iv:NYmQ6BnotzAflwiwYgJ40GaLFzTUBr36icZ7ayCbC/A=,tag:qzzr1wohiDe3N3sgqlgG3g==,type:comment]
#ENC[AES256_GCM,data:GvYbmoYCFLDbjU+uJyrCQM/7xPFBDRr/gaMh/VGWlxpE+e5gZpu7SFGftmFC0bugywe8ustCCDg=,iv:jbVgzuJ09sxB2mlX+b7z45YfaUEB2SFxQPWvcYHJpZk=,tag:wDB3SD6k5GMZv9E4b2mI3w==,type:comment]
#ENC[AES256_GCM,data:UtFyaZ6GiIP2jzcRb2xCii9J8samHQuOX2E9F4qW0Wmch2xzFWYbqcQMvzUmbo40k17Q31veuDt9zdf4vpk=,iv:AkkgbRsT2xBvNZE6IklvzT2mOH9Wyy8bhE62K0XbE64=,tag:HP98sXZUbor6VLD2czFeQQ==,type:comment]
DATABASE_URL: ENC[AES256_GCM,data:apzKypWUk4Cj0d1tgUrnc6qmUVSAvg9Q2hndfhmcLntOtF0ZqFM7bxlsmmbF6w==,iv:+qEMkwxvNbSf1QYZXVfyPnyqKoZvcoBnl3FPQOMhy1E=,tag:AzB8hTZCKyIJMaDhmxszdw==,type:str]
sops:
    age:
        - recipient: age1mr42zd88679gyrk34f5cy8yx2axdrw39f2wq9q3y2du07kxluv5q9cwheu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYlRzcFZoblg0eG41U1o0
            UzUxRTV0YW5oRDlwNEhJeWNXS2dSajJPNFRZCkREK3NaWW5uNkp6SXp0SVBwRVkx
            MGpDMi9MREVicStPQXFjMUJaTmJOaWcKLS0tIEU1UTgvcXlDNVd6TFlOT2JqTjJB
            VVhneHJHSHdvK0hSM1NkcGwxa3h3aUkKe79LabM4AQI/SRnramqVa3kkUYNu3ga2
            mGHXAgv0dHeob9tXDZmHGu6ev/YEXD4TOoFJEbGG9VvCH1u6bHcypQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T14:09:49Z"
    mac: ENC[AES256_GCM,data:Rq0fdM2SvL5dfGTth0AsKnHQlgndbGnICIk+18lH7lsb6zGhAKtq+/Gd4C9lQ9ol8k5EQA9xbfbNFGEXUx20sM7Y6K+FhZoLBaB4icThvz0BmY8VryMFDFyACqgGJucvksYTH/wymQynXUUgwyF1WeOryBEZgDaBV84haLQZZNU=,iv:l3TXR7xPYoEa22bnBLcF4TPp2RiX2mtWpD5zy4pMXRQ=,tag:IS4xeXurLWpSfUMD173Abw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
