#ENC[AES256_GCM,data:D5VmYoZNZaEH8Ok2/VdMonMrAYllKeTTeMMF,iv:TcTIjcsgW8oOt1/LfEQpekcHPSN9BOdFPfhONuoglJI=,tag:Io12xvP82H5F9IQPD3IGcw==,type:comment]
DATABASE_URL: ENC[AES256_GCM,data:h3HDZH1K0r21gfPHRjf23cgxHaZV+w==,iv:SwxfBrD0VOw3xTCESZB6cA03YMnSkDj1I7xnIplihes=,tag:MPZyV+09uJHjyl/AvLK2Iw==,type:str]
CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:zW9V79n0O9mrxxEu9I5KRD36wpux8Q==,iv:kqBnbe6YWKkfSClIP98qF/6/SeYjs0bahZ355cymt84=,tag:DLpmNm6aHOX6x0gDCyV/ag==,type:str]
ALCHEMY_STATE_TOKEN: ENC[AES256_GCM,data:iu+RUKjJA3AYP3ghErXcPW0MX4yccX/ArLE2AtyCmGNI+gdEriUMCCGPyi8=,iv:qZLDCtuRrDGFwIGDLOtlz8i/P8YOmrvwYo0tLc6dpJ0=,tag:/V4S7pVWCR63ebtKPx5Cpw==,type:str]
sops:
    age:
        - recipient: age1dszst59kqxrnvpkkh50ad932znnykjte0chnzuvrr4ukmuasey8s3z7xvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR3lrR1BJVjZIUU9DNC9y
            dVBwMzRJSlRIL3RiREdaLzBobFBrM0o5YkQ4CmtDQXhXY1g0RWxabkVacE5saHFM
            Y09vT1I2SFl2RFBJbmtaK1FYS3E4T1UKLS0tIHdxSlpQNG5MSVd5Um9Ha001T2pQ
            US80ZXlzZkJuOEZEUW13RzExQmdqaW8KQnGP3205zMdAYVhdTC7kRtwrLRkBEksK
            waQb08Q01yRoMdFXkMTSenlVqyA/kvX+Qq2d2/VrcBLHSSKCim/+3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T22:57:55Z"
    mac: ENC[AES256_GCM,data:Wm+ftzAX08q/ibJruA5XcG/2+i65GTnvaA0cpyUAJTRUi4d6DguFVerPvmJyY5PYMecWU2g/IiJkzVmiAW+QsC/9jFu7gSm0c+jTLo0IKq8Vt3hZMuEYN02Rb+0E15SWjyerUSFevc8RVjuv7q1p80gFJ+FamEyIcyVehZ0Gbnk=,iv:XouANJW4xmar4ns2UHejmFaPkLJ6m4kXyXFemybXrH0=,tag:jB0BNabA2MkupJZoCZTLfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
