// Generated by stackpanel — do not edit manually.
import alchemy from "alchemy";
import { CloudflareStateStore } from "alchemy/state";
import Infra from "./src/index.ts";

const app = await alchemy("stackpanel-infra", {
  stateStore: process.env.CLOUDFLARE_API_TOKEN
    ? (scope) =>
        new CloudflareStateStore(scope, {
          apiToken: alchemy.secret(process.env.CLOUDFLARE_API_TOKEN!),
        })
    : undefined,
});

// Import and run infra modules
const aws_ec2_appOutputs = (await import("./modules/aws-ec2-app.ts")).default;

const aws_secretsOutputs = (await import("./modules/aws-secrets/index.ts")).default;

const databaseOutputs = (await import("./modules/database.ts")).default;

const deploymentOutputs = (await import("./modules/deployment.ts")).default;

const machinesOutputs = (await import("./modules/machines.ts")).default;


// Sync declared outputs to storage backend
await Infra.syncAll({
"aws-ec2-app": {
  outputs: aws_ec2_appOutputs,
  syncKeys: ["albOutputs","ecrOutputs","instanceIds","machines","privateIps","publicDns","publicIps","ssmOutputs"],
},
"aws-secrets": {
  outputs: aws_secretsOutputs,
  syncKeys: ["kmsAliasName","kmsKeyArn","kmsKeyId","oidcProviderArn","roleArn","roleName"],
},
"database": {
  outputs: databaseOutputs,
  syncKeys: ["databaseUrl","provider"],
},
"deployment": {
  outputs: deploymentOutputs,
  syncKeys: ["docsUrl"],
},
"machines": {
  outputs: machinesOutputs,
  syncKeys: ["machines"],
},
});

await app.finalize();
