// Generated by stackpanel — do not edit manually.
import alchemy from "alchemy";
import Infra from "./src/index.ts";

const app = await alchemy("stackpanel-infra", {
  password: process.env.ALCHEMY_PASSWORD ?? "local-dev-password",
});

// Import and run infra modules
const aws_secretsOutputs = (await import("./modules/aws-secrets.ts")).default;


// Sync declared outputs to storage backend
await Infra.syncAll({
"aws-secrets": {
  outputs: aws_secretsOutputs,
  syncKeys: ["kmsAliasName","kmsKeyArn","kmsKeyId","oidcProviderArn","roleArn","roleName"],
},
});

await app.finalize();
