package server
package server
































































































































































































































































































































































}	}		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	default:		})			"success": true,		json.NewEncoder(w).Encode(map[string]interface{}{		}			return			})				"error":   err.Error(),				"success": false,			json.NewEncoder(w).Encode(map[string]interface{}{		if err := s.writeFile(req.Path, req.Content); err != nil {		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req FileWriteRequest	case "POST":		})			"data":    content,			"success": true,		json.NewEncoder(w).Encode(map[string]interface{}{		}			return			http.Error(w, err.Error(), http.StatusNotFound)		if err != nil {		content, err := s.readFile(path)		path := r.URL.Query().Get("path")	case "GET":	switch r.Method {func (s *Server) handleFiles(w http.ResponseWriter, r *http.Request) {}	})		"data":    result,		"success": true,	json.NewEncoder(w).Encode(map[string]interface{}{	}		return		})			"error":   err.Error(),			"success": false,		json.NewEncoder(w).Encode(map[string]interface{}{	if err != nil {	result, err := s.nix.Generate()	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != "POST" {func (s *Server) handleNixGenerate(w http.ResponseWriter, r *http.Request) {}	})		"data":    result,		"success": true,	json.NewEncoder(w).Encode(map[string]interface{}{	}		return		})			"error":   err.Error(),			"success": false,		json.NewEncoder(w).Encode(map[string]interface{}{	if err != nil {	result, err := s.nix.Eval(req.Expression)	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	var req NixEvalRequest	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != "POST" {func (s *Server) handleNixEval(w http.ResponseWriter, r *http.Request) {}	})		"data":    result,		"success": true,	json.NewEncoder(w).Encode(map[string]interface{}{	}		return		})			"error":   err.Error(),			"success": false,		json.NewEncoder(w).Encode(map[string]interface{}{	if err != nil {	result, err := s.executor.Run(req.Command, req.Args...)	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	var req ExecRequest	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != "POST" {func (s *Server) handleExec(w http.ResponseWriter, r *http.Request) {// HTTP Handlers}	conn.WriteJSON(resp)	}		Error:   errMsg,		Success: false,		ID:      id,	resp := Response{func (s *Server) sendError(conn *websocket.Conn, id string, errMsg string) {}	conn.WriteJSON(resp)	}		Data:    data,		Success: true,		ID:      id,	resp := Response{func (s *Server) sendResponse(conn *websocket.Conn, id string, data interface{}) {}	s.sendResponse(conn, msg.ID, response)	}		return		s.sendError(conn, msg.ID, err.Error())	if err != nil {	}		return		s.sendError(conn, msg.ID, fmt.Sprintf("Unknown message type: %s", msg.Type))	default:		response = map[string]bool{"ok": true}		err = s.writeFile(req.Path, req.Content)		}			return			s.sendError(conn, msg.ID, "Invalid file.write request")		if err := json.Unmarshal(msg.Payload, &req); err != nil {		var req FileWriteRequest	case "file.write":		response, err = s.readFile(req.Path)		}			return			s.sendError(conn, msg.ID, "Invalid file.read request")		if err := json.Unmarshal(msg.Payload, &req); err != nil {		var req FileRequest	case "file.read":		response, err = s.nix.Generate()	case "nix.generate":		response, err = s.nix.Eval(req.Expression)		}			return			s.sendError(conn, msg.ID, "Invalid nix.eval request")		if err := json.Unmarshal(msg.Payload, &req); err != nil {		var req NixEvalRequest	case "nix.eval":		response, err = s.executor.Run(req.Command, req.Args...)		}			return			s.sendError(conn, msg.ID, "Invalid exec request")		if err := json.Unmarshal(msg.Payload, &req); err != nil {		var req ExecRequest	case "exec":	switch msg.Type {	var err error	var response interface{}	log.Debug().Str("type", msg.Type).Str("id", msg.ID).Msg("Received message")	}		return		s.sendError(conn, msg.ID, "Invalid message format")	if err := json.Unmarshal(message, &msg); err != nil {	var msg Messagefunc (s *Server) handleMessage(conn *websocket.Conn, message []byte) {}	}		s.handleMessage(conn, message)		}			break			}				log.Error().Err(err).Msg("WebSocket error")			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {		if err != nil {		_, message, err := conn.ReadMessage()	for {	log.Info().Str("remote", conn.RemoteAddr().String()).Msg("Client connected")	}()		s.mu.Unlock()		delete(s.clients, conn)		s.mu.Lock()	defer func() {	s.mu.Unlock()	s.clients[conn] = true	s.mu.Lock()	defer conn.Close()	}		return		log.Error().Err(err).Msg("WebSocket upgrade failed")	if err != nil {	conn, err := s.upgrader.Upgrade(w, r, nil)func (s *Server) handleWebSocket(w http.ResponseWriter, r *http.Request) {}	})		"version":      "dev",		"project_root": s.config.ProjectRoot,		"status":       "ok",	json.NewEncoder(w).Encode(map[string]interface{}{func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {// Handlers}	})		next.ServeHTTP(w, r)		// In production, verify token against API		// For now, check for localhost only		// TODO: Implement proper auth		}			return			next.ServeHTTP(w, r)		if r.URL.Path == "/health" {		// Skip auth for health check	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {func (s *Server) authMiddleware(next http.Handler) http.Handler {}	})		next.ServeHTTP(w, r)		}			return			w.WriteHeader(http.StatusOK)		if r.Method == "OPTIONS" {		w.Header().Set("Access-Control-Allow-Headers", "Authorization, Content-Type")		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")		w.Header().Set("Access-Control-Allow-Origin", "*")	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {func (s *Server) corsMiddleware(next http.Handler) http.Handler {// Middleware}	s.http.Shutdown(ctx)	s.mu.Unlock()	}		conn.Close()	for conn := range s.clients {	s.mu.Lock()	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)func (s *Server) Stop() {}	return s.http.ListenAndServe()	log.Info().Str("addr", s.http.Addr).Msg("Agent listening")func (s *Server) Start() error {}	return s, nil	}		Handler: s.corsMiddleware(s.authMiddleware(mux)),		Addr:    fmt.Sprintf("127.0.0.1:%d", cfg.Port),	s.http = &http.Server{	mux.HandleFunc("/api/files", s.handleFiles)	mux.HandleFunc("/api/nix/generate", s.handleNixGenerate)	mux.HandleFunc("/api/nix/eval", s.handleNixEval)	mux.HandleFunc("/api/exec", s.handleExec)	mux.HandleFunc("/health", s.handleHealth)	mux.HandleFunc("/ws", s.handleWebSocket)	mux := http.NewServeMux()	}		},			},				return true				// TODO: Validate origin in production			CheckOrigin: func(r *http.Request) bool {		upgrader: websocket.Upgrader{		clients:  make(map[*websocket.Conn]bool),		nix:      nixMgr,		executor: exec,		config:   cfg,	s := &Server{	}		return nil, fmt.Errorf("failed to create nix manager: %w", err)	if err != nil {	nixMgr, err := nix.NewManager(cfg.ProjectRoot)	}		return nil, fmt.Errorf("failed to create executor: %w", err)	if err != nil {	exec, err := executor.New(cfg.ProjectRoot, cfg.AllowedCommands)func New(cfg *config.Config) (*Server, error) {}	mu       sync.RWMutex	clients  map[*websocket.Conn]bool	upgrader websocket.Upgrader	http     *http.Server	nix      *nix.Manager	executor *executor.Executor	config   *config.Configtype Server struct {)	"github.com/rs/zerolog/log"	"github.com/gorilla/websocket"	"github.com/darkmatter/stackpanel/agent/internal/nix"	"github.com/darkmatter/stackpanel/agent/internal/executor"	"github.com/darkmatter/stackpanel/agent/internal/config"	"time"	"sync"	"net/http"	"fmt"	"encoding/json"	"context"import (
