package codegen

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestComputePayloadHash(t *testing.T) {
	t.Parallel()

	t.Run("deterministic for same input", func(t *testing.T) {
		t.Parallel()
		plaintext := []byte(`{"KEY":"value"}` + "\n")
		recipients := []string{"age1abc", "age1def"}
		h1 := computePayloadHash(plaintext, recipients)
		h2 := computePayloadHash(plaintext, recipients)
		if h1 != h2 {
			t.Fatalf("hash not deterministic: %q != %q", h1, h2)
		}
	})

	t.Run("recipients sorted before hashing", func(t *testing.T) {
		t.Parallel()
		plaintext := []byte(`{"KEY":"value"}` + "\n")
		h1 := computePayloadHash(plaintext, []string{"age1zzz", "age1aaa"})
		h2 := computePayloadHash(plaintext, []string{"age1aaa", "age1zzz"})
		if h1 != h2 {
			t.Fatalf("hash differs by recipient order: %q != %q", h1, h2)
		}
	})

	t.Run("different plaintext yields different hash", func(t *testing.T) {
		t.Parallel()
		r := []string{"age1abc"}
		h1 := computePayloadHash([]byte(`{"KEY":"v1"}`+"\n"), r)
		h2 := computePayloadHash([]byte(`{"KEY":"v2"}`+"\n"), r)
		if h1 == h2 {
			t.Fatal("expected different hashes for different plaintexts")
		}
	})

	t.Run("different recipients yield different hash", func(t *testing.T) {
		t.Parallel()
		p := []byte(`{"KEY":"value"}` + "\n")
		h1 := computePayloadHash(p, []string{"age1abc"})
		h2 := computePayloadHash(p, []string{"age1xyz"})
		if h1 == h2 {
			t.Fatal("expected different hashes for different recipients")
		}
	})

	t.Run("returns hex string", func(t *testing.T) {
		t.Parallel()
		h := computePayloadHash([]byte("test"), []string{"age1abc"})
		if len(h) != 64 {
			t.Fatalf("expected 64-char hex, got %d chars: %q", len(h), h)
		}
		for _, c := range h {
			if !strings.ContainsRune("0123456789abcdef", c) {
				t.Fatalf("non-hex char in hash: %q", h)
			}
		}
	})
}

func TestExtractPayloadHashFromModule(t *testing.T) {
	t.Parallel()

	t.Run("extracts hash from valid module", func(t *testing.T) {
		t.Parallel()
		content := "// Auto-generated by Stackpanel — do not edit manually.\n" +
			"// content-hash: abc123def456\n" +
			"const encryptedPayload = \"data\";\n\n" +
			"export default encryptedPayload;\n"
		path := filepath.Join(t.TempDir(), "module.ts")
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			t.Fatal(err)
		}
		got, err := extractPayloadHashFromModule(path)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got != "abc123def456" {
			t.Fatalf("expected 'abc123def456', got %q", got)
		}
	})

	t.Run("returns empty string when no hash line", func(t *testing.T) {
		t.Parallel()
		content := "// Auto-generated by Stackpanel — do not edit manually.\n" +
			"const encryptedPayload = \"data\";\n\n" +
			"export default encryptedPayload;\n"
		path := filepath.Join(t.TempDir(), "old-module.ts")
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			t.Fatal(err)
		}
		got, err := extractPayloadHashFromModule(path)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got != "" {
			t.Fatalf("expected empty string, got %q", got)
		}
	})

	t.Run("returns error for missing file", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "missing.ts")
		_, err := extractPayloadHashFromModule(path)
		if err == nil {
			t.Fatal("expected error for missing file")
		}
	})
}

func TestRenderGeneratedPayloadModule_EmbedHash(t *testing.T) {
	t.Parallel()

	encrypted := []byte(`{"sops":"..."}`)
	hash := "deadbeef1234"
	out := renderGeneratedPayloadModule(encrypted, hash)

	if !bytes.Contains(out, []byte("// content-hash: deadbeef1234")) {
		t.Fatalf("expected content-hash line in output:\n%s", out)
	}
}

// sopsAvailable returns true when sops is present in PATH.
func sopsAvailable() bool {
	_, err := exec.LookPath("sops")
	return err == nil
}

// requireSopsKey generates a temporary AGE key for integration tests.
// Returns the key path and the public key string.
func requireSopsKey(t *testing.T) (keyPath, pubKey string) {
	t.Helper()
	if _, err := exec.LookPath("age-keygen"); err != nil {
		t.Skip("age-keygen not in PATH")
	}

	dir := t.TempDir()
	keyPath = filepath.Join(dir, "key.txt")
	out, err := exec.Command("age-keygen", "-o", keyPath).CombinedOutput()
	if err != nil {
		t.Fatalf("age-keygen: %v: %s", err, out)
	}

	data, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatal(err)
	}
	for _, line := range bytes.Split(data, []byte("\n")) {
		if bytes.HasPrefix(line, []byte("# public key: ")) {
			pubKey = string(bytes.TrimPrefix(line, []byte("# public key: ")))
			return
		}
	}
	t.Fatal("could not extract public key from age-keygen output")
	return
}

func TestBuildSkipsReencryptionWhenUnchanged(t *testing.T) {
	// Cannot use t.Parallel() with t.Setenv.
	if !sopsAvailable() {
		t.Skip("sops not in PATH")
	}
	keyPath, pubKey := requireSopsKey(t)
	t.Setenv("SOPS_AGE_KEY_FILE", keyPath)

	projectRoot := t.TempDir()
	genDir := filepath.Join(projectRoot, ".stack", "gen", "codegen")
	if err := os.MkdirAll(genDir, 0755); err != nil {
		t.Fatal(err)
	}
	dataDir := filepath.Join(projectRoot, "packages", "gen", "env", "data", "myapp")
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		t.Fatal(err)
	}

	outputPath := "packages/gen/env/data/myapp/dev.sops.json"
	manifest := envManifest{
		SchemaVersion: 1,
		DataRoot:      "packages/gen/env/data",
		Targets: []envTargetSpec{
			{
				App:         "myapp",
				Environment: "dev",
				OutputPath:  outputPath,
				Recipients:  []string{pubKey},
				Vars: map[string]envVarResolver{
					"API_KEY": {Kind: "literal", Value: "secret123"},
				},
			},
		},
	}
	manifestData, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(genDir, "env-manifest.json"), manifestData, 0644); err != nil {
		t.Fatal(err)
	}

	ctx := context.Background()
	req := BuildRequest{ProjectRoot: projectRoot, Force: false}

	// First build: must encrypt.
	out1, err := (envModule{}).Build(ctx, req)
	if err != nil {
		t.Fatalf("first build: %v", err)
	}
	if len(out1.Artifacts) == 0 {
		t.Fatal("expected artifacts on first build")
	}

	// Write artifacts to disk (simulate Builder.writeArtifact).
	for _, a := range out1.Artifacts {
		if err := os.MkdirAll(filepath.Dir(a.Path), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(a.Path, a.Content, a.Mode); err != nil {
			t.Fatal(err)
		}
	}

	// Second build: same plaintext and recipients → must produce identical bytes.
	// writeArtifact would then skip both .sops.json and .ts files.
	out2, err := (envModule{}).Build(ctx, req)
	if err != nil {
		t.Fatalf("second build: %v", err)
	}

	for _, a := range out2.Artifacts {
		isSops := strings.HasSuffix(a.Path, ".sops.json")
		isTS := strings.HasSuffix(a.Path, ".ts")
		if !isSops && !isTS {
			continue
		}
		existing, err := os.ReadFile(a.Path)
		if err != nil {
			t.Fatalf("read artifact %s: %v", a.Path, err)
		}
		if !bytes.Equal(a.Content, existing) {
			t.Errorf("artifact %s changed on second build (re-encryption occurred)", a.Path)
		}
	}
}
