package codegen

import "testing"

func TestRenderGeneratedPayloadModule(t *testing.T) {
	encrypted := []byte(`{"API_KEY":"ENC[AES256_GCM,data:abc,type:str]","sops":{"version":"3.12.1"}}`)
	got := string(renderGeneratedPayloadModule(encrypted, "abc123"))
	want := "// Auto-generated by Stackpanel — do not edit manually.\n" +
		"// content-hash: abc123\n" +
		"const encryptedPayload = {\n" +
		"  \"API_KEY\": \"ENC[AES256_GCM,data:abc,type:str]\",\n" +
		"  \"sops\": {\n" +
		"    \"version\": \"3.12.1\"\n" +
		"  }\n" +
		"};\n\n" +
		"export default JSON.stringify(encryptedPayload);\n"
	if got != want {
		t.Fatalf("payload mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Non-JSON input must round-trip unchanged: the embedder cannot do anything
// useful with it but should also not silently drop the bytes.
func TestRenderGeneratedPayloadModule_NonJSONFallback(t *testing.T) {
	got := string(renderGeneratedPayloadModule([]byte("not-json"), "deadbeef"))
	if !contains(got, "// content-hash: deadbeef") {
		t.Fatalf("expected content-hash line:\n%s", got)
	}
	if !contains(got, "const encryptedPayload = not-json;") {
		t.Fatalf("expected raw fallback embedding:\n%s", got)
	}
}

func contains(s, substr string) bool {
	for i := 0; i+len(substr) <= len(s); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}

func TestRenderGeneratedPayloadRegistry(t *testing.T) {
	targets := []envTargetSpec{
		{App: "web", Environment: "prod"},
		{App: "web", Environment: "dev"},
		{App: "docs", Environment: "dev"},
	}
	got := string(renderGeneratedPayloadRegistry(targets))
	want := `// Auto-generated by Stackpanel — do not edit manually.
const payloadLoaders: Record<string, Record<string, () => Promise<string>>> = {
  "docs": {
    "dev": async () => (await import("./docs/dev")).default,
  },
  "web": {
    "dev": async () => (await import("./web/dev")).default,
    "prod": async () => (await import("./web/prod")).default,
  },
};

export async function loadGeneratedPayload(app: string, env: string): Promise<string | null> {
  const appLoaders = payloadLoaders[app];
  if (!appLoaders) return null;
  const loader = appLoaders[env];
  if (!loader) return null;
  return loader();
}
`
	if got != want {
		t.Fatalf("registry mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}
