// Generated by stackpanel — do not edit manually.
// TypeScript interfaces for infra module inputs.

export interface AwsSecretsInputs {
  accountId: string;
  iam: {
  additionalPolicies: string[];
  roleName: string;
};
  kms: {
  alias: string;
  deletionWindowDays: number;
};
  oidc: {
  flyio: {
  appName: string;
  orgId: string;
};
  githubActions: {
  branch: string;
  org: string;
  repo: string;
};
  provider: string;
  rolesAnywhere: {
  trustAnchorArn: string;
};
};
  projectName: string;
  region: string;
  ssm: {
  additionalPaths: string[];
  enable: boolean;
  groupPaths: string[];
  keyPrefix: string;
};
}

export interface DeploymentInputs {
  apps: {
  web: {
  bindings: string[];
  framework: string;
  host: string;
  path: string;
  secrets: string[];
};
};
}

