// =============================================================================
// aws-ec2-deploy.ts — Provision a self-contained EC2 app environment
//
// Creates a complete VPC-based deployment for a single app:
//   VPC -> Subnet -> IGW -> Route -> Security Group -> IAM Role -> EC2 Instance
//
// The instance's user-data is generated by aws-ec2-userdata.ts, which
// supports both Amazon Linux (tarball + node) and NixOS (static boot
// for Colmena-based deploys).
//
// Runtime secrets are stored in SSM Parameter Store. The instance's IAM
// role grants read access to the parameter path and the S3 artifact bucket.
// =============================================================================
import { isSecret, type Secret } from "alchemy";
import { GetParameterCommand, SSMClient } from "@aws-sdk/client-ssm";
import {
  InternetGateway,
  InternetGatewayAttachment,
  Route,
  RouteTable,
  RouteTableAssociation,
  SecurityGroup,
  SecurityGroupRule,
  SSMParameter,
  Subnet,
  Vpc,
} from "alchemy/aws";
import { Ec2Instance } from "@stackpanel/infra/resources/ec2-instance";
import { IamInstanceProfile } from "@stackpanel/infra/resources/iam-instance-profile";
import { IamRole } from "@stackpanel/infra/resources/iam-role";
import { buildUserData, buildNixosUserData } from "./aws-ec2-userdata";

// ---- Default AMI (Amazon Linux 2023, resolved at deploy time via SSM) -------
const DEFAULT_IMAGE_ID =
  "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}";

// ---- Types ------------------------------------------------------------------

type EnvironmentValue = string | Secret<string>;

export interface Ec2ServerProps {
  appName: string;
  parameterPath: string;
  artifactBucket: string;
  artifactKey: string;
  artifactVersion?: string;
  environment: Record<string, EnvironmentValue>;
  region?: string;
  availabilityZone?: string | null;
  imageId?: string | null;
  instanceType?: string | null;
  keyName?: string | null;
  port?: number | null;
  httpCidrBlocks?: string[];
  sshCidrBlocks?: string[];
  vpcCidrBlock?: string | null;
  subnetCidrBlock?: string | null;
  rootVolumeSize?: number | null;
  tags?: Record<string, string>;
  osType?: "amazon-linux" | "nixos";
}

export interface Ec2Server extends Ec2ServerProps {
  instanceId: string;
  publicIp: string;
  publicDnsName: string;
  url: string;
  vpcId: string;
  subnetId: string;
  securityGroupId: string;
  roleArn: string;
  instanceProfileArn: string;
}

export interface RuntimeLayout {
  slug: string;
  serviceName: string;
  appRoot: string;
  releaseRoot: string;
  envFile: string;
  archivePath: string;
}

// ---- Layout derivation ------------------------------------------------------

/** Standard filesystem layout for a deployed app on an EC2 instance. */
export function deriveRuntimeLayout(appName: string): RuntimeLayout {
  const slug = sanitizeName(appName);
  const baseName = `stackpanel-${slug}`;

  return {
    slug,
    serviceName: `${baseName}.service`,
    appRoot: `/opt/${baseName}`,
    releaseRoot: `/opt/${baseName}/release`,
    envFile: `/etc/${baseName}.env`,
    archivePath: `/tmp/${baseName}-release.tar.gz`,
  };
}

// ---- Main provisioning function ---------------------------------------------

export async function Ec2Server(
  id: string,
  props: Ec2ServerProps,
): Promise<Ec2Server> {
  const region = props.region ?? "us-west-2";
  const availabilityZone = props.availabilityZone ?? `${region}a`;
  const defaultImageId =
    props.osType === "nixos"
      ? await resolveNixosAmi(region)
      : DEFAULT_IMAGE_ID;
  const imageId = await resolveImageId(props.imageId ?? defaultImageId, region);
  const instanceType = props.instanceType ?? "t3.small";
  const port = props.port ?? 80;
  const httpCidrBlocks = props.httpCidrBlocks ?? ["0.0.0.0/0"];
  const sshCidrBlocks = props.sshCidrBlocks ?? [];
  const vpcCidrBlock = props.vpcCidrBlock ?? "10.42.0.0/16";
  const subnetCidrBlock = props.subnetCidrBlock ?? "10.42.1.0/24";
  const rootVolumeSize = props.rootVolumeSize ?? 20;
  const namePrefix = props.tags?.Stage ? `${id}-${props.tags.Stage}` : id;
  const layout = deriveRuntimeLayout(props.appName);
  const tags = {
    Name: id,
    ManagedBy: "alchemy",
    Service: props.appName,
    ...props.tags,
  };

  // -- IAM: role + instance profile -------------------------------------------

  const role = await IamRole(`${id}-instance-role`, {
    roleName: `${namePrefix}-instance-role`,
    assumeRolePolicy: {
      Version: "2012-10-17",
      Statement: [{
        Effect: "Allow",
        Principal: { Service: "ec2.amazonaws.com" },
        Action: "sts:AssumeRole",
      }],
    },
    description: `Allows the EC2 instance for ${props.appName} to read boot-time config and artifacts.`,
    managedPolicyArns: [
      "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
    ],
    policies: [{
      policyName: `${id}-read-config`,
      policyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Action: ["ssm:GetParameter", "ssm:GetParameters", "ssm:GetParametersByPath"],
            Resource: [
              `arn:aws:ssm:${region}:*:parameter${props.parameterPath}`,
              `arn:aws:ssm:${region}:*:parameter${props.parameterPath}/*`,
            ],
          },
          {
            Effect: "Allow",
            Action: ["s3:GetBucketLocation", "s3:ListBucket"],
            Resource: [`arn:aws:s3:::${props.artifactBucket}`],
            Condition: { StringLike: { "s3:prefix": [props.artifactKey] } },
          },
          {
            Effect: "Allow",
            Action: ["s3:GetObject"],
            Resource: [`arn:aws:s3:::${props.artifactBucket}/${props.artifactKey}`],
          },
          {
            Effect: "Allow",
            Action: ["kms:Decrypt"],
            Resource: "*",
          },
        ],
      },
    }],
    tags,
  });

  const instanceProfileName = `${namePrefix}-instance-profile`;
  const instanceProfile = await IamInstanceProfile(`${id}-instance-profile`, {
    name: instanceProfileName,
    roleName: role.roleName,
    tags,
  });

  // -- SSM parameters (runtime environment) -----------------------------------

  await Promise.all(
    Object.entries(props.environment).map(([key, value]) => {
      const name = `${trimTrailingSlash(props.parameterPath)}/${key}`;
      return SSMParameter(`${id}-env-${key.toLowerCase()}`, {
        name,
        description: `Runtime configuration for ${props.appName}: ${key}`,
        ...(isSecret(value) ? { type: "SecureString", value } : { value }),
        tags,
      });
    }),
  );

  // -- VPC + networking -------------------------------------------------------

  const vpc = await Vpc(`${id}-vpc`, {
    cidrBlock: vpcCidrBlock, enableDnsSupport: true, enableDnsHostnames: true, region, tags,
  });

  const internetGateway = await InternetGateway(`${id}-igw`, { region, tags });

  await InternetGatewayAttachment(`${id}-igw-attachment`, {
    internetGateway, vpc, region,
  });

  const routeTable = await RouteTable(`${id}-public-rt`, { vpc, region, tags });

  await Route(`${id}-default-route`, {
    routeTable, region, destinationCidrBlock: "0.0.0.0/0",
    target: { internetGateway },
  });

  const subnet = await Subnet(`${id}-public-subnet`, {
    vpc, region, cidrBlock: subnetCidrBlock, availabilityZone,
    mapPublicIpOnLaunch: true, tags,
  });

  await RouteTableAssociation(`${id}-public-association`, { routeTable, subnet });

  // -- Security group + rules -------------------------------------------------

  const securityGroup = await SecurityGroup(`${id}-sg`, {
    vpc, region, description: `Ingress rules for ${props.appName}`, tags,
  });

  await Promise.all(
    httpCidrBlocks.map((cidr, index) =>
      SecurityGroupRule(`${id}-http-${index}`, {
        securityGroup, type: "ingress", protocol: "tcp",
        fromPort: port, toPort: port, cidrBlocks: [cidr],
        description: `Allow HTTP traffic on port ${port}`,
      }),
    ),
  );

  if (props.keyName && sshCidrBlocks.length > 0) {
    await Promise.all(
      sshCidrBlocks.map((cidr, index) =>
        SecurityGroupRule(`${id}-ssh-${index}`, {
          securityGroup, type: "ingress", protocol: "tcp",
          fromPort: 22, toPort: 22, cidrBlocks: [cidr],
          description: "Allow SSH access",
        }),
      ),
    );
  }

  // -- EC2 instance -----------------------------------------------------------

  const userData =
    props.osType === "nixos"
      ? buildNixosUserData({ region, parameterPath: props.parameterPath })
      : buildUserData({
          appName: props.appName,
          artifactBucket: props.artifactBucket,
          artifactKey: props.artifactKey,
          artifactVersion: props.artifactVersion,
          layout,
          parameterPath: props.parameterPath,
          port,
          region,
        });

  const instance = await Ec2Instance(id, {
    name: id, ami: imageId, instanceType,
    subnetId: subnet.subnetId, securityGroupIds: [securityGroup.groupId],
    keyName: props.keyName ?? undefined, iamInstanceProfile: instanceProfileName,
    userData, rootVolumeSize, associatePublicIp: true, tags,
  });

  const host = instance.publicDns || instance.publicIp;
  const url = `http://${host}${port === 80 ? "" : `:${port}`}`;

  return {
    ...props, availabilityZone, imageId, instanceType, port, rootVolumeSize,
    publicIp: instance.publicIp ?? "",
    instanceId: instance.instanceId,
    publicDnsName: instance.publicDns ?? "",
    url,
    vpcId: vpc.vpcId,
    subnetId: subnet.subnetId,
    securityGroupId: securityGroup.groupId,
    roleArn: role.arn,
    instanceProfileArn: instanceProfile.Arn,
  };
}

// ---- AMI resolution ---------------------------------------------------------

/** Resolve SSM-parameter-style AMI references ({{resolve:ssm:...}}) to real AMI IDs. */
async function resolveImageId(imageId: string, region: string) {
  if (imageId.startsWith("ami-")) return imageId;

  const match = imageId.match(/^\{\{resolve:ssm:([^}:]+)(?::\d+)?\}\}$/);
  if (!match) return imageId;

  const client = new SSMClient({ region });
  const response = await client.send(new GetParameterCommand({ Name: match[1] }));
  const resolvedImageId = response.Parameter?.Value;

  if (!resolvedImageId?.startsWith("ami-")) {
    throw new Error(`Resolved AMI from SSM parameter ${match[1]} was not a valid EC2 image id.`);
  }
  return resolvedImageId;
}

/** Find the latest Determinate Systems NixOS AMI in the given region. */
async function resolveNixosAmi(region: string): Promise<string> {
  const { EC2Client, DescribeImagesCommand } = await import("@aws-sdk/client-ec2");
  const client = new EC2Client({ region });
  const images = await client.send(
    new DescribeImagesCommand({
      Owners: ["535002876703"],
      Filters: [
        { Name: "name", Values: ["determinate/nixos/epoch-1/*"] },
        { Name: "architecture", Values: ["x86_64"] },
        { Name: "state", Values: ["available"] },
      ],
    }),
  );
  const sorted = (images.Images ?? []).sort((a, b) =>
    (b.CreationDate ?? "").localeCompare(a.CreationDate ?? ""),
  );
  const imageId = sorted[0]?.ImageId;
  if (!imageId) throw new Error("No Determinate NixOS AMI found in " + region);
  return imageId;
}

// ---- String helpers ---------------------------------------------------------

function toAwsTags(tags: Record<string, string>) {
  return Object.entries(tags).map(([Key, Value]) => ({ Key, Value }));
}

function trimTrailingSlash(value: string) {
  return value.endsWith("/") ? value.slice(0, -1) : value;
}

function sanitizeName(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "app";
}
