/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as StudioVariablesRouteImport } from './routes/studio/variables'
import { Route as StudioTerminalRouteImport } from './routes/studio/terminal'
import { Route as StudioTeamRouteImport } from './routes/studio/team'
import { Route as StudioTasksRouteImport } from './routes/studio/tasks'
import { Route as StudioSetupRouteImport } from './routes/studio/setup'
import { Route as StudioServicesRouteImport } from './routes/studio/services'
import { Route as StudioSecretsRouteImport } from './routes/studio/secrets'
import { Route as StudioRoadmapRouteImport } from './routes/studio/roadmap'
import { Route as StudioProcessesRouteImport } from './routes/studio/processes'
import { Route as StudioPanelsRouteImport } from './routes/studio/panels'
import { Route as StudioPackagesRouteImport } from './routes/studio/packages'
import { Route as StudioNetworkRouteImport } from './routes/studio/network'
import { Route as StudioModulesRouteImport } from './routes/studio/modules'
import { Route as StudioLocalConfigRouteImport } from './routes/studio/local-config'
import { Route as StudioInspectorRouteImport } from './routes/studio/inspector'
import { Route as StudioInfraRouteImport } from './routes/studio/infra'
import { Route as StudioFilesRouteImport } from './routes/studio/files'
import { Route as StudioExtensionsRouteImport } from './routes/studio/extensions'
import { Route as StudioDevshellsRouteImport } from './routes/studio/devshells'
import { Route as StudioDeployRouteImport } from './routes/studio/deploy'
import { Route as StudioDatabasesRouteImport } from './routes/studio/databases'
import { Route as StudioDashboardRouteImport } from './routes/studio/dashboard'
import { Route as StudioConfigurationRouteImport } from './routes/studio/configuration'
import { Route as StudioChecksRouteImport } from './routes/studio/checks'
import { Route as StudioAppsRouteImport } from './routes/studio/apps'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSeedSnapshotsRouteImport } from './routes/api/seed-snapshots'
import { Route as ApiProvisionDbRouteImport } from './routes/api/provision-db'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioVariablesRoute = StudioVariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTerminalRoute = StudioTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTeamRoute = StudioTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTasksRoute = StudioTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSetupRoute = StudioSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => StudioRoute,
} as any)
const StudioServicesRoute = StudioServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSecretsRoute = StudioSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => StudioRoute,
} as any)
const StudioRoadmapRoute = StudioRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => StudioRoute,
} as any)
const StudioProcessesRoute = StudioProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPanelsRoute = StudioPanelsRouteImport.update({
  id: '/panels',
  path: '/panels',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPackagesRoute = StudioPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => StudioRoute,
} as any)
const StudioNetworkRoute = StudioNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => StudioRoute,
} as any)
const StudioModulesRoute = StudioModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLocalConfigRoute = StudioLocalConfigRouteImport.update({
  id: '/local-config',
  path: '/local-config',
  getParentRoute: () => StudioRoute,
} as any)
const StudioInspectorRoute = StudioInspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => StudioRoute,
} as any)
const StudioInfraRoute = StudioInfraRouteImport.update({
  id: '/infra',
  path: '/infra',
  getParentRoute: () => StudioRoute,
} as any)
const StudioFilesRoute = StudioFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => StudioRoute,
} as any)
const StudioExtensionsRoute = StudioExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => StudioRoute,
} as any)
const StudioDevshellsRoute = StudioDevshellsRouteImport.update({
  id: '/devshells',
  path: '/devshells',
  getParentRoute: () => StudioRoute,
} as any)
const StudioDeployRoute = StudioDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => StudioRoute,
} as any)
const StudioDatabasesRoute = StudioDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => StudioRoute,
} as any)
const StudioDashboardRoute = StudioDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudioRoute,
} as any)
const StudioConfigurationRoute = StudioConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => StudioRoute,
} as any)
const StudioChecksRoute = StudioChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAppsRoute = StudioAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => StudioRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedSnapshotsRoute = ApiSeedSnapshotsRouteImport.update({
  id: '/api/seed-snapshots',
  path: '/api/seed-snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvisionDbRoute = ApiProvisionDbRouteImport.update({
  id: '/api/provision-db',
  path: '/api/provision-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRouteWithChildren
  '/success': typeof SuccessRoute
  '/api/provision-db': typeof ApiProvisionDbRoute
  '/api/seed-snapshots': typeof ApiSeedSnapshotsRoute
  '/docs/$': typeof DocsSplatRoute
  '/studio/apps': typeof StudioAppsRoute
  '/studio/checks': typeof StudioChecksRoute
  '/studio/configuration': typeof StudioConfigurationRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/studio/databases': typeof StudioDatabasesRoute
  '/studio/deploy': typeof StudioDeployRoute
  '/studio/devshells': typeof StudioDevshellsRoute
  '/studio/extensions': typeof StudioExtensionsRoute
  '/studio/files': typeof StudioFilesRoute
  '/studio/infra': typeof StudioInfraRoute
  '/studio/inspector': typeof StudioInspectorRoute
  '/studio/local-config': typeof StudioLocalConfigRoute
  '/studio/modules': typeof StudioModulesRoute
  '/studio/network': typeof StudioNetworkRoute
  '/studio/packages': typeof StudioPackagesRoute
  '/studio/panels': typeof StudioPanelsRoute
  '/studio/processes': typeof StudioProcessesRoute
  '/studio/roadmap': typeof StudioRoadmapRoute
  '/studio/secrets': typeof StudioSecretsRoute
  '/studio/services': typeof StudioServicesRoute
  '/studio/setup': typeof StudioSetupRoute
  '/studio/tasks': typeof StudioTasksRoute
  '/studio/team': typeof StudioTeamRoute
  '/studio/terminal': typeof StudioTerminalRoute
  '/studio/variables': typeof StudioVariablesRoute
  '/docs/': typeof DocsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/api/provision-db': typeof ApiProvisionDbRoute
  '/api/seed-snapshots': typeof ApiSeedSnapshotsRoute
  '/docs/$': typeof DocsSplatRoute
  '/studio/apps': typeof StudioAppsRoute
  '/studio/checks': typeof StudioChecksRoute
  '/studio/configuration': typeof StudioConfigurationRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/studio/databases': typeof StudioDatabasesRoute
  '/studio/deploy': typeof StudioDeployRoute
  '/studio/devshells': typeof StudioDevshellsRoute
  '/studio/extensions': typeof StudioExtensionsRoute
  '/studio/files': typeof StudioFilesRoute
  '/studio/infra': typeof StudioInfraRoute
  '/studio/inspector': typeof StudioInspectorRoute
  '/studio/local-config': typeof StudioLocalConfigRoute
  '/studio/modules': typeof StudioModulesRoute
  '/studio/network': typeof StudioNetworkRoute
  '/studio/packages': typeof StudioPackagesRoute
  '/studio/panels': typeof StudioPanelsRoute
  '/studio/processes': typeof StudioProcessesRoute
  '/studio/roadmap': typeof StudioRoadmapRoute
  '/studio/secrets': typeof StudioSecretsRoute
  '/studio/services': typeof StudioServicesRoute
  '/studio/setup': typeof StudioSetupRoute
  '/studio/tasks': typeof StudioTasksRoute
  '/studio/team': typeof StudioTeamRoute
  '/studio/terminal': typeof StudioTerminalRoute
  '/studio/variables': typeof StudioVariablesRoute
  '/docs': typeof DocsIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRouteWithChildren
  '/success': typeof SuccessRoute
  '/api/provision-db': typeof ApiProvisionDbRoute
  '/api/seed-snapshots': typeof ApiSeedSnapshotsRoute
  '/docs/$': typeof DocsSplatRoute
  '/studio/apps': typeof StudioAppsRoute
  '/studio/checks': typeof StudioChecksRoute
  '/studio/configuration': typeof StudioConfigurationRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/studio/databases': typeof StudioDatabasesRoute
  '/studio/deploy': typeof StudioDeployRoute
  '/studio/devshells': typeof StudioDevshellsRoute
  '/studio/extensions': typeof StudioExtensionsRoute
  '/studio/files': typeof StudioFilesRoute
  '/studio/infra': typeof StudioInfraRoute
  '/studio/inspector': typeof StudioInspectorRoute
  '/studio/local-config': typeof StudioLocalConfigRoute
  '/studio/modules': typeof StudioModulesRoute
  '/studio/network': typeof StudioNetworkRoute
  '/studio/packages': typeof StudioPackagesRoute
  '/studio/panels': typeof StudioPanelsRoute
  '/studio/processes': typeof StudioProcessesRoute
  '/studio/roadmap': typeof StudioRoadmapRoute
  '/studio/secrets': typeof StudioSecretsRoute
  '/studio/services': typeof StudioServicesRoute
  '/studio/setup': typeof StudioSetupRoute
  '/studio/tasks': typeof StudioTasksRoute
  '/studio/team': typeof StudioTeamRoute
  '/studio/terminal': typeof StudioTerminalRoute
  '/studio/variables': typeof StudioVariablesRoute
  '/docs/': typeof DocsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/studio'
    | '/success'
    | '/api/provision-db'
    | '/api/seed-snapshots'
    | '/docs/$'
    | '/studio/apps'
    | '/studio/checks'
    | '/studio/configuration'
    | '/studio/dashboard'
    | '/studio/databases'
    | '/studio/deploy'
    | '/studio/devshells'
    | '/studio/extensions'
    | '/studio/files'
    | '/studio/infra'
    | '/studio/inspector'
    | '/studio/local-config'
    | '/studio/modules'
    | '/studio/network'
    | '/studio/packages'
    | '/studio/panels'
    | '/studio/processes'
    | '/studio/roadmap'
    | '/studio/secrets'
    | '/studio/services'
    | '/studio/setup'
    | '/studio/tasks'
    | '/studio/team'
    | '/studio/terminal'
    | '/studio/variables'
    | '/docs/'
    | '/studio/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/api/provision-db'
    | '/api/seed-snapshots'
    | '/docs/$'
    | '/studio/apps'
    | '/studio/checks'
    | '/studio/configuration'
    | '/studio/dashboard'
    | '/studio/databases'
    | '/studio/deploy'
    | '/studio/devshells'
    | '/studio/extensions'
    | '/studio/files'
    | '/studio/infra'
    | '/studio/inspector'
    | '/studio/local-config'
    | '/studio/modules'
    | '/studio/network'
    | '/studio/packages'
    | '/studio/panels'
    | '/studio/processes'
    | '/studio/roadmap'
    | '/studio/secrets'
    | '/studio/services'
    | '/studio/setup'
    | '/studio/tasks'
    | '/studio/team'
    | '/studio/terminal'
    | '/studio/variables'
    | '/docs'
    | '/studio'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/studio'
    | '/success'
    | '/api/provision-db'
    | '/api/seed-snapshots'
    | '/docs/$'
    | '/studio/apps'
    | '/studio/checks'
    | '/studio/configuration'
    | '/studio/dashboard'
    | '/studio/databases'
    | '/studio/deploy'
    | '/studio/devshells'
    | '/studio/extensions'
    | '/studio/files'
    | '/studio/infra'
    | '/studio/inspector'
    | '/studio/local-config'
    | '/studio/modules'
    | '/studio/network'
    | '/studio/packages'
    | '/studio/panels'
    | '/studio/processes'
    | '/studio/roadmap'
    | '/studio/secrets'
    | '/studio/services'
    | '/studio/setup'
    | '/studio/tasks'
    | '/studio/team'
    | '/studio/terminal'
    | '/studio/variables'
    | '/docs/'
    | '/studio/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  StudioRoute: typeof StudioRouteWithChildren
  SuccessRoute: typeof SuccessRoute
  ApiProvisionDbRoute: typeof ApiProvisionDbRoute
  ApiSeedSnapshotsRoute: typeof ApiSeedSnapshotsRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/variables': {
      id: '/studio/variables'
      path: '/variables'
      fullPath: '/studio/variables'
      preLoaderRoute: typeof StudioVariablesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/terminal': {
      id: '/studio/terminal'
      path: '/terminal'
      fullPath: '/studio/terminal'
      preLoaderRoute: typeof StudioTerminalRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/team': {
      id: '/studio/team'
      path: '/team'
      fullPath: '/studio/team'
      preLoaderRoute: typeof StudioTeamRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/tasks': {
      id: '/studio/tasks'
      path: '/tasks'
      fullPath: '/studio/tasks'
      preLoaderRoute: typeof StudioTasksRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/setup': {
      id: '/studio/setup'
      path: '/setup'
      fullPath: '/studio/setup'
      preLoaderRoute: typeof StudioSetupRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/services': {
      id: '/studio/services'
      path: '/services'
      fullPath: '/studio/services'
      preLoaderRoute: typeof StudioServicesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/secrets': {
      id: '/studio/secrets'
      path: '/secrets'
      fullPath: '/studio/secrets'
      preLoaderRoute: typeof StudioSecretsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/roadmap': {
      id: '/studio/roadmap'
      path: '/roadmap'
      fullPath: '/studio/roadmap'
      preLoaderRoute: typeof StudioRoadmapRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/processes': {
      id: '/studio/processes'
      path: '/processes'
      fullPath: '/studio/processes'
      preLoaderRoute: typeof StudioProcessesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/panels': {
      id: '/studio/panels'
      path: '/panels'
      fullPath: '/studio/panels'
      preLoaderRoute: typeof StudioPanelsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/packages': {
      id: '/studio/packages'
      path: '/packages'
      fullPath: '/studio/packages'
      preLoaderRoute: typeof StudioPackagesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/network': {
      id: '/studio/network'
      path: '/network'
      fullPath: '/studio/network'
      preLoaderRoute: typeof StudioNetworkRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/modules': {
      id: '/studio/modules'
      path: '/modules'
      fullPath: '/studio/modules'
      preLoaderRoute: typeof StudioModulesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/local-config': {
      id: '/studio/local-config'
      path: '/local-config'
      fullPath: '/studio/local-config'
      preLoaderRoute: typeof StudioLocalConfigRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/inspector': {
      id: '/studio/inspector'
      path: '/inspector'
      fullPath: '/studio/inspector'
      preLoaderRoute: typeof StudioInspectorRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/infra': {
      id: '/studio/infra'
      path: '/infra'
      fullPath: '/studio/infra'
      preLoaderRoute: typeof StudioInfraRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/files': {
      id: '/studio/files'
      path: '/files'
      fullPath: '/studio/files'
      preLoaderRoute: typeof StudioFilesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/extensions': {
      id: '/studio/extensions'
      path: '/extensions'
      fullPath: '/studio/extensions'
      preLoaderRoute: typeof StudioExtensionsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/devshells': {
      id: '/studio/devshells'
      path: '/devshells'
      fullPath: '/studio/devshells'
      preLoaderRoute: typeof StudioDevshellsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/deploy': {
      id: '/studio/deploy'
      path: '/deploy'
      fullPath: '/studio/deploy'
      preLoaderRoute: typeof StudioDeployRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/databases': {
      id: '/studio/databases'
      path: '/databases'
      fullPath: '/studio/databases'
      preLoaderRoute: typeof StudioDatabasesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/dashboard': {
      id: '/studio/dashboard'
      path: '/dashboard'
      fullPath: '/studio/dashboard'
      preLoaderRoute: typeof StudioDashboardRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/configuration': {
      id: '/studio/configuration'
      path: '/configuration'
      fullPath: '/studio/configuration'
      preLoaderRoute: typeof StudioConfigurationRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/checks': {
      id: '/studio/checks'
      path: '/checks'
      fullPath: '/studio/checks'
      preLoaderRoute: typeof StudioChecksRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/apps': {
      id: '/studio/apps'
      path: '/apps'
      fullPath: '/studio/apps'
      preLoaderRoute: typeof StudioAppsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-snapshots': {
      id: '/api/seed-snapshots'
      path: '/api/seed-snapshots'
      fullPath: '/api/seed-snapshots'
      preLoaderRoute: typeof ApiSeedSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provision-db': {
      id: '/api/provision-db'
      path: '/api/provision-db'
      fullPath: '/api/provision-db'
      preLoaderRoute: typeof ApiProvisionDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioAppsRoute: typeof StudioAppsRoute
  StudioChecksRoute: typeof StudioChecksRoute
  StudioConfigurationRoute: typeof StudioConfigurationRoute
  StudioDashboardRoute: typeof StudioDashboardRoute
  StudioDatabasesRoute: typeof StudioDatabasesRoute
  StudioDeployRoute: typeof StudioDeployRoute
  StudioDevshellsRoute: typeof StudioDevshellsRoute
  StudioExtensionsRoute: typeof StudioExtensionsRoute
  StudioFilesRoute: typeof StudioFilesRoute
  StudioInfraRoute: typeof StudioInfraRoute
  StudioInspectorRoute: typeof StudioInspectorRoute
  StudioLocalConfigRoute: typeof StudioLocalConfigRoute
  StudioModulesRoute: typeof StudioModulesRoute
  StudioNetworkRoute: typeof StudioNetworkRoute
  StudioPackagesRoute: typeof StudioPackagesRoute
  StudioPanelsRoute: typeof StudioPanelsRoute
  StudioProcessesRoute: typeof StudioProcessesRoute
  StudioRoadmapRoute: typeof StudioRoadmapRoute
  StudioSecretsRoute: typeof StudioSecretsRoute
  StudioServicesRoute: typeof StudioServicesRoute
  StudioSetupRoute: typeof StudioSetupRoute
  StudioTasksRoute: typeof StudioTasksRoute
  StudioTeamRoute: typeof StudioTeamRoute
  StudioTerminalRoute: typeof StudioTerminalRoute
  StudioVariablesRoute: typeof StudioVariablesRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAppsRoute: StudioAppsRoute,
  StudioChecksRoute: StudioChecksRoute,
  StudioConfigurationRoute: StudioConfigurationRoute,
  StudioDashboardRoute: StudioDashboardRoute,
  StudioDatabasesRoute: StudioDatabasesRoute,
  StudioDeployRoute: StudioDeployRoute,
  StudioDevshellsRoute: StudioDevshellsRoute,
  StudioExtensionsRoute: StudioExtensionsRoute,
  StudioFilesRoute: StudioFilesRoute,
  StudioInfraRoute: StudioInfraRoute,
  StudioInspectorRoute: StudioInspectorRoute,
  StudioLocalConfigRoute: StudioLocalConfigRoute,
  StudioModulesRoute: StudioModulesRoute,
  StudioNetworkRoute: StudioNetworkRoute,
  StudioPackagesRoute: StudioPackagesRoute,
  StudioPanelsRoute: StudioPanelsRoute,
  StudioProcessesRoute: StudioProcessesRoute,
  StudioRoadmapRoute: StudioRoadmapRoute,
  StudioSecretsRoute: StudioSecretsRoute,
  StudioServicesRoute: StudioServicesRoute,
  StudioSetupRoute: StudioSetupRoute,
  StudioTasksRoute: StudioTasksRoute,
  StudioTeamRoute: StudioTeamRoute,
  StudioTerminalRoute: StudioTerminalRoute,
  StudioVariablesRoute: StudioVariablesRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  StudioRoute: StudioRouteWithChildren,
  SuccessRoute: SuccessRoute,
  ApiProvisionDbRoute: ApiProvisionDbRoute,
  ApiSeedSnapshotsRoute: ApiSeedSnapshotsRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
