/**
 * Files Panel
 *
 * Displays generated files from stackpanel.files.entries.
 * Shows file metadata, staleness status, and allows regeneration.
 */

import { AlertTriangle, FileCode, Loader2, RefreshCw } from "lucide-react";
import { useState } from "react";
import type { GeneratedFileWithStatus } from "@/lib/types";
import { useGeneratedFiles } from "@/lib/use-generated-files";
import { cn } from "@/lib/utils";
import {
	EmptyState,
	PreviewModal,
	SourceGroup,
	SummaryStats,
	sortSources,
} from "./files";

// =============================================================================
// Main Component
// =============================================================================

export function FilesPanel() {
	const {
		data,
		isLoading,
		isError,
		error,
		refetch,
		filesBySource,
		staleFiles,
	} = useGeneratedFiles();

	const [previewFile, setPreviewFile] =
		useState<GeneratedFileWithStatus | null>(null);
	const [isRefreshing, setIsRefreshing] = useState(false);

	const handleRefetch = async () => {
		setIsRefreshing(true);
		try {
			await refetch();
		} finally {
			setIsRefreshing(false);
		}
	};

	if (isLoading) {
		return (
			<div className="flex min-h-[400px] items-center justify-center">
				<Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
			</div>
		);
	}

	if (isError) {
		return (
			<div className="flex min-h-[400px] flex-col items-center justify-center gap-4">
				<div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
					<p className="text-sm text-destructive">
						Failed to load generated files: {error?.message ?? "Unknown error"}
					</p>
				</div>
				<button
					type="button"
					onClick={handleRefetch}
					className="text-sm text-primary underline-offset-4 hover:underline"
				>
					Try again
				</button>
			</div>
		);
	}

	if (!data || data.totalCount === 0) {
		return <EmptyState onRefresh={handleRefetch} />;
	}

	const sortedSources = sortSources(Object.keys(filesBySource));

	return (
		<div className="space-y-6">
			{/* Header */}
			<div className="flex items-start justify-between">
				<div className="space-y-1">
					<h1 className="flex items-center gap-2 text-2xl font-bold">
						<FileCode className="h-6 w-6" />
						Generated Files
					</h1>
					<p className="text-muted-foreground">
						Files generated by stackpanel.files.entries
					</p>
				</div>
				<button
					type="button"
					onClick={handleRefetch}
					disabled={isRefreshing}
					className="inline-flex items-center gap-2 rounded-md border bg-background px-3 py-2 text-sm font-medium transition-colors hover:bg-accent disabled:opacity-50"
				>
					<RefreshCw
						className={cn("h-4 w-4", isRefreshing && "animate-spin")}
					/>
					{isRefreshing ? "Refreshing..." : "Refresh"}
				</button>
			</div>

			{/* Summary */}
			<div className="rounded-lg border bg-card p-4">
				<SummaryStats
					totalCount={data.totalCount}
					enabledCount={data.enabledCount}
					staleCount={data.staleCount}
					lastUpdated={data.lastUpdated}
				/>
			</div>

			{/* Stale files warning */}
			{staleFiles.length > 0 && (
				<div className="rounded-lg border border-yellow-500/30 bg-yellow-500/5 p-4">
					<div className="flex items-start gap-3">
						<AlertTriangle className="h-5 w-5 text-yellow-500" />
						<div className="space-y-1">
							<p className="font-medium text-yellow-600 dark:text-yellow-400">
								{staleFiles.length} file{staleFiles.length !== 1 ? "s" : ""}{" "}
								need regeneration
							</p>
							<p className="text-sm text-muted-foreground">
								Run <code className="rounded bg-muted px-1">write-files</code>{" "}
								in your devshell to update them.
							</p>
						</div>
					</div>
				</div>
			)}

			{/* File groups */}
			<div className="space-y-4">
				{sortedSources.map((source) => (
					<SourceGroup
						key={source}
						source={source}
						files={filesBySource[source]}
						onPreview={setPreviewFile}
					/>
				))}
			</div>

			{/* Preview modal */}
			<PreviewModal file={previewFile} onClose={() => setPreviewFile(null)} />
		</div>
	);
}
