// ==============================================================================
// Alchemy Bootstrap - State Store Provisioning
//
// Auto-generated by Stackpanel -- do not edit manually.
//
// This script bootstraps the CloudflareStateStore worker using FILESYSTEM state.
// This solves the chicken-and-egg problem: the main alchemy.run.ts needs the
// state store worker to exist, but the worker needs to be deployed via alchemy.
//
// By using filesystem state here, we can deploy the state store worker without
// needing it to already exist. Subsequent deploys use CloudflareStateStore.
//
// Usage (called by alchemy:setup, not directly):
//   CLOUDFLARE_API_TOKEN=xxx ALCHEMY_STATE_TOKEN=xxx bunx alchemy deploy bootstrap.run.ts --stage bootstrap
//
// Template variables (replaced at codegen time):
//   __APP_NAME__            - alchemy app name
//   __CF_API_TOKEN_ENV_VAR__ - env var name for Cloudflare token
//   __STATE_TOKEN_ENV_VAR__ - env var name for state token
// ==============================================================================
import alchemy from "alchemy";
import { CloudflareStateStore } from "alchemy/state";

const cfToken = process.env.__CF_API_TOKEN_ENV_VAR__;
const stateToken = process.env.__STATE_TOKEN_ENV_VAR__;

if (!cfToken) {
  console.error(
    "ERROR: __CF_API_TOKEN_ENV_VAR__ is not set. Run alchemy:setup first.",
  );
  process.exit(1);
}

if (!stateToken) {
  console.error(
    "ERROR: __STATE_TOKEN_ENV_VAR__ is not set. Run alchemy:setup first.",
  );
  process.exit(1);
}

// Initialize alchemy with FILESYSTEM state (the default).
// We intentionally do NOT use CloudflareStateStore here because we're
// bootstrapping the very worker that CloudflareStateStore depends on.
const app = await alchemy("__APP_NAME__-bootstrap", {
  stage: "bootstrap",
  // stateStore is undefined = FileSystemStateStore (no external dependency)
});

// The CloudflareStateStore auto-deploys the alchemy-state-service worker
// when it's first used. We create an instance here to trigger that deployment,
// then immediately verify it works by doing a test write/read cycle.
//
// The bootstrap state file (.alchemy/__APP_NAME__-bootstrap/bootstrap/) is
// gitignored and only used for this one-time provisioning.
const testScope = {
  appName: "__APP_NAME__",
  stage: "bootstrap-verify",
};

const stateStore = new CloudflareStateStore(testScope, {
  apiToken: alchemy.secret(cfToken),
  stateToken: alchemy.secret(stateToken),
});

// Verify the state store works with a round-trip test
const testKey = `_bootstrap_verify_${Date.now()}`;
const testData = JSON.stringify({ bootstrapped: true, at: new Date().toISOString() });

await stateStore.set(testKey, testData);
const readBack = await stateStore.get(testKey);

if (!readBack) {
  console.error("ERROR: State store verification failed -- could not read back test data.");
  process.exit(1);
}

// Clean up test data
await stateStore.delete(testKey);

console.log("State store provisioned and verified successfully.");

await app.finalize();
