// ==============================================================================
// File Helper (SOPS-aware, Alchemy FS composition)
//
// Auto-generated by Stackpanel -- do not edit manually.
//
// Composes Alchemy's `File` resource module with a secret-aware reader that
// supports refs in the form: ref+sops://path/to/file.sops.yaml#/json/pointer
// ==============================================================================

import { dirname, isAbsolute, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import alchemy from "alchemy";
import { File as AlchemyFile } from "alchemy/fs";
// @ts-ignore -- generated package adds runtime dependency; template workspace may not have types installed
import { decryptSops } from "sops-age";

const SOPS_REF_PREFIX = "ref+sops://";
const SOPS_REF_REGEX = /^ref\+sops:\/\/(.+?)#\/(.+)$/;
const SOPS_METADATA_KEYS = new Set<string>([
  "sops",
  "sops_age",
  "sops_azure_kv",
  "sops_gcp_kms",
  "sops_hc_vault",
  "sops_kms",
  "sops_pgp",
]);

export { AlchemyFile };
export type AlchemyFsFileResource = typeof AlchemyFile;

export interface FileModule {
  readFile(path: string): Promise<string>;
  secret(value: string): unknown;
  readSecret(pathOrRef: string): Promise<unknown>;
}

export interface AlchemyFileModuleOptions {
  /**
   * Base directory used to resolve relative paths in ref+sops:// URLs.
   * Defaults to process.cwd().
   */
  rootDir?: string;

  /**
   * Optional plain file reader override (composition hook).
   * If omitted, this module reads plain files via node:fs/promises.
   */
  readPlainFile?: (filePath: string) => Promise<string>;

  /**
   * Optional AGE secret key content passed directly to sops-age.
   * If omitted, sops-age will use SOPS_AGE_KEY_FILE / SOPS_AGE_KEY / SOPS_AGE_KEY_CMD.
   */
  secretKey?: string;
}

/**
 * Secret-aware file module that composes:
 * - Alchemy FS module surface (re-exported `AlchemyFile` resource), and
 * - A read API that understands plain files + ref+sops:// refs.
 * - Alchemy-native secret wrappers for values loaded from files/SOPS.
 */
export class AlchemyFileModule implements FileModule {
  private readonly resolveSopsRefImpl: (ref: string) => Promise<string>;
  private readonly readPlainFileImpl: (filePath: string) => Promise<string>;

  public constructor(options: AlchemyFileModuleOptions = {}) {
    const rootDir = options.rootDir ?? process.cwd();
    this.resolveSopsRefImpl = createDefaultSopsResolver({
      rootDir,
      secretKey: options.secretKey,
    });

    this.readPlainFileImpl =
      options.readPlainFile ??
      (async (filePath: string): Promise<string> =>
        (await import("node:fs/promises")).readFile(filePath, "utf8"));
  }

  public async readFile(filePath: string): Promise<string> {
    if (!filePath.startsWith(SOPS_REF_PREFIX)) {
      return this.readPlainFileImpl(filePath);
    }

    return this.resolveSopsRefImpl(filePath);
  }

  public secret(value: string): unknown {
    return wrapAlchemySecret(value);
  }

  public async readSecret(pathOrRef: string): Promise<unknown> {
    const value = await this.readFile(pathOrRef);
    return this.secret(value);
  }
}

export interface DefaultSopsResolverOptions {
  rootDir?: string;
  secretKey?: string;
}

/**
 * Creates a default SOPS ref resolver backed by `sops-age` (pure JS).
 *
 * Expected behavior:
 * - Accepts refs like:
 *   ref+sops://.stack/secrets/vars/common.sops.yaml#/API_KEY
 * - Decrypts via sops-age
 * - Returns the selected pointer value as a string
 */
export const createDefaultSopsResolver = (
  options: DefaultSopsResolverOptions = {},
): ((ref: string) => Promise<string>) => {
  const rootDir = options.rootDir ?? process.cwd();

  return async (ref: string): Promise<string> => {
    const { filePath, pointerPath } = parseSopsRef(ref, rootDir);

    const decrypted = await decryptSopsToObject({
      path: filePath,
      secretKey: options.secretKey,
    });

    const value = getByJsonPointer(decrypted, pointerPath);

    if (value === null || value === undefined) {
      throw new Error(`SOPS ref resolved to empty value: ${ref}`);
    }

    if (typeof value === "string") {
      return value;
    }

    if (typeof value === "number" || typeof value === "boolean") {
      return String(value);
    }

    return JSON.stringify(value);
  };
};

interface ParsedSopsRef {
  filePath: string;
  pointerPath: string;
}

const parseSopsRef = (ref: string, rootDir: string): ParsedSopsRef => {
  const match = ref.match(SOPS_REF_REGEX);
  if (!match) {
    throw new Error(
      `Invalid SOPS ref format: ${ref}. Expected ref+sops://<path>#/<pointer>`,
    );
  }

  const [, rawPath, pointerPath] = match;

  const filePath = isAbsolute(rawPath) ? rawPath : resolve(rootDir, rawPath);

  return { filePath, pointerPath };
};

interface DecryptSopsInput {
  path: string;
  secretKey?: string;
}

const decryptSopsToObject = async (
  input: DecryptSopsInput,
): Promise<Record<string, unknown>> => {
  try {
    const opts: { path: string; secretKey?: string } = { path: input.path };
    if (input.secretKey) {
      opts.secretKey = input.secretKey;
    }

    const result = (await decryptSops(opts)) as Record<string, unknown>;
    return stripSopsMetadata(result ?? {});
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    if (
      message.includes("could not decrypt") ||
      message.includes("No secret key")
    ) {
      throw new Error(
        `Failed to decrypt ${input.path}. Ensure AGE key is available via SOPS_AGE_KEY_FILE, SOPS_AGE_KEY, or SOPS_AGE_KEY_CMD environment variable.`,
      );
    }
    throw new Error(`Failed to decrypt ${input.path}: ${message}`);
  }
};

const stripSopsMetadata = (
  obj: Record<string, unknown>,
): Record<string, unknown> => {
  const filtered: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (SOPS_METADATA_KEYS.has(key)) {
      continue;
    }
    filtered[key] = value;
  }
  return filtered;
};

const decodeJsonPointerSegment = (segment: string): string =>
  segment.replace(/~1/g, "/").replace(/~0/g, "~");

const wrapAlchemySecret = (value: string): unknown => alchemy.secret(value);

const getByJsonPointer = (root: unknown, pointerPath: string): unknown => {
  const segments = pointerPath
    .split("/")
    .filter(Boolean)
    .map((segment) => decodeJsonPointerSegment(segment));

  let current: unknown = root;

  for (const segment of segments) {
    if (Array.isArray(current)) {
      const index = Number.parseInt(segment, 10);
      if (Number.isNaN(index) || index < 0 || index >= current.length) {
        throw new Error(`SOPS pointer not found: #/${pointerPath}`);
      }
      current = current[index];
      continue;
    }

    if (
      typeof current !== "object" ||
      current === null ||
      !(segment in (current as Record<string, unknown>))
    ) {
      throw new Error(`SOPS pointer not found: #/${pointerPath}`);
    }

    current = (current as Record<string, unknown>)[segment];
  }

  return current;
};

/**
 * Helper to create a module instance with sensible defaults for generated code.
 */
export const createAlchemyFileModule = (
  options: AlchemyFileModuleOptions = {},
): AlchemyFileModule => new AlchemyFileModule(options);

/**
 * Utility for ESM callers that want a stable root relative to current module.
 */
export const moduleDir = (metaUrl: string): string =>
  dirname(fileURLToPath(metaUrl));
