#!/usr/bin/env bash
# ==============================================================================
# Auto-generated entrypoint for docs
# Generated by stackpanel - do not edit manually
# Regenerate by entering the devshell: nix develop --impure
#
# This script ONLY sets up environment variables. It does NOT run commands.
# Source this script, then run your command:
#
#   source packages/scripts/entrypoints/docs.sh --dev
#   bun run dev
#
# Or inline:
#   source packages/scripts/entrypoints/docs.sh --dev && bun run dev
# ==============================================================================

# Prevent execution - this script should only be sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "[ERROR] This script should be sourced, not executed directly." >&2
  echo "Usage: source $0 [--dev] [--env <env>] [--no-secrets]" >&2
  exit 1
fi

# Find script directory and source common library
_ENTRYPOINT_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_ENTRYPOINT_LIB_DIR="$(dirname "$_ENTRYPOINT_SCRIPT_DIR")/lib"

if [[ -f "$_ENTRYPOINT_LIB_DIR/common.sh" ]]; then
  source "$_ENTRYPOINT_LIB_DIR/common.sh"
else
  echo "[ERROR] Could not find common.sh at $_ENTRYPOINT_LIB_DIR/common.sh" >&2
  return 1
fi

# ==============================================================================
# App Configuration (from Nix)
# ==============================================================================

export STACKPANEL_APP_NAME="docs"
export STACKPANEL_APP_PATH="apps/docs"
export STACKPANEL_VARIABLES_BACKEND="chamber"
export STACKPANEL_CHAMBER_SERVICE_PREFIX="stackpanel"
export STACKPANEL_MASTER_KEYS='{"local":{"age-pub":"","ref":"ref+file://.stackpanel/state/keys/local.txt","resolve-cmd":null}}'

# ==============================================================================
# Argument Parsing
# ==============================================================================

_ENTRYPOINT_DEV_MODE=false
_ENTRYPOINT_ENVIRONMENT=""
_ENTRYPOINT_SKIP_SECRETS=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dev)
      _ENTRYPOINT_DEV_MODE=true
      shift
      ;;
    --env)
      _ENTRYPOINT_ENVIRONMENT="$2"
      shift 2
      ;;
    --no-secrets)
      _ENTRYPOINT_SKIP_SECRETS=true
      shift
      ;;
    *)
      # Ignore unknown args (they're for the command, not for us)
      shift
      ;;
  esac
done

# Set default environment
if [[ -z "$_ENTRYPOINT_ENVIRONMENT" ]]; then
  if [[ "$_ENTRYPOINT_DEV_MODE" == "true" ]]; then
    _ENTRYPOINT_ENVIRONMENT="dev"
  else
    _ENTRYPOINT_ENVIRONMENT="prod"
  fi
fi

# Export environment for downstream use
export STACKPANEL_ENVIRONMENT="$_ENTRYPOINT_ENVIRONMENT"
export STACKPANEL_DEV_MODE="$_ENTRYPOINT_DEV_MODE"

log_debug "Entrypoint: docs"
log_debug "Environment: $_ENTRYPOINT_ENVIRONMENT"
log_debug "Dev mode: $_ENTRYPOINT_DEV_MODE"

# ==============================================================================
# Environment Setup
# ==============================================================================

_ENTRYPOINT_PROJECT_ROOT=$(find_project_root) || { log_error "Could not find project root"; return 1; }
export STACKPANEL_PROJECT_ROOT="$_ENTRYPOINT_PROJECT_ROOT"

# Dev mode: ensure devshell environment
if [[ "$_ENTRYPOINT_DEV_MODE" == "true" ]]; then
  ensure_devshell || { log_error "Failed to set up devshell"; return 1; }
fi

# Load secrets (unless skipped)
if [[ "$_ENTRYPOINT_SKIP_SECRETS" != "true" ]] && [[ "${STACKPANEL_NO_SECRETS:-}" != "1" ]]; then
  load_secrets "$STACKPANEL_APP_NAME" "$_ENTRYPOINT_ENVIRONMENT" || log_warn "Secrets loading failed, continuing anyway"
fi

# ==============================================================================
# Done - environment is now set up
# ==============================================================================

log_debug "Entrypoint complete - environment ready for docs"

# Clean up internal variables (keep exported ones)
unset _ENTRYPOINT_SCRIPT_DIR _ENTRYPOINT_LIB_DIR
unset _ENTRYPOINT_DEV_MODE _ENTRYPOINT_ENVIRONMENT _ENTRYPOINT_SKIP_SECRETS
unset _ENTRYPOINT_PROJECT_ROOT
