# ==============================================================================
# module.nix - Fly.io Deployment Module Implementation
#
# Provides Fly.io deployment support for stackpanel apps.
#
# This module:
#   1. Adds deployment.* options to each app via appModules
#   2. Generates fly.toml into packages/infra/fly/
#   3. Contributes Dockerfile config to stackpanel.docker.images
#   4. Adds deploy scripts to packages/infra/package.json
#   5. Registers a single turbo task per deployable app
#
# Generated layout:
#   packages/infra/
#   ├── package.json           # "deploy:web" script (merged via SST)
#   ├── turbo.json             # Per-package turbo config (extends root)
#   ├── docker/
#   │   └── <appName>/
#   │       └── Dockerfile     # Generated by stackpanel.docker (not this module)
#   └── fly/
#       └── <appName>/
#           └── fly.toml       # Fly.io app configuration
#
# Deploy:
#   flyctl deploy --config packages/infra/fly/web/fly.toml
#
# Usage:
#   stackpanel.apps.web = {
#     path = "apps/web";
#     deployment = {
#       enable = true;
#       provider = "fly";
#       fly.appName = "my-app";
#       container = { type = "bun"; port = 3000; };
#     };
#   };
# ==============================================================================
{
  lib,
  config,
  pkgs,
  ...
}:
let
  meta = import ./meta.nix;
  cfg = config.stackpanel;
  deployCfg = cfg.deployment;
  infraPath = "packages/infra";

  # ---------------------------------------------------------------------------
  # Per-app deployment options module (added via appModules)
  # ---------------------------------------------------------------------------
  deploymentAppModule =
    { lib, name, ... }:
    {
      options.deployment = {
        enable = lib.mkEnableOption "deployment for this app";

        provider = lib.mkOption {
          type = lib.types.enum [ "fly" ];
          default = deployCfg.defaultProvider or "fly";
          description = "Deployment provider to use.";
        };

        fly = {
          appName = lib.mkOption {
            type = lib.types.str;
            default = name;
            description = "Fly.io app name.";
          };

          region = lib.mkOption {
            type = lib.types.str;
            default = deployCfg.fly.defaultRegion or "iad";
            description = "Fly.io region for deployment.";
          };

          memory = lib.mkOption {
            type = lib.types.str;
            default = "512mb";
            description = "Memory allocation for the VM.";
          };

          cpuKind = lib.mkOption {
            type = lib.types.enum [
              "shared"
              "performance"
            ];
            default = "shared";
            description = "CPU type for the VM.";
          };

          cpus = lib.mkOption {
            type = lib.types.int;
            default = 1;
            description = "Number of CPUs for the VM.";
          };

          autoStop = lib.mkOption {
            type = lib.types.enum [
              "off"
              "stop"
              "suspend"
            ];
            default = "suspend";
            description = "Auto-stop behavior for machines.";
          };

          autoStart = lib.mkOption {
            type = lib.types.bool;
            default = true;
            description = "Auto-start machines on request.";
          };

          minMachines = lib.mkOption {
            type = lib.types.int;
            default = 0;
            description = "Minimum number of machines to keep running.";
          };

          forceHttps = lib.mkOption {
            type = lib.types.bool;
            default = true;
            description = "Force HTTPS for all requests.";
          };

          env = lib.mkOption {
            type = lib.types.attrsOf lib.types.str;
            default = { };
            description = "Environment variables for fly.toml.";
          };
        };

        container = {
          type = lib.mkOption {
            type = lib.types.enum [
              "bun"
              "node"
              "go"
              "static"
              "custom"
            ];
            default = "bun";
            description = "App type determines the generated Dockerfile.";
          };

          port = lib.mkOption {
            type = lib.types.int;
            default = 3000;
            description = "Internal port the app listens on.";
          };

          entrypoint = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Container CMD override.";
          };

          dockerfile = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Custom Dockerfile content (overrides auto-generation).";
          };
        };
      };
    };

  # ---------------------------------------------------------------------------
  # Filter deployable apps
  # ---------------------------------------------------------------------------
  getDeployableApps =
    apps:
    lib.filterAttrs (
      _: appCfg: (appCfg.deployment.enable or false) && (appCfg.deployment.provider or "fly") == "fly"
    ) apps;

  # ---------------------------------------------------------------------------
  # Generate fly.toml content
  # Dockerfile path references stackpanel.docker's output location
  # ---------------------------------------------------------------------------
  mkFlyToml =
    appName: appCfg:
    let
      d = appCfg.deployment;
      f = d.fly;
      c = d.container;

      allEnv = {
        PORT = toString c.port;
      }
      // f.env;
      envSection = lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: "${k} = '${v}'") allEnv);

      # Dockerfile is generated by stackpanel.docker at this path
      dockerfilePath = "${infraPath}/docker/${appName}/Dockerfile";
    in
    ''
      # Generated by stackpanel - do not edit manually
      # Regenerate by entering the devshell: nix develop --impure

      app = "${f.appName}"

      [build]
      dockerfile = "${dockerfilePath}"

      [env]
      ${envSection}

      [http_service]
      internal_port = ${toString c.port}
      force_https = ${lib.boolToString f.forceHttps}
      auto_stop_machines = "${f.autoStop}"
      auto_start_machines = ${lib.boolToString f.autoStart}
      min_machines_running = ${toString f.minMachines}
      processes = ["app"]

      [[vm]]
      memory = "${f.memory}"
      cpu_kind = "${f.cpuKind}"
      cpus = ${toString f.cpus}
    '';

  # ---------------------------------------------------------------------------
  # Package.json scripts
  # ---------------------------------------------------------------------------
  mkDeployPackageScripts =
    deployableApps:
    lib.foldlAttrs (
      acc: appName: _:
      acc
      // {
        "deploy:${appName}" = "cd ../.. && flyctl deploy --config ${infraPath}/fly/${appName}/fly.toml";
      }
    ) { } deployableApps;

  # ---------------------------------------------------------------------------
  # Turbo task per deployable app
  # ---------------------------------------------------------------------------
  mkDeployTasks = appName: _appCfg: {
    "deploy:${appName}" = {
      description = "Deploy ${appName} to Fly.io";
      cache = false;
    };
  };

  # Per-package turbo.json
  infraTurboJson = builtins.toJSON { extends = [ "//" ]; };

  # ---------------------------------------------------------------------------
  # Contribute docker images from deployable apps
  # ---------------------------------------------------------------------------
  mkDockerImages =
    deployableApps:
    lib.mapAttrs (
      appName: appCfg:
      let
        d = appCfg.deployment;
        c = d.container;
      in
      {
        registry = "registry.fly.io";
        name = d.fly.appName;
        dockerfile = {
          enable = true;
          type = c.type;
          appPath = appCfg.path or "apps/${appName}";
          port = c.port;
          entrypoint = c.entrypoint;
          content = c.dockerfile;
        };
      }
    ) deployableApps;

  # Check if we have any deployable apps
  hasDeployableApps = deployableApps != { };
  deployableApps = getDeployableApps cfg.apps;

in
{
  # ===========================================================================
  # Options
  # ===========================================================================
  options.stackpanel.deployment = {
    enable = lib.mkEnableOption "deployment module" // {
      default = true;
    };

    defaultProvider = lib.mkOption {
      type = lib.types.enum [ "fly" ];
      default = "fly";
      description = "Default deployment provider.";
    };

    fly = {
      organization = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Fly.io organization slug.";
      };

      defaultRegion = lib.mkOption {
        type = lib.types.str;
        default = "iad";
        description = "Default Fly.io region for deployments.";
      };
    };
  };

  # ===========================================================================
  # Configuration
  # ===========================================================================
  config = lib.mkMerge [
    # Always add appModules (unconditionally)
    {
      stackpanel.appModules = [ deploymentAppModule ];
    }

    # Apply config when stackpanel is enabled and has deployable apps
    (lib.mkIf (cfg.enable && deployCfg.enable && hasDeployableApps) {
      # -------------------------------------------------------------------------
      # Contribute container images to stackpanel.docker
      # The docker module generates the Dockerfiles; we just declare what we need
      # -------------------------------------------------------------------------
      stackpanel.docker.enable = true;
      stackpanel.docker.images = mkDockerImages deployableApps;

      # -------------------------------------------------------------------------
      # Merge deploy scripts into SST's packages/infra/package.json
      # -------------------------------------------------------------------------
      stackpanel.sst.package.scripts = mkDeployPackageScripts deployableApps;

      # -------------------------------------------------------------------------
      # Generated Files (fly.toml only — Dockerfiles come from docker module)
      # -------------------------------------------------------------------------
      stackpanel.files.entries = lib.mkMerge [
        # packages/infra/turbo.json
        {
          "${infraPath}/turbo.json" = {
            type = "text";
            text = infraTurboJson;
            source = meta.id;
            description = "Per-package turbo config for deploy tasks";
          };
        }

        # packages/infra/fly/<appName>/fly.toml
        (lib.mapAttrs' (appName: appCfg: {
          name = "${infraPath}/fly/${appName}/fly.toml";
          value = {
            type = "text";
            text = mkFlyToml appName appCfg;
            source = meta.id;
            description = "Fly.io configuration for ${appName}";
          };
        }) deployableApps)
      ];

      # -------------------------------------------------------------------------
      # Turbo Tasks
      # -------------------------------------------------------------------------
      stackpanel.tasks = lib.mkMerge (lib.mapAttrsToList mkDeployTasks deployableApps);

      # -------------------------------------------------------------------------
      # Devshell Packages (flyctl only — skopeo comes from docker module)
      # -------------------------------------------------------------------------
      stackpanel.devshell.packages = [
        pkgs.flyctl
      ];

      # -------------------------------------------------------------------------
      # Health Checks (flyctl only — skopeo comes from docker module)
      # -------------------------------------------------------------------------
      stackpanel.healthchecks.modules.${meta.id} = {
        enable = true;
        displayName = meta.name;
        checks = {
          flyctl-installed = {
            description = "Fly.io CLI is installed and accessible";
            script = ''
              command -v flyctl >/dev/null 2>&1 && flyctl version
            '';
            severity = "critical";
            timeout = 5;
          };

          flyctl-auth = {
            description = "Logged in to Fly.io";
            script = ''
              flyctl auth whoami 2>/dev/null
            '';
            severity = "warning";
            timeout = 10;
          };
        };
      };

      # -------------------------------------------------------------------------
      # Module Registration
      # -------------------------------------------------------------------------
      stackpanel.modules.${meta.id} = {
        enable = true;
        meta = {
          name = meta.name;
          description = meta.description;
          icon = meta.icon;
          category = meta.category;
          author = meta.author;
          version = meta.version;
          homepage = meta.homepage;
        };
        source.type = "builtin";
        features = meta.features;
        tags = meta.tags;
        priority = meta.priority;
      };
    })
  ];
}
