// Auto-generated by Stackpanel — do not edit manually.
// Exposes env for this app by selecting the right environment at runtime.
import * as app from "./{{APP_NAME}}";

const envName = process.env.APP_ENV || process.env.NODE_ENV || "dev";

const env = (() => {
{{ENV_CASES}}
  return (app as any).dev.getEnv();
})();

export { env };
