// Auto-generated by Stackpanel — do not edit manually.
// Exposes env for this app by selecting the right environment at runtime.
import * as app from "../apps/{{APP_NAME}}/index";

const processEnv = typeof process === "undefined"
  ? {}
  : (process.env as Record<string, string | undefined>);

const rawEnvName = processEnv.APP_ENV || processEnv.NODE_ENV || "{{DEFAULT_ENV}}";
const envName = rawEnvName === "production" ? "prod" : rawEnvName === "development" ? "dev" : rawEnvName;

export type Env = {{ENV_TYPE}};

const env: Env = (() => {
{{ENV_CASES}}
  return app.{{DEFAULT_ENV_IDENT}}.getEnv(processEnv);
})();

export { env };
