// Auto-generated by Stackpanel — do not edit manually.
// Runtime environment loader — uses embedded env metadata and encrypted SOPS payloads.

import { existsSync } from "fs";
import { join } from "path";
import { decryptSops } from "sops-age";
import { APP_ENVS, COMPUTED_VARS, SECRET_FILE_CONTENTS, SECRET_YAML_KEYS, SHARED_VARS } from "./embedded-data";

const VARIABLE_LINK_PREFIX = "var://";
const SOPS_REF_PREFIX = "ref+sops://";
const secretCache = new Map<string, string>();
const sopsRefCache = new Map<string, string>();

export interface LoadEnvOptions {
  /** Inject loaded vars into process.env (default: true) */
  inject?: boolean;
  /** Kept for backwards compatibility; embedded data is used by default */
  dataDir?: string;
  /** Skip SOPS decryption (only relevant for shared vars) */
  skipDecrypt?: boolean;
  /** Explicit AGE secret key for decryption (overrides env-based discovery) */
  secretKey?: string;
}

export async function loadEnv(
  app: string,
  env: string,
  options: LoadEnvOptions = {},
): Promise<Record<string, string>> {
  const { inject = true } = options;

  let envVars: Record<string, string>;

  if (app === "shared" && env === "vars") {
    envVars = { ...SHARED_VARS };
  } else {
    const embedded = APP_ENVS[app]?.[env];
    if (!embedded) {
      throw new Error(`Environment data not found for ${app}/${env}`);
    }
    envVars = { ...embedded };
  }

  if (inject) {
    Object.assign(process.env, envVars);
  }

  return envVars;
}

export async function loadSharedVars(
  options: Omit<LoadEnvOptions, "skipDecrypt"> = {},
): Promise<Record<string, string>> {
  return loadEnv("shared", "vars", { ...options, skipDecrypt: true });
}

export async function loadAppEnv(
  app: string,
  env: string,
  options: LoadEnvOptions = {},
): Promise<Record<string, string>> {
  const shared = await loadSharedVars({
    ...options,
    inject: false,
  });
  const rawAppEnv = await loadEnv(app, env, {
    ...options,
    inject: false,
  });
  const appEnv = await resolveVariableLinks(rawAppEnv, shared, options.secretKey);

  const merged = { ...shared, ...appEnv };

  if (options.inject !== false) {
    Object.assign(process.env, merged);
  }

  return merged;
}

async function resolveVariableLinks(
  envVars: Record<string, string>,
  sharedVars: Record<string, string>,
  secretKey?: string,
): Promise<Record<string, string>> {
  const resolved: Record<string, string> = { ...envVars };

  for (const [envKey, value] of Object.entries(envVars)) {
    const variableId = parseVariableLink(value);
    if (!variableId) {
      const sopsRef = parseSopsReference(value);
      if (sopsRef) {
        resolved[envKey] = await loadReferencedSopsValue(sopsRef, secretKey);
      }
      continue;
    }

    const keyGroup = getVariableKeyGroup(variableId);
    const variableName = getVariableName(variableId);

    if (keyGroup === "var") {
      const sharedValue = sharedVars[variableName];
      if (sharedValue === undefined) {
        throw new Error(
          `Could not resolve ${envKey}: linked variable ${variableId} was not found in shared vars`,
        );
      }
      resolved[envKey] = sharedValue;
      continue;
    }

    if (keyGroup === "computed") {
      const computedValue = COMPUTED_VARS[variableId] ?? process.env[variableName];
      if (computedValue === undefined) {
        throw new Error(
          `Could not resolve ${envKey}: linked computed variable ${variableId} is not available at runtime`,
        );
      }
      resolved[envKey] = computedValue;
      continue;
    }

    const secretValue = await loadSecretVariable(variableId, secretKey);
    if (secretValue === undefined) {
      throw new Error(
        `Could not resolve ${envKey}: linked variable ${variableId} was not found in its SOPS file`,
      );
    }
    resolved[envKey] = secretValue;
  }

  return resolved;
}

function parseSopsReference(value: string): { path: string; key: string } | null {
  if (!value.startsWith(SOPS_REF_PREFIX)) {
    return null;
  }

  const raw = value.slice(SOPS_REF_PREFIX.length);
  const hashIndex = raw.indexOf("#/");
  if (hashIndex === -1) {
    return null;
  }

  const path = raw.slice(0, hashIndex);
  const key = raw.slice(hashIndex + 2);
  if (!path || !key) {
    return null;
  }

  return { path, key };
}

function parseVariableLink(value: string): string | null {
  if (!value.startsWith(VARIABLE_LINK_PREFIX)) {
    return null;
  }

  const rawId = value.slice(VARIABLE_LINK_PREFIX.length).trim();
  if (!rawId) {
    return null;
  }

  return rawId.startsWith("/") ? rawId : `/${rawId}`;
}

function getVariableKeyGroup(variableId: string): string {
  const match = variableId.match(/^\/([^/]+)\//);
  return match?.[1] ?? "var";
}

function getVariableName(variableId: string): string {
  const parts = variableId.split("/").filter(Boolean);
  return parts[parts.length - 1] ?? variableId;
}

async function loadReferencedSopsValue(
  ref: { path: string; key: string },
  secretKey?: string,
): Promise<string> {
  const cacheKey = `${ref.path}#/${ref.key}`;
  const cached = sopsRefCache.get(cacheKey);
  if (cached !== undefined) {
    return cached;
  }

  const path = resolveSopsRefPath(ref.path);
  const parsed = filterSopsMetadata(await decryptSopsFile(path, secretKey));
  const value = parsed[ref.key];
  if (value === undefined) {
    throw new Error(`Could not resolve SOPS reference ${cacheKey}: key not found`);
  }
  sopsRefCache.set(cacheKey, value);
  return value;
}

function resolveSopsRefPath(refPath: string): string {
  if (refPath.startsWith("/")) {
    return refPath;
  }
  return join(process.cwd(), refPath);
}

async function loadSecretVariable(
  variableId: string,
  secretKey?: string,
): Promise<string | undefined> {
  const cached = secretCache.get(variableId);
  if (cached !== undefined) {
    return cached;
  }

  const embedded = SECRET_FILE_CONTENTS[variableId];
  const yamlKey = SECRET_YAML_KEYS[variableId] ?? getVariableName(variableId);
  if (embedded) {
    const parsed = filterSopsMetadata(await decryptSopsContent(embedded, secretKey));
    const value = parsed[yamlKey];
    if (value !== undefined) {
      secretCache.set(variableId, value);
    }
    return value;
  }

  const fallbackPath = findSecretSopsFile(variableId);
  if (!fallbackPath) {
    throw new Error(
      `Could not resolve linked variable: missing per-variable SOPS file for ${variableId}`,
    );
  }

  const parsed = filterSopsMetadata(await decryptSopsFile(fallbackPath, secretKey));
  const value = parsed[yamlKey];
  if (value !== undefined) {
    secretCache.set(variableId, value);
  }
  return value;
}

function findSecretSopsFile(variableId: string): string | null {
  const explicitSecretsDir = process.env.STACKPANEL_SECRETS_DIR;
  const fileStem = getVariableName(variableId)
    .replace(/[\\/\s]+/g, "-")
    .replace(/\./g, "-");
  const searchRoots = [
    explicitSecretsDir ? join(explicitSecretsDir, "vars") : null,
    join(process.cwd(), ".stack", "secrets", "vars"),
  ].filter((root): root is string => Boolean(root));

  for (const root of searchRoots) {
    const candidate = join(root, `${fileStem}.sops.yaml`);
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  return null;
}

async function decryptSopsFile(
  filePath: string,
  secretKey?: string,
): Promise<Record<string, string>> {
  try {
    const opts: { path: string; secretKey?: string } = { path: filePath };
    if (secretKey) {
      opts.secretKey = secretKey;
    }
    const result = await decryptSops(opts);
    return (result as Record<string, string>) || {};
  } catch (error: any) {
    if (error.message?.includes("could not decrypt") || error.message?.includes("No secret key")) {
      throw new Error(
        `Failed to decrypt ${filePath}. Ensure AGE key is available via SOPS_AGE_KEY_FILE, SOPS_AGE_KEY, or SOPS_AGE_KEY_CMD environment variable.`,
      );
    }
    throw new Error(`Failed to decrypt ${filePath}: ${error.message}`);
  }
}

async function decryptSopsContent(
  content: string,
  secretKey?: string,
): Promise<Record<string, string>> {
  try {
    const opts: { secretKey?: string; fileType: "yaml" } = { fileType: "yaml" };
    if (secretKey) {
      opts.secretKey = secretKey;
    }
    const result = await decryptSops(content, opts as any);
    return (result as Record<string, string>) || {};
  } catch (error: any) {
    if (error.message?.includes("could not decrypt") || error.message?.includes("No secret key")) {
      throw new Error(
        "Failed to decrypt embedded SOPS content. Ensure AGE key is available via SOPS_AGE_KEY_FILE, SOPS_AGE_KEY, or SOPS_AGE_KEY_CMD environment variable.",
      );
    }
    throw new Error(`Failed to decrypt embedded SOPS content: ${error.message}`);
  }
}

function filterSopsMetadata(obj: Record<string, any>): Record<string, string> {
  const sopsKeys = [
    "sops",
    "sops_age",
    "sops_azure_kv",
    "sops_gcp_kms",
    "sops_hc_vault",
    "sops_kms",
    "sops_pgp",
  ];
  const filtered: Record<string, string> = {};

  for (const [key, value] of Object.entries(obj)) {
    if (sopsKeys.includes(key)) continue;

    if (typeof value === "string") {
      filtered[key] = value;
    } else if (typeof value === "number" || typeof value === "boolean") {
      filtered[key] = String(value);
    }
  }

  return filtered;
}
