// Auto-generated by Stackpanel — do not edit manually.
// Runtime environment loader — decrypts generated per-app env payloads without node-specific APIs.

import { decryptSops } from "sops-age";
import { AVAILABLE_APP_ENVS } from "../embedded-data";
import { loadGeneratedPayload } from "./generated-payloads/registry";

const AGE_SECRET_KEY_PREFIX = "AGE-SECRET-KEY-";
const payloadCache = new Map<string, Record<string, string>>();

export interface LoadEnvOptions {
  inject?: boolean;
  skipDecrypt?: boolean;
  secretKey?: string;
}

type SopsFileType = "json";

export async function loadEnv(
  app: string,
  env: string,
  options: LoadEnvOptions = {},
): Promise<Record<string, string>> {
  const normalizedEnv = normalizeRuntimeEnv(env);
  const cacheKey = `${app}/${normalizedEnv}`;
  const cached = payloadCache.get(cacheKey);
  if (cached) {
    injectIntoProcessEnv(cached, options.inject);
    return cached;
  }

  const encryptedPayload = await loadGeneratedPayload(app, normalizedEnv);
  if (!encryptedPayload) {
    const knownEnvs = AVAILABLE_APP_ENVS[app] || [];
    const hint = knownEnvs.length > 0 ? ` Available environments: ${knownEnvs.join(", ")}.` : "";
    throw new Error(`Environment data not found for ${app}/${normalizedEnv}.${hint}`);
  }

  const payload = normalizeEnvPayload(
    await decryptStructuredContent(encryptedPayload, "json", options.secretKey),
  );
  payloadCache.set(cacheKey, payload);
  injectIntoProcessEnv(payload, options.inject);
  return payload;
}

export async function loadSharedVars(
  options: Omit<LoadEnvOptions, "skipDecrypt"> = {},
): Promise<Record<string, string>> {
  const envObject = getProcessEnv();
  const appName = envObject.APP_NAME || "web";
  const envName = normalizeRuntimeEnv(envObject.APP_ENV || envObject.NODE_ENV || "prod");
  return loadEnv(appName, envName, options);
}

export async function loadAppEnv(
  app: string,
  env: string,
  options: LoadEnvOptions = {},
): Promise<Record<string, string>> {
  return loadEnv(app, env, options);
}

async function decryptStructuredContent(
  content: string,
  fileType: SopsFileType,
  secretKey?: string,
): Promise<Record<string, unknown>> {
  const secretKeys = resolveRuntimeSecretKeys(secretKey);
  if (secretKeys.length === 0) {
    throw new Error(missingKeyMaterialMessage());
  }

  const errors: string[] = [];
  for (const key of secretKeys) {
    try {
      const result = await decryptSops(content, { fileType, secretKey: key });
      return (result as Record<string, unknown>) || {};
    } catch (error: any) {
      errors.push(error?.message || String(error));
    }
  }

  throw new Error(`Failed to decrypt generated payload: ${errors.join("; ")}`);
}

function resolveRuntimeSecretKeys(explicitSecretKey?: string): string[] {
  if (explicitSecretKey) {
    return parseAgeSecretKeys(explicitSecretKey);
  }

  const envObject = getProcessEnv();
  return parseAgeSecretKeys(envObject.SOPS_AGE_KEY);
}

function parseAgeSecretKeys(input?: string): string[] {
  if (!input) {
    return [];
  }

  const keys = input
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith(AGE_SECRET_KEY_PREFIX));

  return [...new Set(keys)];
}

function injectIntoProcessEnv(payload: Record<string, string>, inject = true) {
  if (inject === false) {
    return;
  }

  const processEnv = maybeProcessEnv();
  if (processEnv) {
    Object.assign(processEnv, payload);
  }
}

function maybeProcessEnv(): Record<string, string | undefined> | null {
  if (typeof process === "undefined") {
    return null;
  }
  return process.env as Record<string, string | undefined>;
}

function getProcessEnv(): Record<string, string | undefined> {
  return maybeProcessEnv() ?? {};
}

export function normalizeRuntimeEnv(env: string): string {
  if (env === "production") return "prod";
  if (env === "development") return "dev";
  return env;
}

export function normalizeEnvPayload(payload: Record<string, unknown>): Record<string, string> {
  const result: Record<string, string> = {};

  for (const [key, value] of Object.entries(payload)) {
    if (typeof value === "string") {
      result[key] = value;
    } else if (typeof value === "number" || typeof value === "boolean") {
      result[key] = String(value);
    } else if (value == null) {
      result[key] = "";
    } else {
      result[key] = JSON.stringify(value);
    }
  }

  return result;
}

function missingKeyMaterialMessage(): string {
  return "No SOPS decryption key is configured. Set SOPS_AGE_KEY or pass a secretKey option.";
}
