// Auto-generated by Stackpanel — do not edit manually.
// Node/Bun runtime environment loader — decrypts generated per-app env payloads.
// Built on Effect's platform services (FileSystem + ChildProcessSpawner) so the
// underlying I/O is abstract and the same code path works under Node and Bun.

import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Layer from "effect/Layer";
import * as Stream from "effect/Stream";
import { ChildProcess } from "effect/unstable/process";
import type { ChildProcessSpawner } from "effect/unstable/process/ChildProcessSpawner";
import { decryptSops } from "sops-age";
import { AVAILABLE_APP_ENVS } from "../embedded-data";
import type { AppEnvMap, AppName, EnvFor } from "./app-env-types";
import {
  AGE_SECRET_KEY_PREFIX,
  EnvLoadError,
  type LoadEnvOptions,
  normalizeEnvPayload,
  normalizeRuntimeEnv,
  parseAgeSecretKeys,
} from "./loader";
import { loadGeneratedPayload } from "./generated-payloads/registry";

const payloadCache = new Map<string, Record<string, string>>();

type SopsFileType = "json";

// ---------------------------------------------------------------------------
// Re-exports so callers can `import { ... } from "@gen/env/runtime"` and pick
// up the shared types/helpers from the no-Node loader.
// ---------------------------------------------------------------------------

export {
  AGE_SECRET_KEY_PREFIX,
  EnvLoadError,
  type LoadEnvOptions,
  normalizeEnvPayload,
  normalizeRuntimeEnv,
  parseAgeSecretKeys,
};
export type { AppEnvMap, AppName, EnvFor };

// ---------------------------------------------------------------------------
// Effect-native API. Requires FileSystem + ChildProcessSpawner so the runtime
// can read `.stack/keys/local.txt`, run `SOPS_AGE_KEY_CMD`, and shell out to
// the `sops` binary when `SOPS_KEYSERVICE` is configured.
// ---------------------------------------------------------------------------

export type EnvLoadServices = FileSystem.FileSystem | ChildProcessSpawner;

export const loadEnvEffect = <App extends string>(
  app: App,
  env: string,
  options: LoadEnvOptions = {},
): Effect.Effect<EnvFor<App>, EnvLoadError, EnvLoadServices> =>
  (Effect.gen(function* () {
    const normalizedEnv = normalizeRuntimeEnv(env);
    const cacheKey = `${app}/${normalizedEnv}`;
    const cached = payloadCache.get(cacheKey);
    if (cached) {
      injectIntoProcessEnv(cached, options.inject);
      return cached;
    }

    const encryptedPayload = yield* Effect.tryPromise({
      try: () => loadGeneratedPayload(app, normalizedEnv),
      catch: (cause) =>
        new EnvLoadError({
          message: `Failed to load generated payload for ${app}/${normalizedEnv}.`,
          cause,
        }),
    });

    if (!encryptedPayload) {
      const knownEnvs = AVAILABLE_APP_ENVS[app] || [];
      const hint =
        knownEnvs.length > 0 ? ` Available environments: ${knownEnvs.join(", ")}.` : "";
      return yield* Effect.fail(
        new EnvLoadError({
          message: `Environment data not found for ${app}/${normalizedEnv}.${hint}`,
        }),
      );
    }

    const decrypted = yield* decryptStructuredContentEffect(
      encryptedPayload,
      "json",
      options.secretKey,
    );
    const payload = normalizeEnvPayload(decrypted);
    payloadCache.set(cacheKey, payload);
    injectIntoProcessEnv(payload, options.inject);
    return payload;
  }) as Effect.Effect<EnvFor<App>, EnvLoadError, EnvLoadServices>);

export const loadAppEnvEffect = loadEnvEffect;

// ---------------------------------------------------------------------------
// Promise-returning facade. Backward-compatible with the previous API; runs
// the Effect with the auto-detected Bun/Node platform layer.
// ---------------------------------------------------------------------------

export const loadEnv = <App extends string>(
  app: App,
  env: string,
  options: LoadEnvOptions = {},
): Promise<EnvFor<App>> => runWithPlatform(loadEnvEffect(app, env, options));

export const loadAppEnv = loadEnv;

// ---------------------------------------------------------------------------
// Internal Effect helpers
// ---------------------------------------------------------------------------

const decryptStructuredContentEffect = (
  content: string,
  fileType: SopsFileType,
  explicitSecretKey?: string,
): Effect.Effect<Record<string, unknown>, EnvLoadError, EnvLoadServices> =>
  Effect.gen(function* () {
    const secretKeys = yield* resolveRuntimeSecretKeysEffect(explicitSecretKey);
    if (secretKeys.length > 0) {
      return yield* decryptWithJsKeysEffect(content, fileType, secretKeys);
    }
    if (process.env.SOPS_KEYSERVICE) {
      return yield* decryptWithSopsBinaryEffect(content, fileType);
    }
    return yield* Effect.fail(
      new EnvLoadError({ message: missingKeyMaterialMessage() }),
    );
  });

const decryptWithJsKeysEffect = (
  content: string,
  fileType: SopsFileType,
  secretKeys: ReadonlyArray<string>,
): Effect.Effect<Record<string, unknown>, EnvLoadError> =>
  Effect.gen(function* () {
    const errors: string[] = [];
    for (const key of secretKeys) {
      const result = yield* Effect.tryPromise({
        try: () => decryptSops(content, { fileType, secretKey: key }),
        catch: (error) => error,
      }).pipe(Effect.result);

      if (result._tag === "Success") {
        return (result.success as Record<string, unknown>) || {};
      }
      errors.push(formatError(result.failure));
    }
    return yield* Effect.fail(
      new EnvLoadError({
        message: `Failed to decrypt generated payload: ${errors.join("; ")}`,
      }),
    );
  });

// Shells out to the `sops` binary; required when SOPS_KEYSERVICE is configured.
// Uses a scoped temp file so cleanup is automatic via the Effect Scope.
const decryptWithSopsBinaryEffect = (
  content: string,
  fileType: SopsFileType,
): Effect.Effect<Record<string, unknown>, EnvLoadError, EnvLoadServices> =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const tempPath = yield* fs
      .makeTempFileScoped({ prefix: "stackpanel-env-", suffix: ".sops.json" })
      .pipe(
        Effect.mapError((cause) =>
          new EnvLoadError({
            message: "Failed to allocate temp file for sops decryption.",
            cause,
          }),
        ),
      );

    yield* fs.writeFileString(tempPath, content).pipe(
      Effect.mapError((cause) =>
        new EnvLoadError({
          message: "Failed to write payload to temp file.",
          cause,
        }),
      ),
    );

    const { exitCode, stdout, stderr } = yield* runCapture("sops", [
      "--decrypt",
      "--input-type",
      fileType,
      "--output-type",
      "json",
      tempPath,
    ]).pipe(
      Effect.mapError((cause) => {
        if (cause instanceof Error && (cause as NodeJS.ErrnoException).code === "ENOENT") {
          return new EnvLoadError({
            message:
              "SOPS keyservice is configured via SOPS_KEYSERVICE, but the `sops` binary is not installed.",
            cause,
          });
        }
        return new EnvLoadError({
          message: "Failed to decrypt generated payload with the sops binary.",
          cause,
        });
      }),
    );

    if (exitCode !== 0) {
      return yield* Effect.fail(
        new EnvLoadError({
          message: `Failed to decrypt generated payload with the sops binary: ${
            stderr.trim() || `exit ${exitCode}`
          }`,
        }),
      );
    }

    return yield* Effect.try({
      try: () => (JSON.parse(stdout) as Record<string, unknown>) || {},
      catch: (cause) =>
        new EnvLoadError({
          message: "Failed to parse sops decrypt output as JSON.",
          cause,
        }),
    });
  }).pipe(Effect.scoped);

const resolveRuntimeSecretKeysEffect = (
  explicitSecretKey?: string,
): Effect.Effect<string[], EnvLoadError, EnvLoadServices> =>
  Effect.gen(function* () {
    if (explicitSecretKey) return parseAgeSecretKeys(explicitSecretKey);

    const envKeys = parseAgeSecretKeys(process.env.SOPS_AGE_KEY);
    if (envKeys.length > 0) return envKeys;

    const repoLocalKey = yield* readRepoLocalAgeKeyEffect();
    if (repoLocalKey) {
      const repoKeys = parseAgeSecretKeys(repoLocalKey);
      if (repoKeys.length > 0) return repoKeys;
    }

    const command = process.env.SOPS_AGE_KEY_CMD;
    if (!command) return [];

    const { exitCode, stdout, stderr } = yield* runCapture("sh", [
      "-c",
      command,
    ]).pipe(
      Effect.mapError((cause) =>
        new EnvLoadError({
          message: `SOPS_AGE_KEY_CMD failed: ${formatError(cause)}`,
          cause,
        }),
      ),
    );
    if (exitCode !== 0) {
      return yield* Effect.fail(
        new EnvLoadError({
          message: `SOPS_AGE_KEY_CMD exited ${exitCode}: ${stderr.trim()}`,
        }),
      );
    }
    return parseAgeSecretKeys(stdout);
  });

const readRepoLocalAgeKeyEffect = (): Effect.Effect<
  string | null,
  never,
  FileSystem.FileSystem
> =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const explicitKeysDir = process.env.STACKPANEL_KEYS_DIR;
    const candidate = explicitKeysDir
      ? `${explicitKeysDir}/local.txt`
      : `${process.cwd()}/.stack/keys/local.txt`;
    return yield* fs.readFileString(candidate).pipe(
      Effect.catchCause(() => Effect.succeed(null as string | null)),
    );
  });

interface CommandResult {
  readonly exitCode: number;
  readonly stdout: string;
  readonly stderr: string;
}

// Spawns `command` with `args`, captures stdout/stderr, and waits for exit.
// Errors map to PlatformError (e.g., ENOENT when the binary is missing).
const runCapture = (
  command: string,
  args: ReadonlyArray<string>,
): Effect.Effect<CommandResult, unknown, ChildProcessSpawner> =>
  Effect.gen(function* () {
    const handle = yield* ChildProcess.make(command, args);
    const [exitCode, stdout, stderr] = yield* Effect.all(
      [
        handle.exitCode,
        Stream.mkString(Stream.decodeText(handle.stdout)),
        Stream.mkString(Stream.decodeText(handle.stderr)),
      ],
      { concurrency: 3 },
    );
    return { exitCode, stdout, stderr };
  }).pipe(Effect.scoped);

// ---------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------

function injectIntoProcessEnv(payload: Record<string, string>, inject = true) {
  if (inject === false) return;
  Object.assign(process.env, payload);
}

function missingKeyMaterialMessage(): string {
  return "No SOPS decryption method is configured. Set SOPS_AGE_KEY or SOPS_AGE_KEY_CMD, or set SOPS_KEYSERVICE and install the `sops` binary.";
}

function formatError(error: unknown): string {
  if (error instanceof Error) return error.message;
  return String(error);
}

// ---------------------------------------------------------------------------
// Platform layer auto-detection (Bun vs Node).
// We dynamically import the runtime-specific package so the unused one is
// never loaded — important because @effect/platform-bun imports `bun:*`
// modules that don't exist on Node, and vice versa.
// ---------------------------------------------------------------------------

type PlatformLayer = Layer.Layer<EnvLoadServices>;

let cachedPlatformLayer: Promise<PlatformLayer> | null = null;

function getPlatformLayer(): Promise<PlatformLayer> {
  if (cachedPlatformLayer) return cachedPlatformLayer;
  cachedPlatformLayer = (async () => {
    if (typeof (globalThis as { Bun?: unknown }).Bun !== "undefined") {
      const mod = await import("@effect/platform-bun/BunServices");
      return mod.layer as PlatformLayer;
    }
    const mod = await import("@effect/platform-node/NodeServices");
    return mod.layer as PlatformLayer;
  })();
  return cachedPlatformLayer;
}

const runWithPlatform = async <A>(
  effect: Effect.Effect<A, EnvLoadError, EnvLoadServices>,
): Promise<A> => {
  const layer = await getPlatformLayer();
  return Effect.runPromise(effect.pipe(Effect.provide(layer)));
};
