import { createFileRoute } from "@tanstack/react-router";
import { Badge } from "@ui/badge";
import { Card, CardContent } from "@ui/card";
import { Clock, FileCode2 } from "lucide-react";
import { DEMO_GENERATED_FILES } from "@/components/demo/demo-fixtures";

export const Route = createFileRoute("/demo/files")({
	component: DemoFilesPage,
});

function formatBytes(bytes: number): string {
	if (bytes < 1024) return `${bytes} B`;
	const kb = bytes / 1024;
	if (kb < 1024) return `${kb.toFixed(1)} KB`;
	return `${(kb / 1024).toFixed(2)} MB`;
}

function DemoFilesPage() {
	return (
		<div className="mx-auto max-w-7xl space-y-6 p-6">
			<div className="space-y-1">
				<p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">
					Generated files
				</p>
				<h1 className="font-bold font-[Montserrat] text-3xl text-foreground tracking-tight">
					What Stackpanel writes for you
				</h1>
				<p className="text-muted-foreground text-sm">
					You change <span className="font-mono">.stack/config.nix</span> — the
					Stackpanel agent regenerates IDE settings, the Caddyfile, your{" "}
					<span className="font-mono">@gen/env</span> packages, deploy
					manifests, and more. Always atomic, always in sync with your team.
				</p>
			</div>

			<Card className="overflow-hidden">
				<CardContent className="p-0">
					<table className="w-full text-sm">
						<thead className="border-b border-border/60 bg-muted/30 text-left text-[11px] uppercase tracking-[0.12em] text-muted-foreground">
							<tr>
								<th className="px-4 py-2 font-medium">Path</th>
								<th className="hidden px-4 py-2 font-medium md:table-cell">
									Generated by
								</th>
								<th className="px-4 py-2 font-medium">Size</th>
								<th className="hidden px-4 py-2 font-medium md:table-cell">
									Updated
								</th>
							</tr>
						</thead>
						<tbody className="divide-y divide-border/40">
							{DEMO_GENERATED_FILES.map((file) => (
								<tr key={file.path} className="hover:bg-muted/20">
									<td className="px-4 py-3">
										<div className="flex items-center gap-2">
											<FileCode2 className="h-3.5 w-3.5 text-accent" />
											<span className="font-mono text-xs text-foreground">
												{file.path}
											</span>
										</div>
									</td>
									<td className="hidden px-4 py-3 md:table-cell">
										<Badge
											variant="outline"
											className="border-border/60 px-1.5 py-0 text-[10px] font-normal text-muted-foreground"
										>
											{file.tool}
										</Badge>
									</td>
									<td className="px-4 py-3 font-mono text-[11px] text-muted-foreground">
										{formatBytes(file.bytes)}
									</td>
									<td className="hidden px-4 py-3 md:table-cell">
										<span className="flex items-center gap-1.5 text-xs text-muted-foreground">
											<Clock className="h-3 w-3" />
											{file.updated}
										</span>
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</CardContent>
			</Card>

			<Card>
				<CardContent className="space-y-2 p-4 text-sm">
					<p className="font-medium text-foreground">
						Why generated files (and not symlinks)?
					</p>
					<p className="text-xs text-muted-foreground">
						Stackpanel writes real files into your repo so they show up in PRs,
						work in CI, and stay readable when your editor isn&apos;t inside
						the devshell. The local Go agent debounces writes and rolls back
						on errors, so you never end up with a half-written manifest.
					</p>
				</CardContent>
			</Card>
		</div>
	);
}
