// Package nixgen provides utilities for generating Nix files
package nixgen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/darkmatter/stackpanel/stackpanel-go/internal/github"
)

// Template data structures
type collaboratorsData struct {
	Owner       string
	Repo        string
	GeneratedAt string
	Users       []userTemplateData
}

type userTemplateData struct {
	Identifier string
	Login      string
	ID         int
	Role       string
	IsAdmin    bool
	PublicKeys []string
}

// Template for github-collaborators.nix
var collaboratorsTemplate = template.Must(template.New("collaborators").Parse(`# ==============================================================================
# github-collaborators.nix
#
# AUTO-GENERATED by ` + "`stackpanel users sync`" + `
# Source: https://github.com/{{.Owner}}/{{.Repo}}
# Generated: {{.GeneratedAt}}
#
# DO NOT EDIT MANUALLY - changes will be overwritten on next sync.
# ==============================================================================
{
  _meta = {
    source = "github:{{.Owner}}/{{.Repo}}";
    generatedAt = "{{.GeneratedAt}}";
  };

  collaborators = {
{{- range .Users}}
    {{.Identifier}} = {
      login = "{{.Login}}";
      id = {{.ID}};
      role = "{{.Role}}";
      isAdmin = {{.IsAdmin}};
      publicKeys = [
{{- range .PublicKeys}}
        "{{.}}"
{{- end}}
      ];
    };
{{- end}}
  };
}
`))

// Template for users.nix
var usersTemplate = template.Must(template.New("users").Parse(`# ==============================================================================
# users.nix
#
# User configuration for stackpanel.users option.
# Imports from github-collaborators.nix and transforms to required format.
#
# Edit this file to:
#   - Add non-GitHub users (e.g., CI bots)
#   - Customize secrets-allowed-environments per user
#   - Override display names
#
# The github-collaborators.nix is auto-generated and should not be edited.
# ==============================================================================
let
  ghCollabs = import ./github-collaborators.nix;

  # Transform a GitHub collaborator to stackpanel user format
  toUser = name: collab: {
    inherit name;
    github = collab.login;
    public-keys = collab.publicKeys;
    # Default environments based on admin status
    secrets-allowed-environments =
      if collab.isAdmin
      then [ "dev" "staging" "production" ]
      else [ "dev" ];
  };

  # Convert all collaborators
  githubUsers = builtins.mapAttrs toUser ghCollabs.collaborators;

  # Additional non-GitHub users (e.g., CI bots)
  additionalUsers = {
    # Example CI user:
    # ci = {
    #   name = "CI Bot";
    #   public-keys = [ "age1..." ];
    #   secrets-allowed-environments = [ "dev" "staging" "production" ];
    # };
  };

  # Override specific user settings here
  userOverrides = {
    # Example: give a specific user more access
    # someuser = {
    #   secrets-allowed-environments = [ "dev" "staging" ];
    # };
  };

  # Merge function that applies overrides
  applyOverrides = users:
    builtins.mapAttrs (name: user:
      user // (userOverrides.${name} or {})
    ) users;

in
  applyOverrides (githubUsers // additionalUsers)
`))

// GenerateGitHubCollaboratorsNix generates the github-collaborators.nix file
func GenerateGitHubCollaboratorsNix(users []github.User, owner, repo string) string {
	now := time.Now().Format(time.RFC3339)

	// Prepare template data
	data := collaboratorsData{
		Owner:       owner,
		Repo:        repo,
		GeneratedAt: now,
		Users:       make([]userTemplateData, 0, len(users)),
	}

	for _, user := range users {
		escapedKeys := make([]string, len(user.PublicKeys))
		for i, key := range user.PublicKeys {
			escapedKeys[i] = escapeNixString(key)
		}

		data.Users = append(data.Users, userTemplateData{
			Identifier: sanitizeNixIdentifier(user.Login),
			Login:      escapeNixString(user.Login),
			ID:         user.ID,
			Role:       escapeNixString(user.RoleName),
			IsAdmin:    user.IsAdmin,
			PublicKeys: escapedKeys,
		})
	}

	var buf bytes.Buffer
	if err := collaboratorsTemplate.Execute(&buf, data); err != nil {
		// Fallback to empty on error (shouldn't happen with valid template)
		return fmt.Sprintf("# Error generating template: %v\n{}", err)
	}

	return buf.String()
}

// GenerateUsersNix generates the users.nix file that imports from github-collaborators.nix
// and transforms it to the format expected by stackpanel.options.users
func GenerateUsersNix() string {
	var buf bytes.Buffer
	if err := usersTemplate.Execute(&buf, nil); err != nil {
		return fmt.Sprintf("# Error generating template: %v\n{}", err)
	}
	return buf.String()
}

// WriteNixFile writes content to a file, creating directories as needed
func WriteNixFile(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

// sanitizeNixIdentifier converts a string to a valid Nix identifier
func sanitizeNixIdentifier(s string) string {
	// Replace invalid characters with underscores
	result := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			return r
		}
		return '_'
	}, s)

	// Ensure it doesn't start with a digit
	if len(result) > 0 && result[0] >= '0' && result[0] <= '9' {
		result = "_" + result
	}

	return result
}

// escapeNixString escapes a string for use in Nix
func escapeNixString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "${", "\\${")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}
