#!/usr/bin/env bash
# ==============================================================================
# tests/lib/stackpanel_config.sh
# Helpers for injecting and restoring .stack/config.local.nix during tests.
#
# Requires: tests/lib/common.sh must be sourced first (provides log, ok, warn,
#           info, die).
#
# Module-level state (set by inject_machine_config, read by restore_machine_config):
#   STACKPANEL_CONFIG_BACKED_UP  — "true" if an existing file was backed up
#   STACKPANEL_CONFIG_CREATED    — "true" if we created a brand-new file
#
# Functions:
#   inject_machine_config  <machine_name> <host_ip> <pubkey>
#                          <config_local_path> <bak_path>
#   restore_machine_config <config_local_path> <bak_path>
# ==============================================================================

# Initialise state flags (overwritten by inject_machine_config)
STACKPANEL_CONFIG_BACKED_UP=false
STACKPANEL_CONFIG_CREATED=false

# inject_machine_config <machine_name> <host_ip> <pubkey>
#                       <config_local_path> <bak_path>
#
# Writes an ephemeral machine entry into .stack/config.local.nix.
#   • If config.local.nix already exists, backs it up to <bak_path>, then
#     writes a combined module that imports the backup via lib.mkMerge.
#   • If config.local.nix does not exist, creates a fresh file.
# Sets STACKPANEL_CONFIG_BACKED_UP or STACKPANEL_CONFIG_CREATED accordingly.
inject_machine_config() {
  local machine_name="$1"
  local host_ip="$2"
  local pubkey="$3"
  local config_local_path="$4"
  local bak_path="$5"

  log "Injecting ephemeral machine config into $(basename "${config_local_path}")..."

  if [[ -f "${config_local_path}" ]]; then
    # Preserve the existing file so its settings (e.g. aws.roles-anywhere.*)
    # are not lost during the test.
    cp "${config_local_path}" "${bak_path}"
    STACKPANEL_CONFIG_BACKED_UP=true
    info "Backed up existing $(basename "${config_local_path}") to $(basename "${bak_path}")"

    # Write a combined module: import the backup + add the test machine.
    # lib.mkMerge merges attribute definitions from both modules.
    cat > "${config_local_path}" << NIXEOF
# Generated by stackpanel scenario test — DO NOT EDIT MANUALLY
# Original config.local.nix is backed up as $(basename "${bak_path}")
# and will be restored automatically when the test script exits.
{ config, lib, ... } @ args:
lib.mkMerge [
  (import ./$(basename "${bak_path}") args)
  {
    # Ephemeral machine injected for provision regression testing.
    # The actual target IP is supplied via --install-target at provision time.
    deployment.machines.${machine_name} = {
      host = "${host_ip}";
      user = "root";
      system = "x86_64-linux";
      authorizedKeys = [
        "${pubkey}"
      ];
    };
  }
]
NIXEOF
  else
    # No existing config.local.nix — create a fresh one.
    STACKPANEL_CONFIG_CREATED=true
    cat > "${config_local_path}" << NIXEOF
# Generated by stackpanel scenario test — DO NOT EDIT MANUALLY
# This file will be removed automatically when the test script exits.
{ ... }:
{
  # Ephemeral machine injected for provision regression testing.
  # The actual target IP is supplied via --install-target at provision time.
  deployment.machines.${machine_name} = {
    host = "${host_ip}";
    user = "root";
    system = "x86_64-linux";
    authorizedKeys = [
      "${pubkey}"
    ];
  };
}
NIXEOF
  fi

  ok "$(basename "${config_local_path}") updated with ephemeral machine '${machine_name}'"
}

# restore_machine_config <config_local_path> <bak_path>
#
# Reverses inject_machine_config:
#   • If STACKPANEL_CONFIG_BACKED_UP=true: restores from backup and removes it.
#   • If STACKPANEL_CONFIG_CREATED=true:  removes the ephemeral file (and any bak).
#   • Otherwise: nothing to do.
restore_machine_config() {
  local config_local_path="$1"
  local bak_path="$2"

  if [[ "${STACKPANEL_CONFIG_BACKED_UP:-false}" == "true" ]]; then
    if cp "${bak_path}" "${config_local_path}" 2>/dev/null; then
      rm -f "${bak_path}"
      ok "Restored $(basename "${config_local_path}") from backup"
    else
      warn "Could not restore $(basename "${config_local_path}") — backup is at ${bak_path}"
    fi
  elif [[ "${STACKPANEL_CONFIG_CREATED:-false}" == "true" ]]; then
    rm -f "${config_local_path}"
    rm -f "${bak_path}"
    ok "Removed ephemeral $(basename "${config_local_path}")"
  fi
}
