// protoc-gen-connect-handlers generates Connect handler implementations
// for Nix data entity CRUD operations based on the AgentService definition.
//
// This plugin reads the proto service definition and generates handler code
// that calls the generic Nix data read/write logic, ensuring zero drift between
// proto definitions and handler implementations.
//
// Usage:
//   buf generate --plugin=protoc-gen-connect-handlers
//
// Or add to buf.gen.yaml:
//   plugins:
//     - local: ./tools/protoc-gen-connect-handlers/protoc-gen-connect-handlers
//       out: gen/gopb
package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, file := range gen.Files {
			if !file.Generate {
				continue
			}
			generateFile(gen, file)
		}
		return nil
	})
}

// entityMethod represents a Get/Set method pair for an entity
type entityMethod struct {
	EntityName   string // e.g., "apps", "variables"
	TypeName     string // e.g., "Apps", "Variables"
	GoType       string // e.g., "gopb.Apps"
	HasGet       bool
	HasSet       bool
	GetMethod    *protogen.Method
	SetMethod    *protogen.Method
	IsReadOnly   bool
	SkipGenerate bool
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	// Only process agent.proto
	if file.Proto.GetName() != "agent.proto" {
		return
	}

	// Find AgentService
	var agentService *protogen.Service
	for _, svc := range file.Services {
		if svc.GoName == "AgentService" {
			agentService = svc
			break
		}
	}
	if agentService == nil {
		return
	}

	// Collect entity methods
	entities := make(map[string]*entityMethod)

	for _, method := range agentService.Methods {
		name := string(method.Desc.Name())

		// Check for Get* methods that return stackpanel.db.* types
		if strings.HasPrefix(name, "Get") {
			outputType := string(method.Output.Desc.FullName())
			if strings.HasPrefix(outputType, "stackpanel.db.") {
				typeName := strings.TrimPrefix(outputType, "stackpanel.db.")
				entityName := strings.ToLower(typeName)

				em, ok := entities[entityName]
				if !ok {
					em = &entityMethod{
						EntityName: entityName,
						TypeName:   typeName,
						GoType:     "gopb." + typeName,
					}
					entities[entityName] = em
				}
				em.HasGet = true
				em.GetMethod = method
			}
		}

		// Check for Set* methods that take stackpanel.db.* types
		if strings.HasPrefix(name, "Set") {
			inputType := string(method.Input.Desc.FullName())
			if strings.HasPrefix(inputType, "stackpanel.db.") {
				typeName := strings.TrimPrefix(inputType, "stackpanel.db.")
				entityName := strings.ToLower(typeName)

				em, ok := entities[entityName]
				if !ok {
					em = &entityMethod{
						EntityName: entityName,
						TypeName:   typeName,
						GoType:     "gopb." + typeName,
					}
					entities[entityName] = em
				}
				em.HasSet = true
				em.SetMethod = method
			}
		}
	}

	// Skip if no entities found
	if len(entities) == 0 {
		return
	}

	// Generate the file
	g := gen.NewGeneratedFile("connect_entities_gen.go", file.GoImportPath)

	g.P("// Code generated by protoc-gen-connect-handlers. DO NOT EDIT.")
	g.P("// Source: ", file.Proto.GetName())
	g.P()
	g.P("package server")
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"encoding/json"`)
	g.P()
	g.P(`	"connectrpc.com/connect"`)
	g.P(`	gopb "github.com/darkmatter/stackpanel/packages/proto/gen/gopb"`)
	g.P(`	"google.golang.org/protobuf/encoding/protojson"`)
	g.P(")")
	g.P()

	// Generate handlers for each entity
	for _, em := range entities {
		if em.SkipGenerate {
			continue
		}

		// Generate Get handler
		if em.HasGet {
			g.P("// Get", em.TypeName, " retrieves the ", em.EntityName, " entity from Nix data.")
			g.P("// Generated from proto - do not edit manually.")
			g.P("func (s *AgentServiceServer) Get", em.TypeName, "(")
			g.P("	ctx context.Context,")
			g.P("	req *connect.Request[gopb.Get", em.TypeName, "Request],")
			g.P(") (*connect.Response[", em.GoType, "], error) {")
			g.P(`	data, err := s.server.readNixEntityJSON("`, em.EntityName, `")`)
			g.P("	if err != nil {")
			g.P("		return nil, connect.NewError(connect.CodeInternal, err)")
			g.P("	}")
			g.P()
			g.P("	var result ", em.GoType)
			g.P("	if len(data) > 0 {")
			g.P("		if err := protojson.Unmarshal(data, &result); err != nil {")
			g.P("			// Fall back to standard JSON if protojson fails")
			g.P("			if err := json.Unmarshal(data, &result); err != nil {")
			g.P("				return nil, connect.NewError(connect.CodeInternal, err)")
			g.P("			}")
			g.P("		}")
			g.P("	}")
			g.P()
			g.P("	return connect.NewResponse(&result), nil")
			g.P("}")
			g.P()
		}

		// Generate Set handler
		if em.HasSet && !em.IsReadOnly {
			g.P("// Set", em.TypeName, " updates the ", em.EntityName, " entity in Nix data.")
			g.P("// Generated from proto - do not edit manually.")
			g.P("func (s *AgentServiceServer) Set", em.TypeName, "(")
			g.P("	ctx context.Context,")
			g.P("	req *connect.Request[", em.GoType, "],")
			g.P(") (*connect.Response[", em.GoType, "], error) {")
			g.P("	data, err := protojson.Marshal(req.Msg)")
			g.P("	if err != nil {")
			g.P("		return nil, connect.NewError(connect.CodeInternal, err)")
			g.P("	}")
			g.P()
			g.P(`	if err := s.server.writeNixEntityJSON("`, em.EntityName, `", data); err != nil {`)
			g.P("		return nil, connect.NewError(connect.CodeInternal, err)")
			g.P("	}")
			g.P()
			g.P("	return connect.NewResponse(req.Msg), nil")
			g.P("}")
			g.P()
		}
	}

	return
}
