# Secrets schema + code generation for TypeScript, Python, Go
# Per-app code generation based on .stackpanel/secrets/apps/{appName}/config.nix
#
# Each app defines:
#   - config.nix: { codegen = { language = "typescript"; path = "..."; }; }
#   - common.nix: shared schema across all environments
#   - {env}.nix: per-environment schema overrides
#
# Generated code provides:
#   - Type-safe env access in your language of choice
#   - Nullable types for optional secrets
#   - PUBLIC_* prefix for client-safe values (non-sensitive)
#
{
  lib,
  config,
  pkgs,
  ...
}: let
  inherit (lib) concatStringsSep concatMapStringsSep optionalString;
  cfg = config.stackpanel.secrets;

  # ══════════════════════════════════════════════════════════════════════════════
  # Per-App Schema Processing
  # ══════════════════════════════════════════════════════════════════════════════

  # Merge common schema with environment-specific overrides
  # Environment schema takes precedence
  mergeSchemas = commonSchema: envSchema:
    lib.recursiveUpdate commonSchema envSchema;

  # Get the full merged schema for an app (common + all env overrides combined)
  getAppSchema = appName: appData: let
    common = appData.common-schema or {};
    envSchemas = lib.mapAttrsToList (_env: envCfg: envCfg.schema or {}) (appData.environments or {});
    # Merge common with all env schemas (to get all possible keys)
    allEnvKeys = lib.foldl' lib.recursiveUpdate {} envSchemas;
  in
    mergeSchemas common allEnvKeys;

  # Convert schema attrs to list with name included
  schemaToEntries = schema:
    lib.mapAttrsToList (name: opts: (opts // {inherit name;})) schema;

  # Apply defaults to schema entry
  normalizeEntry = entry: {
    name = entry.name;
    required = entry.required or true;
    sensitive = entry.sensitive or true;
    description = entry.description or "";
    default = entry.default or null;
  };

  # ══════════════════════════════════════════════════════════════════════════════
  # TypeScript Code Generation
  # ══════════════════════════════════════════════════════════════════════════════

  tsServerGetter = s: let
    type =
      if s.required
      then "string"
      else "string | undefined";
    desc =
      if s.description != ""
      then s.description
      else s.name;
    tag =
      if s.required
      then "@required"
      else "@optional";
    defaultComment = optionalString (s.default != null) " (default: ${s.default})";
    bodyLines =
      if s.required
      then [
        "    const value = process.env.${s.name};"
        ''    if (!value) throw new Error("Missing required env var: ${s.name}");''
        "    return value;"
      ]
      else ["    return process.env.${s.name};"];
  in
    concatStringsSep "\n" ([
        "  /**"
        "   * ${desc}${defaultComment}"
        "   * ${tag}"
        "   */"
        "  get ${s.name}(): ${type} {"
      ]
      ++ bodyLines ++ ["  }"]);

  tsClientGetter = s: let
    type =
      if s.required
      then "string"
      else "string | undefined";
    desc =
      if s.description != ""
      then s.description
      else s.name;
    tag =
      if s.required
      then "@required"
      else "@optional";
    bodyLines =
      if s.required
      then [
        "    const value = process.env.PUBLIC_${s.name} ?? process.env.NEXT_PUBLIC_${s.name};"
        ''    if (!value) throw new Error("Missing required env var: PUBLIC_${s.name}");''
        "    return value;"
      ]
      else [
        "    return process.env.PUBLIC_${s.name} ?? process.env.NEXT_PUBLIC_${s.name};"
      ];
  in
    concatStringsSep "\n" ([
        "  /**"
        "   * ${desc}"
        "   * ${tag}"
        "   */"
        "  get ${s.name}(): ${type} {"
      ]
      ++ bodyLines ++ ["  }"]);

  tsKeyTypes = secrets:
    if secrets != []
    then concatMapStringsSep " | " (s: ''"${s.name}"'') secrets
    else "never";

  generateTsCode = appName: allSecrets: let
    sensitiveSecrets = lib.filter (s: s.sensitive) allSecrets;
    publicSecrets = lib.filter (s: !s.sensitive) allSecrets;
  in
    concatStringsSep "\n" ([
        "// Generated by stackpanel secrets module"
        "// App: ${appName}"
        "// Regenerate with: devenv shell"
        ""
        "/**"
        " * Server-side environment variables (all secrets)"
        " * Use with: import { serverEnv } from \"./env\";"
        " */"
        "class ServerEnv {"
      ]
      ++ (map tsServerGetter allSecrets)
      ++ [
        "}"
        ""
        "/**"
        " * Client-side environment variables (public only)"
        " * Safe to use in browser code"
        " * Use with: import { clientEnv } from \"./env\";"
        " */"
        "class ClientEnv {"
      ]
      ++ (map tsClientGetter publicSecrets)
      ++ [
        "}"
        ""
        "/** Server environment - all secrets */"
        "export const serverEnv = new ServerEnv();"
        ""
        "/** Client environment - public secrets only */"
        "export const clientEnv = new ClientEnv();"
        ""
        "/** Default export for convenience */"
        "export default serverEnv;"
        ""
        "// Type exports"
        "export type ServerEnvKeys = ${tsKeyTypes allSecrets};"
        "export type ClientEnvKeys = ${tsKeyTypes publicSecrets};"
        ""
      ]);

  # ══════════════════════════════════════════════════════════════════════════════
  # Python Code Generation
  # ══════════════════════════════════════════════════════════════════════════════

  pyServerProp = s: let
    type =
      if s.required
      then "str"
      else "str | None";
    desc =
      if s.description != ""
      then s.description
      else s.name;
    name = lib.toLower s.name;
    bodyLines =
      if s.required
      then [
        ''        value = os.environ.get("${s.name}")''
        "        if not value:"
        ''            raise ValueError("Missing required env var: ${s.name}")''
        "        return value"
      ]
      else [''        return os.environ.get("${s.name}")''];
  in
    concatStringsSep "\n" ([
        ""
        "    @property"
        "    def ${name}(self) -> ${type}:"
        ''        """${desc}"""''
      ]
      ++ bodyLines);

  pyClientProp = s: let
    type =
      if s.required
      then "str"
      else "str | None";
    desc =
      if s.description != ""
      then s.description
      else s.name;
    name = lib.toLower s.name;
    bodyLines =
      if s.required
      then [
        ''        value = os.environ.get("PUBLIC_${s.name}")''
        "        if not value:"
        ''            raise ValueError("Missing required env var: PUBLIC_${s.name}")''
        "        return value"
      ]
      else [''        return os.environ.get("PUBLIC_${s.name}")''];
  in
    concatStringsSep "\n" ([
        ""
        "    @property"
        "    def ${name}(self) -> ${type}:"
        ''        """${desc}"""''
      ]
      ++ bodyLines);

  generatePyCode = appName: allSecrets: let
    sensitiveSecrets = lib.filter (s: s.sensitive) allSecrets;
    publicSecrets = lib.filter (s: !s.sensitive) allSecrets;
  in
    concatStringsSep "\n" ([
        "# Generated by stackpanel secrets module"
        "# App: ${appName}"
        "# Regenerate with: devenv shell"
        ""
        "import os"
        ""
        ""
        "class ServerEnv:"
        ''    """Server-side environment variables (all secrets)"""''
      ]
      ++ (map pyServerProp allSecrets)
      ++ [
        ""
        ""
        "class ClientEnv:"
        ''    """Client-side environment variables (public only)"""''
      ]
      ++ (map pyClientProp publicSecrets)
      ++ [
        ""
        ""
        "# Singleton instances"
        "server_env = ServerEnv()"
        "client_env = ClientEnv()"
        ""
        "# Convenience alias"
        "env = server_env"
        ""
      ]);

  # ══════════════════════════════════════════════════════════════════════════════
  # Go Code Generation
  # ══════════════════════════════════════════════════════════════════════════════

  goField = s: let
    type =
      if s.required
      then "string"
      else "*string";
    comment = optionalString (s.description != "") " // ${s.description}";
  in "	${s.name} ${type}${comment}";

  goLoadField = s:
    if s.required
    then
      concatStringsSep "\n" [
        ''	if v := os.Getenv("${s.name}"); v != "" {''
        "		env.${s.name} = v"
        "	} else {"
        ''		return nil, fmt.Errorf("missing required env var: ${s.name}")''
        "	}"
      ]
    else
      concatStringsSep "\n" [
        ''	if v := os.Getenv("${s.name}"); v != "" {''
        "		env.${s.name} = &v"
        "	}"
      ];

  goLoadClientField = s:
    if s.required
    then
      concatStringsSep "\n" [
        ''	if v := os.Getenv("PUBLIC_${s.name}"); v != "" {''
        "		env.${s.name} = v"
        "	} else {"
        ''		return nil, fmt.Errorf("missing required env var: PUBLIC_${s.name}")''
        "	}"
      ]
    else
      concatStringsSep "\n" [
        ''	if v := os.Getenv("PUBLIC_${s.name}"); v != "" {''
        "		env.${s.name} = &v"
        "	}"
      ];

  generateGoCode = appName: allSecrets: let
    sensitiveSecrets = lib.filter (s: s.sensitive) allSecrets;
    publicSecrets = lib.filter (s: !s.sensitive) allSecrets;
  in
    concatStringsSep "\n" ([
        "// Generated by stackpanel secrets module"
        "// App: ${appName}"
        "// Regenerate with: devenv shell"
        ""
        "package env"
        ""
        "import ("
        ''	"fmt"''
        ''	"os"''
        ")"
        ""
        "// ServerEnv contains all environment variables (sensitive + public)"
        "type ServerEnv struct {"
      ]
      ++ (map goField allSecrets)
      ++ [
        "}"
        ""
        "// ClientEnv contains only public environment variables"
        "type ClientEnv struct {"
      ]
      ++ (map goField publicSecrets)
      ++ [
        "}"
        ""
        "// LoadServerEnv loads all environment variables"
        "func LoadServerEnv() (*ServerEnv, error) {"
        "	env := &ServerEnv{}"
      ]
      ++ (map goLoadField allSecrets)
      ++ [
        "	return env, nil"
        "}"
        ""
        "// LoadClientEnv loads only public environment variables"
        "func LoadClientEnv() (*ClientEnv, error) {"
        "	env := &ClientEnv{}"
      ]
      ++ (map goLoadClientField publicSecrets)
      ++ [
        "	return env, nil"
        "}"
        ""
        "// MustLoadServerEnv loads server env or panics"
        "func MustLoadServerEnv() *ServerEnv {"
        "	env, err := LoadServerEnv()"
        "	if err != nil {"
        "		panic(err)"
        "	}"
        "	return env"
        "}"
        ""
        "// MustLoadClientEnv loads client env or panics"
        "func MustLoadClientEnv() *ClientEnv {"
        "	env, err := LoadClientEnv()"
        "	if err != nil {"
        "		panic(err)"
        "	}"
        "	return env"
        "}"
        ""
      ]);

  # ══════════════════════════════════════════════════════════════════════════════
  # Per-App Code Generator
  # ══════════════════════════════════════════════════════════════════════════════

  # Generate code for a single app
  generateAppCode = appName: appData: let
    appConfig = appData.app-config or {};
    codegen = appConfig.codegen or null;
    language = codegen.language or null;
    path = codegen.path or null;

    # Get merged schema for this app
    schema = getAppSchema appName appData;
    entries = map normalizeEntry (schemaToEntries schema);

    # Generate code based on language
    code =
      if language == "typescript"
      then generateTsCode appName entries
      else if language == "python"
      then generatePyCode appName entries
      else if language == "go"
      then generateGoCode appName entries
      else null;
  in
    if codegen != null && language != null && path != null && code != null
    then {${path}.text = code;}
    else {};

  # Generate code for all apps
  allAppCodeFiles =
    lib.foldl' (acc: appName:
      acc // (generateAppCode appName cfg.apps.${appName})) {} (lib.attrNames cfg.apps);
in {
  # No additional options needed - we read from cfg.apps which is defined in secrets.nix

  config = lib.mkIf cfg.enable {
    # Generate code files for all apps with codegen enabled
    files = allAppCodeFiles;
  };
}
