# ==============================================================================
# entrypoints.nix
#
# Nix module for generating per-app entrypoint shell scripts.
#
# Each app defined in stackpanel.apps can have an entrypoint generated that:
#   - Auto-sources devshell in dev mode
#   - Loads secrets for the appropriate environment
#   - Executes the app's start command
#
# Generated entrypoints are written to packages/scripts/entrypoints/<app>.sh
# via the stackpanel.files system.
#
# Usage:
#   stackpanel.apps.web = {
#     path = "apps/web";
#     entrypoint = {
#       enable = true;
#       command = "bun run start";  # Optional, defaults to commands.start or bun run start
#     };
#   };
#
# Then run:
#   ./packages/scripts/entrypoints/web.sh --dev   # Dev mode
#   ./packages/scripts/entrypoints/web.sh         # Prod mode
# ==============================================================================
{
  lib,
  config,
  pkgs,
  ...
}:
let
  cfg = config.stackpanel;

  # Get master keys config for secrets loading (use empty default to avoid recursion)
  secretsCfg = cfg.secrets or { };
  masterKeysConfig = secretsCfg.master-keys or { };
  masterKeysJson = builtins.toJSON (
    lib.mapAttrs (name: key: {
      age-pub = key.age-pub or "";
      ref = key.ref or "";
      "resolve-cmd" = key.resolve-cmd or null;
    }) masterKeysConfig
  );

  # Generate entrypoint shell script for an app
  # NOTE: This function is called lazily inside mkIf, so it's safe to access app options
  generateEntrypointSh = name: app:
    let
      appPath = app.path or "apps/${name}";
      # Get commands with safe fallbacks
      commands = app.commands or { };
      entrypoint = app.entrypoint or { };
      
      # Get command from entrypoint config, commands.start, or default
      startCommand = 
        if entrypoint.command or null != null then
          entrypoint.command
        else if commands.start.command or null != null then
          commands.start.command
        else if commands.dev.command or null != null then
          # Fall back to dev command for dev mode default
          commands.dev.command
        else
          "bun run start";
      
      devCommand =
        if commands.dev.command or null != null then
          commands.dev.command
        else
          "bun run dev";
    in
    ''
      #!/usr/bin/env bash
      # ==============================================================================
      # Auto-generated entrypoint for ${name}
      # Generated by stackpanel - do not edit manually
      # Regenerate by entering the devshell: nix develop --impure
      # ==============================================================================
      
      set -euo pipefail
      
      # Find script directory and source common library
      SCRIPT_DIR="$(cd "$(dirname "''${BASH_SOURCE[0]}")" && pwd)"
      LIB_DIR="$(dirname "$SCRIPT_DIR")/lib"
      
      if [[ -f "$LIB_DIR/common.sh" ]]; then
        source "$LIB_DIR/common.sh"
      else
        echo "[ERROR] Could not find common.sh at $LIB_DIR/common.sh" >&2
        exit 1
      fi
      
      # ==============================================================================
      # App Configuration (from Nix)
      # ==============================================================================
      
      APP_NAME="${name}"
      APP_PATH="${appPath}"
      START_COMMAND="${startCommand}"
      DEV_COMMAND="${devCommand}"
      MASTER_KEYS_JSON='${masterKeysJson}'
      
      # Export master keys for secrets loading
      export STACKPANEL_MASTER_KEYS="$MASTER_KEYS_JSON"
      
      # ==============================================================================
      # Argument Parsing
      # ==============================================================================
      
      DEV_MODE=false
      ENVIRONMENT=""
      SKIP_SECRETS=false
      APP_ARGS=()
      
      while [[ $# -gt 0 ]]; do
        case "$1" in
          --dev)
            DEV_MODE=true
            shift
            ;;
          --env)
            ENVIRONMENT="$2"
            shift 2
            ;;
          --no-secrets)
            SKIP_SECRETS=true
            shift
            ;;
          --)
            shift
            APP_ARGS=("$@")
            break
            ;;
          *)
            APP_ARGS+=("$1")
            shift
            ;;
        esac
      done
      
      # Set default environment
      if [[ -z "$ENVIRONMENT" ]]; then
        if [[ "$DEV_MODE" == "true" ]]; then
          ENVIRONMENT="dev"
        else
          ENVIRONMENT="prod"
        fi
      fi
      
      log_debug "App: $APP_NAME"
      log_debug "Dev mode: $DEV_MODE"
      log_debug "Environment: $ENVIRONMENT"
      
      # ==============================================================================
      # Environment Setup
      # ==============================================================================
      
      PROJECT_ROOT=$(find_project_root) || die "Could not find project root"
      
      # Dev mode: ensure devshell
      if [[ "$DEV_MODE" == "true" ]]; then
        ensure_devshell || die "Failed to set up devshell"
      fi
      
      # Load secrets (unless skipped)
      if [[ "$SKIP_SECRETS" != "true" ]] && [[ "''${STACKPANEL_NO_SECRETS:-}" != "1" ]]; then
        load_secrets "$APP_NAME" "$ENVIRONMENT" || log_warn "Secrets loading failed, continuing anyway"
      fi
      
      # ==============================================================================
      # Execute App
      # ==============================================================================
      
      # Change to app directory
      APP_DIR="$PROJECT_ROOT/$APP_PATH"
      if [[ -d "$APP_DIR" ]]; then
        cd "$APP_DIR"
        log_debug "Changed to app directory: $APP_DIR"
      else
        log_warn "App directory not found: $APP_DIR"
        cd "$PROJECT_ROOT"
      fi
      
      # Select command based on mode
      if [[ "$DEV_MODE" == "true" ]]; then
        COMMAND="$DEV_COMMAND"
      else
        COMMAND="$START_COMMAND"
      fi
      
      log_info "Running $APP_NAME: $COMMAND"
      
      # Execute the command
      # shellcheck disable=SC2086
      exec $COMMAND "''${APP_ARGS[@]}"
    '';

  # Entrypoint options submodule - defined at top level
  entrypointModule = { lib, ... }: {
    options = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Whether to generate an entrypoint for this app.";
      };

      command = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = ''
          Command to run in production mode.
          Defaults to commands.start.command or "bun run start".
        '';
        example = "node dist/server.js";
      };
    };
  };

in
{
  # ===========================================================================
  # Options - extend app schema with entrypoint config
  # ===========================================================================
  config = lib.mkMerge [
    # Add entrypoint option to all apps via appModules
    {
      stackpanel.appModules = [
        ({ lib, ... }: {
          options.entrypoint = lib.mkOption {
            type = lib.types.submodule entrypointModule;
            default = { };
            description = ''
              Entrypoint configuration for this app.
              
              When enabled (default), generates a shell script at
              packages/scripts/entrypoints/<app>.sh that:
              - Auto-sources devshell in --dev mode
              - Loads secrets for the appropriate environment
              - Executes the app's start/dev command
            '';
          };
        })
      ];
    }

    # Generate entrypoint files when apps are defined
    # NOTE: We compute appsWithEntrypoints lazily here (inside the config block)
    # to avoid infinite recursion with appModules
    (
      let
        # Filter apps that have entrypoints enabled
        # Only check for 'path' attribute which is user-defined (not via appModules)
        # The entrypoint.enable check is done lazily in the filter function
        appsWithPaths = lib.filterAttrs (
          name: app: (app.path or null) != null
        ) cfg.apps;
        
        # Further filter by entrypoint.enable (now safe since we're inside mkMerge)
        appsWithEntrypoints = lib.filterAttrs (
          name: app: (app.entrypoint.enable or true)
        ) appsWithPaths;

        hasApps = appsWithEntrypoints != { };
      in
      lib.mkIf hasApps {
        # Generate entrypoint shell scripts via files system
        stackpanel.files.entries = lib.mkMerge (
          lib.mapAttrsToList (name: app: {
            "packages/scripts/entrypoints/${name}.sh" = {
              type = "text";
              mode = "0755";  # executable
              text = generateEntrypointSh name app;
              source = "entrypoints.nix";
              description = "Entrypoint script for ${name}";
            };
          }) appsWithEntrypoints
        );

        # Also create as Nix derivations for flake outputs
        stackpanel.outputs = lib.mapAttrs' (name: app: {
          name = "${name}-entrypoint";
          value = pkgs.writeShellApplication {
            name = "${name}-entrypoint";
            runtimeInputs = [ ]; # Dependencies are loaded via devshell
            text = generateEntrypointSh name app;
          };
        }) appsWithEntrypoints;
      }
    )
  ];
}
