# ==============================================================================
# module.nix - Bun Module Implementation
#
# Provides Bun/TypeScript application support using bun2nix for packaging.
#
# Prerequisites:
#   - bun.nix lockfile (generated via: bun2nix or bunx bun2nix)
#   - package.json in the app or root directory
#
# App definition example:
#   stackpanel.apps.my-app = {
#     path = "apps/web";
#     bun = {
#       enable = true;
#       buildPhase = "bun run build";
#       startScript = "bun run start";
#     };
#   };
#
# See: https://nix-community.github.io/bun2nix/building-packages/writeBunApplication.html
# ==============================================================================
{
  lib,
  config,
  pkgs,
  ...
}:
let
  meta = import ./meta.nix;
  sp = config.stackpanel;

  # ---------------------------------------------------------------------------
  # Per-app options module
  # ---------------------------------------------------------------------------
  appModule =
    { lib, name, ... }:
    {
      options.bun = {
        enable = lib.mkEnableOption "Bun app support for this app";

        mainPackage = lib.mkOption {
          type = lib.types.str;
          default = ".";
          description = "Main entry point for bun run";
        };

        version = lib.mkOption {
          type = lib.types.str;
          default = "0.1.0";
          description = "App version";
        };

        binaryName = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          description = "Binary name (if different from app name)";
          example = "my-app";
        };

        buildPhase = lib.mkOption {
          type = lib.types.str;
          default = "bun run build";
          description = "Build phase command";
        };

        startScript = lib.mkOption {
          type = lib.types.str;
          default = "bun run start";
          description = "Start script for runtime";
        };

        runtimeInputs = lib.mkOption {
          type = lib.types.listOf lib.types.package;
          default = [ ];
          description = "Runtime nix dependencies";
        };

        runtimeEnv = lib.mkOption {
          type = lib.types.attrsOf lib.types.str;
          default = { };
          description = "Runtime environment variables";
          example = {
            NODE_ENV = "production";
          };
        };

        inheritPath = lib.mkOption {
          type = lib.types.bool;
          default = false;
          description = "Whether to inherit PATH from environment at runtime";
        };

        description = lib.mkOption {
          type = lib.types.str;
          default = "";
          description = "App description";
        };
      };
    };

  # ---------------------------------------------------------------------------
  # Helper Functions
  # ---------------------------------------------------------------------------

  # Filter apps to only Bun-enabled apps
  bunApps = lib.filterAttrs (name: app: app.bun.enable or false) sp.apps;
  hasBunApps = bunApps != { };

  # Build a Bun app package using bun2nix.writeBunApplication
  # Supports both per-app bun.nix lockfile and root bun.nix layouts
  mkBunPackage =
    name: app:
    let
      bunCfg = app.bun;
      repoRoot = ../../../..;
      appPath = app.path;

      # Check if app has its own bun.nix lockfile (per-app layout)
      hasPerAppBunNix = builtins.pathExists (repoRoot + "/${appPath}/bun.nix");

      # For per-app layout, use the app directory as source
      # For workspace layout, use repo root
      src = if hasPerAppBunNix then repoRoot + "/${appPath}" else repoRoot;

      # package.json location
      packageJsonPath =
        if hasPerAppBunNix then repoRoot + "/${appPath}/package.json" else repoRoot + "/package.json";

      # bun.nix lockfile location (generated by running `bun2nix`)
      bunNixPath = if hasPerAppBunNix then repoRoot + "/${appPath}/bun.nix" else repoRoot + "/bun.nix";
    in
    pkgs.bun2nix.writeBunApplication {
      pname = if bunCfg.binaryName != null then bunCfg.binaryName else name;
      version = bunCfg.version;
      packageJson = packageJsonPath;
      inherit src;

      buildPhase = bunCfg.buildPhase;
      startScript = bunCfg.startScript;
      runtimeInputs = bunCfg.runtimeInputs;
      runtimeEnv = bunCfg.runtimeEnv;
      inheritPath = bunCfg.inheritPath;

      bunDeps = pkgs.bun2nix.fetchBunDeps { bunNix = bunNixPath; };
    };

in
{
  # ===========================================================================
  # Options
  # ===========================================================================
  # Expose Bun packages for nix build (separate from modules attrsOf)
  options.stackpanel.bun.packages = lib.mkOption {
    type = lib.types.attrsOf lib.types.unspecified;
    default = { };
    description = ''
      Bun packages for apps with bun.enable = true.
      These are exposed for `nix build` but NOT included in devshell.
      Access via config.stackpanel.bun.packages.apps.<name>.
    '';
  };

  # ===========================================================================
  # Configuration
  # ===========================================================================
  config = lib.mkMerge [
    # Always register appModules (unconditionally)
    {
      stackpanel.appModules = [ appModule ];
    }

    # Apply config when stackpanel is enabled and bun apps exist
    (lib.mkIf (sp.enable && hasBunApps) {
      # -----------------------------------------------------------------------
      # Packages - Build Bun applications
      # -----------------------------------------------------------------------
      stackpanel.bun.packages = {
        apps = lib.mapAttrs mkBunPackage bunApps;
      };

    # -------------------------------------------------------------------------
    # Scripts - Add run-<app> and test-<app> commands
    # -------------------------------------------------------------------------
    stackpanel.scripts = lib.mkIf hasBunApps (
      lib.mkMerge (
        lib.mapAttrsToList (name: app: {
          "run-${name}" = {
            exec = ''cd "$STACKPANEL_ROOT/${app.path}" && exec bun run ${app.bun.mainPackage} "$@"'';
            runtimeInputs = [ pkgs.bun ];
            description = "Run ${name} Bun app";
          };
          "test-${name}" = {
            exec = ''cd "$STACKPANEL_ROOT/${app.path}" && exec bun test "$@"'';
            runtimeInputs = [ pkgs.bun ];
            description = "Test ${name} Bun app";
          };
        }) bunApps
      )
    );

    # =========================================================================
    # Flake Checks (CI)
    # =========================================================================
    stackpanel.moduleChecks.${meta.id} = {
      eval = {
        description = "${meta.name} module evaluates correctly";
        required = true;
        derivation = pkgs.runCommand "${meta.id}-eval-check" { } ''
          echo "Bun module evaluates successfully"
          touch $out
        '';
      };

      packages = {
        description = "${meta.name} packages are available";
        required = true;
        derivation = pkgs.runCommand "${meta.id}-packages-check" { nativeBuildInputs = [ pkgs.bun ]; } ''
          bun --version
          echo "Bun runtime available"
          touch $out
        '';
      };
    };

    # =========================================================================
    # Health Checks (Runtime)
    # =========================================================================
    stackpanel.healthchecks.modules.${meta.id} = {
      enable = true;
      displayName = meta.name;
      checks = {
        bun-installed = {
          description = "Bun runtime is installed and accessible";
          script = ''
            command -v bun >/dev/null 2>&1 && bun --version
          '';
          severity = "critical";
          timeout = 5;
        };

        bun-version = {
          description = "Bun version is 1.0 or newer";
          script = ''
            version=$(bun --version 2>/dev/null)
            major=$(echo "$version" | cut -d. -f1)
            [ "$major" -ge 1 ]
          '';
          severity = "warning";
          timeout = 5;
        };

        lockfile-exists = {
          description = "bun.nix lockfile exists for Nix builds";
          script = ''
            test -f "$STACKPANEL_ROOT/bun.nix" || \
            find "$STACKPANEL_ROOT/apps" -name "bun.nix" -type f | head -1 | grep -q .
          '';
          severity = "warning";
          timeout = 5;
        };
      };
    };

      # -----------------------------------------------------------------------
      # Module Registration
      # -----------------------------------------------------------------------
      stackpanel.modules.${meta.id} = {
        enable = true;
        meta = {
          name = meta.name;
          description = meta.description;
          icon = meta.icon;
          category = meta.category;
          author = meta.author;
          version = meta.version;
          homepage = meta.homepage;
        };
        source.type = "builtin";
        features = meta.features;
        tags = meta.tags;
        priority = meta.priority;
        healthcheckModule = meta.id;
      };
    })
  ];
}
