# ==============================================================================
# module.nix - Bun Module Implementation
#
# Provides Bun/TypeScript application support using bun2nix for packaging.
#
# Features:
#   - Automatic bun2nix CLI in devshell (converts bun.lock -> bun.nix)
#   - Generated package.json with postinstall script that runs bun2nix
#   - Hermetic app packaging via bun2nix.writeBunApplication
#   - run-<app> and test-<app> wrapper scripts
#   - Health checks for bun, bun2nix, and lockfile presence
#
# Prerequisites:
#   - bun.nix lockfile (auto-generated via postinstall or: bun2nix)
#   - package.json in the app or root directory
#
# Architecture:
#   Generated files (package.json) are created via stackpanel.files system
#   and materialized on shell entry. package.json uses type="json" for
#   deep-merge support so other modules can contribute to the same file.
#
# App definition example:
#   stackpanel.apps.my-app = {
#     path = "apps/web";
#     bun = {
#       enable = true;
#       buildPhase = "bun run build";
#       startScript = "bun run start";
#       generateFiles = true;  # Generates package.json with bun2nix postinstall
#     };
#   };
#
# See: https://nix-community.github.io/bun2nix/building-packages/writeBunApplication.html
# ==============================================================================
{
  lib,
  config,
  pkgs,
  ...
}: let
  meta = import ./meta.nix;
  sp = config.stackpanel;

  # Import unified field definitions (single source of truth)
  bunSchema = import ./schema.nix {inherit lib;};
  spField = import ../../db/lib/field.nix {inherit lib;};

  # Compute npm scope prefix from config (project.repo or name)
  # e.g., "stackpanel" -> "@stackpanel"
  prefix = sp.project.repo or sp.name;

  # Portless configuration — used to prefix the dev script in package.json
  portlessCfg = config.stackpanel.portless or {enable = false;};
  portsLib = import ../../lib/ports.nix {inherit lib;};
  repoKey = sp.apps.github or "darkmatter/stackpanel";

  # ---------------------------------------------------------------------------
  # Helper Functions
  # ---------------------------------------------------------------------------

  # Filter apps to only Bun-enabled apps
  bunApps = lib.filterAttrs (name: app: app.bun.enable or false) sp.apps;
  hasBunApps = bunApps != {};

  # Build a Bun app package using bun2nix.writeBunApplication
  # Supports both per-app bun.nix lockfile and root bun.nix layouts
  mkBunPackage = name: app: let
    bunCfg = app.bun;
    repoRoot = ../../../..;
    appPath = app.path;

    # Check if app has its own bun.nix lockfile (per-app layout)
    hasPerAppBunNix = builtins.pathExists (repoRoot + "/${appPath}/bun.nix");

    # For per-app layout, use the app directory as source
    # For workspace layout, use repo root
    src =
      if hasPerAppBunNix
      then repoRoot + "/${appPath}"
      else repoRoot;

    # package.json location
    packageJsonPath =
      if hasPerAppBunNix
      then repoRoot + "/${appPath}/package.json"
      else repoRoot + "/package.json";

    # bun.nix lockfile location (generated by running `bun2nix`)
    bunNixPath =
      if hasPerAppBunNix
      then repoRoot + "/${appPath}/bun.nix"
      else repoRoot + "/bun.nix";
  in
    pkgs.bun2nix.writeBunApplication {
      pname =
        if bunCfg.binaryName != null
        then bunCfg.binaryName
        else name;
      version = bunCfg.version;
      packageJson = packageJsonPath;
      inherit src;

      buildPhase = bunCfg.buildPhase;
      startScript = bunCfg.startScript;
      runtimeInputs = bunCfg.runtimeInputs;
      runtimeEnv = bunCfg.runtimeEnv;
      inheritPath = bunCfg.inheritPath;

      bunDeps = pkgs.bun2nix.fetchBunDeps {bunNix = bunNixPath;};
    };

  # ---------------------------------------------------------------------------
  # File Generation (package.json with bun2nix postinstall)
  # ---------------------------------------------------------------------------

  # Generate package.json for a Bun app
  generatePackageJson = name: app: let
    bunCfg = app.bun;
    usePortless = portlessCfg.enable && (app.domain or null) != null;
    appPort = portsLib.stablePort {
      repo = repoKey;
      service = name;
    };
    portlessName = "${app.domain}.${portlessCfg.project-name or sp.ports.project-name or "default"}";
    devScript =
      if usePortless
      then "portless ${portlessName} --app-port ${toString appPort} bun run --hot ${bunCfg.mainPackage}"
      else "bun run --hot ${bunCfg.mainPackage}";
  in {
    name = name;
    private = true;
    dependencies = {
      "@${prefix}/scripts" = "workspace:*";
    };
    scripts = {
      preinstall = "check-devshell";
      postinstall = "bun2nix";
      dev = devScript;
      build = bunCfg.buildPhase;
      start = bunCfg.startScript;
      test = "bun test";
    };
  };

  # Create file entries for materialization (uses stackpanel.files system)
  # package.json uses type="json" for deep-merge support from other modules
  mkGeneratedFileEntries = name: app: {
    "${app.path}/package.json" = {
      type = "json";
      jsonValue = generatePackageJson name app;
      source = "bun";
      description = "Bun app package.json (scripts, dependencies, bun2nix postinstall)";
    };
  };
in {
  # ===========================================================================
  # Options
  # ===========================================================================
  # Expose Bun packages for nix build (separate from modules attrsOf)
  options.stackpanel.bun.packages = lib.mkOption {
    type = lib.types.attrsOf lib.types.unspecified;
    default = {};
    description = ''
      Bun packages for apps with bun.enable = true.
      These are exposed for `nix build` but NOT included in devshell.
      Access via config.stackpanel.bun.packages.apps.<name>.
    '';
  };

  # ===========================================================================
  # Configuration
  # ===========================================================================
  config = lib.mkMerge [
    # Always register appModules (unconditionally)
    # Options are auto-generated from bun-app.proto.nix (single source of truth)
    # runtimeInputs is Nix-only (listOf package - no proto equivalent)
    {
      stackpanel.appModules = [
        (
          {lib, ...}: {
            options.bun = lib.mkOption {
              type = lib.types.submodule {
                options =
                  lib.mapAttrs (_: spField.asOption) bunSchema.fields
                  // {
                    # Nix-only option: package references can't be proto fields
                    runtimeInputs = lib.mkOption {
                      type = lib.types.listOf lib.types.package;
                      default = [];
                      description = "Runtime nix dependencies";
                    };
                  };
              };
              default = {};
              description = "Bun-specific configuration for this app";
            };
          }
        )
      ];
    }

    # Apply config when stackpanel is enabled and bun apps exist
    (lib.mkIf (sp.enable && hasBunApps) {
      # -----------------------------------------------------------------------
      # Packages - Build Bun applications via writeBunApplication
      # -----------------------------------------------------------------------
      stackpanel.bun.packages = {
        apps = lib.mapAttrs mkBunPackage bunApps;
      };

      # -----------------------------------------------------------------------
      # Devshell - Add bun2nix CLI to shell environment
      # -----------------------------------------------------------------------
      stackpanel.devshell.packages = [
        pkgs.bun2nix # Native bun2nix CLI (converts bun.lock -> bun.nix)
      ];

      # -----------------------------------------------------------------------
      # File Generation - package.json with bun2nix postinstall
      # -----------------------------------------------------------------------
      stackpanel.files.entries = lib.mkMerge (
        lib.mapAttrsToList (
          name: app: lib.optionalAttrs app.bun.generateFiles (mkGeneratedFileEntries name app)
        )
        bunApps
      );

      # -----------------------------------------------------------------------
      # Scripts - Add run-<app> and test-<app> commands
      # -----------------------------------------------------------------------
      stackpanel.scripts = lib.mkMerge (
        lib.mapAttrsToList (name: app: {
          "run-${name}" = {
            exec = ''cd "$STACKPANEL_ROOT/${app.path}" && exec bun run ${app.bun.mainPackage} "$@"'';
            runtimeInputs = [pkgs.bun];
            description = "Run ${name} Bun app";
            args = [
              {
                name = "...";
                description = "Arguments passed to the bun script";
              }
            ];
          };
          "test-${name}" = {
            exec = ''cd "$STACKPANEL_ROOT/${app.path}" && exec bun test "$@"'';
            runtimeInputs = [pkgs.bun];
            description = "Test ${name} Bun app";
            args = [
              {
                name = "...";
                description = "Arguments passed to bun test";
              }
            ];
          };
        })
        bunApps
      );

      # -----------------------------------------------------------------------
      # Flake Checks (CI)
      # -----------------------------------------------------------------------
      stackpanel.moduleChecks.${meta.id} = {
        eval = {
          description = "${meta.name} module evaluates correctly";
          required = true;
          derivation = pkgs.runCommand "${meta.id}-eval-check" {} ''
            echo "Bun module evaluates successfully"
            touch $out
          '';
        };

        packages = {
          description = "${meta.name} packages are available";
          required = true;
          derivation = pkgs.runCommand "${meta.id}-packages-check" {nativeBuildInputs = [pkgs.bun];} ''
            bun --version
            echo "Bun runtime available"
            touch $out
          '';
        };
      };

      # -----------------------------------------------------------------------
      # Health Checks (Runtime)
      # -----------------------------------------------------------------------
      stackpanel.healthchecks.modules.${meta.id} = {
        enable = true;
        displayName = meta.name;
        checks = {
          bun-installed = {
            description = "Bun runtime is installed and accessible";
            script = ''
              command -v bun >/dev/null 2>&1 && bun --version
            '';
            severity = "critical";
            timeout = 5;
          };

          bun-version = {
            description = "Bun version is 1.2 or newer";
            script = ''
              version=$(bun --version 2>/dev/null)
              major=$(echo "$version" | cut -d. -f1)
              minor=$(echo "$version" | cut -d. -f2)
              [ "$major" -gt 1 ] || ([ "$major" -eq 1 ] && [ "$minor" -ge 2 ])
            '';
            severity = "warning";
            timeout = 5;
          };

          bun2nix-installed = {
            description = "bun2nix CLI is installed and accessible";
            script = ''
              command -v bun2nix >/dev/null 2>&1 && bun2nix --version
            '';
            severity = "warning";
            timeout = 5;
          };

          lockfile-exists = {
            description = "bun.nix lockfile exists for Nix builds";
            script = ''
              STACKPANEL_ROOT="''${STACKPANEL_ROOT:-$(pwd)}"
              test -f "$STACKPANEL_ROOT/bun.nix" || \
              find "$STACKPANEL_ROOT/apps" -name "bun.nix" -type f | head -1 | grep -q .
            '';
            severity = "warning";
            timeout = 5;
          };
        };
      };

      # -----------------------------------------------------------------------
      # Module Registration
      # -----------------------------------------------------------------------
      stackpanel.modules.${meta.id} = {
        enable = true;
        meta = {
          name = meta.name;
          description = meta.description;
          icon = meta.icon;
          category = meta.category;
          author = meta.author;
          version = meta.version;
          homepage = meta.homepage;
        };
        source.type = "builtin";
        features = meta.features;
        flakeInputs = meta.flakeInputs or [];
        tags = meta.tags;
        priority = meta.priority;
        healthcheckModule = meta.id;
      };
    })
  ];
}
