// Custom alchemy Resource for AWS KMS Key.
// Generated by stackpanel — static library code.
import type { Context } from "alchemy";
import { Resource } from "alchemy";

export interface KmsKeyProps {
  /** Description of the key */
  description?: string;
  /** Enable automatic key rotation (default: true) */
  enableKeyRotation?: boolean;
  /** Deletion window in days (default: 30, range: 7-30) */
  deletionWindowInDays?: number;
  /** Key policy JSON document */
  policy?: string;
  /** Resource tags */
  tags?: Record<string, string>;
}

export interface KmsKey extends KmsKeyProps {
  /** ARN of the KMS key */
  arn: string;
  /** Key ID */
  keyId: string;
}

export const KmsKey = Resource(
  "kms::Key",
  async function (
    this: Context<KmsKey>,
    _id: string,
    props: KmsKeyProps,
  ): Promise<KmsKey> {
    const {
      KMSClient,
      CreateKeyCommand,
      DescribeKeyCommand,
      EnableKeyRotationCommand,
      DisableKeyRotationCommand,
      PutKeyPolicyCommand,
      ScheduleKeyDeletionCommand,
      TagResourceCommand,
    } = await import("@aws-sdk/client-kms");
    const client = new KMSClient({});

    if (this.phase === "delete") {
      if (this.output?.keyId) {
        try {
          await client.send(
            new ScheduleKeyDeletionCommand({
              KeyId: this.output.keyId,
              PendingWindowInDays: props.deletionWindowInDays ?? 30,
            })
          );
        } catch (err: any) {
          if (err.name !== "NotFoundException") throw err;
        }
      }
      return this.destroy();
    }

    let keyId: string;

    if (this.phase === "create") {
      const result = await client.send(
        new CreateKeyCommand({
          Description: props.description,
          KeyUsage: "ENCRYPT_DECRYPT",
          Origin: "AWS_KMS",
          Tags: [
            ...Object.entries(props.tags ?? {}).map(([Key, Value]) => ({ TagKey: Key, TagValue: Value })),
            { TagKey: "alchemy_stage", TagValue: this.stage },
            { TagKey: "alchemy_resource", TagValue: this.id },
          ],
          ...(props.policy ? { Policy: props.policy } : {}),
        })
      );
      keyId = result.KeyMetadata!.KeyId!;
    } else {
      keyId = this.output!.keyId;
    }

    // Enable/disable key rotation
    if (props.enableKeyRotation !== false) {
      await client.send(new EnableKeyRotationCommand({ KeyId: keyId }));
    } else {
      await client.send(new DisableKeyRotationCommand({ KeyId: keyId }));
    }

    // Update policy if provided
    if (props.policy) {
      await client.send(
        new PutKeyPolicyCommand({
          KeyId: keyId,
          PolicyName: "default",
          Policy: props.policy,
        })
      );
    }

    // Update tags
    const tags = {
      ...props.tags,
      alchemy_stage: this.stage,
      alchemy_resource: this.id,
    };
    await client.send(
      new TagResourceCommand({
        KeyId: keyId,
        Tags: Object.entries(tags).map(([TagKey, TagValue]) => ({ TagKey, TagValue })),
      })
    );

    // Describe to get full info
    const desc = await client.send(new DescribeKeyCommand({ KeyId: keyId }));

    return {
      ...props,
      arn: desc.KeyMetadata!.Arn!,
      keyId: desc.KeyMetadata!.KeyId!,
    };
  }
);
