// Custom alchemy Resource for AWS ALB Listener Rule.
// Generated by stackpanel — static library code.
import type { Context } from "alchemy";
import { Resource } from "alchemy";

export interface ListenerRuleProps {
  listenerArn: string;
  priority: number;
  hostnames: string[];
  targetGroupArn: string;
  destroyOnDelete?: boolean;
}

export interface ListenerRule {
  arn: string;
  priority: number;
  adopted?: boolean;
}

export const ListenerRule = Resource(
  "stackpanel::ListenerRule",
  async function (
    this: Context<ListenerRule>,
    _id: string,
    props: ListenerRuleProps,
  ): Promise<ListenerRule> {
    const {
      ElasticLoadBalancingV2Client,
      DescribeRulesCommand,
      CreateRuleCommand,
      DeleteRuleCommand,
    } = await import("@aws-sdk/client-elastic-load-balancing-v2");

    const client = new ElasticLoadBalancingV2Client({});

    if (this.phase === "delete") {
      if (props.destroyOnDelete === false) {
        return this.destroy();
      }
      if (this.output?.arn) {
        try {
          await client.send(new DeleteRuleCommand({ RuleArn: this.output.arn }));
        } catch (err: any) {
          if (err.name !== "RuleNotFound") throw err;
        }
      }
      return this.destroy();
    }

    let arn = this.output?.arn;
    let adopted = this.output?.adopted ?? false;

    if (!arn) {
      const existing = await client.send(
        new DescribeRulesCommand({ ListenerArn: props.listenerArn }),
      );
      const found = (existing.Rules ?? []).find(
        (rule) => rule.Priority === String(props.priority),
      );
      if (found?.RuleArn) {
        arn = found.RuleArn;
        adopted = true;
      }
    }

    if (!arn) {
      const created = await client.send(
        new CreateRuleCommand({
          ListenerArn: props.listenerArn,
          Priority: props.priority,
          Actions: [
            {
              Type: "forward",
              TargetGroupArn: props.targetGroupArn,
            },
          ],
          Conditions: [
            {
              Field: "host-header",
              HostHeaderConfig: {
                Values: props.hostnames,
              },
            },
          ],
        }),
      );
      const rule = created.Rules?.[0];
      if (!rule?.RuleArn) {
        throw new Error("Unable to create listener rule");
      }
      arn = rule.RuleArn;
    }

    if (!arn) {
      throw new Error("Unable to resolve listener rule");
    }

    return {
      arn,
      priority: props.priority,
      adopted,
    };
  },
);
