// Custom alchemy Resource for AWS Target Group Attachment.
// Generated by stackpanel — static library code.
import type { Context } from "alchemy";
import { Resource } from "alchemy";

export interface TargetGroupAttachmentProps {
  targetGroupArn: string;
  targetId: string;
  port?: number;
  destroyOnDelete?: boolean;
}

export interface TargetGroupAttachment {
  targetGroupArn: string;
  targetId: string;
}

export const TargetGroupAttachment = Resource(
  "stackpanel::TargetGroupAttachment",
  async function (
    this: Context<TargetGroupAttachment>,
    _id: string,
    props: TargetGroupAttachmentProps,
  ): Promise<TargetGroupAttachment> {
    const {
      ElasticLoadBalancingV2Client,
      RegisterTargetsCommand,
      DeregisterTargetsCommand,
    } = await import("@aws-sdk/client-elastic-load-balancing-v2");

    const client = new ElasticLoadBalancingV2Client({});

    if (this.phase === "delete") {
      if (props.destroyOnDelete === false) {
        return this.destroy();
      }
      try {
        await client.send(
          new DeregisterTargetsCommand({
            TargetGroupArn: props.targetGroupArn,
            Targets: [{ Id: props.targetId, Port: props.port }],
          }),
        );
      } catch (err: any) {
        if (err.name !== "TargetGroupNotFound") throw err;
      }
      return this.destroy();
    }

    await client.send(
      new RegisterTargetsCommand({
        TargetGroupArn: props.targetGroupArn,
        Targets: [{ Id: props.targetId, Port: props.port }],
      }),
    );

    return {
      targetGroupArn: props.targetGroupArn,
      targetId: props.targetId,
    };
  },
);
