# ==============================================================================
# agenix.nix
#
# Agenix compatibility layer (minimal).
#
# With the master key model, agenix integration is simpler:
# - All secrets use master key public keys as recipients
# - No per-user or per-environment key management needed
#
# This module generates a secrets.nix file compatible with agenix CLI
# if you want to use agenix tooling alongside stackpanel.
# ==============================================================================
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.stackpanel.secrets;

  # Get all SECRET type variables
  secretVariables = lib.filterAttrs (
    _: v: v.type == "SECRET"
  ) (config.stackpanel.variables or { });

  # Generate the secrets.nix content for agenix CLI compatibility
  secretsNixContent =
    let
      # Get public keys for a secret based on its master-keys
      getPublicKeysForSecret = secretCfg:
        let
          keyNames = secretCfg.master-keys or [ "local" ];
          keys = map (name: cfg.master-keys.${name}.age-pub or "") keyNames;
        in
        lib.filter (k: k != "") keys;

      # Format each secret entry
      formatSecret = id: secretCfg:
        let
          filename = builtins.replaceStrings [ "/" ] [ "-" ] (lib.removePrefix "/" id);
          publicKeys = getPublicKeysForSecret secretCfg;
          keysStr = lib.concatMapStringsSep "\n    " (k: ''"${k}"'') publicKeys;
        in
        ''
          "${filename}.age".publicKeys = [
            ${keysStr}
          ];
        '';

      secretEntries = lib.concatStringsSep "\n" (lib.mapAttrsToList formatSecret secretVariables);
    in
    ''
      # Auto-generated by StackPanel for agenix CLI compatibility
      # Regenerate with: nix eval --raw .#stackpanelConfig.secrets.secrets-nix-content
      {
      ${secretEntries}
      }
    '';

in
{
  options.stackpanel.secrets = {
    secrets-nix-content = lib.mkOption {
      type = lib.types.str;
      readOnly = true;
      description = ''
        Generated content for secrets.nix file (agenix CLI compatibility).
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    stackpanel.secrets.secrets-nix-content = secretsNixContent;

    stackpanel.scripts = {
      "secrets:write-agenix-config" = {
        description = "Write secrets.nix for agenix CLI compatibility";
        exec = ''
          echo "Writing ${cfg.secrets-dir}/secrets.nix..."
          mkdir -p "${cfg.secrets-dir}"
          cat > "${cfg.secrets-dir}/secrets.nix" << 'EOF'
          ${secretsNixContent}
          EOF
          echo "✅ Done"
        '';
      };
    };
  };
}
