/// <reference path="./.sst/platform/config.d.ts" />

/**
 * SST Configuration for Stackpanel Infrastructure
 *
 * This configures:
 * 1. OIDC provider for GitHub Actions
 * 2. IAM role for secrets access
 * 3. KMS key for secrets encryption/decryption
 *
 * Generated by stackpanel - do not edit manually.
 * Regenerate with: nix run .#generate
 */

// ===========================================================================
// Interpolated values from Nix configuration
// ===========================================================================
const projectName = "stackpanel";
const awsRegion = "us-west-2";

export default $config({
  app(input) {
    return {
      name: projectName,
      removal: input?.stage === "production" ? "retain" : "remove",
      protect: ["production"].includes(input?.stage ?? ""),
      home: "aws",
      providers: {
        aws: {
          region: awsRegion,
        },
      },
    };
  },

  async run() {
// syntax: ts
// ========================================================================
// GitHub Actions OIDC Provider
// ========================================================================
const githubOrg = "darkmatter";
const githubRepo = "stackpanel";

const githubOidcProvider = new aws.iam.OpenIdConnectProvider("github-oidc", {
  url: "https://token.actions.githubusercontent.com",
  clientIdLists: ["sts.amazonaws.com"],
  thumbprintLists: ["6938fd4d98bab03faadb97b34396831e3780aea1"],
  tags: {
    Name: "github-actions-oidc",
    ManagedBy: "sst",
  },
});

const oidcProviderArn = githubOidcProvider.arn;
const oidcProviderUrl = "token.actions.githubusercontent.com";
const oidcConditions = [
  {
    test: "StringEquals",
    variable: `${oidcProviderUrl}:aud`,
    values: ["sts.amazonaws.com"],
  },
  {
    test: "StringLike",
    variable: `${oidcProviderUrl}:sub`,
    values: [`repo:${githubOrg}/${githubRepo}:*`],
  },
];

// syntax: ts
// ========================================================================
// IAM Role for OIDC Authentication
// ========================================================================
const roleName = "stackpanel-secrets-role";

const secretsRole = new aws.iam.Role(roleName, {
  name: roleName,
  assumeRolePolicy: aws.iam.getPolicyDocumentOutput({
    statements: [{
      effect: "Allow",
      principals: [{
        type: "Federated",
        identifiers: [oidcProviderArn],
      }],
      actions: ["sts:AssumeRoleWithWebIdentity"],
      conditions: oidcConditions,
    }],
  }).json,
  tags: {
    Name: roleName,
    Environment: $app.stage,
    ManagedBy: "sst",
  },
});

// syntax: ts
// ========================================================================
// KMS Key for Secrets Encryption
// ========================================================================
const kmsAlias = "stackpanel-secrets";
const kmsDeletionDays = 30;
const awsAccountId = "950224716579";

const secretsKey = new aws.kms.Key(kmsAlias, {
  description: "KMS key for encrypting stackpanel secrets",
  enableKeyRotation: true,
  deletionWindowInDays: kmsDeletionDays,
  policy: aws.iam.getPolicyDocumentOutput({
    statements: [
      // Allow root account full access
      {
        effect: "Allow",
        principals: [{
          type: "AWS",
          identifiers: [`arn:aws:iam::${awsAccountId}:root`],
        }],
        actions: ["kms:*"],
        resources: ["*"],
      },
      // Allow the secrets role to use the key
      {
        effect: "Allow",
        principals: [{
          type: "AWS",
          identifiers: [secretsRole.arn],
        }],
        actions: [
          "kms:Decrypt",
          "kms:Encrypt",
          "kms:GenerateDataKey*",
          "kms:DescribeKey",
        ],
        resources: ["*"],
      },
    ],
  }).json,
  tags: {
    Name: kmsAlias,
    Environment: $app.stage,
    ManagedBy: "sst",
  },
});

const secretsKeyAlias = new aws.kms.Alias(`${kmsAlias}-alias`, {
  name: `alias/${kmsAlias}`,
  targetKeyId: secretsKey.id,
});

// syntax: ts
// ========================================================================
// IAM Policy for KMS Access
// ========================================================================
new aws.iam.RolePolicy(`${roleName}-kms`, {
  name: `${roleName}-kms-policy`,
  role: secretsRole.id,
  policy: aws.iam.getPolicyDocumentOutput({
    statements: [
      {
        effect: "Allow",
        actions: [
          "kms:Decrypt",
          "kms:Encrypt",
          "kms:GenerateDataKey*",
          "kms:DescribeKey",
        ],
        resources: [secretsKey.arn],
      },
      {
        effect: "Allow",
        actions: ["kms:Decrypt"],
        resources: ["*"],
        conditions: [
          {
            test: "StringLike",
            variable: "kms:RequestAlias",
            values: [`alias/${kmsAlias}`],
          },
        ],
      },
    ],
  }).json,
});

    // ========================================================================
    // Outputs
    // ========================================================================
    const providerType = "github-actions";
    const providerDisplayName = "GitHub Actions";

    return {
      roleArn: secretsRole.arn,
      roleName: secretsRole.name,
      kmsKeyArn: secretsKey.arn,
kmsKeyId: secretsKey.id,
kmsKeyAlias: secretsKeyAlias.name,
oidcProviderArn: githubOidcProvider.arn,
provider: providerType,
      setupInstructions: $interpolate`
╔════════════════════════════════════════════════════════════════════╗
║ Stackpanel Infrastructure Setup Complete                           ║
╚════════════════════════════════════════════════════════════════════╝

Role ARN: ${secretsRole.arn}
KMS Key Alias: alias/${kmsAlias}

Provider: ${providerDisplayName}

To use this infrastructure:
1. Configure your secrets with the KMS key
2. Use the IAM role for decryption in your applications
`,
    };

  },
});
