# ==============================================================================
# config-package.nix
#
# Generates the @gen/config package — a TypeScript constant containing the
# evaluated stackpanel config, importable from anywhere in the monorepo.
#
# Usage:
#   import { PROJECT_CONFIG } from "@gen/config";
#   console.log(PROJECT_CONFIG.projectName);
#   console.log(PROJECT_CONFIG.apps.web.port);
#
# The config is evaluated at Nix shell entry time (same as @gen/env).
# The type is derived from the JSON shape, not from proto — proto types
# cover the user-editable schema, while this covers the evaluated output.
#
# Structure:
#   packageDir/
#     package.json
#     src/
#       index.ts          — re-exports PROJECT_CONFIG and ProjectConfig
#       config.ts         — the actual const with full evaluated config
# ==============================================================================
{
  lib,
  config,
  ...
}:
let
  cfg = config.stackpanel;
  packageDir = "packages/gen/config";
  packageName = "@gen/config";

  # Re-use the same fullConfig that the CLI consumes. This is the evaluated
  # stackpanel config with computed ports, URLs, services, etc.
  #
  # We import cli.nix's fullConfig shape by reading the relevant fields
  # directly from the evaluated module system (config.stackpanel.*).
  portsCfg = cfg.ports;
  appsComputed = cfg.appsComputed or { };

  # Build the config object that becomes PROJECT_CONFIG.
  # This mirrors cli.nix's fullConfig but is purpose-built for TS consumption.
  projectConfig = {
    version = 1;
    projectName = portsCfg.project-name;
    basePort = portsCfg.base-port;

    apps = lib.mapAttrs (_: app: {
      port = app.port;
      domain = app.domain or null;
      url = app.url or null;
      tls = app.tls or false;
      path = app.path or null;
    }) appsComputed;

    services = lib.listToAttrs (
      map (svc: {
        name = lib.toLower svc.key;
        value = {
          key = svc.key;
          name = svc.displayName;
          port = svc.port;
        };
      }) (lib.attrValues (portsCfg.service or { }))
    );

    deployment = {
      aws = {
        region = cfg.deployment.aws.region or "us-west-2";
        instanceType = cfg.deployment.aws."instance-type" or "t3.small";
        port = cfg.deployment.aws.port or 80;
      };
    };

    colmena = {
      enable = cfg.colmena.enable or false;
      flake = cfg.colmena.flake or null;
    };

    binaryCache = {
      enable = cfg.binary-cache.enable or false;
      cachix = {
        enable = cfg.binary-cache.cachix.enable or false;
        cache = cfg.binary-cache.cachix.cache or "";
      };
    };
  };

  configJson = builtins.toJSON projectConfig;

  # --------------------------------------------------------------------------
  # TypeScript generation
  # --------------------------------------------------------------------------

  configTs = ''
    // Auto-generated by Stackpanel — do not edit manually.
    // Evaluated stackpanel config, regenerated on each devshell entry.

    export const PROJECT_CONFIG = ${configJson} as const;

    export type ProjectConfig = typeof PROJECT_CONFIG;
  '';

  indexTs = ''
    // Auto-generated by Stackpanel — do not edit manually.
    export { PROJECT_CONFIG, type ProjectConfig } from "./config";
  '';

  packageJson = builtins.toJSON {
    name = packageName;
    type = "module";
    exports = {
      "." = {
        default = "./src/index.ts";
      };
    };
  };

in
{
  config = lib.mkIf (cfg.enable or false) {
    stackpanel.files.entries = {
      "${packageDir}/package.json" = {
        type = "json";
        jsonValue = builtins.fromJSON packageJson;
        mode = "0644";
        description = "Package manifest for ${packageName}";
        source = "config-codegen";
      };

      "${packageDir}/src/config.ts" = {
        text = configTs;
        mode = "0644";
        description = "Evaluated stackpanel config as a TypeScript constant";
        source = "config-codegen";
      };

      "${packageDir}/src/index.ts" = {
        text = indexTs;
        mode = "0644";
        description = "Re-exports for ${packageName}";
        source = "config-codegen";
      };
    };
  };
}
