# ==============================================================================
# env-typescript.nix
#
# Pure Nix TypeScript codegen for environment variables.
# Generates znv-based TypeScript modules from stackpanel.apps configuration.
#
# This integrates with stackpanel.files for automatic generation on shell entry.
# No shell scripts required - all computation happens in Nix evaluation.
#
# Generated structure:
#   packages/env/src/generated/<app>/<env>.ts  - znv modules per app/env
#   packages/env/src/generated/<app>/index.ts  - barrel exports per app
#   packages/env/src/generated/index.ts        - root barrel export
# ==============================================================================
{ lib, config, ... }:
let
  cfg = config.stackpanel;
  apps = cfg.apps or { };
  variables = cfg.variables or { };

  # Get the output directory from codegen config
  codegenCfg = cfg.secrets.codegen or { };
  tsConfig = codegenCfg.typescript or null;
  outputDir = if tsConfig != null then tsConfig.directory or "packages/env/src/generated" else "packages/env/src/generated";

  # Resolve a variable reference to get its actual type
  # variable-id like "/apps/web/port" -> { type, value, ... }
  resolveVariable = variableId:
    variables.${variableId} or null;

  # Convert variable type to Zod schema string
  # Handles both numeric (from data files) and string enum values (from Nix config)
  # Type 0/STRING = string, 1/SECRET = string, 2/VARIABLE = reference, 3/NUMBER = number, 4/BOOLEAN = boolean
  typeToZodSchema = varType:
    let
      # Normalize to string for comparison
      typeStr = if builtins.isInt varType then toString varType else varType;
    in
    if typeStr == "1" || typeStr == "SECRET" || typeStr == "VARIABLE_TYPE_SECRET" then "z.string()"
    else if typeStr == "3" || typeStr == "NUMBER" || typeStr == "VARIABLE_TYPE_NUMBER" then "z.coerce.number()"
    else if typeStr == "4" || typeStr == "BOOLEAN" || typeStr == "VARIABLE_TYPE_BOOLEAN" then "z.coerce.boolean()"
    else "z.string()";  # STRING (0), VARIABLE (2), or default

  # Get Zod schema for an app variable
  getZodSchema = appVar:
    let
      # If it's a reference (type = 2), resolve to get actual type
      resolved = if (appVar.type or 0) == 2 && (appVar.variable-id or null) != null
        then resolveVariable appVar.variable-id
        else null;
      actualType = if resolved != null
        then resolved.type or 0
        else appVar.type or 0;
    in
    typeToZodSchema actualType;

  # Generate TypeScript content for an app/environment
  mkEnvModule = appName: envName: envCfg:
    let
      vars = envCfg.variables or { };
      # Sort keys for consistent output
      sortedKeys = lib.sort (a: b: a < b) (lib.attrNames vars);
      
      # Generate field entries
      fields = lib.concatMapStringsSep "\n" (varName:
        let
          appVar = vars.${varName};
          envKey = appVar.key or varName;
          zodSchema = getZodSchema appVar;
        in
        "    ${envKey}: ${zodSchema},"
      ) sortedKeys;
    in
    if vars == { } then null else ''
      // Auto-generated by Stackpanel - do not edit manually
      // Run 'write-files' or restart devshell to regenerate
      import { parseEnv, z } from "znv";

      export const env = parseEnv(process.env, {
      ${fields}
      });
    '';

  # Generate barrel export for an app
  mkAppBarrelExport = appName: envNames:
    let
      exports = lib.concatMapStringsSep "\n" (envName:
        "export * as ${envName} from './${envName}';"
      ) (lib.sort (a: b: a < b) envNames);
    in
    ''
      // Auto-generated by Stackpanel - do not edit manually
      ${exports}
    '';

  # Generate root barrel export
  mkRootBarrelExport = appNames:
    let
      exports = lib.concatMapStringsSep "\n" (appName:
        "export * as ${appName} from './${appName}';"
      ) (lib.sort (a: b: a < b) appNames);
    in
    ''
      // Auto-generated by Stackpanel - do not edit manually
      ${exports}
    '';

  # Collect all files to generate
  # Returns: { "path/to/file.ts" = "content"; ... }
  generatedFiles =
    let
      # Per-app/env modules
      envModules = lib.concatMapAttrs (appName: appCfg:
        let
          envs = appCfg.environments or { };
        in
        lib.concatMapAttrs (envName: envCfg:
          let
            content = mkEnvModule appName envName envCfg;
            path = "${outputDir}/${appName}/${envName}.ts";
          in
          lib.optionalAttrs (content != null) {
            ${path} = content;
          }
        ) envs
      ) apps;

      # Per-app barrel exports
      appBarrels = lib.concatMapAttrs (appName: appCfg:
        let
          envs = appCfg.environments or { };
          envNames = lib.attrNames (lib.filterAttrs (envName: envCfg:
            (envCfg.variables or { }) != { }
          ) envs);
          path = "${outputDir}/${appName}/index.ts";
        in
        lib.optionalAttrs (envNames != []) {
          ${path} = mkAppBarrelExport appName envNames;
        }
      ) apps;

      # Root barrel export
      appsWithEnvs = lib.attrNames (lib.filterAttrs (appName: appCfg:
        let
          envs = appCfg.environments or { };
          hasVars = lib.any (envCfg: (envCfg.variables or { }) != { }) (lib.attrValues envs);
        in
        hasVars
      ) apps);
      
      rootBarrel = lib.optionalAttrs (appsWithEnvs != []) {
        "${outputDir}/index.ts" = mkRootBarrelExport appsWithEnvs;
      };
    in
    envModules // appBarrels // rootBarrel;

  # Convert to stackpanel.files.entries format
  fileEntries = lib.mapAttrs (path: content: {
    type = "text";
    text = content;
    source = "codegen/env-typescript.nix";
    description = "Auto-generated znv environment module";
  }) generatedFiles;

in
{
  # Export the generated file entries for use in stackpanel.files.entries
  inherit generatedFiles fileEntries;

  # Helper to check if codegen is enabled
  enabled = tsConfig != null && apps != { };
}
