# ==============================================================================
# module.nix - Docker & Container Module
#
# Provides container image building and registry tooling.
#
# Other modules contribute images by setting stackpanel.docker.images:
#
#   stackpanel.docker.enable = true;
#   stackpanel.docker.images.web = {
#     registry = "registry.fly.io";
#     name = "stackpanel-web";
#     dockerfile = {
#       type = "bun";
#       appPath = "apps/web";
#       port = 3000;
#     };
#   };
#
# This module then:
#   - Generates Dockerfiles at packages/infra/docker/<image>/Dockerfile
#   - Provides skopeo in the devshell (push to any registry)
#   - Computes full image refs (registry/name:tag)
#   - Exposes nix2container.enable flag per image (advanced path)
#
# Generated layout:
#   packages/infra/docker/
#   └── <imageName>/
#       └── Dockerfile
# ==============================================================================
{
  lib,
  config,
  pkgs,
  ...
}:
let
  meta = import ./meta.nix;
  cfg = config.stackpanel;
  dockerCfg = cfg.docker;
  infraPath = "packages/infra";

  # ---------------------------------------------------------------------------
  # Compute full image reference: registry/name:tag
  # ---------------------------------------------------------------------------
  mkImageRef =
    _key: imgCfg:
    let
      base = if imgCfg.registry != null then "${imgCfg.registry}/${imgCfg.name}" else imgCfg.name;
    in
    "${base}:${imgCfg.tag}";

  # ---------------------------------------------------------------------------
  # Filter images that have Dockerfile generation enabled
  # ---------------------------------------------------------------------------
  dockerfileImages = lib.filterAttrs (_: img: img.dockerfile.enable) dockerCfg.images;

  # ---------------------------------------------------------------------------
  # Dockerfile generators by type
  # ---------------------------------------------------------------------------
  mkDockerfileContent =
    _imgName: imgCfg:
    let
      df = imgCfg.dockerfile;
      port = toString df.port;
      appPath = df.appPath;
    in
    if df.content != null then
      df.content
    else if df.type == "bun" then
      mkBunDockerfile appPath port df
    else if df.type == "node" then
      mkNodeDockerfile appPath port df
    else if df.type == "go" then
      mkGoDockerfile appPath port df
    else if df.type == "static" then
      mkStaticDockerfile appPath port
    else
      mkBunDockerfile appPath port df; # default fallback

  mkBunDockerfile = appPath: port: df: ''
    # Generated by stackpanel - do not edit manually
    # Build context: repo root

    FROM oven/bun:1 AS build
    WORKDIR /app
    COPY package.json bun.lock* ./
    COPY ${appPath}/package.json ${appPath}/
    COPY packages/ packages/
    RUN bun install --frozen-lockfile
    COPY ${appPath}/ ${appPath}/
    WORKDIR /app/${appPath}
    RUN bun run build

    FROM oven/bun:slim
    WORKDIR /app
    COPY --from=build /app/${appPath}/.output .output/
    EXPOSE ${port}
    CMD ${
      if df.entrypoint != null then
        ''["${df.entrypoint}"]''
      else
        ''["bun", "run", ".output/server/index.mjs"]''
    }
  '';

  mkNodeDockerfile = appPath: port: df: ''
    # Generated by stackpanel - do not edit manually
    # Build context: repo root

    FROM node:22-slim AS build
    WORKDIR /app
    COPY package.json package-lock.json* yarn.lock* ./
    COPY ${appPath}/package.json ${appPath}/
    COPY packages/ packages/
    RUN npm ci
    COPY ${appPath}/ ${appPath}/
    WORKDIR /app/${appPath}
    RUN npm run build

    FROM node:22-slim
    WORKDIR /app
    COPY --from=build /app/${appPath}/.output .output/
    EXPOSE ${port}
    CMD ${
      if df.entrypoint != null then ''["${df.entrypoint}"]'' else ''["node", ".output/server/index.mjs"]''
    }
  '';

  mkGoDockerfile = appPath: port: df: ''
    # Generated by stackpanel - do not edit manually
    # Build context: repo root

    FROM golang:1.23 AS build
    WORKDIR /app
    COPY ${appPath}/go.mod ${appPath}/go.sum* ${appPath}/
    WORKDIR /app/${appPath}
    RUN go mod download
    WORKDIR /app
    COPY ${appPath}/ ${appPath}/
    WORKDIR /app/${appPath}
    RUN CGO_ENABLED=0 go build -o /server .

    FROM gcr.io/distroless/static-debian12
    COPY --from=build /server /server
    EXPOSE ${port}
    CMD ${if df.entrypoint != null then ''["${df.entrypoint}"]'' else ''["/server"]''}
  '';

  mkStaticDockerfile = appPath: port: ''
    # Generated by stackpanel - do not edit manually
    # Build context: repo root

    FROM oven/bun:1 AS build
    WORKDIR /app
    COPY package.json bun.lock* ./
    COPY ${appPath}/package.json ${appPath}/
    COPY packages/ packages/
    RUN bun install --frozen-lockfile
    COPY ${appPath}/ ${appPath}/
    WORKDIR /app/${appPath}
    RUN bun run build

    FROM nginx:alpine
    COPY --from=build /app/${appPath}/dist /usr/share/nginx/html
    EXPOSE ${port}
  '';

  # ---------------------------------------------------------------------------
  # Compute Dockerfile output path for an image
  # ---------------------------------------------------------------------------
  dockerfilePath = imgName: "${infraPath}/docker/${imgName}/Dockerfile";

in
{
  # ===========================================================================
  # Options
  # ===========================================================================
  options.stackpanel.docker = {
    enable = lib.mkEnableOption "container tooling (skopeo, Dockerfile generation, OCI images)";

    images = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.submodule (
          { name, ... }:
          {
            options = {
              # ----- Identity -----
              name = lib.mkOption {
                type = lib.types.str;
                default = name;
                description = "Image name (e.g., 'stackpanel-web').";
              };

              tag = lib.mkOption {
                type = lib.types.str;
                default = "latest";
                description = "Image tag.";
              };

              registry = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                description = "Registry URL (e.g., 'registry.fly.io', 'ghcr.io/org').";
                example = "registry.fly.io";
              };

              # ----- Dockerfile build -----
              dockerfile = {
                enable = lib.mkOption {
                  type = lib.types.bool;
                  default = true;
                  description = "Generate a Dockerfile for this image.";
                };

                type = lib.mkOption {
                  type = lib.types.enum [
                    "bun"
                    "node"
                    "go"
                    "static"
                    "custom"
                  ];
                  default = "bun";
                  description = "App type determines the generated Dockerfile template.";
                };

                appPath = lib.mkOption {
                  type = lib.types.str;
                  default = "apps/${name}";
                  description = "App directory relative to repo root (e.g., 'apps/web').";
                };

                port = lib.mkOption {
                  type = lib.types.int;
                  default = 3000;
                  description = "Port the app listens on inside the container.";
                };

                entrypoint = lib.mkOption {
                  type = lib.types.nullOr lib.types.str;
                  default = null;
                  description = "Custom CMD override for the container.";
                };

                content = lib.mkOption {
                  type = lib.types.nullOr lib.types.str;
                  default = null;
                  description = ''
                    Custom Dockerfile content. When set, overrides the type-based
                    auto-generated Dockerfile entirely.
                  '';
                };
              };

              # ----- nix2container (advanced) -----
              nix2container = {
                enable = lib.mkOption {
                  type = lib.types.bool;
                  default = false;
                  description = ''
                    Build this image with nix2container (reproducible, no Docker daemon).
                    When enabled, a flake output is created at containers.<name>.
                    Requires nix2container flake input.
                  '';
                };
              };
            };
          }
        )
      );
      default = { };
      description = ''
        Container image definitions. Other modules contribute images here.

        Each image can have a Dockerfile (auto-generated or custom) and/or
        nix2container config. Dockerfiles are generated at:
          packages/infra/docker/<name>/Dockerfile
      '';
    };

    # Read-only computed outputs
    imagesComputed = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      readOnly = true;
      default = { };
      description = "Computed full image references (registry/name:tag).";
    };

    dockerfilePaths = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      readOnly = true;
      default = { };
      description = "Computed Dockerfile paths per image (relative to repo root).";
    };
  };

  # ===========================================================================
  # Configuration
  # ===========================================================================
  config = lib.mkIf (cfg.enable && dockerCfg.enable) {
    # Computed outputs
    stackpanel.docker.imagesComputed = lib.mapAttrs mkImageRef dockerCfg.images;
    stackpanel.docker.dockerfilePaths = lib.mapAttrs (
      imgName: _: dockerfilePath imgName
    ) dockerfileImages;

    # Generate Dockerfiles
    stackpanel.files.entries = lib.mapAttrs' (imgName: imgCfg: {
      name = dockerfilePath imgName;
      value = {
        type = "text";
        text = mkDockerfileContent imgName imgCfg;
        source = meta.id;
        description = "Dockerfile for ${imgName}";
      };
    }) dockerfileImages;

    # Devshell packages
    stackpanel.devshell.packages = [
      pkgs.skopeo
    ];

    # Health checks
    stackpanel.healthchecks.modules.${meta.id} = {
      enable = true;
      displayName = meta.name;
      checks = {
        skopeo-installed = {
          description = "Skopeo is installed for OCI image operations";
          script = ''
            command -v skopeo >/dev/null 2>&1 && skopeo --version
          '';
          severity = "critical";
          timeout = 5;
        };
      };
    };

    # Module registration
    stackpanel.modules.${meta.id} = {
      enable = true;
      meta = {
        name = meta.name;
        description = meta.description;
        icon = meta.icon;
        category = meta.category;
        author = meta.author;
        version = meta.version;
        homepage = meta.homepage;
      };
      source.type = "builtin";
      features = meta.features;
      tags = meta.tags;
      priority = meta.priority;
    };
  };
}
