package docgen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// CLICommandView is the template view model for rendering a CLI command page.
// Separates presentation concerns (formatted strings, slugs) from the raw
// Cobra command data.
type CLICommandView struct {
	Title            string
	Description      string
	Long             string
	Usage            string
	Aliases          []string
	AliasesFormatted string
	Example          string
	Flags            []CLIFlagView
	GlobalFlags      []CLIFlagView
	Subcommands      []CLICommandSummary
	Slug             string
}

// CLIFlagView is the template view model for a single CLI flag.
type CLIFlagView struct {
	Name             string
	Shorthand        string
	FlagSyntax       string // Pre-formatted flag display, e.g. "--verbose, -v"
	Type             string
	Default          string
	DefaultFormatted string // Markdown-formatted default, e.g. "`value`" or "_none_"
	Description      string
}

// CLICommandSummary is a summary of a command for index pages
type CLICommandSummary struct {
	Name  string
	Short string
	Slug  string
}

// CLIIndexView is the view model for the CLI index page
type CLIIndexView struct {
	Commands    []CLICommandSummary
	GlobalFlags []CLIFlagView
}

// GenerateCLIDocs generates MDX documentation for all non-hidden CLI commands.
// Commands with subcommands get a directory with an index.mdx; leaf commands
// get a single .mdx file. The "help" and "completion" built-in commands are
// excluded since they're auto-generated by Cobra and not useful in docs.
func GenerateCLIDocs(rootCmd *cobra.Command, outputDir string) error {
	if rootCmd == nil {
		return fmt.Errorf("root command is nil")
	}

	// Ensure output directory exists
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create CLI docs directory: %w", err)
	}

	// Parse templates
	cliTemplates := template.Must(template.New("cli").ParseFS(templateFS,
		"templates/cli_command.mdx.tmpl",
		"templates/cli_index.mdx.tmpl",
	))

	// Collect top-level commands (excluding hidden ones)
	var commands []CLICommandSummary
	for _, cmd := range rootCmd.Commands() {
		if cmd.Hidden || cmd.Name() == "help" || cmd.Name() == "completion" {
			continue
		}
		commands = append(commands, CLICommandSummary{
			Name:  cmd.Name(),
			Short: cmd.Short,
			Slug:  cmd.Name(),
		})
	}

	// Sort commands alphabetically
	sort.Slice(commands, func(i, j int) bool {
		return commands[i].Name < commands[j].Name
	})

	// Extract global flags from root command
	globalFlags := extractFlags(rootCmd.PersistentFlags())

	// Generate index page
	indexView := CLIIndexView{
		Commands:    commands,
		GlobalFlags: globalFlags,
	}

	indexPath := filepath.Join(outputDir, "index.mdx")
	if err := renderToFile(cliTemplates, "cli_index.mdx.tmpl", indexView, indexPath); err != nil {
		return fmt.Errorf("failed to write CLI index: %w", err)
	}
	fmt.Printf("  ✓ %s\n", indexPath)

	// Generate docs for each command recursively
	for _, cmd := range rootCmd.Commands() {
		if cmd.Hidden || cmd.Name() == "help" || cmd.Name() == "completion" {
			continue
		}
		if err := generateCommandDocs(cliTemplates, cmd, outputDir, globalFlags, cmd.Name()); err != nil {
			return fmt.Errorf("failed to generate docs for %s: %w", cmd.Name(), err)
		}
	}

	fmt.Printf("\nGenerated CLI documentation for %d commands\n", len(commands))
	return nil
}

// escapeMDX escapes characters that MDX would interpret as JSX ({, }, <, >).
// Content inside fenced code blocks and inline code spans is left untouched
// since MDX treats those as literal text. Already-escaped sequences (preceded
// by backslash) are also preserved to avoid double-escaping.
func escapeMDX(text string) string {
	var result strings.Builder
	result.Grow(len(text))

	lines := strings.Split(text, "\n")
	inFencedBlock := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Toggle fenced code block state on ``` lines
		if strings.HasPrefix(trimmed, "```") {
			inFencedBlock = !inFencedBlock
			result.WriteString(line)
			if i < len(lines)-1 {
				result.WriteByte('\n')
			}
			continue
		}

		// Inside a fenced code block — pass through unchanged
		if inFencedBlock {
			result.WriteString(line)
			if i < len(lines)-1 {
				result.WriteByte('\n')
			}
			continue
		}

		// Outside code blocks — escape character-by-character,
		// skipping inline code spans delimited by backticks.
		// Also skip already-escaped sequences (preceded by \).
		inInlineCode := false
		for j := 0; j < len(line); j++ {
			ch := line[j]

			if ch == '`' {
				inInlineCode = !inInlineCode
				result.WriteByte(ch)
				continue
			}

			if inInlineCode {
				result.WriteByte(ch)
				continue
			}

			// If this is a backslash followed by a char we'd escape,
			// pass both through unchanged (already escaped).
			if ch == '\\' && j+1 < len(line) {
				next := line[j+1]
				if next == '<' || next == '>' || next == '{' || next == '}' {
					result.WriteByte(ch)
					result.WriteByte(next)
					j++ // skip next char
					continue
				}
			}

			switch ch {
			case '{':
				result.WriteString("\\{")
			case '}':
				result.WriteString("\\}")
			case '<':
				result.WriteString("\\<")
			case '>':
				result.WriteString("\\>")
			default:
				result.WriteByte(ch)
			}
		}

		if i < len(lines)-1 {
			result.WriteByte('\n')
		}
	}

	return result.String()
}

// generateCommandDocs recursively generates documentation for a command and
// all its subcommands. Each level in the command tree maps to a directory level
// in the output, mirroring the CLI's hierarchy in the docs navigation.
func generateCommandDocs(tmpl *template.Template, cmd *cobra.Command, baseDir string, inheritedFlags []CLIFlagView, pathPrefix string) error {
	// Collect subcommands
	var subcommands []CLICommandSummary
	for _, sub := range cmd.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		subcommands = append(subcommands, CLICommandSummary{
			Name:  sub.Name(),
			Short: sub.Short,
			Slug:  sub.Name(),
		})
	}

	// Sort subcommands
	sort.Slice(subcommands, func(i, j int) bool {
		return subcommands[i].Name < subcommands[j].Name
	})

	// Extract command-specific flags (non-persistent)
	localFlags := extractFlags(cmd.LocalNonPersistentFlags())

	// Merge inherited flags with this command's persistent flags
	persistentFlags := extractFlags(cmd.PersistentFlags())
	allInheritedFlags := mergeFlags(inheritedFlags, persistentFlags)

	// Build usage string
	usage := buildUsageString(cmd)

	// Format aliases
	aliasesFormatted := ""
	if len(cmd.Aliases) > 0 {
		aliasesFormatted = "`" + strings.Join(cmd.Aliases, "`, `") + "`"
	}

	// Get the long description, fall back to short if empty
	long := cmd.Long
	if long == "" {
		long = cmd.Short
	}

	// Create view
	view := CLICommandView{
		Title:            fmt.Sprintf("%s %s", "stackpanel", pathPrefix),
		Description:      cmd.Short,
		Long:             long,
		Usage:            usage,
		Aliases:          cmd.Aliases,
		AliasesFormatted: aliasesFormatted,
		Example:          cmd.Example,
		Flags:            localFlags,
		GlobalFlags:      allInheritedFlags,
		Subcommands:      subcommands,
		Slug:             cmd.Name(),
	}

	// Determine output path
	var outputPath string
	if len(subcommands) > 0 {
		// Command has subcommands - create a directory
		cmdDir := filepath.Join(baseDir, cmd.Name())
		if err := os.MkdirAll(cmdDir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", cmdDir, err)
		}
		outputPath = filepath.Join(cmdDir, "index.mdx")
	} else {
		// Leaf command - just create a file
		outputPath = filepath.Join(baseDir, cmd.Name()+".mdx")
	}

	if err := renderToFile(tmpl, "cli_command.mdx.tmpl", view, outputPath); err != nil {
		return err
	}
	fmt.Printf("  ✓ %s\n", outputPath)

	// Recursively generate docs for subcommands
	for _, sub := range cmd.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		subDir := filepath.Join(baseDir, cmd.Name())
		subPath := pathPrefix + " " + sub.Name()
		if err := generateCommandDocs(tmpl, sub, subDir, allInheritedFlags, subPath); err != nil {
			return err
		}
	}

	return nil
}

// extractFlags converts a Cobra FlagSet into sorted CLIFlagView slice.
// The built-in --help flag is excluded since every command has it implicitly.
func extractFlags(flags *pflag.FlagSet) []CLIFlagView {
	var result []CLIFlagView
	if flags == nil {
		return result
	}

	flags.VisitAll(func(f *pflag.Flag) {
		// Skip help flag as it's always present
		if f.Name == "help" {
			return
		}

		view := CLIFlagView{
			Name:        f.Name,
			Shorthand:   f.Shorthand,
			Type:        f.Value.Type(),
			Default:     f.DefValue,
			Description: f.Usage,
		}

		// Build flag syntax
		if f.Shorthand != "" {
			view.FlagSyntax = fmt.Sprintf("--%s, -%s", f.Name, f.Shorthand)
		} else {
			view.FlagSyntax = "--" + f.Name
		}

		// Format default value
		if f.DefValue == "" {
			view.DefaultFormatted = "_none_"
		} else if f.Value.Type() == "bool" && f.DefValue == "false" {
			view.DefaultFormatted = "`false`"
		} else if f.Value.Type() == "bool" && f.DefValue == "true" {
			view.DefaultFormatted = "`true`"
		} else {
			view.DefaultFormatted = fmt.Sprintf("`%s`", f.DefValue)
		}

		result = append(result, view)
	})

	// Sort flags by name
	sort.Slice(result, func(i, j int) bool {
		return result[i].Name < result[j].Name
	})

	return result
}

// mergeFlags combines two flag slices, deduplicating by name. Used to build
// the full set of inherited flags as we recurse through the command tree —
// each level's persistent flags get merged with the parent's inherited set.
func mergeFlags(existing, additional []CLIFlagView) []CLIFlagView {
	seen := make(map[string]bool)
	result := make([]CLIFlagView, 0, len(existing)+len(additional))

	for _, f := range existing {
		if !seen[f.Name] {
			seen[f.Name] = true
			result = append(result, f)
		}
	}
	for _, f := range additional {
		if !seen[f.Name] {
			seen[f.Name] = true
			result = append(result, f)
		}
	}

	// Re-sort merged result
	sort.Slice(result, func(i, j int) bool {
		return result[i].Name < result[j].Name
	})

	return result
}

// buildUsageString constructs the full usage string by walking the parent chain.
// For example, a "start" subcommand under "services" produces "stackpanel services start [flags]".
func buildUsageString(cmd *cobra.Command) string {
	// Build from parent chain
	var parts []string
	for c := cmd; c != nil; c = c.Parent() {
		if c.Name() != "" {
			parts = append([]string{c.Name()}, parts...)
		}
	}

	usage := strings.Join(parts, " ")

	// Add the Use field's argument portion if it has arguments
	if cmd.Use != "" {
		useArgs := strings.TrimPrefix(cmd.Use, cmd.Name())
		useArgs = strings.TrimSpace(useArgs)
		if useArgs != "" {
			usage += " " + useArgs
		}
	}

	return usage
}

// renderToFile renders a Go template to a file, applying MDX escaping to the
// output. Used for all CLI doc page generation.
func renderToFile(tmpl *template.Template, name string, data interface{}, path string) error {
	var buf bytes.Buffer
	var safe bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
		return fmt.Errorf("failed to execute template %s: %w", name, err)
	}

	// escape
	safe.WriteString(escapeMDX(buf.String()))

	if err := os.WriteFile(path, safe.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", path, err)
	}

	return nil
}
