# ==============================================================================
# per-system/shell.nix — Build devShells.default from evaluated stackpanel config
# ==============================================================================
{
  pkgs,
  lib,
  eval,
  extraPackages ? [ ],
}:
let
  inherit (eval)
    spConfig
    allPackages
    stackpanelSerializable
    allSerializedPackages
    ;
  devshellOutputs = spConfig.devshell;

  hooks =
    devshellOutputs.hooks or {
      before = [ ];
      main = [ ];
      after = [ ];
    };

  timingEnabled = (spConfig.debug or false) || (devshellOutputs.timing or false);
  wrapWithTimer =
    label: hookStr:
    if timingEnabled then
      ''
        TIMEFORMAT=$'time ${label} completed in %3Rs'
        time {
        ${hookStr}
        :
        }
      ''
    else
      hookStr;
  timedHookList =
    phase: hooks':
    lib.imap0 (idx: hookStr: wrapWithTimer "hooks.${phase}[${toString idx}]" hookStr) (
      lib.filter (hookStr: hookStr != "") hooks'
    );

  stackpanelHook = lib.concatStringsSep "\n\n" (
    lib.flatten [
      (timedHookList "before" hooks.before)
      (timedHookList "main" hooks.main)
      (timedHookList "after" hooks.after)
    ]
  );

  profileEnabled = devshellOutputs.profile.enable or false;
  profileDrv = devshellOutputs.profile.package or null;
  shellPackages =
    (if profileEnabled && profileDrv != null then [ profileDrv ] else allPackages) ++ extraPackages;
  allEnv = devshellOutputs.env or { };

  shellHookContent = ''
    # ================================================================
    # Stackpanel Shell Hook (wrapper)
    # Generated by: nix/flake/per-system/shell.nix
    # ================================================================

    __stackpanel_shell_hook_main() {
      if [[ -n "''${__STACKPANEL_HOOK_RAN:-}" ]]; then
        return 0
      fi
      __STACKPANEL_HOOK_RAN=1

      ${lib.concatStringsSep "\n" (
        lib.mapAttrsToList (k: v: "export ${k}=${lib.escapeShellArg (toString v)}") allEnv
      )}

      ${stackpanelHook}
    }

    __stackpanel_shell_hook_main >&2
  '';

  shellHookFile = pkgs.writeTextFile {
    name = "stackpanel-shellhook";
    text = shellHookContent;
    executable = true;
    destination = "/shellhook.sh";
  };
in
pkgs.mkShell {
  name = "stackpanel-${spConfig.name or "dev"}";

  packages = shellPackages;
  nativeBuildInputs = devshellOutputs.nativeBuildInputs or [ ];
  buildInputs = devshellOutputs.buildInputs or [ ];

  STACKPANEL_SHELL_HOOK_PATH = "${shellHookFile}/shellhook.sh";

  shellHook = ''
    source "${shellHookFile}/shellhook.sh"

    if [[ -n "''${STACKPANEL_STATE_DIR:-}" ]]; then
      mkdir -p "$STACKPANEL_STATE_DIR"
      ln -sf "${shellHookFile}/shellhook.sh" "$STACKPANEL_STATE_DIR/shellhook.sh"
    fi
  '';

  passthru = {
    stackpanelConfig = stackpanelSerializable;
    inherit stackpanelSerializable;
    stackpanelPackages = allSerializedPackages;
    devshellConfig = devshellOutputs;
    packages = allPackages;
    env = allEnv;
    processes = spConfig.process-compose.processes or { };
  };
}
