HELLO: ENC[AES256_GCM,data:jPBgHM4=,iv:bKBMY/bFEaWmX0BLKYBqvNQ4J+UK0kSDCLoTIgl2fjw=,tag:evy3TmSLry/XG31eVxiZLQ==,type:str]
sops:
    age:
        - recipient: age1sy6t7kdeyf63mjnrdnqm08rjv2s5ddexgncuq4ps6z4c5hgg4dzqp6pznq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK2VzV2loYnR5VXhsM2l2
            akNjWnpuYW8va0lEemM1VVVJQ2JxVjBCUFdNCjl3MkpkM2xHN01Dd1dKNU91SDZS
            TTN5WFFINlpWdlZsN0R2U0JNaW43STgKLS0tIEkvaWVjRmdJMmlqcFlGWDJOMnJG
            Q0d1aUZvMGZmUGNlVWE1Y1FCdmRWTlEKHCPyL687r5qLW5N8ZTChQcmSDtYETFYs
            GXHIzsQ+JRsmSPiuCbG/zhNJRaTPoQZ7rTEt629XkDOJUQo4WPRIjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14vpdar7vzznyxgskp9772zjar95n8l2f36w6tzk980889t7kjdqsc5a50q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWHovbTloVzZac29tZUNG
            blkyaXdiMUUxTDVHdjlzdEVMWTlzanFPdVd3CjI4Qk41TDk3U1phdGUyUzB0cU82
            ZFRqMEU4aW8zT1JkcHpjL0FqWnN4ZkEKLS0tIFdRajhiT3NjcGJxUENQQ0ViYkJn
            VkpmUW5OMGVxY3VzVzgybEZKWjBXcW8KFcVcHEUl4eKxr2Z7mC6VDoqU0BGd2Z1O
            c2LBvdAAKYdquZNLUjA75wws1NqYqKAlzg2yn83VWlHsyjIQyHsjoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ph0gtrpvus5y2kl5t5wnmlcjpevavxf4l2aagrqyp7nng7jvluus959fvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweUZvTU0vNkpyWmFSTlFy
            SnJiQS9KczFBRWVka2s1c2c3Rjkya2ZnM1NzCnc2eWpZa2R2UEhMbktSVVVMSnhG
            dzIzbXlZNmhyRHo1eDN1dnBTdWVKVDgKLS0tIG1wYWVPcU5TSUdtcFpiNlU4b2Ru
            RDQ0SFRYeTVXbFcwYlIyazhqK09Oam8K4OT1jt6BwknQWnJbg94YzzgVLWg0UwT2
            WF4E6dcxNwHknoGuY149D216eTz7/jzAuQcseXv/r8WCUBKzBV4O6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fm7zr0ea3d589tkgcz2klqgnajduzkr25e8tnhh7qxzuleqxq3yq3c0s3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTC9LQUxvMnNsS09uRzQw
            OU1DY0JxWHk2OGhoWUN3OGlqSmFzaUNVR3k0CndqZ3RuMWFSdnMvSEgwN1hxL1Mx
            d3Z2UHhTcDA0dW13c3RVRVFxVXI1SFkKLS0tIGx1K3ROYTdXc2dpODhkeG4zblln
            c2t0Qm9Sck9YYzJndDBneXVLY0M4WkUKsx6blxWAZBX4LfIOJdXNX1/zFW0EPVLT
            SbdOqYdTT13pZ3zv8OiwCi5IIP8pRBQcicqqaV5vajWC+W+GlPLiaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h0nv9lwkkhd9y0rlf832g3lualvjafqpyvlkgf8d0cn6c4zg959qkrfzt3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTUJHaVZFem5SVDIreElW
            Q0hFeGcvQ2dwRkp6YngrTmpHTCtWSlVzYlhrClZIVFZmT24wOWx6ME0xazQ5QU54
            Rkp5THR4Q1BuUnZIMXdXNDF0eW53enMKLS0tIGlqdXJJUmZlNUdDc1hNak9OUGtq
            R09tNmlWZWRoYTVBRGhhT3d2WDIrelkKs+cAt8+GMT6PpcAOnVLpqn1X96L3o1QT
            XbnMGlC1cv6/hAQBUIwld5jztK9mkp36NwTBeXUMNr06i+sXMQp2NA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dwqnyurvm7vasf9n7alduzmg79nczkuafknr8x3l4jnzwnuzzydqj0y92p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcmJyNjZ2YlBhZ1MreHR5
            bHBnK21TUjVDa21PS2FRUWY4bnJaM1pJakRZCjJKN3MyZ2lSSW5Fd2djZ3NLUlFq
            QWdEeXEyUUtYNENzTkZZL3o0TmJ3Nk0KLS0tIFMrVzMxQktjR1RwZmQ4R1VEZHlB
            N1VRVGhLQkthSkJEYk5yWGVPVDl0R0EKGFF0KARIR+ic6PP7+xXsTNHyrKlwNZuo
            FiR3qDZ4JhbeW8sMPLqCkrQtXwzPPYSCZn9CLofHy84pb//lxD7wZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yuh8vhakrwn2nm4dzxmdp99cmvl3cd4af36p5w2v559263a4uy4sulpn60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTmw5SnArcVJMeTI5SW9W
            ZmZCSlpvRjNSUVM2M2g2eVJIMUV4azZDUlFrCit2WUJTZGJENDlLWVZOSURpUitm
            TEh6eEp6enQySjZmZnplRzlYNFk1WU0KLS0tIEtyNXJJZzBuUnM0QzlRNmJFamNZ
            eGpDNFIxZG9NWnc2YWhoYmpNT2VGbGMKHm7QwkrnyN4KwWDaezMUYluxGGQigvPR
            45LLcgAKuRCAmYEDaVrSURoInIuZv1CBQ/5s88s0ZaJAGA0zQLa6ig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ugmyh9qcz05ehtkgnt2nn3jfz2rf2umnmqx69pgp2ue82dn7vpuqlc3g7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbkRtajRTTUtRb2JOTGdr
            Uy8rQWRwUCs2S1NVYUlpVFNKNlJRQ1FhSUFZCnVmWElVSjBwWER1ckJ2Z2xoWU9y
            dFhCYUppQzI4TU44R2tSMUdvcEIyUE0KLS0tIDJEb2pmcFNYdkJVb0Znb3o0MEkv
            YTdKTnUybzFQR1JmR3ZEUUo1cmZLbGMKdqj3wDiXipIKqSG7eu2r+na6Q3Vik/Hk
            D5yFCNc4a5meme7PYn4y7EquSqrvwiKHqF5VgJ68P7gsduw4F1y9HA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12vnpyjwhnnm85vktfmg6jwzn55fcg0lmgn6q0wx2z4wawnwgm5cqt6yf2f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYm55TEdKY2FKYzZvYS9y
            OFdRbHFtaFhJQklheVNJc09HeXRjQlhQM2xZCkd2TG1sZXhqL1Y1VkRKSGVOcHQ3
            T05jN0hBNXppTjRTL1VseFU3SVNjajAKLS0tIEh4Zkk2N0NNbFdZM2pNRllrMERO
            SWpwZHpab2dVZFhuSDdHNFh0L2RqWVUKsKBVjVdWA3xzNLlRuLX7QSMeLB/jybkb
            rgVO9W2/Dfr9qTHRfZ7t8z3iWTxJvtOezsHxiClsmw38JJZsxc8+zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16ymszt6hmv7p3w596w5wlzng7wgk6mwcchr8s2nvwutnx2nrzyqsvn678s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ043RmcrWW5STEd1QU15
            WHIvSkxKVmU0ZnBhSzZvcWlzRVM5dlNOTEhVCnpsTzNuWUhWQnphMHhUZEVrMXZU
            MWcwTW5USE4xV1hreC9FejB6eDErVWMKLS0tIHNhK3EydlIwOGY3d0JNaW9pUkha
            eWlrbmdVbm94eEVBTUdUcjBqNUI0R1EKM6ekCTpkxY+K6wyHyQ/736mbHIaZyiOg
            pCoFrmOjGPh6v3zbzP4z2TT1f/qnI3jddeV9p/G7My7Yy7Yz09Ipzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ruav09tz635tt3sgq55pgn83qnte0j2nx0jd6gvjxelkqqdtygcqgcam2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTEpmTkl6RHdOWEtQQ0dF
            d2t0Ym1KWjg2b3YvYjRTK1BtRGlsWStOcERJCnc5cGVMQ2JpMlp5anhNUUlSQmps
            ekhiSGppWS9TdnBERUJIazRPOEdVb0UKLS0tIG1YaFl2RUhtZTliNWxhcFF0cGQ3
            bnZ6K0N0T3J1SkhWVkI0TG9RSVQvVnMKGkRaf4c+ygp6116ZS3weyzTnUnURzy58
            C2tYWfBUMRfTvApQX8LKhmiLVGfzrEEp7RsRO6sTx/MVbF2pU8anvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17dh936q0l622ez7m0zfak46awqdx35hldqzsfnh72cgtcthlhg4qdl74fh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUE5TSVhwd1hOS2dSZmdO
            S1hJNGtmbFRienN4TzZtekxKeDVER0NleWhzCjdOVHhpVGZ4cjQ5bkFqRTNvMXlr
            NGsxU3VXT0R1OXFxWE9GY3pjcEwzKzQKLS0tIEZFUE4rZnROTXlZUUtXQXdnanpt
            NHUxUXlpcU51dllPVHZaZWpIOTduN2MK+jjMiSLveBrrkthc1/unqxUhOILMbGBw
            /UYZqiIz5oRLWV9HJYgqv5tC0sYc8uR+dl1YbTjGoVgFSa9QL+CENQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T23:25:29Z"
    mac: ENC[AES256_GCM,data:OLOiyENG9b/AmC5Q16/u6HVuh2VDBjvuD03zSyW5m+ezuRBmU/dOmkYjb2iT0uFFskzzcbOipX0Fgc8IG+mpmnlwqOokPuhcRITHDZe4Uwe1YZCBPvMnwYXv3yQ4jI7g8gpvOW8cNNEjd9wIyT2Ft1Wuv0VBceN8hhdCt16xoB8=,iv:35JBPuvupV+zOOSZjWOyhFVba7pRoEJND/OMDmRrpDw=,tag:qxKBU/YRhUroZHM/iVaAiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
