HELLO: ENC[AES256_GCM,data:vuh8iQQ=,iv:PT9jMJOQD42i9LjfzEW8ct7GaYZLgU1ri/eMZeU2+f8=,tag:FU/3mRVsBLjtdKHGa7pVwQ==,type:str]
sops:
    age:
        - recipient: age1sy6t7kdeyf63mjnrdnqm08rjv2s5ddexgncuq4ps6z4c5hgg4dzqp6pznq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUtPcVV5ZXZiMXUyQkFu
            cFBhZWVaemwrNDBWczUwTUtBMlBDRmcvaERJCmxGUGN0YUxndFJJNVhHT2QyY1Bw
            Ny8wdlJKQk55VmQwUEk0ZnRESnpYNk0KLS0tIHFzSmJMT0RNc1BiVjE3bGUyMXc3
            eFAzdkwwR1NKaGUxTFlYNWlZci9zMmMKtKLgoW65JppcUa31kCCgaENF2wMzhrlO
            AL7CmxbX9WKedQ+40zniZzLBwktfLeFCKKANhDvAKwWOU2hK5aNBlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14vpdar7vzznyxgskp9772zjar95n8l2f36w6tzk980889t7kjdqsc5a50q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TWxza0ZaQVJsUEhNUGtk
            QkNheDc1Y1l3N1hMelp2ck5WaUlkTUNuWnlzCnFtdVdKcU5YOHFFOHpjZU1hSGp6
            Wkx1dWtSU3dkSlRiS2RSS3IzM2IvSjgKLS0tIFJWcDMzM2FUNW9SUGUrdWxVUExB
            NXJOTXhoNHp4TERvZ3I2SmxiSHFmL0kK+fvdBxqsFi3WFkekJ2wHvCyp2EHJbAW9
            oi/YNXh7sR/APsZomYzULtKsu+r128i+wjTUcgM1kkbOKwGferi0SA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ph0gtrpvus5y2kl5t5wnmlcjpevavxf4l2aagrqyp7nng7jvluus959fvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcFcyeU1BcEtmT2U3S3VS
            YUpwYXJKbTY4TlRaZmRrbXhwR0xLZmQ3WjNzCmY0YmhCU0dycU9LQkVGOEpPVUo2
            ZndqOTlHUDFCcHI2dXJsV245WlZYT3cKLS0tIGp3OEQvMGphTmxkQkw3NGZSOGhs
            SWhGTUZhc0d4Z0VkT05sTllKeTAxM0EKxBRxszkr/688BG72t5DEZWrZkdo2DGAf
            cxlt8DkQBk8nhGfW0pTlT6ho3Oteuhq8nYhmTabKTtpCAnUiYf/W/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fm7zr0ea3d589tkgcz2klqgnajduzkr25e8tnhh7qxzuleqxq3yq3c0s3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdmxPRXNvVVRvODY0WWhp
            RWpEYWZhaXhzM3ZVa0JuQlJkZGNBeTVoS2tZCmkzbjdtUEltak9iWURtTWp5MlMx
            aXl1a05yL0pZVGZUOGZ1YTc0bVljRDgKLS0tIEluckV4bzFYVjN5ZTN5U3oyQi9w
            anZ5OXpibzFSMmhnUnJVOWJoT20rMEkKgLLzg5/lvjrWjrIw814hjgJ0NK/ZwLgf
            Z/e6PBBsvVUMz19Yi/45FtWfza/LjScXdaACezgvlGftubJ98rulrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h0nv9lwkkhd9y0rlf832g3lualvjafqpyvlkgf8d0cn6c4zg959qkrfzt3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZHp3eGxDNWJhUHNUUUpw
            RXp0eUF6SWIrZURsT1puVWw0amRrSXUzUmlvCnJaNHJ2TUZ4QVIyUEtiaHpKMS9t
            d2NReXYyU2EvQ3I5ejI2RmdERUs3ZmcKLS0tIEc0bTRZR1ppbStVMmc1TzlZOFhJ
            S2M3eWRTVzJOcjQ3a0UrYjc2a2s0blUK4KZs5a0QSMAfpF5ZBIt1AviZc4i6ClI6
            A9TofwSI4kP4KpmCFgq1zUpr0v2rPsBZbz1vbuK67wmM3VLCy3w9jA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dwqnyurvm7vasf9n7alduzmg79nczkuafknr8x3l4jnzwnuzzydqj0y92p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU2xxS2RBR2JhNkl6aS9G
            MnpWY2NXWGprMm9ydVdoSWNBNHdUVzN4THhrCnZCSjJ6emwzUysvSUZuNFR2NjNL
            RVlPSWJjTm50VlducHFwZjJxV0hySXMKLS0tIG1aaFU0Uk5ka2V3bVhhZHl4VXdW
            STZHbFZjYlNzRE1QQ0dKREhJcVVUZ0UK9xheZz5zRfjJdn3iXqnfErgvNYuvF9de
            3EDQ1w6Lcby6eiixnNDZH8w0dmVq72KqRdkfhD9B9SDuVEGBXghQCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yuh8vhakrwn2nm4dzxmdp99cmvl3cd4af36p5w2v559263a4uy4sulpn60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSjBEU0t6cVVlR0VsaXhL
            ZzVmRGNPOElycnNDVVEzaXgzMEVtRE4wTUZNCjdRYzVlVHBZNGdvVEhRUmFDaWgz
            RVh4MWRPN3VybUtGRmd6VktZV0o4M28KLS0tIGx1dk40QVpUbHpabzBKYjlmaGE5
            b0czZUp4d3E0b05Wb2syNWkzZUYxbDAK7X4s593NJFsDBzkVKaMRondc5z3zkkBX
            l5KKNByvruRR5/94zzrtKJyrH80t+iYjFkn4BjUNEl4QFlpxiMfWag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ugmyh9qcz05ehtkgnt2nn3jfz2rf2umnmqx69pgp2ue82dn7vpuqlc3g7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TnAvZm1JdEVMZmRBVkx3
            WkNDQi96S0M3cG56V000UnpCT3NUOUZOYlVVClJ3UStPT0pmcTZSVVF3NFI4VDVv
            WkZvNytqb2NrSFo1Z2FNOXhwSTIyQWMKLS0tIHlCTkw5eHZRWmZ2Z0crZllNV1Bi
            ZUUrS0JzYm55VUc5UGhrN1hpZXVxY0UKlPwW7iVa022JvkpsTBlnRNTU+JNAt71o
            Yop/mexJlzgzNfBWiIcrZFaUT9SU04SFzJVema7WHz0Io0Xg3j/a/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12vnpyjwhnnm85vktfmg6jwzn55fcg0lmgn6q0wx2z4wawnwgm5cqt6yf2f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbmV2NTNzak9tZTFnM0pD
            ejUwalcxSEVJVmVaRFpUZEVxSHl3VnVCeXdVCk1UT1lMaDJxQTFUdFNtOVNJMEpZ
            QU14akdkQ1J1ajB2YW5mNEFkU01GQVUKLS0tIElncEV1eHZ2OHhvcDFpQ3AvM2Nj
            THRHRzFZaUVOTDJaUERyUytwUHFRMTQKMM3QZTgjAmvJz+sHecMto5cG9gZuTOtK
            pP6TIP23VwMthctqepjUqorbEFiPexUsiLgVfzX5/94oODcZr5oO+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16ymszt6hmv7p3w596w5wlzng7wgk6mwcchr8s2nvwutnx2nrzyqsvn678s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXY29PeHlzTUFRNkN0NGdx
            R002d2xxSnlmdFpjeU5ObU5VNzB2ZWRURzBFCjhKbm5HQWhrYURwMDBoYWR1eGll
            RnlRZDlCNjluWXBod1lCZ3F5V3FwK2cKLS0tIFBMSU9qT0tRSWNWeU81ZkR3VVZP
            cC9EVTQzUGhiWkFtczJVV2V3eG85WVUKTy5282ao7oejyA04yh1KIyOf7WjkSzQb
            QTWwZhLmWYLCq+mwHufGurvjhnjkxTMUXLRX12nEw+MRHH+hwIeD/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ruav09tz635tt3sgq55pgn83qnte0j2nx0jd6gvjxelkqqdtygcqgcam2t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYWdEd3FoWUdJdE53aU9t
            YzQ3eGRvTlBwbEpDMjlMMHUwNlk4bWU3QlZFClRta2dXZko5OFcwVGZxaXh0cEc4
            Nk84NWpNWHpNYzJ5WEJQSCszWmU0THcKLS0tIGVJOUlKdWNnMGFQSkl0alZ1RGdV
            cTZoR0JpNmJYYTVUUWVoc2IycW04NVkKDIMnbg7cfn7rA7CeMT2q21UR1w4r9TVb
            d3FmlVXjFnVhvNz+ln20jgaG03HgVbg52SOQcNvWQUvpL/4cw66nyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17dh936q0l622ez7m0zfak46awqdx35hldqzsfnh72cgtcthlhg4qdl74fh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQlhrdFBPZ2haQlY4Q0Jy
            ckI0ejVmTnA2NWVXOW5WNURoZDhXVnVEeVNFCmVxYzNxNWNHR2dXMEJlSVRXdU1F
            WEhUaDJ1RnprMTFBdW1IZE9XTSs1VzgKLS0tIG94T3p1S1MyS25uOVlMQmo2UW1Q
            QjdoY2c2WlpHaGJ1MGFkUVBNakpPc1UKJUbdwOn9w6QZpxmAkcRNbq+MiGUm25IA
            R/w1TdqspNbPQLnsX/Vj80GogwzL516MDJ8Ma1VG7IZ5/ZjNpl+QeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T23:25:29Z"
    mac: ENC[AES256_GCM,data:NLCMDHMoywqMLPgm4NVegg9FRY+a6eh46N9ughTFkfU+N+p3UzN3S+LAoAEv3y2rkCwoy1cEGgzjmf+yVatIdgtuYS7yFJW3gqFsKo+p35R993qWcIArwolylhgF4E1lscSFOHTv6YNLQ39nz7XzTrVLYkbO/7bqQfEijveHCWk=,iv:IgJwo6DVNLMS7b8OtCLmEe4h6rdY/QCvlvpvFrGCrsI=,tag:++rensxjN1GZkHWxY1ZbMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
