// ==============================================================================
// @gen/alchemy - Shared Alchemy Configuration
//
// Auto-generated by Stackpanel -- do not edit manually.
// Regenerate with `write-files` or restart devshell.
//
// This package provides a pre-configured alchemy app factory and shared
// helpers for all alchemy consumers in the project.
// ==============================================================================
import alchemy from "alchemy";
import type { Scope } from "alchemy";
// @ts-ignore
import { createStateStore } from "./state-store";
// @ts-ignore
export * from "./file";

// Project config embedded at codegen time
const PROJECT_CONFIG = {
  appName: "__APP_NAME__",
  stateStoreProvider: "__STATE_STORE_PROVIDER__" as
    | "cloudflare"
    | "filesystem"
    | "auto",
  cfApiTokenEnvVar: "__CF_API_TOKEN_ENV_VAR__",
} as const;

export interface CreateAppOptions {
  /** Override the default stage. Falls back to STAGE env var. */
  stage?: string;
  /** Override state store configuration entirely. */
  stateStore?: (scope: Scope) => any;
}

/**
 * Create a pre-configured alchemy app instance.
 *
 * Uses the project's centralized state store and app name configuration.
 * All alchemy.run.ts files should use this instead of calling alchemy() directly.
 *
 * @param name - App name override (defaults to project name)
 * @param opts - Additional options
 *
 * @example
 * ```ts
 * import { createApp } from "@gen/alchemy";
 *
 * const app = await createApp();
 * // ... provision resources ...
 * await app.finalize();
 * ```
 *
 * @example
 * ```ts
 * // Override name and stage
 * const app = await createApp("my-app-infra", { stage: "prod" });
 * ```
 */
export async function createApp(name?: string, opts?: CreateAppOptions) {
  const appName = name ?? PROJECT_CONFIG.appName;
  const stage = opts?.stage ?? process.env.STAGE ?? undefined;

  return alchemy(appName, {
    ...(stage ? { stage } : {}),
    stateStore:
      opts?.stateStore ??
      createStateStore(
        PROJECT_CONFIG.stateStoreProvider,
        PROJECT_CONFIG.cfApiTokenEnvVar,
      ),
  });
}

// Re-export alchemy core for convenience
export { default as alchemy } from "alchemy";
export { Resource } from "alchemy";
export type { Context, Scope } from "alchemy";
