// ==============================================================================
// State Store Provider
//
// Auto-generated by Stackpanel -- do not edit manually.
//
// Provides the createStateStore() factory that returns the appropriate
// alchemy state store based on the Nix-configured provider.
// ==============================================================================
import alchemy from "alchemy";
import type { Scope } from "alchemy";
import { CloudflareStateStore } from "alchemy/state";

type StateStoreProvider = "cloudflare" | "filesystem" | "auto";

/**
 * Create the appropriate state store based on the configured provider.
 *
 * @param provider - State store provider type
 * @param cfApiTokenEnvVar - Environment variable name for Cloudflare API token
 * @returns State store factory function, or undefined for filesystem (alchemy default)
 */
export function createStateStore(
  provider: StateStoreProvider,
  cfApiTokenEnvVar: string,
): ((scope: Scope) => CloudflareStateStore) | undefined {
  switch (provider) {
    case "cloudflare": {
      const token = process.env[cfApiTokenEnvVar];
      if (!token) {
        throw new Error(
          `State store provider is "cloudflare" but ${cfApiTokenEnvVar} is not set`,
        );
      }
      return (scope) =>
        new CloudflareStateStore(scope, {
          apiToken: alchemy.secret(token),
        });
    }

    case "filesystem":
      // Return undefined to use alchemy's built-in FileSystemStateStore
      return undefined;

    case "auto":
    default: {
      const token = process.env[cfApiTokenEnvVar];
      if (token) {
        return (scope) =>
          new CloudflareStateStore(scope, {
            apiToken: alchemy.secret(token),
          });
      }
      // No token available -- fall back to filesystem
      return undefined;
    }
  }
}
