# ==============================================================================
# variables.nix - Workspace variables
#
# Variables are simple id → value pairs.
# ID format: /<keygroup>/<NAME> where keygroup determines storage:
#
# Keygroups:
#   /dev/*      - Dev secrets (encrypted in dev.yaml)
#   /staging/*  - Staging secrets (encrypted in staging.yaml)
#   /prod/*     - Production secrets (encrypted in prod.yaml)
#   /var/*      - Shared config (plaintext in vars.yaml, NOT encrypted)
#   /computed/* - Generated by Nix modules (read-only, not stored here)
#
# Values can be:
#   - Literal strings: "3000", "debug", "https://api.example.com"
#   - SOPS secrets: "ref+sops://.stackpanel/secrets/<keygroup>.yaml#/<NAME>"
#   - Plain YAML: "ref+yaml://.stackpanel/secrets/vars.yaml#/<NAME>"
#   - Other vals refs: "ref+awsssm://...", "ref+vault://...", etc.
# ==============================================================================
{
  # ---------------------------------------------------------------------------
  # Shared configuration (plaintext, NOT encrypted)
  # Use /var/* for non-sensitive config shared across environments/apps
  # ---------------------------------------------------------------------------
  "/var/LOG_LEVEL" = {
    value = "info";
  };
  "/var/API_VERSION" = {
    value = "v1";
  };

  # ---------------------------------------------------------------------------
  # Development secrets (encrypted in .stackpanel/secrets/dev.yaml)
  # ---------------------------------------------------------------------------
  "/dev/OPENAI_API_KEY" = {
    value = "ref+sops://.stackpanel/secrets/dev.yaml#/OPENAI_API_KEY";
  };

  # ---------------------------------------------------------------------------
  # Production secrets (encrypted in .stackpanel/secrets/prod.yaml)
  # ---------------------------------------------------------------------------
  "/prod/POSTGRES_URL" = {
    value = "ref+sops://.stackpanel/secrets/prod.yaml#/POSTGRES_URL";
  };
}
