hello: ENC[AES256_GCM,data:LESQ+Aw=,iv:5/OBLIl+lGSkaGZJrR6Y+W1mZS1fRLsLVBzxEhUQIUA=,tag:alKLASvlb6D1KhYVPYaE4Q==,type:str]
sops:
    age:
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRZy5oeMfqhk91usPMfWM3qZjOu91mhxP5FNISekFeUuHVWciOTjObUquvXcBXPBECsMkkHCuBVW01usaqvMWl0fGGs6oV0oHBjMVNoNTR8PoXklvXQyTVKH4XDHt21guAZcdIyAWrcjGaUbCotN8gbBQ4qJe8EgVrwOHBiIwKzQT8SQKJAkbwLFmQpHfcSpibr/h/UDuEpgKv6dKE5TNiEKdWKYYbCFei98A1Vax56HXVQKVZmzz0WrH3M5uLVi4BG0Ed1o6IjhBl2iJOBNZpuK6N44mc0wUQcqKwshinDPprstfaV5vYsB3U2nDLeNaO1yvOXkOA+PqGeu5Kx5k3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgdFJPbGx3CkYxRmF1cytv
            ZUpvdmh0eXlodm1QaGFtUm81WFRXalhQMHFuOXl3MU1EN2FKMjdwSkEyRFROdXI3
            cElGZ3c2MFgKMUhQeVFXdko5Mitsbnp1UGF4UEtDWEJWd2F5SVYrcjdmY25VaDIv
            ODlZSGcvZDlUMkMyNG9QZzR0cDJYc3R4MwpiRmkxMHBjZmJSenZHOXEvL2ZoSnpv
            ckx4aStweFFOT2M2WkFTOGRGRWJHZnRRWHNJcXFNdXNWOHpBSXppVTRQCjhnS05I
            OTVLUHlHZ1NXNkVkTTAxa0c3cU1LQkNhd1dLV2l4MVkzelhOUVdwZ3owRDdYQzJZ
            RERBeU1hc3dpdmIKVlU5ZENXRGRJdGR4bm44NzZtWHpZWGZSWkhLVWJUSktXY2tY
            SnRJazgvUFpTbzU5dWg4TER3Z0x0ZWsrK2Z0ZwowZW9KUXBvRnlpcEZoZENUY2hX
            OC9nCi0tLSBtdk91TGZNVVhaZFprWnl2OUpIb3g2SU5GcW1BVW5mQktHSm1jV1ly
            cnYwCgTN9UguWHPx3qiibAitQJ0CThBd7jAdj9k3mwSLe9khVRr3rGErFTW1MRbQ
            f71xiuqV6lyMiIIMxW4YxkbU6LY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJiwo+71EEnDQfxVjnRlB5Ofpg6fPTFB80W5TQh+TgoKpxTsFqjvukltmnOT8kCFv11KE3QU5LWt70WNOseCS5xTY940SWBZA7zeE7ed4/CCyNP/O2DcCsoc6iIkaSegcrIcOe5Ei1nxMr0F/84GiX06tvD6r56jmu2Teer7ty7baKEjplbT+bEnfNvjMRzvcttzI3Cp6OzvZvrnv2yXm42fw380SU1H9y7uVcAYDZNPiBv0sLue5HxqDW3InQYs9fkuH5hJdLHRhBgvcczVW31fc2P9imLA3IPLF4hNNndS32dKZwfhnhwDaIEUWSwhVqZcQNZZg6P0NFU25aSzcB/FDKrTRoJQBaM4YSCsL4K0J2NI3cFDi64sP35XfcWif/DwtcmmCmxlOO7721fhOO8VwYpZXyeoYt62+EHnCqaQp0AK80hGVco0ZUraoqwnZ8YbJmzpVC7so1bJWncTCutJmgeMDdEyLWRoBV6HUx8wJUVqylQjE3OijgBHa1lxE=
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgTXExV2JRCk1remsvd29Q
            RTd0QlVWWTJMU2F1WW5QNnc4cFZJaitaQ0JNSEJqTDNnQ3I2bzFVaWlNV3dWYUNa
            NEZFMXkyRkcKcXJwZ0daWTdmb0pDNTV3cTNsblQvUnk1WWZHV1d4a3d1dTNYUUJV
            ZXdydEtqbUYxYm1mYm14SXRmMzNVRDE3SApKc04yL0FZeFRqZHdZVVR1NEtxU2Ni
            NWpWZkd1dUl4TnJ1alRENno0b3IwdEoxTUJSVkpWandycXNtQnNaUFM5CnpKMDdT
            SmVFTC9kRGRaSXNJL2packdyQ0JDNWN1YTJQOUw2ZE84Q3Zja2hkZXB0SDRGRzlP
            RWg4d25rQjFhbHoKRnZrekpEcGdSRWtkbjVob2dkblJPUGpvcnU3RG9FSHhZWGhY
            STAyandGMWlDVWI4OUc4QndyZ0laMkdvTG1JZAp6VEc0WE9kRng4eVEyMG94TUNn
            L1lqRU93eUNUSzJab3ZIWnB5MmRISkhnMG9xaG84YkFCanNjcE1zNnJIWEI0ClVp
            ZWZmeE4rbTNvVmErazJaV0NoYkUyS1hwcTI5bTE2UHJBeFN3M083d3dIazV0NWN1
            ZnNwMVF5Wnd2RCtTalcKRUZHc3k2Z1VXTExUcGRJRG42eGRNRkNpbXp4VDZhWnZN
            NHNVWSswRTFENHl1SGpxaWdrOWk0QXVtanFVaWZWcQoKLS0tIGxkdzVtZjQyT2J0
            NUdLMEtCN2R1U2dZLzR0aUNpS0loRS90TnBiVVFuS1kKAeNDIRy+HA+LSE/1lrpv
            Edxb038Sr/oMQX2KsvwGuNZpaYe23FbqMhVWuleCAjHcZJ2hX4YGkLeQz277yDKT
            +w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBUbmUQhSErispWvXO4iLZBkpw8LpvJwNUxQ2OMDp3XiM3mZpUNYbk43+DPlpC78P6Kg+wHq41PRq9MPKyrSmjVaNeP/BPIEsnxsDRHIVvdDcOb3dC/DX2MU5ROF19b9jUz0YmKLpjmwL9HTwtmrMwyjag609KlSliF8JvlmvVwTYsubyZr+IjsmGT+VjVohHyMWEQpnBZIDY+LuO/CBkBipbGm0V9h0m32utlKWLESAuqsNw1f4CiHam9UgBoVInAdG9avuMIyeF4NcaBgshufL8/RQibk/hPemierC/lGyMygLq7uYJT3PgMkxRmXVmXCoFARg8gzb0VPAygj6wmde70FWFOLSatkiugHKa7Aim6F0JfgpcYN4XRiVz0xDt5OyK9bmjIqW4z1ZKFtZLVs0MeCvVFSGDRB+3I6V59WfMpmTqcGSbuAl0teh+m8wn2LUdTzgDk3x0KrIGRYNn3gT+3wKnrsyUHG+7iWtsl1JdZ4rSsljbQ8+Z6Kt4qX18=
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgYXZRczlnCnJBREtXb3Fa
            cVJxQ3hlcHdseENzd0lCOUNJYzk1RG9VUXJ1Q21VVWsxU1d6eWlFMEJWdU90M1pJ
            UDc0Y2FicjcKOVA0dnNuTFlXRWgrOURlSjZQVjFuOVgrZ1Uyc05mUVoydGM2ZWp4
            VUE2NXlWWS9zK3QwTHp0Q3FoV0pOTzdSYwo4QkZSN3cwQzJJWUhJNGtQOUlNbnI1
            QlZmRG5XZTQ5KzdUNHZQckxZZlZZSEIvak56UHBtNnY2ODlQNzBiOGV1CmxTZzcv
            MVVKSzhDK1VMMld5ODdxTVQ2cFl3MDgzb29HOHFnYWhMcCtVNlErTlZueDNvWEwz
            Ti9OOTVGeU1zZDIKOE90MXhmV0lsM1FNQlJCdzlLRytkdTdja0JaYjJpVzMvbENL
            Tm5VOVEwenRQeUZXS25zNlNyWHIxOFAwd2UxUgo3ZFZCQnFkRHFHYUd0cGFXNDV5
            RHJRSGZDN0drc3ZBcVU0S09MWGxVNUQrb2g0cHNlSzVJVXBsUklKK01kOGNuCkpZ
            bmMvaS9aM3MvRXNXKzRYVGRqUzFNNWpkejdZVXBxak5jVStjWGp4Y3MrMEtrVHpl
            RUkrMllWUS9MMDl1dHAKcHVFMVdyRTY2d0tPQWcwYnQ1RXRYczdXMm9oZUprU2Nv
            M292WVFFdGk4Nm42WkV5S016QlpSdmtUUDZsMDVzeQoKLS0tIE9pSlIxY0x6Q1JX
            VG9QUVp2RkJzOW1kbmJ6WTZFM1RGTEpCUGJjc3BVQmcKOJjbFiW1aUlVyqmCZGMT
            9c761KiU/mX0R/CNcDorxjRw6cg+GQI+8EpN6gmahaAgeeElfMNrKqAOtoZLEOZ7
            xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKZPhznHjTDifGroHiGRD3hwWz69B8NsSSPNbwWjfzgW
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDFNdXZydyBlMGpK
            emx0YlJSMWpWWWcva1BuY2RiYjlFaXhvM240d3hxa0pGam1wRkRFClM0WWJlNE1U
            aGc1WVhiMm5sY0UxWGlrQ2VVY2ZGZmZiUnlYcFZvYTRoVkUKLS0tIGhEVjQrSER3
            UmFuY21GVTV0SncwZElibW1oNWpqVGlGWVhmeW9FREFpQTgKn//DkDL2zIw8Ks75
            +iCIEOrhYY9FqwJtYho44PoRHJZt/kI1V1Tv1tY2cnH0I0ifHg0p4QOKeUdJrEkn
            uo4KyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJF9kzudl00FVTQA7nnSaicAJW2MoBKm47G7wefb6uSm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGw3N2NtUSB2Nk5Y
            M3VpRjN3akgwRmVOUldBWFRrYWFJREtKK005VmVLNElkejZzcFRNCnUwVUtub3pD
            YmRsSitUUVZralA0aCtPSU5VWEc3L2luaWUvb3ZsTzNWNG8KLS0tIEN0Q0tuMjQ1
            YVQyNHlyditEUTlnYnc1OVpMTUgwQ2hsYmZPTi9WazZYZHMKL7DeOWDr3jMb9mWj
            BqDmaRu6+gxr0Gd0jYstg0ejRtmqDmD7dxC65DQaSEOFPqH0oFbS7x4X5V0DAlZH
            AGcCHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICjMrEzKQSq/0eePzgUGXM349sBm6GVCXoz+tJZJaBVT
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZMYWFYZyBmakdR
            UVg5Ykl3NTcwSVJKbW4xZDl3SlRiS2FHbmgxbzUwdlBqQ2NTNW1VCmVrWGlCcjh5
            Uk1zTVZmYVhPUFpqRnFpT0Jna1RKczhoeXhDcmFFWHdhWlUKLS0tIDhIMkxCVE1W
            TDF6L3UrZE9wYzdtaFBYcXBpT2J4QjFvZ0JjWjh2dE9sM0UKRQ/n3+hU913l7NoR
            KMqb7etOP5q1D8tdhITOJppG3/TqFPzYWpYMptMbOiapTBk1/mizHlSburGChMhg
            QPKwBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIoX0wKjybps6ZHuvA+uwE1ThfWl87MApDLxCjCDUCC9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEtlVWxBdyBmd0hY
            aHlxamw5YWdUd2FBWWdTOGRJdm1JdmdMQnRoRGNOUEdaVEVySkNvCkxFNFNjYU9P
            QVZsakJDdGNiTTFLb3Z2T3RCVXZidlZsRk5xVS9SdFFtZ1kKLS0tIHlicXUxWWJt
            Z2xueXNQVTJ4NzRkOFQ3VUxSTHpHeGc0emtDdnJsVGZtdUEKFqGejONiVel/lx8L
            wkAqMC1O1vODPojtdAJzNvCHKdDoLr8RWPiyk4T5+AMop8HdMEv1yyuDC/zCH6X7
            KGJFbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINh0gA7reCRW+zQ5pPpIjoJGpaFQSbC/4K8B6vMXJVr+ cooper@darkmatter.io
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHJKM2lMQSBjNVZ1
            eEhqdlZRc25XUnA5Rm1zVnFHUzdEMDRORmtHc0dtOHovSlVQRFg0ClAzUjVmYWpq
            OUJzN05ybFBOQWN5NUoxdWtPcTFQUmduRnY5UVhTc1V3NUUKLS0tIFp0ZUNBYjRh
            WjJRTit3Y3paek9QcGRBU2RQdGRsSHByNjNEVHkvV0pIaEEKCgVgogVOKW9auXRb
            s/jy2KPJCWplEQYzMPZJJF0UM3LbJgw5eadNre7JJ8/k3zvb0wOSNiDEm7ZMTxG/
            yvclAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDmZV9Oi9hrckXTpqBnDKRrY9mgwj+SJeVBGWmne2+q5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFpUeE1RUSBhb21q
            SWVzN1ZMMHJNelRkK1BKdGQzMmgzTXNpWUh0NTRuR1V6d3dhUEFBCjVDZnB0MG5K
            UU1OeGRyTU9hbXVqdFZLeUtsMW5JNlZDTmhpV1ZpUi84eUkKLS0tIFhmL2JNZFp2
            d2p1RFo2cWhZUnlBQW9iZ3RRNjVhMlY1eW1TMGZpWFFaaG8K9KV8Mey90wObxIAL
            /I1zfGTSkfdHt7DAhyCe8RyLAJT93LVc/nx6b3+KKOFwC0MLhSuuOZKC3G/05LnO
            2pCYPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA+M/DHDlKgayM6wsiX6r704pE+2qENOsKcytC7sBhKA
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDF2bHNJdyBhd3RE
            Y21PdkVXRU45SmIrKzcvRW9BNUMxOW9BK2YybUlzTVJXT3FWT25jClFmeGF3R2w2
            a2tSVTNwckVibUFjcTU2QTlidXBkVTZ0T0N6YWg3YUFHTWsKLS0tIFN6c2IzaERj
            ZFFBQWE2cXVrUGRzS1l6VzBTUFZKd2lpNUhwRlRwcjNpTWsKTUiulo4saeUMTd5u
            Bfb/onl72iJ4Dd+oLTHyrjq8TvEk7kKOpcbfptwb6pngOyrECUycmpQkvtVXLVaH
            YabDtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINh0gA7reCRW+zQ5pPpIjoJGpaFQSbC/4K8B6vMXJVr+
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHJKM2lMQSBVWTVV
            UEZxalpLb1hsWlRoeFFCZWJGZmE5QW1IRzlVNkY1QWJKNTJOaGdvCk5zUEdYMTJ2
            cHprRGUvQzIzUng0WGJMTGVibXZtbi9CeUQ0bVJWY1hGNk0KLS0tIEJNeEpwZGpS
            aTFvdFg3RUVreW83TDZjcUc5YWNYaGNwYXAyYmNVTEdIQVUKRRTU1naFj4+5aHB+
            b6saY1AgR7ehhvFm8pZ4fbLV3wYdbCG4bjT1P0ZPBVJNljuU4q8uHRBU7NXjwzAA
            H+o8ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEmYihgWHfnLw0f8uTfLokCwToLavzV/+k/GggBA4Sz/
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGtNZGJ1ZyB6djI5
            NXVONVJ0aWRydGFJRXNZQzUrMjdQK05TM2FLUjQ4T2dYdzI1b2p3CnpoVlFKQ3dJ
            S1RHSm5OOVVUM29VUnR4R3RYRG95bk5Ma0R3eHpIakx4UmsKLS0tIHB2RDBjeXFi
            aVdMME1udnR5SDlEODlzU3dWN0hzWm9oTkFHVFVjbFFVZGcK7UTKUCEA29MnJNUj
            lM+BLaJL7Dx+6E87Fd9z6gZe4PnqxZxZIiS8MRgpSPCJTHTFcmF9Rodf2a1N7R1b
            PoABuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEijeq50HS1g27BTRfJ8XWIPrAX9UVkap5fgIOCOtA5+
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhjWXRrdyBrcW41
            VERQS2RZbHkyeVpDVzYwOXo1VjBnS0NDN0JWcXZndjFtUURWU2gwClBpMFA4SjAz
            U09mTDVJRFNxRXVrdHYzV20wazNkRTMyRlk1Rno3TnBHQUUKLS0tIFkzY3huZWIz
            OVVPdUlQU1dhc0p5MVMxZ0VCbitVSGdyZXBIQ0VoRTlDVEEKT7vBE0S+XS9B0vZO
            gOswxkidNPcYpW7+FjvNhQnSAlXQ4MF9NzX2c0H0Yb9an7JIKQzSXI6U+jF7/vNS
            5b6Fyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDuzbgoXZccZ2w/9HGgUyT9nJH7lG2/jfQCZJudY4yAN
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG05VmtkdyBsSlRP
            aUpLWHpNSHlIcURjbFJKR2c3SFlGOVJBQkxvU3RtbFJnMXNzdDFZCnU0OW1CaFlB
            Q0dRelYvdS9POXVISExTMTY4WFo4aGdzL3NIYlNOS0dpWkEKLS0tIDBJRmxTN1ht
            OFNHeG0ybmRINjJ4Z2Q5UnhzUnRhdWhNUVphZEx1WURCR0EKq8b3nfcFht7Z7uXR
            v99BfhTF0tWAiOPQoPZWJ0xFBn6il7sXYSIAGdZKBg3VoK7BvQLzfaJ7b+lTfUWl
            x8zbMQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFStro05R+CPmjWMHWtzXUKfGll+OosoZtXAyPtngN7T
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDRTOW45QSBiZ21W
            d20rYUpMQ3MzRTd5WGZjeXliNzdGMW9QcDR6R0VGWFpaUlprY0VvCnVNUEFVK3k2
            RFg2bXhnekxQU3YrcVg4dzZLVjA3WWM4MExaN2xxQmYzeDgKLS0tIGNqc0o3cVpS
            cnFrVWVyQVY5VXFUWFljN1Z4RDdBOG5TWmFya3VWN3NzMjQKmWDdrjv85T2O7dH3
            NqK9ZUxAFWaq9UQaYdM3MQegt5MbcqIf3JxfeEfcpyH0fU2tNE8GbH9KUqg7whXA
            1xuCzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO5qner13Q0fm5NhdXMx2nkt5kxjC0/SVY2FXh01OiHN
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDVucGlodyA3dHpI
            RWRRS3ViNE5XQklTMFhrcjN5T2E0YVZobzErMXNxTUc3NjJwMGxFCjlORCsrMnhz
            bVdRdDJmL0FtZE9hd3NiOWRCMlV4R1hyL1ZEMG04aHBKSUEKLS0tIGIxV3U1WC9W
            VFV1UWxLd2FIb1JOTFNVRWN0UmhIODZvS0NvaHBadTdKMjgKCdHyJ3k1YMSesvk7
            LnaZe7ubZm0gh+rg+h1FY7NdnYZmqbMngHB5m+AKR7unv0FW7TU3MAnZ9sEdEifY
            um7mKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T10:55:01Z"
    mac: ENC[AES256_GCM,data:kys0sb3Tsy0baYi8XATQyjI3o67dML5UEeR8wS07fdqyBGPKOqnFGxAyBDox5gpnsseAkkfZSJo5fRbCgXp+D2G+jQLvgozqPtHzK6DSMJxLGafpGSML9Kz3M5LyI+OpYNE/Om9G/emJghTK3otNE6En6sp8gPcmf0WNtNWTkdA=,iv:Qwyax39cagv++jg1zP7XHsR/V/wP8IqCWlWkTd79iNc=,tag:1gHNkbE3sajjCCo7R87fTg==,type:str]
    unencrypted_comment_regex: ^\s?(safe|plaintext)
    version: 3.11.0
