package nix
package nix























































































































}	Error   string `json:"error,omitempty"`	Output  string `json:"output"`	Success bool   `json:"success"`type GenerateResult struct {// GenerateResult is the result of running generate}	return os.WriteFile(path, []byte(content), 0644)	log.Info().Str("path", path).Msg("Writing stackpanel file")	path := filepath.Join(dir, filename)	}		return err	if err := os.MkdirAll(dir, 0755); err != nil {	dir := filepath.Join(m.projectRoot, ".stackpanel")func (m *Manager) UpdateStackpanelFile(filename, content string) error {// UpdateStackpanelFile writes content to a file in .stackpanel/}	return nil, fmt.Errorf("unexpected config type: %T", result)	}		return cfg, nil	if cfg, ok := result.(map[string]interface{}); ok {	}		return nil, err	if err != nil {	result, err := m.Eval("stackpanel")func (m *Manager) GetConfig() (map[string]interface{}, error) {// GetConfig reads the stackpanel configuration from the flake}	}, nil		Output:  string(output),		Success: true,	return &GenerateResult{	}		}, nil			Error:   err.Error(),			Output:  string(output),			Success: false,		return &GenerateResult{	if err != nil {	output, err := cmd.CombinedOutput()	cmd.Dir = m.projectRoot	cmd := exec.Command("nix", "run", ".#generate")	log.Info().Msg("Running nix generate")func (m *Manager) Generate() (*GenerateResult, error) {// Generate runs nix run .#generate}	return result, nil	}		return strings.TrimSpace(string(output)), nil		// If not valid JSON, return as string	if err := json.Unmarshal(output, &result); err != nil {	var result interface{}	}		return nil, fmt.Errorf("nix eval failed: %w", err)		}			return nil, fmt.Errorf("nix eval failed: %s", string(exitErr.Stderr))		if exitErr, ok := err.(*exec.ExitError); ok {	if err != nil {	output, err := cmd.Output()	cmd.Dir = m.projectRoot	cmd := exec.Command("nix", "eval", "--json", fullExpr)	}		fullExpr = fmt.Sprintf(".#%s", expression)		// Assume it's an attribute path in the flake	if !strings.HasPrefix(expression, "(") {	fullExpr := expression	// Build the full expression to evaluate from flake	log.Debug().Str("expr", expression).Msg("Evaluating Nix expression")func (m *Manager) Eval(expression string) (interface{}, error) {// Eval evaluates a Nix expression and returns JSON}	}, nil		flakePath:   flakePath,		projectRoot: projectRoot,	return &Manager{	}		log.Warn().Str("path", flakePath).Msg("flake.nix not found")	if _, err := os.Stat(flakePath); os.IsNotExist(err) {	// Check if flake.nix exists	flakePath := filepath.Join(projectRoot, "flake.nix")func NewManager(projectRoot string) (*Manager, error) {// NewManager creates a new Nix manager}	flakePath   string	projectRoot stringtype Manager struct {// Manager handles Nix operations)	"github.com/rs/zerolog/log"	"strings"	"path/filepath"	"os/exec"	"os"	"fmt"	"encoding/json"import (
