/**
 * Nix Data Layer
 *
 * Minimal adapter for reading/writing Stackpanel configuration from Nix data files.
 * Proto types use snake_case, Nix uses kebab-case - we transform at the boundary.
 *
 * IMPORTANT: For map entities (like variables, apps, services), we only transform
 * the field names within each value object, NOT the map keys (IDs) themselves.
 * Map keys (like variable IDs, environment names, env var names) should be preserved exactly as-is.
 */

// Re-export proto types for convenience
export type * from "@stackpanel/proto";

/**
 * Fields that are maps with user-defined keys that should NOT be transformed.
 * When the parent key matches one of these, child keys are preserved as-is.
 * This must match the Go agent's mapFieldNames() in json_transform.go.
 */
const MAP_FIELD_NAMES = new Set([
	"aliases",
	"apps",
	"categories",
	"codegen",
	"collaborators",
	"commands",
	"databases",
	"env",
	"environments",
	"entries",
	"extensions",
	"masterKeys",
	"modules",
	"outputs",
	"scripts",
	"sites",
	"steps",
	"tasks",
	"users",
	"variables",
	"zones",
]);

/**
 * Convert snake_case keys to kebab-case (for writing to Nix).
 * Preserves keys in map fields (like variables, environments) where keys are user data.
 */
export function snakeToKebab<T>(obj: T, parentKey = ""): T {
	if (Array.isArray(obj)) {
		return obj.map((item) => snakeToKebab(item, parentKey)) as T;
	}
	if (obj !== null && typeof obj === "object") {
		const skipKeyTransform = MAP_FIELD_NAMES.has(parentKey);
		return Object.fromEntries(
			Object.entries(obj).map(([k, v]) => {
				// If parent is a map field, preserve this key as-is
				const newKey = skipKeyTransform ? k : k.replace(/_/g, "-");
				return [newKey, snakeToKebab(v, newKey)];
			}),
		) as T;
	}
	return obj;
}

/**
 * Convert kebab-case keys to snake_case (for reading from Nix).
 * Preserves keys in map fields (like variables, environments) where keys are user data.
 */
export function kebabToSnake<T>(obj: T, parentKey = ""): T {
	if (Array.isArray(obj)) {
		return obj.map((item) => kebabToSnake(item, parentKey)) as T;
	}
	if (obj !== null && typeof obj === "object") {
		const skipKeyTransform = MAP_FIELD_NAMES.has(parentKey);
		return Object.fromEntries(
			Object.entries(obj).map(([k, v]) => {
				// If parent is a map field, preserve this key as-is
				const newKey = skipKeyTransform ? k : k.replace(/-/g, "_");
				return [newKey, kebabToSnake(v, newKey)];
			}),
		) as T;
	}
	return obj;
}

/**
 * Convert snake_case to kebab-case for map VALUES only, preserving top-level keys.
 * Use this for map entities like variables, apps, services where the keys
 * are user-defined IDs that should not be transformed.
 */
export function snakeToKebabValues<V>(
	obj: Record<string, V>,
): Record<string, V> {
	if (obj === null || typeof obj !== "object") {
		return obj;
	}
	return Object.fromEntries(
		Object.entries(obj).map(([key, value]) => [
			key, // Preserve the key as-is
			snakeToKebab(value, key), // Transform field names within the value
		]),
	) as Record<string, V>;
}

/**
 * Convert kebab-case to snake_case for map VALUES only, preserving top-level keys.
 * Use this for map entities like variables, apps, services where the keys
 * are user-defined IDs that should not be transformed.
 */
export function kebabToSnakeValues<V>(
	obj: Record<string, V>,
): Record<string, V> {
	if (obj === null || typeof obj !== "object") {
		return obj;
	}
	return Object.fromEntries(
		Object.entries(obj).map(([key, value]) => [
			key, // Preserve the key as-is
			kebabToSnake(value, key), // Transform field names within the value
		]),
	) as Record<string, V>;
}

/**
 * Entity types available in .stackpanel/data/
 */
export type Entity =
	| "apps"
	| "aws"
	| "commands"
	| "databases"
	| "dns"
	| "extensions"
	| "onboarding"
	| "secrets"
	| "services"
	| "shells"
	| "step-ca"
	| "theme"
	| "users"
	| "variables";

/**
 * Read an entity from .stackpanel/data/{entity}.nix
 * Returns data with snake_case keys matching proto types
 */
export async function read<T>(
	nixEval: (expr: string) => Promise<unknown>,
	entity: Entity,
): Promise<T> {
	const raw = await nixEval(`import ./.stackpanel/data/${entity}.nix`);
	return kebabToSnake(raw) as T;
}

/**
 * Write an entity to .stackpanel/data/{entity}.nix
 * Accepts data with snake_case keys, converts to kebab-case for Nix
 */
export async function write<T>(
	writeFile: (path: string, content: string) => Promise<void>,
	entity: Entity,
	data: T,
): Promise<void> {
	const nixData = snakeToKebab(data);
	const content = `# Auto-generated by Stackpanel
${jsonToNix(nixData)}
`;
	await writeFile(`.stackpanel/data/${entity}.nix`, content);
}

/**
 * Convert JSON value to Nix expression
 */
function jsonToNix(value: unknown, indent = 0): string {
	const pad = "  ".repeat(indent);
	const pad1 = "  ".repeat(indent + 1);

	if (value === null || value === undefined) return "null";
	if (typeof value === "boolean") return value ? "true" : "false";
	if (typeof value === "number") return String(value);
	if (typeof value === "string") {
		return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;
	}
	if (Array.isArray(value)) {
		if (value.length === 0) return "[ ]";
		return `[\n${value.map((v) => `${pad1}${jsonToNix(v, indent + 1)}`).join("\n")}\n${pad}]`;
	}
	if (typeof value === "object") {
		const entries = Object.entries(value);
		if (entries.length === 0) return "{ }";
		return `{\n${entries
			.map(([k, v]) => {
				const key = /^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(k) ? k : `"${k}"`;
				return `${pad1}${key} = ${jsonToNix(v, indent + 1)};`;
			})
			.join("\n")}\n${pad}}`;
	}
	return String(value);
}
