/**
 * Nix Data Layer
 *
 * Minimal adapter for reading/writing Stackpanel configuration from Nix data files.
 * Proto types use snake_case, Nix uses kebab-case - we transform at the boundary.
 */

// Re-export proto types for convenience
export type * from "@stackpanel/proto";

/**
 * Convert snake_case keys to kebab-case (for writing to Nix)
 */
export function snakeToKebab<T>(obj: T): T {
  if (Array.isArray(obj)) {
    return obj.map(snakeToKebab) as T;
  }
  if (obj !== null && typeof obj === "object") {
    return Object.fromEntries(
      Object.entries(obj).map(([k, v]) => [
        k.replace(/_/g, "-"),
        snakeToKebab(v),
      ])
    ) as T;
  }
  return obj;
}

/**
 * Convert kebab-case keys to snake_case (for reading from Nix)
 */
export function kebabToSnake<T>(obj: T): T {
  if (Array.isArray(obj)) {
    return obj.map(kebabToSnake) as T;
  }
  if (obj !== null && typeof obj === "object") {
    return Object.fromEntries(
      Object.entries(obj).map(([k, v]) => [
        k.replace(/-/g, "_"),
        kebabToSnake(v),
      ])
    ) as T;
  }
  return obj;
}

/**
 * Entity types available in .stackpanel/data/
 */
export type Entity =
  | "apps"
  | "aws"
  | "commands"
  | "databases"
  | "dns"
  | "extensions"
  | "onboarding"
  | "secrets"
  | "services"
  | "shells"
  | "step-ca"
  | "theme"
  | "users";

/**
 * Read an entity from .stackpanel/data/{entity}.nix
 * Returns data with snake_case keys matching proto types
 */
export async function read<T>(
  nixEval: (expr: string) => Promise<unknown>,
  entity: Entity
): Promise<T> {
  const raw = await nixEval(`import ./.stackpanel/data/${entity}.nix`);
  return kebabToSnake(raw) as T;
}

/**
 * Write an entity to .stackpanel/data/{entity}.nix
 * Accepts data with snake_case keys, converts to kebab-case for Nix
 */
export async function write<T>(
  writeFile: (path: string, content: string) => Promise<void>,
  entity: Entity,
  data: T
): Promise<void> {
  const nixData = snakeToKebab(data);
  const content = `# Auto-generated by Stackpanel
${jsonToNix(nixData)}
`;
  await writeFile(`.stackpanel/data/${entity}.nix`, content);
}

/**
 * Convert JSON value to Nix expression
 */
function jsonToNix(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  const pad1 = "  ".repeat(indent + 1);

  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;
  }
  if (Array.isArray(value)) {
    if (value.length === 0) return "[ ]";
    return `[\n${value.map((v) => `${pad1}${jsonToNix(v, indent + 1)}`).join("\n")}\n${pad}]`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value);
    if (entries.length === 0) return "{ }";
    return `{\n${entries
      .map(([k, v]) => {
        const key = /^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(k) ? k : `"${k}"`;
        return `${pad1}${key} = ${jsonToNix(v, indent + 1)};`;
      })
      .join("\n")}\n${pad}}`;
  }
  return String(value);
}
