#!/usr/bin/env bun
// Bundle the file-based Drizzle migrations under `drizzle/` into a TypeScript
// module the runtime can import without a filesystem. Cloudflare Workers (and
// our SSR/dev pipeline) bundle every imported module at build time, so we
// inline each `0000_*.sql` next to its journal entry — that way `runMigrations`
// in `src/migrate.ts` works identically on Node, Bun, Workers, and tests
// without any filesystem shim.
//
// Run via `bun run --cwd packages/db db:generate` (which invokes
// `drizzle-kit generate && bun run db:bundle`) — never edit the generated
// `src/migrations-bundle.generated.ts` by hand.

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const DB_ROOT = resolve(import.meta.dirname, "..");
const DRIZZLE_DIR = join(DB_ROOT, "drizzle");
const JOURNAL_PATH = join(DRIZZLE_DIR, "meta", "_journal.json");
const OUT_PATH = join(DB_ROOT, "src", "migrations-bundle.generated.ts");

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

if (!existsSync(JOURNAL_PATH)) {
  console.error(
    `[db:bundle] no journal at ${JOURNAL_PATH} — did you run \`drizzle-kit generate\` first?`,
  );
  process.exit(1);
}

const journal = JSON.parse(readFileSync(JOURNAL_PATH, "utf-8")) as Journal;
const sqlFiles = new Set(
  readdirSync(DRIZZLE_DIR).filter((f) => f.endsWith(".sql")),
);

const bundle = journal.entries
  .slice()
  .sort((a, b) => a.idx - b.idx)
  .map((entry) => {
    const fileName = `${entry.tag}.sql`;
    if (!sqlFiles.has(fileName)) {
      throw new Error(
        `[db:bundle] journal entry ${entry.tag} (idx ${entry.idx}) has no matching SQL file at drizzle/${fileName}`,
      );
    }
    const sql = readFileSync(join(DRIZZLE_DIR, fileName), "utf-8");
    return { ...entry, sql };
  });

const header = `// Auto-generated by packages/db/scripts/bundle-migrations.ts.
// Do NOT edit by hand — re-run \`bun run --cwd packages/db db:generate\`
// (or \`bun run --cwd packages/db db:bundle\` if you only changed the bundler).
//
// Each entry mirrors a row in drizzle/meta/_journal.json with the matching
// SQL inlined, so runtime callers (Cloudflare Workers, Node, Bun, tests) can
// apply migrations without filesystem access.
`;

const body = `export interface BundledMigration {
  /** Sort order — matches the \`idx\` field in drizzle/meta/_journal.json. */
  readonly idx: number;
  /** Tag — drizzle's stable, content-derived identifier (also the filename). */
  readonly tag: string;
  /** Drizzle Kit version that produced the SQL. */
  readonly version: string;
  /** Wall-clock ms when drizzle generated the migration. */
  readonly when: number;
  /** Whether drizzle wrote \`--> statement-breakpoint\` separators. */
  readonly breakpoints: boolean;
  /** Raw SQL contents of drizzle/<tag>.sql, untouched. */
  readonly sql: string;
}

export const MIGRATIONS_BUNDLE: readonly BundledMigration[] = ${JSON.stringify(
  bundle,
  null,
  2,
)} as const;

export const JOURNAL_VERSION = ${JSON.stringify(journal.version)} as const;
export const JOURNAL_DIALECT = ${JSON.stringify(journal.dialect)} as const;
`;

writeFileSync(OUT_PATH, `${header}\n${body}`);
console.log(
  `[db:bundle] wrote ${bundle.length} migration${bundle.length === 1 ? "" : "s"} to ${OUT_PATH}`,
);
