schema = 3

[mod]
  [mod."github.com/alecthomas/chroma/v2"]
    version = "v2.14.0"
    hash = "sha256-d+zcIobMS5Y0/Ym9Uxubf20uyw0aBCr0f1oEOAGHlEA="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/aymerick/douceur"]
    version = "v0.2.0"
    hash = "sha256-NiBX8EfOvLXNiK3pJaZX4N73YgfzdrzRXdiBFe3X3sE="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.21.0"
    hash = "sha256-cfjUHgy9eq5SretTHuYuRaeeT6QmJYQBB9dsI8QSnW0="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v1.3.10"
    hash = "sha256-7wr85TLszu1CHNEMv+o4w+r24Z0xdzCgecPv+ZtRX/A="
  [mod."github.com/charmbracelet/colorprofile"]
    version = "v0.2.3-0.20250311203215-f60798e515dc"
    hash = "sha256-D9E/bMOyLXAUVOHA1/6o3i+vVmLfwIMOWib6sU7A6+Q="
  [mod."github.com/charmbracelet/glamour"]
    version = "v0.10.0"
    hash = "sha256-Vbn/axm6qE67ZVH2YM7slYq0b/CKin4YbUmV3xPmKaU="
  [mod."github.com/charmbracelet/harmonica"]
    version = "v0.2.0"
    hash = "sha256-fi5N0IXhSbbYHdSZFngCfpT4kdiEaKedqj8YpnlvX0o="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v1.1.1-0.20250404203927-76690c660834"
    hash = "sha256-CwS1AyoRsPOFA4SrC0CTtwLnbg57FmmSW/mvVQUFYcc="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.10.1"
    hash = "sha256-nY4zkUGnuD+Lczwt+NMXdQ38cAsy5mtxzXrFSJmR0E4="
  [mod."github.com/charmbracelet/x/cellbuf"]
    version = "v0.0.13"
    hash = "sha256-ubgBd82jcS5L4i6rCFLOB1BXGrDEu6wWlciJA0gsH2g="
  [mod."github.com/charmbracelet/x/exp/slice"]
    version = "v0.0.0-20250327172914-2fdc97757edf"
    hash = "sha256-C1tksnevc/RdytJRQg5LQ0+VVSWlTwbNGic649m6E1Q="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.1"
    hash = "sha256-VBkCZLI90PhMasftGw3403IqoV7d3E5WEGAIVrN5xQM="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.11.0"
    hash = "sha256-iXBBgykYu9Dcd+7LMJyRYc3Ry47jmuLGZFW13zU6toU="
  [mod."github.com/erikgeiser/coninput"]
    version = "v0.0.0-20211004153227-1c3628e74d0f"
    hash = "sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU="
  [mod."github.com/fatih/color"]
    version = "v1.18.0"
    hash = "sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY="
  [mod."github.com/gorilla/css"]
    version = "v1.0.1"
    hash = "sha256-6JwNHqlY2NpZ0pSQTyYPSpiNqjXOdFHqrUT10sv3y8A="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.16"
    hash = "sha256-NC+ntvwIpqDNmXb7aixcg09il80ygq6JAnW0Gb5b/DQ="
  [mod."github.com/microcosm-cc/bluemonday"]
    version = "v1.0.27"
    hash = "sha256-EZSya9FLPQ83CL7N2cZy21fdS35hViTkiMK5f3op8Es="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20230316100256-276c6243b2f6"
    hash = "sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.16.0"
    hash = "sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.1"
    hash = "sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."github.com/yuin/goldmark"]
    version = "v1.7.8"
    hash = "sha256-SNJMPPiXkRDLVOldrHN0ErC3bUB2VoWaLDkd9zmMATw="
  [mod."github.com/yuin/goldmark-emoji"]
    version = "v1.0.5"
    hash = "sha256-GtMipzIcZ0Be7y8fhZ9VkT9dg6bqj9U+DhvliGcMkaU="
  [mod."golang.org/x/net"]
    version = "v0.33.0"
    hash = "sha256-9swkU9vp6IflUUqAzK+y8PytSmrKLuryidP3RmRfe0w="
  [mod."golang.org/x/sys"]
    version = "v0.36.0"
    hash = "sha256-9h4SHGnlJzmTENUp6226hC8fQ73QrQC3D85NNMxLuXg="
  [mod."golang.org/x/term"]
    version = "v0.31.0"
    hash = "sha256-Oy/fGIj1/4byUQKqWPNKKSybeUfEK2s1Os22OVrZUAc="
  [mod."golang.org/x/text"]
    version = "v0.24.0"
    hash = "sha256-qFbmteGOvJfvbLXiOSI8Fsz5Ixt2ZhSYx0/sIqApC7Y="
