// Package state provides access to the Stackpanel state file.
//
// The state file is generated by the Nix devenv and contains
// information about the project configuration, apps, services, and ports.
package state

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// State represents the stackpanel state file structure
type State struct {
	Version     int    `json:"version"`
	ProjectName string `json:"projectName"`
	BasePort    int    `json:"basePort"`

	Paths    Paths              `json:"paths"`
	Apps     map[string]App     `json:"apps"`
	Services map[string]Service `json:"services"`
	Network  Network            `json:"network"`
}

// Paths contains directory paths (relative to project root)
type Paths struct {
	State string `json:"state"`
	Gen   string `json:"gen"`
	Data  string `json:"data"`
}

// App represents an application with its port and domain configuration
type App struct {
	Port   int     `json:"port"`
	Domain *string `json:"domain"`
	URL    *string `json:"url"`
	TLS    bool    `json:"tls"`
}

// Service represents an infrastructure service
type Service struct {
	Key    string `json:"key"`
	Name   string `json:"name"`
	Port   int    `json:"port"`
	EnvVar string `json:"envVar"`
}

// Network contains network configuration
type Network struct {
	Step StepConfig `json:"step"`
}

// StepConfig contains Step CA configuration
type StepConfig struct {
	Enable bool    `json:"enable"`
	CAUrl  *string `json:"caUrl"`
}

// DefaultStateFile is the default name of the state file
const DefaultStateFile = "stackpanel.json"

// Load reads the state file from the given path or auto-discovers it
func Load(path string) (*State, error) {
	if path == "" {
		path = findStateFile()
		if path == "" {
			return nil, fmt.Errorf("state file not found")
		}
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read state file: %w", err)
	}

	var state State
	if err := json.Unmarshal(data, &state); err != nil {
		return nil, fmt.Errorf("failed to parse state file: %w", err)
	}

	return &state, nil
}

// LoadFromProjectRoot loads the state file from a project root directory
func LoadFromProjectRoot(projectRoot string) (*State, error) {
	path := filepath.Join(projectRoot, ".stackpanel", "state", DefaultStateFile)
	return Load(path)
}

// findStateFile searches for the state file in standard locations
func findStateFile() string {
	// 1. Check STACKPANEL_STATE_FILE env var
	if path := os.Getenv("STACKPANEL_STATE_FILE"); path != "" {
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}

	// 2. Check STACKPANEL_STATE_DIR env var
	if dir := os.Getenv("STACKPANEL_STATE_DIR"); dir != "" {
		path := filepath.Join(dir, DefaultStateFile)
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}

	// 3. Look relative to current directory
	candidates := []string{
		".stackpanel/state/stackpanel.json",
		"../.stackpanel/state/stackpanel.json",
		"../../.stackpanel/state/stackpanel.json",
	}

	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			abs, _ := filepath.Abs(c)
			return abs
		}
	}

	return ""
}

// GetApp returns app info by name, or nil if not found
func (s *State) GetApp(name string) *App {
	if app, ok := s.Apps[name]; ok {
		return &app
	}
	return nil
}

// GetService returns service info by key (lowercase), or nil if not found
func (s *State) GetService(key string) *Service {
	if svc, ok := s.Services[key]; ok {
		return &svc
	}
	return nil
}

// GetServicePort returns the port for a service, or 0 if not found
func (s *State) GetServicePort(key string) int {
	if svc, ok := s.Services[key]; ok {
		return svc.Port
	}
	return 0
}

// GetAppPort returns the port for an app, or 0 if not found
func (s *State) GetAppPort(name string) int {
	if app, ok := s.Apps[name]; ok {
		return app.Port
	}
	return 0
}
