// Custom alchemy Resource for AWS ECR Repository.
// Generated by stackpanel — static library code.
import type { Context } from "alchemy";
import { Resource } from "alchemy";

export interface EcrRepositoryProps {
  name: string;
  imageTagMutability?: "MUTABLE" | "IMMUTABLE";
  scanOnPush?: boolean;
  tags?: Record<string, string>;
  lifecyclePolicy?: string;
  destroyOnDelete?: boolean;
}

export interface EcrRepository {
  arn: string;
  name: string;
  repositoryUrl: string;
  adopted?: boolean;
}

export const EcrRepository = Resource(
  "stackpanel::EcrRepository",
  async function (
    this: Context<EcrRepository>,
    _id: string,
    props: EcrRepositoryProps,
  ): Promise<EcrRepository> {
    const {
      ECRClient,
      DescribeRepositoriesCommand,
      CreateRepositoryCommand,
      DeleteRepositoryCommand,
      PutLifecyclePolicyCommand,
      TagResourceCommand,
    } = await import("@aws-sdk/client-ecr");

    const client = new ECRClient({});

    if (this.phase === "delete") {
      if (props.destroyOnDelete === false) {
        return this.destroy();
      }
      if (this.output?.name) {
        try {
          await client.send(
            new DeleteRepositoryCommand({
              repositoryName: this.output.name,
              force: true,
            }),
          );
        } catch (err: any) {
          if (err.name !== "RepositoryNotFoundException") throw err;
        }
      }
      return this.destroy();
    }

    let arn = this.output?.arn;
    let repositoryUrl = this.output?.repositoryUrl;
    let adopted = this.output?.adopted ?? false;

    if (!arn) {
      try {
        const existing = await client.send(
          new DescribeRepositoriesCommand({ repositoryNames: [props.name] }),
        );
        const repo = existing.repositories?.[0];
        if (repo?.repositoryArn && repo.repositoryUri) {
          arn = repo.repositoryArn;
          repositoryUrl = repo.repositoryUri;
          adopted = true;
        }
      } catch (err: any) {
        if (err.name !== "RepositoryNotFoundException") throw err;
      }
    }

    if (!arn) {
      const created = await client.send(
        new CreateRepositoryCommand({
          repositoryName: props.name,
          imageTagMutability: props.imageTagMutability ?? "MUTABLE",
          imageScanningConfiguration: {
            scanOnPush: props.scanOnPush ?? true,
          },
        }),
      );
      const repo = created.repository;
      if (!repo?.repositoryArn || !repo.repositoryUri) {
        throw new Error(`Unable to create ECR repository ${props.name}`);
      }
      arn = repo.repositoryArn;
      repositoryUrl = repo.repositoryUri;
    }

    if (!arn || !repositoryUrl) {
      throw new Error(`Unable to resolve ECR repository ${props.name}`);
    }

    if (props.tags && Object.keys(props.tags).length > 0) {
      await client.send(
        new TagResourceCommand({
          resourceArn: arn,
          tags: Object.entries(props.tags).map(([Key, Value]) => ({ Key, Value })),
        }),
      );
    }

    if (props.lifecyclePolicy) {
      await client.send(
        new PutLifecyclePolicyCommand({
          repositoryName: props.name,
          lifecyclePolicyText: props.lifecyclePolicy,
        }),
      );
    }

    return {
      arn,
      name: props.name,
      repositoryUrl,
      adopted,
    };
  },
);
