// Custom alchemy Resource for AWS IAM Instance Profile.
// Generated by stackpanel — static library code.
import type { Context } from "alchemy";
import { Resource } from "alchemy";

export interface IamInstanceProfileProps {
  name: string;
  roleName: string;
  tags?: Record<string, string>;
  destroyOnDelete?: boolean;
}

export interface IamInstanceProfile {
  name: string;
  arn: string;
  roleName: string;
  adopted?: boolean;
}

export const IamInstanceProfile = Resource(
  "stackpanel::IamInstanceProfile",
  async function (
    this: Context<IamInstanceProfile>,
    _id: string,
    props: IamInstanceProfileProps,
  ): Promise<IamInstanceProfile> {
    const {
      IAMClient,
      GetInstanceProfileCommand,
      CreateInstanceProfileCommand,
      AddRoleToInstanceProfileCommand,
      RemoveRoleFromInstanceProfileCommand,
      TagInstanceProfileCommand,
      DeleteInstanceProfileCommand,
    } = await import("@aws-sdk/client-iam");

    const client = new IAMClient({});

    if (this.phase === "delete") {
      if (props.destroyOnDelete === false) {
        return this.destroy();
      }
      try {
        const existing = await client.send(
          new GetInstanceProfileCommand({ InstanceProfileName: props.name }),
        );
        const roles = existing.InstanceProfile?.Roles ?? [];
        for (const role of roles) {
          await client.send(
            new RemoveRoleFromInstanceProfileCommand({
              InstanceProfileName: props.name,
              RoleName: role.RoleName!,
            }),
          );
        }
        await client.send(
          new DeleteInstanceProfileCommand({ InstanceProfileName: props.name }),
        );
      } catch (err: any) {
        if (err.name !== "NoSuchEntity") throw err;
      }
      return this.destroy();
    }

    let adopted = this.output?.adopted ?? false;
    let profile = this.output;

    if (!profile) {
      try {
        const existing = await client.send(
          new GetInstanceProfileCommand({ InstanceProfileName: props.name }),
        );
        if (existing.InstanceProfile?.Arn) {
          adopted = true;
          profile = {
            name: props.name,
            arn: existing.InstanceProfile.Arn,
            roleName: props.roleName,
          };
        }
      } catch (err: any) {
        if (err.name !== "NoSuchEntity") throw err;
      }
    }

    if (!profile) {
      const created = await client.send(
        new CreateInstanceProfileCommand({
          InstanceProfileName: props.name,
          Tags: props.tags
            ? Object.entries(props.tags).map(([Key, Value]) => ({ Key, Value }))
            : undefined,
        }),
      );
      if (!created.InstanceProfile?.Arn) {
        throw new Error(`Unable to create instance profile ${props.name}`);
      }
      profile = {
        name: props.name,
        arn: created.InstanceProfile.Arn,
        roleName: props.roleName,
      };
    }

    if (props.tags && Object.keys(props.tags).length > 0) {
      await client.send(
        new TagInstanceProfileCommand({
          InstanceProfileName: props.name,
          Tags: Object.entries(props.tags).map(([Key, Value]) => ({ Key, Value })),
        }),
      );
    }

    const current = await client.send(
      new GetInstanceProfileCommand({ InstanceProfileName: props.name }),
    );
    const existingRoles = new Set(
      (current.InstanceProfile?.Roles ?? []).map((role) => role.RoleName),
    );
    if (!existingRoles.has(props.roleName)) {
      await client.send(
        new AddRoleToInstanceProfileCommand({
          InstanceProfileName: props.name,
          RoleName: props.roleName,
        }),
      );
    }

    return {
      name: props.name,
      arn: current.InstanceProfile?.Arn ?? profile.arn,
      roleName: props.roleName,
      adopted,
    };
  },
);
