// Generated by stackpanel — do not edit manually.
// @stackpanel/infra — Infrastructure module library
import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

// Embedded project config
// @ts-ignore
const PROJECT_CONFIG = __PROJECT_CONFIG__ as const;

/**
 * Resolve the project root directory.
 */
function getRoot(): string {
  return (
    PROJECT_CONFIG.root ||
    process.env.STACKPANEL_ROOT ||
    execSync("git rev-parse --show-toplevel", { encoding: "utf-8" }).trim() ||
    process.cwd()
  );
}

let _root: string | undefined;
function ROOT(): string {
  if (!_root) _root = getRoot();
  return _root;
}

/**
 * Read and parse the infra inputs JSON file.
 * Resolution order:
 *   1. STACKPANEL_INFRA_INPUTS env var (path to JSON file)
 *   2. .stack/state/infra-inputs.json (default location)
 */
function loadAllInputs(): Record<string, any> {
  const relPath =
    process.env.STACKPANEL_INFRA_INPUTS ??
    ".stack/state/infra-inputs.json";
  const inputsPath = path.resolve(ROOT(), relPath);

  try {
    const raw = fs.readFileSync(inputsPath, "utf-8");
    return JSON.parse(raw);
  } catch {
    console.warn(
      `[infra] Could not read inputs from ${inputsPath}, using empty inputs`,
    );
    return {};
  }
}

/**
 * Decrypt AGE-encrypted values in an object tree.
 * Values matching ENC[age,...] are decrypted using STACKPANEL_AGE_KEY.
 */
function decryptValues<T>(obj: T): T {
  if (typeof obj === "string" && obj.startsWith("ENC[age,")) {
    const ageKey = process.env.STACKPANEL_AGE_KEY;
    if (!ageKey) {
      console.warn(
        "[infra] Found AGE-encrypted value but STACKPANEL_AGE_KEY is not set",
      );
      return obj;
    }
    try {
      const encrypted = obj.slice(8, -1); // Remove ENC[age,...] wrapper
      const result = execSync(
        `echo "${encrypted}" | base64 -d | age -d -i <(echo "${ageKey}")`,
        {
          encoding: "utf-8",
          shell: "/bin/bash",
          stdio: ["pipe", "pipe", "pipe"],
        },
      ).trim();
      return result as unknown as T;
    } catch (err) {
      console.warn("[infra] Failed to decrypt AGE value:", err);
      return obj;
    }
  }

  if (Array.isArray(obj)) {
    return obj.map(decryptValues) as unknown as T;
  }

  if (obj !== null && typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = decryptValues(value);
    }
    return result as T;
  }

  return obj;
}

/**
 * Deep merge two objects (overrides win).
 */
function deepMerge(base: any, overrides: any): any {
  if (overrides === undefined || overrides === null) return base;
  if (typeof base !== "object" || typeof overrides !== "object")
    return overrides;
  if (Array.isArray(base) || Array.isArray(overrides)) return overrides;

  const result = { ...base };
  for (const [key, value] of Object.entries(overrides)) {
    result[key] = deepMerge(result[key], value);
  }
  return result;
}

/**
 * Format an output key using the project key format template.
 */
function formatKey(moduleId: string, key: string): string {
  return PROJECT_CONFIG.keyFormat
    .replace(/\$module/g, moduleId)
    .replace(/\$key/g, key);
}

// =========================================================================
// Infra class
// =========================================================================

export default class Infra {
  private moduleId: string;

  constructor(moduleId: string) {
    this.moduleId = moduleId;
  }

  /**
   * Resolve inputs for this module.
   *
   * @param overrides - Optional overrides (JSON string or object).
   *   Use process.env.STACKPANEL_INFRA_INPUTS_OVERRIDES for CI tweaks.
   * @returns The module's input configuration with AGE values decrypted.
   */
  inputs<T = Record<string, any>>(overrides?: string | Record<string, any>): T {
    const allInputs = loadAllInputs();
    let moduleInputs = allInputs[this.moduleId] ?? {};

    // Apply overrides
    if (overrides) {
      const overrideObj =
        typeof overrides === "string" ? JSON.parse(overrides) : overrides;
      moduleInputs = deepMerge(moduleInputs, overrideObj);
    }

    // Decrypt any AGE-encrypted values
    return decryptValues(moduleInputs) as T;
  }

  /**
   * Scoped alchemy resource identifier.
   * Prevents collisions between modules.
   *
   * @example
   * infra.id("role") // → "aws-secrets-role"
   */
  id(resourceName: string): string {
    return `${this.moduleId}-${resourceName}`;
  }

  /**
   * Sync all module outputs to the configured storage backend.
   *
   * @param modules - Map of module ID → { outputs, syncKeys }
   */
  static async syncAll(
    modules: Record<
      string,
      {
        outputs: Record<string, string>;
        syncKeys: string[];
      }
    >,
  ): Promise<void> {
    const backend = PROJECT_CONFIG.storageBackend;
    if (backend.type === "none") {
      console.log("[infra] Storage backend is 'none', skipping output sync");
      return;
    }

    // Collect all entries to sync
    const entries: Array<{ formattedKey: string; value: string }> = [];
    for (const [moduleId, mod] of Object.entries(modules)) {
      for (const syncKey of mod.syncKeys) {
        const value = mod.outputs[syncKey];
        if (value !== undefined && value !== null) {
          entries.push({
            formattedKey: formatKey(moduleId, syncKey),
            value: String(value),
          });
        }
      }
    }

    if (entries.length === 0) {
      console.log("[infra] No outputs to sync");
      return;
    }

    console.log(
      `[infra] Syncing ${entries.length} outputs to ${backend.type}...`,
    );

    switch (backend.type) {
      case "chamber": {
        const service = (backend as any).service;
        for (const { formattedKey, value } of entries) {
          try {
            execSync(
              `printf '%s' ${JSON.stringify(value)} | chamber write ${service} ${formattedKey}`,
              { stdio: "pipe" },
            );
            console.log(`  ✓ chamber write ${service} ${formattedKey}`);
          } catch (err) {
            console.error(
              `  ✗ Failed to write ${formattedKey} to chamber:`,
              err,
            );
          }
        }
        break;
      }

      case "sops": {
        const filePath = (backend as any).filePath;
        const dir = path.dirname(filePath);

        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

        // Create the SOPS file if it doesn't exist yet
        if (!fs.existsSync(filePath)) {
          const initYaml = `_init: true\n`;
          const tmpPath = `${filePath}.tmp`;
          fs.writeFileSync(tmpPath, initYaml);
          try {
            execSync(`sops --encrypt --in-place "${tmpPath}"`, {
              stdio: "pipe",
            });
            fs.renameSync(tmpPath, filePath);
            console.log(`  Created new SOPS file: ${filePath}`);
          } catch (err) {
            console.error(`  ✗ Failed to create SOPS file:`, err);
            if (fs.existsSync(tmpPath)) fs.unlinkSync(tmpPath);
            break;
          }
        }

        // Use `sops set` for each key — non-destructive, preserves existing secrets
        for (const { formattedKey, value } of entries) {
          try {
            const jsonPath = JSON.stringify([formattedKey]);
            const jsonValue = JSON.stringify(value);
            execSync(`sops set ${JSON.stringify(filePath)} ${JSON.stringify(jsonPath)} ${JSON.stringify(jsonValue)}`, {
              stdio: "pipe",
              cwd: ROOT(),
            });
            console.log(`  ✓ sops set ${formattedKey} in ${filePath}`);
          } catch (err) {
            console.error(
              `  ✗ Failed to set ${formattedKey} in ${filePath}:`,
              err,
            );
          }
        }

        // Clean up _init placeholder if it exists
        try {
          const decrypted = execSync(`sops decrypt ${JSON.stringify(filePath)}`, {
            encoding: "utf-8",
            stdio: ["pipe", "pipe", "pipe"],
          });
          if (decrypted.includes("_init:")) {
            const tmpPath = `${filePath}.tmp`;
            // Remove _init key via yq, re-encrypt
            execSync(
              `sops decrypt ${JSON.stringify(filePath)} | yq 'del(._init)' > "${tmpPath}" && sops --encrypt --in-place "${tmpPath}" && mv "${tmpPath}" ${JSON.stringify(filePath)}`,
              { stdio: "pipe" },
            );
          }
        } catch {
          // Non-fatal: _init cleanup is best-effort
        }
        break;
      }

      case "ssm": {
        const prefix = (backend as any).prefix;
        const { SSMParameter } = await import("alchemy/aws");
        const alchemy = await import("alchemy");
        for (const { formattedKey, value } of entries) {
          try {
            await SSMParameter(`infra-output-${formattedKey}`, {
              name: `${prefix}/${formattedKey}`,
              value: alchemy.default.secret(value),
              type: "SecureString",
              description: `Infrastructure output: ${formattedKey}`,
              tags: {
                "managed-by": "stackpanel-infra",
                module: formattedKey.split("-")[0] ?? "unknown",
              },
            });
            console.log(`  ✓ SSM ${prefix}/${formattedKey}`);
          } catch (err) {
            console.error(`  ✗ Failed to write ${formattedKey} to SSM:`, err);
          }
        }
        break;
      }
    }

    console.log("[infra] Output sync complete");
  }
}
