// Custom alchemy Resource for AWS Target Group.
// Generated by stackpanel — static library code.
import type { Context } from "alchemy";
import { Resource } from "alchemy";

export interface TargetGroupHealthCheck {
  enabled?: boolean;
  protocol?: "HTTP" | "HTTPS" | "TCP";
  port?: string;
  path?: string;
  interval?: number;
  timeout?: number;
  healthyThreshold?: number;
  unhealthyThreshold?: number;
  matcher?: string;
}

export interface TargetGroupProps {
  name: string;
  port: number;
  protocol: "HTTP" | "HTTPS" | "TCP";
  vpcId: string;
  targetType?: "instance" | "ip";
  healthCheck?: TargetGroupHealthCheck;
  tags?: Record<string, string>;
  destroyOnDelete?: boolean;
}

export interface TargetGroup {
  arn: string;
  name: string;
  adopted?: boolean;
}

export const TargetGroup = Resource(
  "stackpanel::TargetGroup",
  async function (
    this: Context<TargetGroup>,
    _id: string,
    props: TargetGroupProps,
  ): Promise<TargetGroup> {
    const {
      ElasticLoadBalancingV2Client,
      DescribeTargetGroupsCommand,
      CreateTargetGroupCommand,
      DeleteTargetGroupCommand,
      AddTagsCommand,
    } = await import("@aws-sdk/client-elastic-load-balancing-v2");

    const client = new ElasticLoadBalancingV2Client({});

    if (this.phase === "delete") {
      if (props.destroyOnDelete === false) {
        return this.destroy();
      }
      if (this.output?.arn) {
        try {
          await client.send(
            new DeleteTargetGroupCommand({ TargetGroupArn: this.output.arn }),
          );
        } catch (err: any) {
          if (err.name !== "ResourceInUse" && err.name !== "TargetGroupNotFound") {
            throw err;
          }
        }
      }
      return this.destroy();
    }

    let arn = this.output?.arn;
    let adopted = this.output?.adopted ?? false;

    if (!arn) {
      try {
        const existing = await client.send(
          new DescribeTargetGroupsCommand({ Names: [props.name] }),
        );
        const tg = existing.TargetGroups?.[0];
        if (tg?.TargetGroupArn) {
          arn = tg.TargetGroupArn;
          adopted = true;
        }
      } catch (err: any) {
        if (err.name !== "TargetGroupNotFound") throw err;
      }
    }

    if (!arn) {
      const created = await client.send(
        new CreateTargetGroupCommand({
          Name: props.name,
          Port: props.port,
          Protocol: props.protocol,
          VpcId: props.vpcId,
          TargetType: props.targetType ?? "instance",
          HealthCheckEnabled: props.healthCheck?.enabled,
          HealthCheckProtocol: props.healthCheck?.protocol,
          HealthCheckPort: props.healthCheck?.port,
          HealthCheckPath: props.healthCheck?.path,
          HealthCheckIntervalSeconds: props.healthCheck?.interval,
          HealthCheckTimeoutSeconds: props.healthCheck?.timeout,
          HealthyThresholdCount: props.healthCheck?.healthyThreshold,
          UnhealthyThresholdCount: props.healthCheck?.unhealthyThreshold,
          Matcher: props.healthCheck?.matcher
            ? { HttpCode: props.healthCheck.matcher }
            : undefined,
        }),
      );
      const tg = created.TargetGroups?.[0];
      if (!tg?.TargetGroupArn) {
        throw new Error(`Unable to create target group ${props.name}`);
      }
      arn = tg.TargetGroupArn;
    }

    if (!arn) {
      throw new Error(`Unable to resolve target group ${props.name}`);
    }

    if (props.tags && Object.keys(props.tags).length > 0) {
      await client.send(
        new AddTagsCommand({
          ResourceArns: [arn],
          Tags: Object.entries(props.tags).map(([Key, Value]) => ({ Key, Value })),
        }),
      );
    }

    return {
      arn,
      name: props.name,
      adopted,
    };
  },
);
