/**
 * Re-exports auto-generated types from Nix configuration schema and Proto types.
 *
 * Proto types (source of truth for data entities):
 *   packages/proto/gen/ts/
 *
 * Nix types (for evaluated config):
 *   Generated by: nix/stackpanel/core/generate-types.sh
 */

// Import types for use in interface extensions
import type {
  App as ProtoApp,
  GeneratedFile as ProtoGeneratedFile,
} from "@stackpanel/proto";

// Re-export proto types for data entities (snake_case field names)
export type {
  App,
  Apps,
  AppTask,
  AppVariable,
  AppVariableType,
} from "@stackpanel/proto";
export type { Task, Tasks } from "@stackpanel/proto";
export type { Variable, Variables, VariableType } from "@stackpanel/proto";
export type { User, Users } from "@stackpanel/proto";
export type { Config } from "@stackpanel/proto";
export type {
  GeneratedFile,
  GeneratedFiles,
  FileType,
} from "@stackpanel/proto";
export type { Command, Commands } from "@stackpanel/proto";

// Re-export generated Nix types for evaluated config
export type { StackpanelDB as StackpanelConfig } from "./generated/nix-types";
export type { ServicesServices as Service } from "./generated/nix-types";

// Also export the raw generated names for consumers who prefer them
export * from "./generated/nix-types";

// =============================================================================
// App Entity Types (for UI compatibility)
// =============================================================================

/**
 * AppEntity - Extended App type with ID for UI usage.
 * The proto App type doesn't include ID since it's the map key.
 */
export interface AppEntity extends ProtoApp {
  /** The app identifier (map key) */
  id: string;
}

/**
 * AppEntities - Map of app ID to AppEntity
 */
export type AppEntities = Record<string, AppEntity>;

/**
 * ResolvedApp - App with resolved variables/tasks for display.
 * Used by UI components that need to display app details.
 */
export interface ResolvedApp extends ProtoApp {
  /** The app identifier (map key) */
  id: string;
  /** Computed stable port based on project name and app ID */
  stablePort: number;
  /** Whether the app is currently running */
  isRunning: boolean;
}

// =============================================================================
// Additional Types (not generated from Nix)
// =============================================================================

/**
 * SSE event types from the agent
 */
export interface ConfigChangedEvent {
  type: "config.changed";
  files: string[];
}

export interface HeartbeatEvent {
  type: "heartbeat";
  timestamp: number;
}

/**
 * Turbo config changed event - fired when turbo.json or package.json files change
 */
export interface TurboChangedEvent {
  type: "turbo.changed";
  files: string[];
}

export type SSEEvent = ConfigChangedEvent | HeartbeatEvent | TurboChangedEvent;

// =============================================================================
// API Response Types
// =============================================================================

/** Base response for data operations */
export interface DataResponse<T> {
  entity: string;
  exists: boolean;
  data: T | null;
}

/** Write response */
export interface WriteResponse {
  entity: string;
  path: string;
  success: boolean;
}

/** Delete response */
export interface DeleteResponse {
  entity: string;
  deleted: boolean;
  reason?: string;
}

/** List response */
export interface ListResponse {
  entities: string[];
}

// =============================================================================
// API Request/Response Types
// =============================================================================

/** Exec command request */
export interface ExecRequest {
  command: string;
  args?: string[];
  cwd?: string;
  env?: string[];
}

/** Exec command result */
export interface ExecResult {
  exit_code: number;
  stdout: string;
  stderr: string;
}

/** Nix eval request */
export interface NixEvalRequest {
  expression: string;
  file?: string;
}

/** File content response */
export interface FileContent {
  path: string;
  content: string;
  exists: boolean;
}

/** Generate command result */
export interface GenerateResult {
  success: boolean;
  output: string;
  error?: string;
}

/** Secret environment */
export type SecretEnv = "dev" | "staging" | "prod";

/** Set secret request */
export interface SetSecretRequest {
  env: SecretEnv;
  key: string;
  value: string;
}

/** Set secret result */
export interface SetSecretResult {
  path: string;
}

// =============================================================================
// Generated Files API Types (extends proto types with runtime status)
// =============================================================================

/**
 * Extended GeneratedFile with runtime status information.
 * Base fields come from proto GeneratedFile, plus runtime status fields
 * computed by the agent.
 */
export interface GeneratedFileWithStatus extends ProtoGeneratedFile {
  // Runtime status fields (added by agent, not in proto)
  /** Whether the file exists on disk */
  existsOnDisk: boolean;
  /** Whether the disk file differs from expected content */
  isStale: boolean;
  /** File size in bytes (if exists on disk) */
  size: number | null;
  /** SHA256 hash of disk file content */
  contentHash: string | null;
}

/** Response from GET /api/nix/files */
export interface GeneratedFilesResponse {
  /** List of generated file entries with status */
  files: GeneratedFileWithStatus[];
  /** Total number of file entries */
  totalCount: number;
  /** Number of stale (out-of-date) files */
  staleCount: number;
  /** Number of enabled file entries */
  enabledCount: number;
  /** ISO timestamp when data was fetched */
  lastUpdated: string;
}

/** Nix data write request */
export interface NixDataWriteRequest {
  entity: string;
  data: unknown;
}

// =============================================================================
// Nixpkgs Search Types
// =============================================================================

/** A package from nixpkgs */
export interface NixpkgsPackage {
  /** Package name (pname) */
  name: string;
  /** Full attribute path (e.g., "pkgs.nodejs_20") */
  attr_path: string;
  /** Package version */
  version: string;
  /** Package description */
  description: string;
  /** Link to package on search.nixos.org */
  nixpkgs_url?: string;
  /** License name */
  license?: string;
  /** Homepage URL */
  homepage?: string;
  /** Supported platforms */
  platforms?: string[];
  /** Package outputs */
  outputs?: string[];
}

/** Nixpkgs search request */
export interface NixpkgsSearchRequest {
  /** Search query */
  query: string;
  /** Nixpkgs channel (e.g., "unstable", "24.05") */
  channel?: string;
  /** Max results to return */
  limit?: number;
  /** Offset for pagination */
  offset?: number;
}

/** Nixpkgs search response */
export interface NixpkgsSearchResponse {
  /** Matching packages */
  packages: NixpkgsPackage[];
  /** Total number of matches */
  total: number;
  /** The query that was searched */
  query: string;
  /** The channel that was searched */
  channel: string;
}
