/**
 * Re-exports auto-generated types from Nix configuration schema and Proto types.
 *
 * Proto types (source of truth for data entities):
 *   packages/proto/gen/ts/
 *
 * Nix types (for evaluated config):
 *   Generated by: nix/stackpanel/core/generate-types.sh
 */

// Re-export proto types for data entities (snake_case field names)
export type { App, Apps } from "@stackpanel/proto";
export type { User, Users } from "@stackpanel/proto";
export type { Config } from "@stackpanel/proto";

// Re-export generated Nix types for evaluated config
export type { StackpanelDB as StackpanelConfig } from "./generated/nix-types";
export type { ServicesServices as Service } from "./generated/nix-types";

// Also export the raw generated names for consumers who prefer them
export * from "./generated/nix-types";

// =============================================================================
// Additional Types (not generated from Nix)
// =============================================================================

/**
 * SSE event types from the agent
 */
export interface ConfigChangedEvent {
  type: "config.changed";
  files: string[];
}

export interface HeartbeatEvent {
  type: "heartbeat";
  timestamp: number;
}

export type SSEEvent = ConfigChangedEvent | HeartbeatEvent;

// =============================================================================
// Data Entity Types - For .stackpanel/data/ files
// =============================================================================

/** Base response for data operations */
export interface DataResponse<T> {
  entity: string;
  exists: boolean;
  data: T | null;
}

/** Write response */
export interface WriteResponse {
  entity: string;
  path: string;
  success: boolean;
}

/** Delete response */
export interface DeleteResponse {
  entity: string;
  deleted: boolean;
  reason?: string;
}

/** List response */
export interface ListResponse {
  entities: string[];
}

// =============================================================================
// API Request/Response Types
// =============================================================================

/** Exec command request */
export interface ExecRequest {
  command: string;
  args?: string[];
  cwd?: string;
  env?: string[];
}

/** Exec command result */
export interface ExecResult {
  exit_code: number;
  stdout: string;
  stderr: string;
}

/** Nix eval request */
export interface NixEvalRequest {
  expression: string;
  file?: string;
}

/** File content response */
export interface FileContent {
  path: string;
  content: string;
  exists: boolean;
}

/** Generate command result */
export interface GenerateResult {
  success: boolean;
  output: string;
  error?: string;
}

/** Secret environment */
export type SecretEnv = "dev" | "staging" | "prod";

/** Set secret request */
export interface SetSecretRequest {
  env: SecretEnv;
  key: string;
  value: string;
}

/** Set secret result */
export interface SetSecretResult {
  path: string;
}

/** Nix data write request */
export interface NixDataWriteRequest {
  entity: string;
  data: unknown;
}
